### ISSUE TITLE
Fix video viewing

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1015]
When making a video file private, trying to view it with the android video player fails as the system is unable to access the file. We need to use FileProvider for this https://developer.android.com/training/secure-file-sharing/setup-sharing.html

**Comment by valllllll2000** [comment]
## Test plan
Create a video question. Answer video question. Make sure thumbnail is displayed. Make sure you can view the video.
Sync a video datapoint from another device. Make sure you can download and view the video.

**Comment by janagombitova** [comment]
👍all works good for me. There is one small detail I think could make the implementation perfect - see this new issue: https://github.com/akvo/akvo-flow-mobile/issues/1076

But these changes are ready for release
