### ISSUE TITLE
Motorola device not saving photos, videos, signatures, geoshapes 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#1033]
# Broken device details:
Motorola Moto G
Android 5.1 

On this device (have not tested other Motorola phones or other phones with this Android version) I cannot save a photo, video, signature or any geographic shape. Once I hit save on the page and Flow brings me back to the form nothing is saved. 

This means that users of this phone simply cannot use Flow and submit data if there are the above mentioned questions in the forms and mandatory. If not mandatory they will not be able to submit the answers to these questions. 

![app](https://user-images.githubusercontent.com/12456965/37083803-f9b38f76-21f0-11e8-8fef-bc20f31bd226.gif)

# Other devices checked
I have checked other phones and they **all work ok**. Here is the list: 

## Other Motorola 
- Moto E4 (XT1762), Build Number: NMA26.42-113, Android version: 7.1.1
- Moto G, MPB24.65-34-3, Android version 6.0 

## Other brands 
- Samsung GT-S5839i, Android version 2.3.6 
- Samsung GT_I9301l, Android version 4.4.2
- Samsung Galaxy On5 Pro SM-G550FY, Android version 6.0.1
- Samsung Galaxy S7, Android version 7.0
- ASUS_Z00LD, Android version 5.0.2

**Comment by valllllll2000** [comment]
exact device model: Motorola Moto G 4G XT1039

**Comment by valllllll2000** [comment]
@stellan that is prefect, please do! thanks a lot

**Comment by janagombitova** [comment]
Andrew checked on his Motorola phone that is also a Moto-G with  Android version 5.1 and everything worked well on his phone. His build version is LPBS23.13-56-2

Is there anything else we need to get from Molo or from myself to check why we might be experiencing this issue? Can there be a Setting on the device causing this problem?

**Comment by valllllll2000** [comment]
Very odd as the devices are quite similar, only the build changes slightly. @janagombitova I can see on sentry that your device was charing while you were testing. Was it connected to the computer via usb? If so, could you try testing without the device being connected to the computer or charging. In any case, I need to make sure I display the user an error message in all the cases and not just silently ignore the error.

**Comment by janagombitova** [comment]
@valllllll2000 I agree on displaying an error. 

I just tried again using the phone, not changing at all and I still have the same problem.

**Comment by valllllll2000** [comment]
@janagombitova Do other question types work? It may be an issue with the device but it is quite odd that there is no error message, no crashes. Could you paste a screenshot of Preference -> System -> About the phone screen? There seems to be momory available but could you check Settings -> Storage just in case?

**Comment by janagombitova** [comment]
Yes other questions work well. Here are the details you requested. 

![screenshot_2018-03-12-15-19-22](https://user-images.githubusercontent.com/12456965/37289013-eef38b56-2608-11e8-8658-d09830ce93ad.png)

![screenshot_2018-03-12-15-19-29](https://user-images.githubusercontent.com/12456965/37289015-f067630e-2608-11e8-863e-23b69b0acd5c.png)

![screenshot_2018-03-12-15-19-49](https://user-images.githubusercontent.com/12456965/37289014-ef4164a2-2608-11e8-84e0-2bf6a68f71f0.png)

**Comment by valllllll2000** [comment]
These questions have in common:
They call on other activities and rely on these activities to provide a result: Image and Video depend on android external apps whereas Signature and GeoShape are our own Activities.

**Comment by janagombitova** [comment]
It turned out,on my phone in Settings -> Developer options > in Apps (at the bottom)
Don't keep activities was checked. @valllllll2000 pointed this out, and after unchecking this option everything worked as it should! 👍

**Comment by janagombitova** [comment]
@valllllll2000 do you still want to add a warming for the user?

**Comment by valllllll2000** [comment]
@janagombitova this is is a very unusual case, forced by a developer setting which should not be used by normal users, so no need to add anything

**Comment by janagombitova** [comment]
@valllllll2000 agree. Case closed.
