### ISSUE TITLE
Errors when publishing private data

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1040]
While working on #993, I have realised there are 2 pending issues/corner cases to consider:
1) If the user has no data to export, do we still enable the "Publish data" setting? Then, if user presses the setting, shall we say there was no data to copy?

2) What if for some reason publishing data fails, we should show an error message, SnackBar?
How about the message?
The reasons for failure could be:
    - No data to copy (see 1) )
    - No space on sd card
    - Something else (generic error)

**Comment by janagombitova** [comment]
@valllllll2000 Good catch. 

1. Yes, we should definitely inform him/her that there is no data. For how and what should be told, see point 2.
2. On the errors themselves: 
- Snackbar sounds good. We use it across the app so that brings good consistency 
- No data to copy --> I would say 'No data available for bulk upload.' or even 'No data.' 
- No space on SD card --> agree. Question, do we need to bring the user to Settings to clean up storage and create space? 
- not sure how to phrase the generic error :D

**Comment by valllllll2000** [comment]
@janagombitova 
Generic error: "Error publishing data, please try again" with "Retry" button on snackbar
No space: so I am not 100% sure I will be able to catch this error but the message on the snackbar could be. Options;

1) "Device memory full, would you like to free some space?" with a "Free space" button which would take the user to the settings section. Although we cannot really help him much there as he needs to decide which files he deletes. 
2) We could also just have this message:
"Publishing failed due to lack of memory, please delete unneeded files and try again".

**Comment by janagombitova** [comment]
@valllllll2000 Generic error sounds perfect and on the No space one, I would go for option 3. It is simple and clear and we do not bring the user to another part of his phone where he might be expecting one and sees something else. I would simplify the text of the message though. How about: "Error publishing data. No storage space. Please delete unneeded files and try again."

**Comment by valllllll2000** [comment]
## Test plan
Generic error and no space on device are very hard to reproduce.
To try the "no data", first delete all data from device (the confirmation should be displayed in a snackbar), log back in, go to settings and try to publish. You should get the error that no data is available for bulk upload.

**Comment by janagombitova** [comment]
I was able to reproduce the test plan and thus we can consider this ready for release. I get the no data error when there was no data or when there was only saved data. Wonderful 👍
