### ISSUE TITLE
Videos can no longer be opened on devices with Android 8 

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1042]
After making data private, on Android 8.0 devices we are unable to open video files as the file path is unexpected and renaming does not work as on previous versions.

**Comment by valllllll2000** [comment]
## Test plan
You need a device with android 8

**Comment by janagombitova** [comment]
@valllllll2000 do you have an Android 8? If yes, could you test it? I do not and no one around me either.

**Comment by valllllll2000** [comment]
Tested with latest version 2.5.0 and pixel 2 XL with Android 8.1.0. Videos work fine.
