### ISSUE TITLE
Show loading while data is being published

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1048]
When there are lots of files to be copied it may take some time, to avoid lags we should show the user with "loading" progress bar.

**Comment by valllllll2000** [comment]
This is how it looks (the loading spinner is moving in cicles)
![screenshot_20180326-113514](https://user-images.githubusercontent.com/923280/37898893-4df9d90c-30ea-11e8-82dc-3303910267e9.png)
@janagombitova I have a question though, should the text be "Making data available in the public folder for bulk upload" or "publising files..."

**Comment by janagombitova** [comment]
@valllllll2000 so if I understand this correctly we have three steps now: 
1. Alphonso hits to publish the data 
2. Flow publishes the data 
3. Then the data is available for 90 minutes for bulk upload. 

Right? 

For the 1st step we say: Make data available in the public folder for bulk upload. For the 3rd step we say: Data is available for bulk upload over the next. For this step we **yes** need to change the text to make it clear to Alphonso on what is happening. Title remains 'Publish data'. Here are some ideas for the text below:
- Making data available in the public folder for bulk upload.  
- Data will be available in the public folder for bulk upload shortly. 
- Preparing data in the public folder for bulk upload.
- Copying data to the public folder. 

What do you think? 

One more question: Clicking on the option will not be possible, right?

**Comment by valllllll2000** [comment]
@janagombitova I think 
Making data available in the public folder for bulk upload

And yes clicking should not be possible, good reminder

**Comment by valllllll2000** [comment]
![screenshot_20180326-140726](https://user-images.githubusercontent.com/923280/37905705-004ade8e-3100-11e8-9130-b585e0f5f327.png)

**Comment by janagombitova** [comment]
Tested with larger videos and works like a charm
