### ISSUE TITLE
Secure data and images: filter out "saved" images when publishing

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1052]
After reviewing the workflow I have implemented for publishing media and data files, I have found the following issues:
1) Images of the "saved" forms will also be exported
2) Images which have already been synced or even the ones that have been synced in from dashboard (they were not even created by our device).
3) Same thing is valid for data zip files which have already been synced.

All this may end up in lot of files being exported unnecessarily, do we need to filter out?

**Comment by valllllll2000** [comment]
After talking to @janagombitova and considering several options we have decided to export all the files except the ones that belong to "saved" datapoints. This means that media files from saved datapoints have to be filtered out from the publishing

**Comment by valllllll2000** [comment]
## Test plan
Add some responses with images but do not submit.
Publish files. Make sure those images that are saved are not within the published folder.

**Comment by janagombitova** [comment]
saved photos do not show in the published file 👍
