### ISSUE TITLE
Exported files folder

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1053]
For now we use the folder `akfoflow/data/` folder to store `files` and `media` but since we have a service which moves all of them to a private folder. If we publish the files to the same place it may clash with that service. The private files made public will be placed inside `akvoflow/published/files` and `akvoflow/published/media`.

**Comment by valllllll2000** [comment]
## Test plan
Already covered by #977

**Comment by janagombitova** [comment]
👍 seems ready to me
