### ISSUE TITLE
Improve user handing in FlowApp

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1056]
Keeping the user as var in FlowApp and accessing it from everywhere is not the correct way to do it. In order to work on #1049 I first need to fix this dependency. The work includes:
Creating UseCase to get current user.
Make sure FlowApp does not keep reference to user.
Add a way to all the activities to access the user via the UseCase

**Comment by valllllll2000** [comment]
## Test plan
This should be covered while testing "delete all" in settings but make sure to test user operations just incase:
add user, select it, delete user, make sure cannot delete current user. Put app in background, make sure the same user is still seelcted

**Comment by janagombitova** [comment]
User management works like a charm 👍 Ready to roll
