### ISSUE TITLE
Logic for deleting files and data

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1058]
The current logic for deleting files using async task does not work for the new files we have exported.
First step is to add data and domain logic to delete collected data.

**Comment by janagombitova** [comment]
@valllllll2000 any specific tests steps I should follow?

**Comment by valllllll2000** [comment]
## Test plan
With published files, try deleting collected data and delete everything. Make sure the published files are deleted. Also make sure the remaining time in settings is no longer showing "remaining minutes".

**Comment by janagombitova** [comment]
All works perfectly 👍

**Comment by janagombitova** [comment]
@valllllll2000 I noticed one issue. Sorry. When I select the Option to Delete collected data and images the published file is removed as expected, the data too, but the published timer is still active and ticking.

**Comment by valllllll2000** [comment]
We have decided with @janagombitova that PreferenceActivity will be dismissed after both of these actions. User will taken to:
* login screen if he chooses to delete all
* datapoint list if he chose to delete collected data

**Comment by janagombitova** [comment]
works like a charm for both option :)
