### ISSUE TITLE
Cleanup SurveyDbAdapter and SurveyDbDataSource

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1059]
These 2 classes contain lots of unused methods and needs cleanup

**Comment by janagombitova** [comment]
@valllllll2000 is there anything here to test besides a regular regression round?

**Comment by valllllll2000** [comment]
@janagombitova No, regression should catch any issues

**Comment by janagombitova** [comment]
I did not find anything, so we can consider the issue ready. If I do I will comment.
