### ISSUE TITLE
Add Pijin and Tok Pisin to languages list

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1062]
New languages have been added to Flow https://github.com/akvo/akvo-flow/issues/2202 but we also need to add them to the app:
Tok Pisin has an ISO 639-2 code: "tpi".
Solomon Islands Pijin has an ISO 639-3 code: "pis"

**Comment by valllllll2000** [comment]
## Test plan
Add several languages to a form especially Pijin and Tok Pisin. Make sure they are displayed in the menu -> Languages and also in the form.

**Comment by janagombitova** [comment]
👍 works like a charm (in submitting new data and viewing submissions). Ready to roll
