### ISSUE TITLE
Transmission keeps absolute path to files

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1084]
The Transmission table saves the full path to the files on the device to the database but this is not recommended. We should use only the filename and folder and rebuild the path as it may change.

**Comment by valllllll2000** [comment]
## Test plan
with version 2.4.8  add some datapoints and make sure they are synced
update to latest version
check datapoint transmission - > path should be filename only

**Comment by kymni** [comment]
Looks good

**Comment by valllllll2000** [comment]
tested on both android 6.0 and 8.0 devices and works as expected
