### ISSUE TITLE
Add android build version code to deviceapprest call

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1091]
example deviceapprest?`action=getLatestVersion&deviceType=androidPhone&appCode=flowapp&androidBuildVersion=27`

**Comment by valllllll2000** [comment]
## Test plan
Try updating the android version (if a new one is available) 
I will need to provide you a special apk for this

**Comment by janagombitova** [comment]
@valllllll2000 with the apk that is now on UAT1 I installed it on my tablet running a 4.something Android version, all went well, installed a software update and opened up Flow and all still worked fine. Is this a good enough test?
