### ISSUE TITLE
Idea to allow to stop the publishing 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#1107]
# Context 

With the 2.5.0 app we introduced the new feature the publish data to make it available for bulk upload. This makes data available for 90 minutes when Salim can copy the data over to his computer, zip it and bulk upload it. 

# Opportunity

Sometimes 90 minutes may seem too long. There is a chance he will create more submissions since he published. Then he has to wait the remaining minutes to be able to publish them and bulk import. 

The likelihood is very low, but we should keep this idea open and revisit if a few weeks after the release, based on the feedback we get.

**Comment by valllllll2000** [comment]
I think allowing to stop publishing manually is a good idea, how can we represent that in the ui?

Another idea: we could have a whole section in settings for **Publish data**. There we could also allow to configure the time the data is published for. Also, we could have 2 other entries: one for publish files which would work as it is now, another one, hidden by default would be to "unpublish files" and would only appear when users publish the files.

**Comment by Kiarii** [comment]
I dig the idea of providing flexibility when it comes to publishing / unpublishing data; would be handy though to get some feedback from users who have used the feature..

**Comment by muloem** [comment]
> Another idea: we could have a whole section in settings for **Publish data**. There we could also allow to configure the time the data is published for. Also, we could have 2 other entries: one for publish files which would work as it is now, another one, hidden by default would be to "unpublish files" and would only appear when users publish the files.

I like the idea to have an unpublish feature.  This would be a normal workflow for someone interested in keeping data secure.  Publish the data, upload it and then unpublish when done.  Also it gives the chance to indeed address this use case where a user has published and then realises they needed to collect one or two more... 👍 

The thing I would avoid is giving them the possibility to set the time for which data is published.  This is heading in the direction of too many choices which in the end causes "settings fatigue" if such a term exists.
