### ISSUE TITLE
Replace image loading library

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1114]
Due to method counts limitations for older devices we were forced to use the Picasso library to load images. Picasso has the advantage of having smaller size but in this article, we can see the threadoffs and one of them is the out of memory errors we are experiencing https://medium.com/@multidots/glide-vs-picasso-930eed42b81d
With the minimum SDK set to 15, we no longer have the limitation and hence can use glide which is more memory efficient.

**Comment by janagombitova** [comment]
@valllllll2000 Anything specific to keep an eye out on when testing this one?

**Comment by valllllll2000** [comment]
@janagombitova ah sorry forgot...
## Test plan
Pay attention to crashes related to images.
Please test the following question types:
Image
Signature
Video
Try creating datapoints and also syncing in existing ones.
Try with large image setting
Try with many image questions at once

**Comment by janagombitova** [comment]
All works well 👍
