### ISSUE TITLE
Learn about how the app is used 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#1126]
# Opportunity

We currently learn about how the app is used via user research interviews (discovery or usability). We currently have 35,801 devices using the Flow app. We should learn more about how the app is used, which functionality is used the most, which not at all, etc.

The idea is to track how the app is used, so we can better understand out users experience and make data based decisions on improvements to the app.

**Comment by valllllll2000** [comment]
Done as Firebase tracking added in #1361
