### ISSUE TITLE
Resize of images removes rotation information

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow-mobile#113]
Steps to reproduce:
1. on the device, turn off the 'resize images' feature
2. collect some data including a photo, taken in portrait mode (phone vertical)
3. on the dashboard, look at the photo, and observe that the image appears correct.
4. on the device, turn on the 'resize images' feature
5. collect some data including a photo, taken in portrait mode (phone vertical) 
6. on the dashboard, look at the resized photo, and observe that the image appears with incorrect rotation.

Likely cause: When an image is taken by a device, usually the jpg includes exif data (or tiff data) on the rotation. This is information is used by browsers and other image display / process programmes to display the image with correct orientation.

However, when we resize the image, this exif metadata is possibly lost from the image.

Proposed solution: check if there is a way to preserve the rotation information in resized images.

**Comment by janagombitova** [comment]
@valllllll2000 crossed checked this issue by testing all possible photo sizes on both portrait and landscape mode and the way the images are shown in Flow's online space is fine and works as expected. 

Can we close this issue?

**Comment by valllllll2000** [comment]
Closing the issue as seems it has been fixed a long time ago.
