### ISSUE TITLE
Media files in saved forms

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1130]
If you create a submission with images but do not submit and then update the app, those images are lost forever. For some reason the paths do not get updated and the images cannot be found by the app.
If you later submit, the datapoint never gets synced as the images are not found.

Maybe related to:
https://github.com/akvo/akvo-flow-mobile/issues/1098
https://github.com/akvo/akvo-flow-mobile/issues/1084

**Comment by kymni** [comment]
Unable to reproduce this issue using older versions of the app. What I did was
1. Install v2.4.7 of app
2. Download survey with image question
3. Fill survey and capture image for photo question but not submit
4. Update app to v2.4.8
5. Image still on unsubmitted photo question
6. Update app to v2.5.1
7. Image still on unsubmitted photo question

**Comment by valllllll2000** [comment]
tested on both android 6.0 and 8.0 devices, works as expected
