### ISSUE TITLE
Upload datapoints from one survey

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1138]
Uploading datapoints from one survey (instead of syncing everything) requires some changes to the data sync logic

**Comment by valllllll2000** [comment]
## Test plan
Create survey with signature, image, video, caddisfly e coli tests (needs image) .... 
Place device in flight mode. Create datapoint and submit.
Remove flight mode. In the menu, press "upload". Datapoint should turn to green.

**Comment by janagombitova** [comment]
Turns green 👍
