### ISSUE TITLE
Data processing request includes the entire file path

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow-mobile#1147]
When requesting the backend to process an uploaded file, the app sends the entire file path and therefore the backend is unable to find the file. e.g. 
`https://.../devicezip//data/user/0/org.akvo.flow/files/akvoflow/data/files/82f...20.zip`

**Comment by janagombitova** [comment]
@valllllll2000 just tried to reproduce the issue on my device. So in the list of data points all submissions have the synced status with the green icon, but on the instance when I check my survey forms they show no data.

I used uat1 > _2.5.1 folder and both surveys in there. 

![screenshot_2018-07-09-08-56-46](https://user-images.githubusercontent.com/12456965/42435216-24756998-8356-11e8-86a2-2448d13d8546.png)
![screenshot_2018-07-09-08-56-34](https://user-images.githubusercontent.com/12456965/42435217-2494326a-8356-11e8-8a4b-b7eb1c279da3.png)

**Comment by valllllll2000** [comment]
Update:
It turns out, making the fix with a script is not possible so we need to make those changes in the app too

**Comment by kymni** [comment]
Test plan passed
