### ISSUE TITLE
Refactor data export and sync

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1152]
In order to work on issues
https://github.com/akvo/akvo-flow-mobile/issues/1138
https://github.com/akvo/akvo-flow-mobile/issues/1090
We need to refactor the logic for exporting and syncing the datapoints as they should be allowed to run either together or separated.

**Comment by valllllll2000** [comment]
## Test plan
Regression tests should catch this but basically you should be able to submit datapoints and the should be exported and sent to dashboard correctly (if online)

**Comment by janagombitova** [comment]
@valllllll2000 Here are three things I found so far around the changes to syncing

# No more submitted status? 
After I submit a data point with a bit more data, so the syncing takes more time, my data point status is in `saved` where it should be in `submitted` and goes from `saved` to synced once syncing is completed. This is confusing as I submitted my data so it should be in the submitted state. 

# Large submissions seem to stay in saved status
When I create a submission with ta video, it syncs well but on the app it remains in the saved status what is confusing as I can open the data point and it seems I can submit again even thought I have already and the submission is visible in the Data tab. 

*sending you a movie directly* 

# Snack bar out of place
The syncing snack bar is oddly located not in the bottom of the screen when syncing happens. Once syncing stops it comes back down to the bottom of the screen. 

![screenshot_2018-08-21-08-52-13](https://user-images.githubusercontent.com/12456965/44387801-c9560c00-a526-11e8-84cf-6231d3abefe2.png)

**Comment by janagombitova** [comment]
When testing the app offline to then trigger the syncing with the new `upload` button I see that all my submitted but not synced submissions are in `saved` status. 

![screen shot 2018-08-21 at 12 08 52](https://user-images.githubusercontent.com/12456965/44395711-04fad100-a53b-11e8-80fc-b06c94cf66a1.png)

**Comment by janagombitova** [comment]
All works well now 👍
