### ISSUE TITLE
Monitoring: Downloading data points should also download images to the device

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#1167]
# Context 

With monitoring Al can download all the data points to his device, so then he can monitor also the data points that he did not register. When downloading the data points, submissions to the assigned forms get downloaded too. This helps Al to look at the History of the data point when in the field to check if he is at the right point, or to check other information. 

# Opportunity 

Having the previous submissions downloaded is very helpful for Al. He tends to open these submissions in the History tab to check if he is at the right spot. He comes to the farmer he thinks he needs to interview, goes to the data point, goes to the History and opens the registration form submission to check that this is his farmer. He often uses the photo for this verification. 

However, with photos and videos, they do not get downloaded to the device fully when Al hits download/sync. He needs to open the form submission in the History tab, and download the photo separately. 

If Al works in an area in the field with no connectivity, he has no way to download the photo, not helping him the verify his farmer. 

# Next steps 

Can we make it possible to also download photos and videos into the device when downloading the data points?

**Comment by valllllll2000** [comment]
Update:
We obviously can but, here is to bear in mind:
1) When lots of datapoints -> lost of images and video we have to make sure the users are aware, may require extra memory on device
2) Extra costs required to download if not over wifi
