### ISSUE TITLE
Single app

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1179]
Currently each dashboard has its own configuration so we have as many android apps as dashboards. This is very inconvenient for several reasons:
* deployments take a long time ~ 2 hours
* app has to read configuration files
* it would be complicated to have the apps published to the google platy store as each dashboard would need its app
* we need to handle updates manually (notify user etc...)

Having a single app would allow:
* fast deploy ~ 3 minutes
* easily publish to google play store
* no need to update dashboards on deploy
* no need to store apk to s3
* users can disable the insecure setting "allow install from unknown sources" as app can be downloaded from google play.
* updates are taken care of by the play store
* presence in the google play store (marketing)

Issues:
How to configure app after first install. Dashboard url should be easy but s3 keys are more complex for the user to input.

**Comment by muloem** [comment]
This is the same as #286 right?  Do we need to copy any info from there to here and then close the other one?

**Comment by janagombitova** [comment]
Besides the technical benefits of this change, we also want to move the Flow app to Google Play Store for reasons that will benefit our users and allow for scaling. 
* When Al goes to download an app today he simply goes to the Play Store. Having to download the Flow app via a url is confusing and feels odd to new users. (it is not a good 1st impression) 
* Being able to download the app from Play Store and easily get started will give Al more independence as he will not need to be 'trained' or to get specific instructions on how to get started, he will just follow what the app tells him to to 
* We see it more and more that Al does not only collect data for one organisation but for multiple.. Our partners collaborate more, which sometimes means that Al collects data for 2 Flow instances from the same spot in the field. Now Al needs to uninstall the app and reinstall it from the other organisations URL to be able to get his assigned forms and submit data. Ideally, we would want him to be able to switch from one Flow instance to another to support this cross-organisational data collaboration.
