### ISSUE TITLE
Download forms

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1180]
Downloading forms is currently inside settings. We will redesign that feature and add it to the navigation drawer.
Here is the design:
![image](https://cloud.githubusercontent.com/assets/12692444/24549165/b9cb8a9e-1620-11e7-82cf-b5d982acc278.png)

**Comment by muloem** [comment]
Do we want to keep allowing anyone to download _any_ form if they have the `formId` or should we restrict the downloading by `formId` to still check whether the form has actually be assigned to the said device?

The other thing is if we download the form by ID then do we need to create an assignment for it on the backend?

Finally do we really still need the admin passcode?

**Comment by janagombitova** [comment]
We have been unclear for a while now on the value of the option to download forms using the form ID. Secondly, we were not sure if it is used. As we are now collecting usage stats we can see if the functionality is being used. As indeed getting forms to the devices via assignment is the preferred option. 

Here is a screen shot of our stats over the last 28 days, keeping in mind that not all devices are running on the latest Flow app version, so this is just sample data. 

![Screen Shot 2019-05-10 at 15 54 34](https://user-images.githubusercontent.com/12456965/57532678-5c94d300-733c-11e9-89e0-6d47b72f9f4f.png)

The data is ordered by number of users . This image shows that downloading form pressed and updated are the 4th most used events. Valeria can you clarify which exactly functionality this is? Is it the download form by ID? As on the 9th row is another entry called 'download forms' so it would be handy to know which one is which. Thanks 

This change is not a priority right now for us. But before we pick it up and take it further we should take a look at the stats to make an informed decision.

**Comment by janagombitova** [comment]
Just to add to the issue a bit more clarity: 
* I would suggest keeping both download options for now - assignments is the preferred way but we see partners using the download by ID for testing out forms (before the real data collection starts) or just for one-time data collection efforts where it is easy just to give Al the form ID
* we should remove the admin passcode - having the enumerator know the Form ID is already enough to prove that Al got this information from a reliable source (Salim with access to the organisational instance and form)

**Comment by muloem** [comment]
Passcode is now gone #1532

**Comment by janagombitova** [comment]
I would like to revisit the designs now that the passcode is removed (well done 👍 ) to see if we can further simplify them. For example, the `Reload all forms` now has a double action that is unnecessary.
