### ISSUE TITLE
Prohibit trailing/leading whitespace in user ids and device ids?

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow-mobile#1181]
A user entered his user id with a trailing space. This was almost impossible to see in the dashboard, and then the data filter strips trailing spaces so it was impossible to search for.
It might be better if the user simply could not enter such.

**Comment by valllllll2000** [comment]
We already trim the username and device id https://github.com/akvo/akvo-flow-mobile/blob/develop/app/src/main/java/org/akvo/flow/activity/AddUserActivity.java#L116
