### ISSUE TITLE
Auto Save for geoshapes

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#1199]
# Context 
One of the more complex question types Al needs to fill in are geographic shapes (geoshapes). He can capture points, lines or areas. Usually this question type is used in agricultural project to plot land. 

When creating a geoshape Al has to add each point one by one to create it, making it time and energy consuming to do. Once done, Al has to click on the 'save' button to save the shape. 

Often Al clicks on the back button what can cause him to loose his work done till that point as he did not save the shape. 

# Opportunity
Considering the process of creating a geoshape takes time and the current user workflow is not simple, the opportunity to ease the current pains is to autosave anything created. Thus if Al hits the back button, he is sure what he created is not lost. 

The question that we should answer is how will Al complete the geoshape/go back to the form? Is this needed? 

# Extra note
We did discuss the need for a larger improvement around geoshapes and their creation handling points as: 
- you should not be able to create more than one shape per question
- in the survey editor Salim should explicitly choose which shape type is created
- simplify the UI in the app
- simplify how shapes are created by considering automation and movement tracking 
- etc. 

These points will not be handled in this issue. This issue is to consider the possibility of adding autosave in the current set up. 

# Created via Reamaze:

Link: /admin/conversations/feature-request-auto-save-for-geoshape
Assignee: Jana Gombitova

**Comment by valllllll2000** [comment]
When moving the geoshapes to mapbox, this feature has been forgotten, so reopening
