### ISSUE TITLE
Repeated group redesign

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1201]
While working with #1103 there is also the need to redesign the repeated question groups.
here is current design
![screenshot_20180906-142053](https://user-images.githubusercontent.com/923280/45157155-911a2300-b1e0-11e8-9a38-d935f352d5f4.png)

**Comment by Kiarii** [comment]
there has been some ideas - [see prototype](https://invis.io/ZQYQSWY64E5#/325763658_Form-_QG-_Group_Repeated) - about how to better handle repeat question group.. (making the note here for when we might address this..)

The idea also suggest a reorganization of the question groups as a whole - to simplify orientation and navigation thereof
<img width="374" alt="Screenshot 2020-10-28 at 9 50 59" src="https://user-images.githubusercontent.com/12692444/97402163-2158dc00-1903-11eb-8246-5f9225273bb6.png">
