### ISSUE TITLE
Add geoshape validation

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1215]
Before saving a geoshape we need to check if they are valid but how can we do that?

Idea:
At least one point needs to be added or also validate depending on the shape type (as polygons should have at least 3 points and lines at least 2 - I think)

**Comment by janagombitova** [comment]
What we should validate: 
* validate that the shape contains the minimum points needed before allowing to save it --> only enable Save button if a point has at least 1 point, a line has at least 2 points, an area at least 3 points https://github.com/akvo/akvo-flow-mobile/issues/322
* do not allow to save more to an existing shape - today I can create an area (for example) save it and then click on the create button again and add another area to the existing one. This should not be allowed as we should stick to the rule, one shape per question. Thus after saving the shape, Alphonso can only go back and edit the existing shape. 
   
![geoshape2](https://user-images.githubusercontent.com/12456965/64856433-3e105280-d622-11e9-892a-1798e0ee543b.gif)

**Comment by janagombitova** [comment]
I am splitting this issue into two: 
1. Validate before saving 
2. Do not allow to add another shape after 1st is saved

**Comment by valllllll2000** [comment]
I would suggest to do it differently: we allow saving partial shapes but we do not allow submitting them.
Before allowing submission, we check the validity of the shape, the same way we check if the double entries questions match. 
Why: I think there may be cases where Alphonso may add the first points of the shape but need to move and then he needs to fill other questions in the meantime. If we restrict him it may make things hard for him.
