### ISSUE TITLE
Simplify cascade usage

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1218]
Currently in the app we show cascades level by level inside spinners and you cannot see the next level until you select the current item. Sometimes cascades have 5 or more levels and you have to go through several spinners to get to the option. For example, say you want Barcelona and in order to get to it you have to select:
World -> Europe -> South Europe -> Spain -> Barcelona
The idea would be to be able to start typing Barce ... and we would start suggesting cascade paths so user just have to select between one or more paths and avoid him to have to select all the intermediate levels.

**Comment by janagombitova** [comment]
Requested today by a partner: When using in Flow - resources - cascades - a cascade with many options (for example a list of 50 options), I believe there is currently no search button in the Flow app to make life of data collectors easier. A partner asks wether this is something we want to add in the future

**Comment by Kiarii** [comment]
Question: the suggested idea of reversing the cascade and starting with the endpoint selection might work for location cascades, but do we have cases where cascades refer to different things and it might not be easy to start from the end? (e.g. I remember tree type spec for Ecosia - would we break it if we reversed things?

Still exploring options..

**Comment by Kiarii** [comment]
meself and @valllllll2000 discussed this issue and had 3 options:

1. Make every cascade level / option searchable
<img width="335" alt="Screen Shot 2021-01-04 at 13 58 15" src="https://user-images.githubusercontent.com/12692444/103528793-9f9ea500-4e95-11eb-97c8-6d00d8e2f93a.png">


2. (Building on 1) Make it possible to [save an entered cascade as a default for the subsequent form submissions](https://www.figma.com/proto/UHii6RPTlf3wcUMqE7NzUb/Cascading-questions?node-id=4%3A124&scaling=scale-down)
<img width="346" alt="Screen Shot 2021-01-04 at 13 58 36" src="https://user-images.githubusercontent.com/12692444/103528751-8ac21180-4e95-11eb-82ab-4512c72eb16a.png">


3. Do [a reverse cascade entry](https://www.figma.com/proto/UHii6RPTlf3wcUMqE7NzUb/Cascading-questions?node-id=2%3A294&scaling=min-zoom) by typing in the lowest value and selecting a corresponding cascade hierarchy.
<img width="479" alt="Screen Shot 2021-01-04 at 13 59 48" src="https://user-images.githubusercontent.com/12692444/103528719-7e3db900-4e95-11eb-8c52-8212b254cdcb.png">

We decided to go with option 1, why:

- option 3 would be the ideal situation, but requires some research into types of cascade used by partners (besides location), and possibly some backend work to toggle certain cascades as reverse-pickable i.e. when Alp can know the last level in the hierarchy... This also requires Salim to change the question to the last level's Label e.g. in the screenshot above: City, which would require some additional UI changes to onboard Salim on dealing with the new changes


- option 2 is an increment on option 1, so we thought to start small, both dont require any backend work
- option 1 is a small change, but might bring some added benefit to users working cascades with many levels and several values in each

**Comment by valllllll2000** [comment]
<img src="https://user-images.githubusercontent.com/923280/105893972-0be37300-6014-11eb-80e1-cb2dea084e82.png" width="200" /><img src="https://user-images.githubusercontent.com/923280/105893978-0c7c0980-6014-11eb-8f73-771dc64f2b6e.png" width="200" /><img src="https://user-images.githubusercontent.com/923280/105894109-359c9a00-6014-11eb-99c0-bfb1f6e50058.png" width="200" />
