### ISSUE TITLE
Setting about mobile data usage

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#1220]
# Context 

In Flow app Settings Salim can decide to Enable usage of mobile data. This setting is disabled by default. The reason Flow has this setting was to prevent users from spending too much mobile data with using Flow and rather capturing data offline. 

# Issue 
But we have learned that users decide if they want to use their mobile data or not on the overall phone/table level. So having this setting specially only for Flow is confusing. 

We have many cases when new users install the Flow app and are using their mobile data, that they ask why are surveys not downloading. They then need to go and enable the setting in Flow to connect to the network. 

# Next steps 
~~remove functionality~~ -> see details below

**Comment by valllllll2000** [comment]
## Test plan
Install the app from scratch (not update)
Make sure all assigned surveys are downloaded to the device
Try syncing a datapoint, make sure syncing works
Try submitting a datapoint, make sure it is uploaded and the synced state appears.
Try checking for app update
Open an existing datapoint with images and videos and make sure they work

**Comment by muloem** [comment]
@janagombitova so from other apps, the typical setting that I have seen is to make the choice of whether to sync over Wifi Only, and Wifi and Mobile.  I was wondering why not this option instead of only relying on the phone data setting?

**Comment by janagombitova** [comment]
The main intention was to simplify things and remove the current confusion. We wanted to keep the handling of what option to connect to the internet you use for the device Settings rather than the app one. 

To be honest, we did not consider that option at all.

**Comment by muloem** [comment]
I agree.  The upload of images and videos is the unexpected and large data consumer.  The download as you point out is initiated by the user so they are conscious of when they want to use up their data or not.

**Comment by janagombitova** [comment]
Hi both, should we talk about this issue in person to move it further?

**Comment by valllllll2000** [comment]
Services that use internet:
1) Crash reporting -> shall we have a special setting "enable crash reporting", on by default, hidden in settings
2) Check device time -> very small data usage
3) Syncing data out (datapoint upload) -> can be small or big depends if there are images, videos, signature... big surveys 
4) Datapoint download -> Triggered by user, can be lots of data or not depends. Maybe will be less once we start assigning actual datapoints to users. Images and videos are not downloaded, only urls actual download of individual media file can be triggered by user media by media. Shall we offer the user the possibility to enable "automatic media download"? see https://github.com/akvo/akvo-flow-mobile/issues/1167
5) Download surveys. This is triggered every time app starts (app restart, screen rotation). This can also be triggered by user (located in settings, also only one form can be downloaded). There is a project to download forms fro inside the navigation drawer. How can this be optimized? Ideally the device should be notified via push notification that there are changes to a survey/form structure and then device downloads forms. Forms are defined in xml files. There can also be sqlite databases for cascades. Surveys can be assigned and unassigned and also deleted.

**Comment by valllllll2000** [comment]
Here is how the dialog looks:
![screenshot_20181031-131407](https://user-images.githubusercontent.com/923280/47787405-20d6dc00-dd0f-11e8-984b-be19ffdad78f.png)
What do you think @janagombitova @Kiarii ?

**Comment by janagombitova** [comment]
I think we need to simplify the text according to the rules here: https://material.io/design/components/dialogs.html#anatomy

**Option A**
Title options: Upload submissions over mobile data 
Text: When disabled submissions will only be uploaded when a wifi connection is available. 
Buttons: Cancle/No thanks, Upload 

**Option B**
Title: Enable uploading submissions over mobile data
Text: When disabled submissions will only be uploaded when a wifi connection is available. 
Buttons: Cancle/No thanks, Enable

**Option C**
Title: Use mobile data to upload submissions
Text: When disabled submissions will only be uploaded when a wifi connection is available. 
Buttons: Cancle/No thanks, Use mobile data

But I am fishing in deep waters here. @Kiarii what are your thoughts

**Comment by valllllll2000** [comment]
I like option B, more direct, and then I would use Enable/No thanks, but that's just my opinion

**Comment by Kiarii** [comment]
It is not a good practice to put a 'settings option' on a dialog; better to reserve such options for the settings where the user knows where to find all provided options. This creates a good expectation of where to find things no matter where the user is in the app. Else, it becomes a challenge to figure out how to trigger the dialog setting, which there is no way to trigger again, if it is system triggered. In this case, if the user affirmed the action over the dialog and realized they need to undo, they would be lost as unto where to do it..

If it is a must to have the dialog, then affirming the action should open the settings where the user can toggle the option on/off

**Comment by valllllll2000** [comment]
![screenshot_20181105-151052](https://user-images.githubusercontent.com/923280/48002902-2ff1cb80-e10d-11e8-84a4-1e99c65fc2ed.png)

**Comment by valllllll2000** [comment]
Test plan
Install the app from scratch (not update)
Make sure all assigned surveys are downloaded to the device
Try syncing a datapoint, make sure syncing works
Try submitting a datapoint, make sure it is uploaded and the synced state appears.
Try checking for app update
Open an existing datapoint with images and videos and make sure they work

**Comment by janagombitova** [comment]
All works fine and I like the new workflow. It makes sense. Well done 👍
