### ISSUE TITLE
Read Phone State Permission

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1234]
This permission is quite sensitive and users do not like it.
If we request for it we need to explain why.
Here is where it is used:
Phone number -> only below android 21 
Imei -> all devices
This permission is need right at the beginning of opening the app as we use the phone info to forms to the device

**Comment by muloem** [comment]
Is it possible to run things without this permission if it is refused?

**Comment by valllllll2000** [comment]
@muloem there is no simple answer:
* Devices with android 5.0 -> they cannot refuse

* Devices with android 6.0:
1) For new installs we could remove the usage of imei and phone, we still have to find a a way to know if it's a new install
2) For existing ones: we need to check because imei is sent when getting assignments, datapoints, syncing data. Not sending it, would require the users to be logged out and all assignments to be reassigned unless we do some changes in the backend.

**Comment by valllllll2000** [comment]
## Test plan
With android 6.0 device
Have surveys assigned 
Update the app from previous version using beta
Make sure you are asked for permissions and accept them
Delete everything form phone
Login again and make sure the correct surveys are downloaded
Make sure you are able to submit data correctly
