### ISSUE TITLE
Location permission

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1235]
This permission is used for:
Calculating distance to datapoints (if location is available)
Locating pictures when the geotagging is disabled in the camera app (if location is available)
When there is a geoshape question to locate the user
datapoints map -> required or app crashes
-> need to check if we can make it non mandatory.
When user presses "check geo location" here location is mandatory.

**Comment by valllllll2000** [comment]
## Test plan
With a freshly installed app try both devices older than Android 6.0 (when runtime permissions started) and 6.0 onwards.
1)  Geoshape question. Make sure you can fill it and app does not crash. Make sure you can view submitted geoshapes.
2) Sync some datapoint in with location data (that use them as datapoint location). Make sure you can view them in datapoint map. Also select one datapoint and once inside history click on the menu  to view map, make sure datapoint is visible on the map and there is no crash.
3) Geoquestion. Press "check geo location" make sure this works fine on all devices. On older devices (prior 6.0) there will be no change, you may just be asked to enable GPS if it disabled but that's it. On newer devices you will be asked to accept location permissions. If you refuse, you will not be able to use device location, only input the location manually if the question allows it.

**Comment by janagombitova** [comment]
Hi @valllllll2000 all works fine besides one thing and I want to check I understood it correctly: 

Steps I have taken: 
1. Disabled location tagging in the photo app
2. took a photo with Flow and waited for location to not be captured 
3. Submitted the form 

What however happened, was that even though I have the location tagging disabled on my device, Flow showed that location can captured for my photo. See images below. Is this ok? 

![screenshot_2018-11-12-12-10-58](https://user-images.githubusercontent.com/12456965/48344296-e9542200-e674-11e8-8702-3b40e034f75a.png)
![screenshot_2018-11-12-12-05-41](https://user-images.githubusercontent.com/12456965/48344297-e9542200-e674-11e8-9b2a-65143dbcedc2.png)
![screen shot 2018-11-12 at 12 18 23](https://user-images.githubusercontent.com/12456965/48344345-16a0d000-e675-11e8-9608-66ddd1316b4b.png)
