### ISSUE TITLE
Update url under Terms of service 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#1238]
In the Flow apps About page the last url points to the old page with our terms of service. We need to make sure to point to the correct new URL as we have updated the Terms of Service recently. 

New url: https://akvo.org/help/akvo-policies-and-terms-2/

Linked issue from Flow repo: https://github.com/akvo/akvo-flow/issues/2898

**Comment by valllllll2000** [comment]
## Test plan
form navigation drawer go to About -> terms, make sure the right page is shown

**Comment by janagombitova** [comment]
All good.
