### ISSUE TITLE
Remove settings migration

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1243]
Since we make everyone update to 2.4.8 before going any further, there is no longer need to migrate the settings table to preferences

**Comment by valllllll2000** [comment]
## Test plan

Install version 2.4.8. Make some changes to settings. Go offline. Submit some questions (also repeated groups). Submit. Update to latest version (the one being tested). Check settings, make sure everything is  preserved. Go online. Make sure everything syncs. Check repeated groups that they are shown correctly.

**Comment by janagombitova** [comment]
Works like a charm.
