### ISSUE TITLE
Allow sharing zip files with the app

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1245]
Currently we have a bootstrap service to check if there are new zip files in the inbox folder. We could also allow users to click on a survey zip file and do "open with"  or "share with" and flow app would be listed. In this case we would extract forms from a single zip file. It is a more straight forward alternative to the use pasting the file to a certain folder and then opening the app although I would keep the old method too.

**Comment by muloem** [comment]
Great proposal!
