### ISSUE TITLE
Replace file publishing by file export

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1246]
While reading the issue https://github.com/akvo/akvo-flow-mobile/issues/1107 I had a new suggestion which implies:
1) Remove the publishing of files
2) Add "export data in a zip file":
A zip file would be created with all the images and data files.
Once the file is ready, 2 options:
* share zip archive via email, bluetooth, 
* save it somewhere on the device, user can chose where

There is also a new sharing app ushareit: https://www.ushareit.com/?referer=gp&app=shareit

Advantage: we do not have to track the 90 minutes, Salim can export again before the 90 minutes, he can decide what to do with the data, either share it or save it.
Disadvantages: we cannot really delete it anymore or maybe we could still delete it after some time???

**Comment by muloem** [comment]
I was thinking about this and initially got excited but then I realised that the _Publish files_ functionality is used in a scenario for submitting data from a device that is not connected to the internet so sharing via email seems redundant. If they are able to connect to the internet to send an email then they may as well submit from the app itself.  

The bluetooth option is interesting but I believe that we should ideally leave the user to choose which tool they find easiest to use to share the files with another device.

It may be an idea to allow the user to save the files to any location they want to but maybe in the interesting of preventing the user from shooting themselves in the foot, e.g. saving sensitive data and not deleting it, then we may want to only allow them the unpublish option to allow them to updte the submissions but then we delete everything once the 90 mins are up.
