### ISSUE TITLE
Removing an answer to an option question allows to submit even if mandatory

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#1247]
# Context 
Questions marked as mandatory and not filled in on the app prevent Al from submitting the form. 

# Issue 
Camille found a case where this rule is not followed: A question was answered (option question), then I voluntarily went back at the end of the form to delete the answer and tried sending the form anyway and this was possible.

# Next steps
Can you try to reproduce and handle the issue? 

# Created via Reamaze:

Link: /admin/conversations/akvoflow-support-request-number-161079-from-camille-at-akvo-dot-org

**Comment by valllllll2000** [comment]
I have tried and removing any question anwer, not just option, the submission is still possible.

We have this issue about the clear dialog
https://github.com/akvo/akvo-flow-mobile/issues/1007

**Comment by valllllll2000** [comment]
## Test plan
Create a survey with several questions, also dependent ones. Fill them all. Check submit tab, make sure submit button is enabled. Go back to one of the groups. Long press mandatory question title. Confirm question clear. Make sure question is marked with error and submit button is disabled. Also try deleting the option question: long press the selected option, confirm to delete.

**Comment by janagombitova** [comment]
Works like a charm
