### ISSUE TITLE
Crash related to incorrect OkhttptClient use

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1271]
This error 
_java.net.ConnectException: Too many open files_

seems to be due to having too many insances of OkHttpClient.
Reduce the amount to 2 clients (we need 2 different ones)

**Comment by valllllll2000** [comment]
Sentry issue: [FLOW-ANDROID-27J](https://sentry.io/akvo-foundation/flow-android/issues/791803889/?referrer=github_plugin)

**Comment by janagombitova** [comment]
See comment here: https://github.com/akvo/akvo-flow-mobile/issues/1273#issuecomment-448148803 

Overall issue I could not reproduce anymore and all works well 👍
