### ISSUE TITLE
Datapoint status not updated correctly

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1273]
There have been reports of:
* datapoints status be "uploaded" while some transmissions failed
* datapoints status "failed" when transmissions are actually updated correctly.

**Comment by janagombitova** [comment]
Created via Reamaze:

Link: /admin/conversations/submissions-not-updating-to-uploaded

**Comment by janagombitova** [comment]
Created via Reamaze:

Link: /admin/conversations/akvoflow-fr-requete-de-support-number-170-721-de-mpiquet-at-snv-dot-org

**Comment by valllllll2000** [comment]
## Test plan
Download some old apk for example in the beta app version 2.5.1

New version
This bug is hard to reproduce manually.
Try creating many datapoints, make sure it all syncs correctly especially media files.
Try with bad connections if possible
Try disabling internet and then enabling once several datapoints have been created.

**Comment by janagombitova** [comment]
@valllllll2000 I could reproduce the problem on the old apk and then with updating to the new one not anymore, so that is good. Also trying out the steps you mentioned, all syncs eventually well so I feel we should push this out and see what reactions we get from our users. 

Well done! 👍
