### ISSUE TITLE
Show captured location on a map in Flow app

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#1284]
This issue is a copy of https://github.com/akvo/akvo-product-design/issues/256 as we are closing down that repo and brining all the issues to their individual product repos. 

# Context 
Currently when Alphonso captures location he can either type the coordinates manually or get the location info from the device. What he then sees are the numerical coordinates and the accuracy of the measurement (if captured from the device GPS). He does not have to go to a separate page on the phone to capture the location info, he simply does this in the form screen.

![screenshot_2017-03-27-11-57-38](https://cloud.githubusercontent.com/assets/12456965/24351383/c57d06e4-12e5-11e7-80eb-d9c448571e21.png)

# Opportunity
Alphonso has no real clue about the location captured as seeing coordinates does not tell him where  the location is, if it is where he wants it to be. To show the location on a map, besides the numerical value, can give him more insight on the coordinates he has captured.

Secondly, when capturing location manually he sometimes does not know the coordinates, so being able to add the point on a map and then get the coordinates can visually help him make sure he answered the question correctly.

We need to keep in mind a few cases though: 
- Alphonso usually collects data offline, thus he is not able to load in the map 
- the survey is set up by Salim who decides, if Alphonso can collect the location data only manually, only using the device's GPS or he can give Alphonso both options 
- when the location is being captured by the device, it takes a minutes (then times out) so Alphonso needs to see that the location is being captured and he should not be able to type in the values, as they will be overwritten 
- minimise the steps he needs to take when capturing the location data, seeing it on a map can be considered as an extra possible option for validation

**Comment by valllllll2000** [comment]
Point 3 is no longer relevant as we have:
![Screenshot_20191029-164331](https://user-images.githubusercontent.com/923280/67784539-3ab71600-fa6c-11e9-9c71-53e8d0122dcf.png)

**Comment by muloem** [comment]
* It would be good to have some rough idea about how often GPS location is entered manually vs autodetected.

* This could be an interesting use case for the offline maps functionality.

**Comment by muloem** [comment]
A first step could be to implement this functionality for users who are online.  While keeping things as they are for offline users. @Kiarii any thoughts here?

**Comment by Kiarii** [comment]
> GPS location is entered manually vs autodetected

- When we say GPS is entered manually do we mean that Alphonso have a separate GPS device from which he reads the numbers and types them into the app?
- I do note the issue is about showing location on a map not about how the coordinates are obtained.. 
 

> A first step could be to implement this functionality for users who are online

We might actually do a wholesale support for all scenarios. i.e.
- When Alphonso is using live or offline maps he should be able to see the location on map
- When he works offline and is not using offline maps, then in place of the map we could show the coordinates as is currently the case

**Comment by Kiarii** [comment]
A side question, for the manual entry, why is height/altitude information required? Is it used to calculate something? To locating on a map, it does not appear necessary to have the altitude..

**Comment by Kiarii** [comment]
I reached out to Molo regarding the manual location details entry;
> We usually advocate the gps location to be fetched automatically. I haven't come across a situation where one fills in manually

**Comment by janagombitova** [comment]
I would suggest to keep this issue **only to showing the capture location on a map ** and handle capturing location by using the map in a separate task. This way we can solve the problem of not knowing what location is collected while figuring out the details of the second part.

**Comment by janagombitova** [comment]
Redesign here: https://github.com/akvo/akvo-flow-mobile/issues/1680#issuecomment-658093130

**Comment by Kiarii** [comment]
here's the [prototype](https://www.figma.com/proto/3A3zZ1XgqIGIcgv8AZgM2B/Loc-and-Img-capture?node-id=31%3A112&scaling=min-zoom)
