### ISSUE TITLE
Flow app separation of view from database access

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow-mobile#1285]
The Flow app currently has the database code very tightly coupled to the views, in addition to a single data base class that is called everywhere, increasing the likelihood of bugs when changes are made.  We would like to separate the data access from the view and make this more modular as well as testable.

We start with an [ADR](https://github.com/akvo/akvo-product-design/blob/master/FLOW/arch/ADR-005.md) where we need to decide how we want to architecture to be setup.

**Comment by janagombitova** [comment]
@valllllll2000 I am cleaning up an old repository we had and found this issue @muloem created a while back? Is it still relevant, or can it be closed? Please take a look, thanks.

**Comment by valllllll2000** [comment]
This is a general issue which still makes lot of sense. Parts of the database access has been refactored in the navigation drawer (left menu) and datapoint sync. Unfortunately there are still parts of the app which there is still direct database access in the Activities: SurveyActivity (even if the actual datapoint list and map fragments have been refactored) and FormActivity still need a major refactor. I am leaving this issue for now even if when needed we may have to split it up in separate tasks.
