### ISSUE TITLE
Flow App datapoint sync improvements

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1286]
Currently the app displays too many notifications which are not necessary or are not meant to be a notification.
As a first step we have decided to modify datapoint sync and not to display any notifications but use ui loading, snackbars and display of data to inform users about the status of the sync.
see https://github.com/akvo/akvo-flow-mobile/issues/583 for more details.

The current architecture of the app is not ideal and the objective is to take this first step to improve the architecture of the app starting with the datapoints display and syncing.

**Comment by janagombitova** [comment]
@valllllll2000 I found this issue in the Product-design repository that I aim to close down, so I moved it here. Can you decide if this issue is still relevant in the light of all the changes you have made since then and either elaborate or close it? Thanks

**Comment by valllllll2000** [comment]
this task has been completed so closing it
