### ISSUE TITLE
Handle Survey Group monitoring flag change

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#129]
**Problem:** If a regular form is synced into the device, a new _Project_ is created and the form is the unique item found in this project. This behaviour is better described in #100. However, it could be the case in which an already downloaded form/group changes its nature from regular to monitored, in which case, an uncertain scenario is presented.

First of all, we need to accordingly create the new Project and assign the form (unchanged ID) to this project. The current version of the app (v1.15.10) is retaining the old group, without deleting it. 

One the main concerns is data collected with the old project (non-monitored), which cannot simply be moved to the new Project. The references this Data Points hold are related to a completely different project, with different ID and properties.

A possible solution is to retain the old project and form, without allowing users to provide new responses, displaying some kind of _deprecated_ status.

Another alternative is to only allow monitoring flag changes when no data has been collected. This is more difficult to handle, as collected data can exist without being synced yet in the dashboard.

Any ideas?

CC/ @mtwestra, @iperdomo, @muloem

**Comment by janagombitova** [comment]
Is this still relevant? If you change a non-monitoring survey to a monitoring survey, republish and re-open the app, the survey changes are reflected properly

**Comment by valllllll2000** [comment]
@janagombitova If it no loger happens then we can close it
