### ISSUE TITLE
Deleting a repetition with answers does not delete

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#1294]
# Issue 

When Al repeats a question group he follows these steps: 
1. First 'repetition' is by defaults open (you must have at least one repetition) and he adds the answers. 
2. Hits 'Repeat group' to add another repetition and adds answers. 
3. Hits on 'Repeat group' again by mistake adding a 3rd repetition, so he deletes this repetition. Flow app asks him to confirm the deletion with a pop up message. 
4. Moves on to the following group. 

In this case, the repetition is discarded and in the dataset he sees only the 2 repetitions he filled in. 

## Deleting a repetition with answers 
However, if he fills in at least one answer to a repetition and then deletes the entire repetition, Flow app ignores that. It saves the 3rd repetition that then shows in the dataset, even though Al deleted it. 

### Example
uat1.akvoflow.org > _1.9.40 & 1.9.41 > 1.9.41 Dependent questions survey with IDs and repeat > Dep Form with translations

The first column indicates what happened to the 2nd repeated group for each submission. In the image below the 3rd repetition was deleted. 
<img width="1205" alt="screen shot 2019-01-17 at 11 38 13" src="https://user-images.githubusercontent.com/12456965/51312836-7d16e580-1a4c-11e9-8edd-be91ca441e78.png">

## Deleting a repetition with answers and then adding a following one 
If I fill in a 3rd repetition and delete it and then add a 4th repetition (actually 3rd one) it is saved properly. I have only three repetitions in the data set with the correct answers. 

## Adding 6 repetitions and then deleting the 3rd one
If I fill in a 3rd repetition and then add a 4th and 5th and 6th. Then I decide to delete the 3rd one. In the add the group disappears and the following repetitions update their number. But in the dataset I still have 6 repetitions instead of 5, with the data. 

# Created via Reamaze:

Link: /admin/conversations/akvoflow-you-got-a-feedback-on-an-article-from-s-dot-berendschot-at-icco-dot-nl

**Comment by janagombitova** [comment]
@valllllll2000 I tested this also with the 2.6.3.1 app version on UAT1 and the issue is also present there. So this is not related to the test app version I was trying out last week. Thought you should know.

**Comment by valllllll2000** [comment]
OK, I understand what happens here, iteration numbers are inserted in the database, and we can have for example:
response 0 - iteration 0
response 1 - iteration 1
response 2 - iteration 2
If I delete iteration 1, it gets deleted correctly but the iteration in the database does not get updated, so now we have:
response 0 - iteration 0
response 2 - iteration 2
now if I try to delete response 2, the ui will think it's iteration 1 but the database will not find it and it will not be deleted correctly but silently ignored (although disappears from ui)

**Comment by valllllll2000** [comment]
## Test plan
Create a survey with all question types inside a repeatable group
Try filling 3 repetitions of the group with all the answers
delete last iteration
submit
make sure only 2 reps show in dashboard and try syncing to another device, make sure repeated group is displayed correctly
