### ISSUE TITLE
Repetitions not show in History

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#1295]
We had a similar issue in the past: https://github.com/akvo/akvo-flow-mobile/issues/600.

When testing on 2.7.0 I noticed that when viewing the submission I made in the form History, I see only my 1st repetition even though I have made 6 for example. 

![screenshot_2019-01-17-11-53-36](https://user-images.githubusercontent.com/12456965/51314026-42fb1300-1a4f-11e9-8c16-b20bb2dc8412.png)

<img width="829" alt="screen shot 2019-01-17 at 11 54 35" src="https://user-images.githubusercontent.com/12456965/51313775-b2243780-1a4e-11e9-96fb-e69100af9213.png">

After I download datapoints, to another device I get the same result with only the 1st repetition showing.

**Comment by janagombitova** [comment]
@valllllll2000 I tested this one again just now with the 2.6.3.1 version on UAT1 and is works well, no issue. So I will close it, but we need to make sure that 2.7.0 does not introduce the issue again.

**Comment by valllllll2000** [comment]
Found this issue again in app v 2.7.1 with the form uat1.akvoflow.org > _1.9.40 & 1.9.41 > 1.9.41 Dependent questions survey with IDs and repeat > Dep Form with translations
