### ISSUE TITLE
Handle stalled IN_PROGRESS files

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#131]
The sync process only checks for `queued` and `failed` files to upload. There can be edge cases where an `in progress` status is leaked from a previous attempt to sync a file.

The sync process should:
- Avoid leaking `in progress` transmissions between sync cycles.
- If a leak occurs, handle these transmissions in the next sync cycle.

**Comment by janagombitova** [comment]
Does this still need to be open?

**Comment by valllllll2000** [comment]
Closing it as that part of the code will be refactored
