### ISSUE TITLE
Missing (MissingUnknow) device files

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1315]
Some media files are "missing unknown" which means they don't have a deviceId and are sent to all devices from that dashboard. When a device receives them they are inserted in the Transmission table of the device database. The device tries to send them but if the files do not exist on the device, transmission fails but keeps getting retries.

What should be done with those files, options
 1) If not found the first time we mark them as deleted on the device so we do not retry sending them. 
2) Before inserting them to device database we should check if the file exists on local memory, if not, do not insert them.

How to reproduce DeviceFileJobQueue with null deviceId
bulk uploads datapoints for a form with images but only the data (just delete the corresponding images) and wait for a few minutes or hours as the processing takes time and is retried several times.

**Comment by stellanl** [comment]
Both solutions sound good to me. Would 2. use less storage? If that is not significant, go with the simplest one.

**Comment by valllllll2000** [comment]
Backend issue https://github.com/akvo/akvo-flow/issues/2973 would reduce significantly the amount of null deviceIds
