### ISSUE TITLE
Form version inconsistency

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1324]
Currently we use the form version received from the backend to display to the user. Same for data.json file, it contains the version saved in sqlite database after we get the form metadata from the backed. The issue is sometimes the survey xml file on S3 is not up to date and this may be confusing to the users as the version of the data should be the one from the survey file and not the one in the backend.
Ideally if the backend version is more recent we should inform that the device does not have the latest file.

**Comment by stellanl** [comment]
In particular, the version in the response must be the same as that of the form that was actually *used*.

**Comment by valllllll2000** [comment]
## Make sure the version in the backend corresponds to the version of the form
