### ISSUE TITLE
Add details about offline maps to walkthrough

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1343]
Walkthrough are the screens that are displayed when the user first views the app (the new version).
Currently they contain information about data publishing:
<img src="https://user-images.githubusercontent.com/923280/38686323-5b02ff7e-3e74-11e8-8f46-18438fd15aed.png" width="200">
<img src="https://user-images.githubusercontent.com/923280/38686325-5b23373a-3e74-11e8-93b4-e2e990a30581.png" width="200">

## Offline maps walkthrough
With offline maps feature we should add it to the walkthrough:
<img src="https://user-images.githubusercontent.com/923280/54286181-a0b96080-45a3-11e9-96ee-4354e547031e.png" width="200">

## Revise old content
Old walkthrough should be deleted.
Added issue to delete this walthrough after a few releases: https://github.com/akvo/akvo-flow-mobile/issues/1436

**Comment by janagombitova** [comment]
I asked Georgia is she can tweak up the copy in the walkthrough and here is her suggestion to keep it simple and informative but to make it more inviting too: 

Offline maps
Collecting data offline? Simply download a map of your desired area and use it while you’re off-grid.

**Comment by janagombitova** [comment]
Hey @valllllll2000 the only thing that I noticed when testing the app today (Friday) was that the walkthrough is not updated. I assume the changes are not reviewed and merged yet. Otherwise all is well
