### ISSUE TITLE
Offline maps list actions

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1345]
The offline maps list should allow
* Add new offline map
* Select a map to use
* Map item menu: 
     * View
     * Rename
     * Redownload
     * Delete (with confirmation)

<img src="https://user-images.githubusercontent.com/923280/54287988-fa6f5a00-45a6-11e9-8849-20e4da8a5668.png" width="200">

**Comment by valllllll2000** [comment]
Notes:
* Redownload is not possible, mapbox handles downloads themselves when new tiles are available
* There is not data such as the age of the map, mapbox does not provide it so I would have to do it by hand, not sure if it's worth it.

**Comment by janagombitova** [comment]
@valllllll2000 I would say that for the 1st implementation it is not worth the effort. We should get the feature out and then learn how users experience things and what is missing. Redownloading can be a thing to explore for the next iterations if it proves to be confusing or needed.

**Comment by valllllll2000** [comment]
![Screenshot from 2019-07-05 16-36-04](https://user-images.githubusercontent.com/923280/60729465-15dde680-9f43-11e9-843c-4907ffcd8bc7.png)

**Comment by valllllll2000** [comment]
Offline Area item view:
![Screenshot from 2019-07-08 14-10-22](https://user-images.githubusercontent.com/923280/60809137-3ba8fc80-a18a-11e9-8139-6c029025f930.png)
