### ISSUE TITLE
Replace deprecated sqlbrite library

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1388]
We are using the sqlbrite library for the database related operations (in most parts of the app). Unfortunately it has been deprecated 
https://github.com/square/sqlbrite
We need to migrate to something else, for example [Room](https://developer.android.com/topic/libraries/architecture/room.html) 
Here is a migration guide: https://medium.com/androiddevelopers/incrementally-migrate-from-sqlite-to-room-66c2f655b377

**Comment by muloem** [comment]
What consequence will this have for the lower versions of Android that we still support?

**Comment by valllllll2000** [comment]
I don't think room has a requirement higher than what we support but will check and if needed and will find something else depending on the version. We were also talking to raise the minimum from 14 to 16 (very little devices have less than 16) but this is still pending.
