### ISSUE TITLE
Datapoint creation feedback

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1392]
After adding firebase tracking, it seems users use the "upload" option quite often (on average 8.3 times per user, per day). With Jana we have been brainstorming about the possible reasons of why that is and how to solve it.

## Possible reasons
Uploads do not start fast enough and syncing of datapoints is not sequential (ie some latest datapoints may end up being sent first than a few older ones).
There is no actual internet connection uploads do not start but users may still think they are connected to the internet if the phone shows it.
Uploads may fail due to disconnection half way (unstable network).
Uploads fail due to other reason?

## Possible solutions
After submission, try syncing the submitted datapoint immediately (if connection available and user allowed datasync).
After submission add more feedback, for now we just display a snackbar but show an Activity or a Dialog saying the data point was submitted and it will be synced once a connection is available.

**Comment by janagombitova** [comment]
Here are some of the stats to paint the picture (please note that not all users are using the latest version of the Flow app where we run usage tracking, so we need to take the numbers as a representative sample).

But overall we can see that clicking to **upload** is one of the most commonly done things by our users. On one hand, it is a great validation for adding this functionality, as it is used thus valuable. On the other hand, as @valllllll2000 mentions, it raises questions on why are users using it so actively for a task Flow should handle smoothly (in limits of what is possible) on its own. 

## From the last 28 days 
<img width="613" alt="Screen Shot 2019-05-15 at 08 25 41" src="https://user-images.githubusercontent.com/12456965/57753030-48a9f200-76eb-11e9-97d1-32b15595c2b0.png">

### In comparison to other actions - by number of users 
<img width="900" alt="Screen Shot 2019-05-15 at 08 28 30" src="https://user-images.githubusercontent.com/12456965/57753177-bbb36880-76eb-11e9-8441-d4c6df285e40.png">

### In comparison to other actions - by count 
<img width="902" alt="Screen Shot 2019-05-15 at 08 29 00" src="https://user-images.githubusercontent.com/12456965/57753179-be15c280-76eb-11e9-95fb-e3594646fdda.png">

## From yesterday 
<img width="604" alt="Screen Shot 2019-05-15 at 08 26 49" src="https://user-images.githubusercontent.com/12456965/57753197-c5d56700-76eb-11e9-9d4f-4671dc639446.png">

<img width="900" alt="Screen Shot 2019-05-15 at 08 31 35" src="https://user-images.githubusercontent.com/12456965/57753241-eb627080-76eb-11e9-8a88-9c5ebf4ea971.png">

## Based on the location 
<img width="382" alt="Screen Shot 2019-05-15 at 08 26 00" src="https://user-images.githubusercontent.com/12456965/57753350-3e3c2800-76ec-11e9-9386-85482189eab8.png">
