### ISSUE TITLE
Weird Bootstrap bug with 1.13.x apk - perhaps an edge case?

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow-mobile#140]
@ichinaski could maybe ignore this one

When you perform the following steps:

* Install FieldSurvey app
* Transfer a bootstrap file to the device
* Open application

The surveys load fine however they have no names - just what appears to be the default value:

![screenshot_2014-08-13-15-45-28](https://cloud.githubusercontent.com/assets/3003031/3913117/6f16dbe0-2332-11e4-9ade-6db2a2b61cb7.png)

The same behaviour occurs if a user has been using the application for a while, then selects the "delete everything" option, and then performs the bootstrap.

However if you fetch the survey assignment with a data connection, long click to delete each individual survey, and then perform the bootstrap process - the names appear correctly (I'm guessing there's a correct reference to the names being held over in a db somewhere)

**Comment by ichinaski** [comment]
Field Survey app won't get new features -- only bugfixes --,  therefore closing this issue.
