### ISSUE TITLE
2.0 Version - Available survey translations bug

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow-mobile#141]
When I have multiple projects on my phone, and then select one and go to change the language I get the following screen:

![screenshot_2014-08-13-16-39-09](https://cloud.githubusercontent.com/assets/3003031/3913180/1a2ddf1a-2333-11e4-87a1-010d2f8a68cd.png)

However from the survey definition file we can see that french should be the only option:

![surveydefinition](https://cloud.githubusercontent.com/assets/3003031/3913196/34aba3e0-2333-11e4-89bd-18d795037e57.JPG)

I think what is happening is that the app is providing a list of all the translations across all surveys i.e. I have some different forms in different projects which have these translations available but they should not be options on this one

**Comment by janagombitova** [comment]
This is no longer an issue
