### ISSUE TITLE
Review background work tasks and services

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1414]
See in which cases it makes sense to use the [Workmanager](https://developer.android.com/topic/libraries/architecture/workmanager)

GcmTaskService and JobIntentService have issues on some devices especially ones that do not have google apps. Services are no longer allowed in the background.

**Comment by valllllll2000** [comment]
## Test plan
make sure data is properly synced

**Comment by janagombitova** [comment]
👍 all works fine as far as I can tell.
