### ISSUE TITLE
Testing offline maps

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1428]
The purpose of this issue is to detail what can be tested for offline maps new feature. 

## Currently ready features:
- [ ] Offline maps entry in navigation drawer should be visible and clicking it should take you to the offline maps list.
* Known issue: there is one separator missing at the top of that entry
- [ ] Inside datapoint map there should be a new button (top left). That button should only be visible when maps are visible and disappear when list appears. clicking it should display a dialog with a list of available offline maps or a button to create new ones. Choosing different maps should be displayed immediately either user location or saved map. If no survey is selected, the offline map button is not visible.
* Known issue: if the location is not enabled/permissions not granted on Android 6.0 we do not request it but user location is not displayed (currently it's also how it works). For usability this may need to be improved.
- [ ] Inside the list of offline areas try selecting/deselecting, renaming, deleting and viewing maps.
* Known issue: when a map is shown in downloading it will not update to "not downloading" untill you leave the screen and come back.
- [ ] From the list you can also add more offline maps, try selecting different sizes of maps.
- [ ] When the offline areas are downloaded try disabling internet (flight mode) to see how the offline areas are displayed.

## Coming soon
- [ ] Regression testing should be run (once the final version is ready) 
- [x] View one datapoint on a map
- [x] walkthrough for offline maps
- [x] Firebase stats

**Comment by janagombitova** [comment]
Hey @valllllll2000 I did some initial playing and I must say, you are an impressive developer! What functionality! Congratulations.

After a few playing around, I experienced the below issues and had a few points where I felt that not everything is clear. I expect @Kiarii will also share his comments here too. 

Please note I have been using my Samsung GT, with Android 4.4.2.  

## Side navigation design
![Slide3](https://user-images.githubusercontent.com/12456965/61534235-54899b80-aa2f-11e9-863d-811ed227017f.png)

In the side panel menu, we should divide more the Offline maps from surveys in my opinion. Now when you have 0 surveys it seems as if those are disabled or that you have a survey called Offline maps :) 

## Map selector from the data point-map view 
![Slide2](https://user-images.githubusercontent.com/12456965/61534239-59e6e600-aa2f-11e9-8bca-c2aa6a922c84.png)

- When in the Map view of data points you click on the `Map selector icon` the action button seems disabled with the grey background 
- I have created 3 maps when in the Map view of data points you click on the `Map selector icon` I no longer see the button to create a new map. Did we agree that once you create on a map you can no longer create a 2nd one from here? Possible I do not remember anymore. 

## Downloading a map 
![Slide1](https://user-images.githubusercontent.com/12456965/61534249-5fdcc700-aa2f-11e9-8b67-393e415722c4.png)

When Downloading a map you select the area, add the name and then after I hide the keyboard I get this odd black panel on the top of my screen. 

## Data points not showing on an offline map
![offline maps](https://user-images.githubusercontent.com/12456965/61534127-feb4f380-aa2e-11e9-9701-6a3fdc076bf1.gif)

I created a map in an area where I already had a few data points, already downloaded to the phone before creating the map. They show well on the `Live map` but the points do not show at all on the offline map.

**Comment by Kiarii** [comment]
Hey, I am actually running the app on an emulator as I dont have a charger for an Android device (after having switched to an iDevice :( ) I am actually super excited to see functionality coming to life :)

Some of the things I've noted so far (I cannot download a map on the emulator so for now I can test the map selection, view, edit and delete):

- Offline map screen has a [X] button but I think it should be a back icon
<img width="476" alt="Screenshot 2019-07-19 at 15 53 58" src="https://user-images.githubusercontent.com/12692444/61536573-9b7e8d80-aa3d-11e9-812d-637f2282d860.png">

- I assume this is a known issue; the Add map button in the Offline map screen misses a [+] and the selection icon on the Map tab misses a [dropdown] icon 

- If I am in a New map screen I think cancelling the action by tapping [X] should take me back to the Offline maps screen; atm it jumps back to the survey. When the New map screen has been reached directly from the Map tab, [X] takes the user back to the Map tab, we need to figure these and see that they dont end up being confusing

**Comment by valllllll2000** [comment]
@janagombitova & @Kiarii thanks a lot for this feed back, it's really helpful. I will try to address all the issues today and will let you know.

**Comment by janagombitova** [comment]
@valllllll2000 in regards to: 
>  After creating a few maps, the "new offline map button" is gone -> it was like this in the UI designs, I can change it if needed, it may seem confusing to users to have it gone if they do not know about the navigation drawer entry. By the way, we have 2 ways of listing the maps: this small dialogue and the bigger list (accessed from the navigation drawer). Would it maybe make sense for the FAB of the map also take you to the full-screen list instead of having this dialogue? What do you guys think?

I indeed felt when testing, that if I once created a new offline map from the Datapoint list-Map's tab, then I might go there again to create a new one again. Thus my question. 
Secondly, I like your idea to stop using the pop-up but instead bring the user to the full page view of the list of maps, to select which to use (or to create a new map) 

@Kiarii what are your thoughts on this?

**Comment by valllllll2000** [comment]
> * [ ]  On an Android 7 device, with an offline map selected, it seems that I can zoom out of the 'downloaded' map. i.e. the download map somehow exceeded the selection bounds... -> so for now I download offline map with zoom +2 and -2, shall I just download that zoom only?
> * (Kiarii) I think it might be dependent on how the +2 will affect storage space; if mostly used devices are not large in space, then perhaps just downloading the select area itself might make sense..

I have tried removing the max and min zoom but the downloaded size does not change so I think the zoom depends on the tiles that correspond to the selected area. When I disabled internet on the device, I could zoom out but there was a point from where I could no longer see (the surrounding areas). On the other hand you can zoom in but depending on the starting zoom you cannot get many details despite zooming in.

**Comment by valllllll2000** [comment]
> * we will need to figure the map option selection possibilities in cases where the New offline map [icon] occludes the [...] map edit option icon. in this case, the was no vertical scrolling so its impossible to bring that Icon into view

We can move the FloatingActionButton to the middle so it will never cover the menu:
![Screenshot_20190724-132214](https://user-images.githubusercontent.com/923280/61790622-06eaa580-ae18-11e9-91cc-7414c72d4a7a.png)

**Comment by janagombitova** [comment]
I would rather not... I rather we keep all our FABs in one spot. Would it be possible to add some extra space under the last element in the list to enable to scroll up and see the map edit options?

**Comment by Kiarii** [comment]
am gonna do some investigation to see if there are any guidelines how to handle this..

**Comment by valllllll2000** [comment]
Here is how it would look with Jana's solution:
![Screenshot_20190724-145313](https://user-images.githubusercontent.com/923280/61795158-0dcae580-ae23-11e9-8c89-d89061a29ae4.png)
