### ISSUE TITLE
Offline maps issues part2

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1445]
1) Datapoint info window does not disappear if another survey is selected
Steps to reproduce:
Have a survey with a location question set as "use as datapoint location". Create one datapoint. Go to map tab, click on datapoint so the info window is displayed.
Use the navigation drawer to select another survey. You will see that the datapoint marker disappears but the info window is still there.
2) When in offline mode trying to switch surveys provokes a crash (caught by sentry).

**Comment by janagombitova** [comment]
Offline maps do not work with geoshapes. I tried to capture a geoshape, but the Google map loaded and it did not matter that I had an offline map selected

**Comment by janagombitova** [comment]
Issue above seems resolved
