### ISSUE TITLE
Consider providing an offline map package with the apk

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1454]
When the used is offline if he never downloads any maps, he will see an absolute empty map. We could consider adding just a few tiles for the word map to make it nicer https://docs.mapbox.com/help/troubleshooting/mobile-offline/

**Comment by janagombitova** [comment]
My only concern is: would this not make me think that I can use the map because I see the tiles but then I actually cannot because I have no map nor internet to work with?

**Comment by valllllll2000** [comment]
> My only concern is: would this not make me think that I can use the map because I see the tiles but then I actually cannot because I have no map nor internet to work with?

makes sense, I will close this issue then
