### ISSUE TITLE
datapoint map tab scrolling issue

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1469]
There is a map-scrolling problem with the latest app on all devices. (Android, CyanogenMod, LineageOS). One can scroll vertically ok, but horizontally one can only scroll a tiny bit. Then the app wants to switch tabs instead...

This did not happen with google maps. 
Unfortunately the trick is to scroll very slowly but it can become very uncomfortable to use.

**Comment by stellanl** [comment]
Maybe we can turn off the "swipe content to switch tabs" function, and only use the tab bar?
