### ISSUE TITLE
Retrieve datapoints along with assignments

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow-mobile#1470]
At the moment, when we retrieve datapoints for an assignment, _all_ datapoints are synced to the device.  However with the work in https://github.com/akvo/akvo-flow/issues/3166 we are moving to have a selected list of datapoints assigned to a device.  ~We need to update the device implementation to only retrieve the datapoints assigned to the syncing device.~

**Comment by muloem** [comment]
@valllllll2000 Do we need to modify the implementation or is it enough that if the backend returns an already filtered list the devices do not need change their interaction?

**Comment by valllllll2000** [comment]
> @valllllll2000 Do we need to modify the implementation or is it enough that if the backend returns an already filtered list the devices do not need change their interaction?

1) If the endpoint does not change, and the returned format is exactly the same, we do not need to change anything and the change will be automatically working on all device even those that do not update.
2) If we want to change the format of the response then that would require changes in the app and in this case we would need a new endpoint so that the old versions are not broken (old endpoint will continue working as before) but users would have to update the app in order to get the new assignments.

**Comment by muloem** [comment]
So as a first perhaps we can see how it works without changing the endpoint and simply filtering.  And only go for option 2 if we discover that it doesn't work.  @janagombitova ?

**Comment by janagombitova** [comment]
I agree. It is a safer bet.

**Comment by valllllll2000** [comment]
It has been decided to create a new endpoint https://github.com/akvo/akvo-flow/issues/3167 for the new assignments for backward compatibility reasons it is not possible to use the old one. Only new app versions will use that one. App needs to send androidId. No need to send mac or phone number

**Comment by valllllll2000** [comment]
the new endpoint has been merged. Now the title of this issue implies we need to get the datapoints with assignments? Does it mean we need to retrieve them together with the form downloads? or does the user open the device, have the forms synced and then open each survey and download the datapoints per survey manually as it is done currently.

**Comment by janagombitova** [comment]
@valllllll2000 and @muloem I propose we keep the user interaction as we have it today. Meaning: Once the surveys and forms sync Al needs to select the survey and needs to go to the top-right menu and click 'download' to get the data points. This workflow keeps Al in charge to decide whether he is going to monitor, thus needs the existing data points, or not. 

**Just as a side note:** we should keep the rules as they are today: 
* only download submitted forms for the data points that are assigned to the device 
* if the registration form is not assigned, but monitoring forms are, allow to download data points but not to submit a new data point with the registration form 

Considering we will introduce this "new" functionality with a new version I suggest: 
* we bump the app version
* we create a new walkthrough screen introducing the change (in a separate issue)

**Comment by valllllll2000** [comment]
Considering this scenario:
Al has some datapoints of the device which are in not in a green state because their submissions were not submitted (saved state) or they did not get to be sent to the dashboard (submitted state). Shall we delete them when he syncs the datapoints and they are no longer assigned?

**Comment by janagombitova** [comment]
@valllllll2000 how do we handle that today?

**Comment by valllllll2000** [comment]
> @valllllll2000 how do we handle that today?

we keep everything but today datapoints cannot be unassigned

**Comment by valllllll2000** [comment]
> My first hint would be to make sure the data points are synced out before we delete anything from his list
OK so we keep the datapoints that are saved/failed/submitted and delete the uploaded/downloaded ones if they are not in the new list right?

**Comment by janagombitova** [comment]
I would suggest: 
* if all data points are submitted and synced but some have been unassigned in the meantime, upon downloading data points we remove those that are not assigned from the device. 
   * do you think we need to tell Al which data points were removed as they are not assigned anymore? Like an overview list/pop up? 
* if there are data points with submissions that are submitted but not synced yet (submitted state) we should first try to sync them out before we download data points in. Don't you think? And then we can delete them following the 1st point 
* if there are data points with submissions in the saved state, here I assume the enumerator is not done yet and still needs to finish something. So I would not touch these. 

What do you think?

**Comment by valllllll2000** [comment]
@janagombitova all seems reasonable but I am wondering: 
1) What if submission failed, then we should keep those in your 
1) But then what if Petra decided that they do not want any more submissions for the unassigned datapoints? Do we still want to submit this data?
1) I had this idea: what if we do not delete the datapoints but "hide" the unassigned ones. In this case there could be a menu option to reveal the deleted datapoints and Al would be able to finish his work on them or submit them?

**Comment by valllllll2000** [comment]
In this issue I will make sure to call the new api and delete unassigned datapoints unless they are saved.
Here are the other issues:
Inform about deletion: https://github.com/akvo/akvo-flow-mobile/issues/1513
Make sure we do not allow unassigned submissions: https://github.com/akvo/akvo-flow-mobile/issues/1514
