### ISSUE TITLE
Save time of creation of photos/videos

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#1482]
# Context 
## Why do we create this issue 
Photos/videos besides enriching the dataset serve as a way to validate the data. They answer questions like was this photo taken in the field, can I trust the enumerator went to the location, can I trust the data. We read the geotag from the EXIF file (if available) to ensure the reliability of photos and in an extension of the submission. 

## If this change is successful what might we observe?
* more photos being captures 
* more analysis on photo metadata 

## Current status quo
There are two ways to add a photo to a Flow submission: 
- capture it on the spot
- add it from the device's Gallery 

In both cases, we read and save the photo geotag (if available). However, sometimes there is no geotag. This can be because the user disabled geotagging in the device Settings or because there were issues with capturing the GPS data. So how can Petra analysis the data know if this photo is trustworthy or not if she missed the geolocation data? 

# Opportunity 
The idea is to also save the time of creation as a timestamp with the photo. If a photo is taken on the spot it will match the submission time stamp and the duration. If a photo is added via the Gallery, its timestamp will be from the past in comparison to the submission date.  

## How will this benefit our users 
If we solve the above-mentioned problems we assume these benefits to users:
- Petra can trust the data coming in as she has more metadata to cross-check the submissions 

## How will this benefit Akvo 
If we solve the above-mentioned problems we assume these benefits to Akvo:
- Remain GDPR compliant by not saving the location information if the user disabled it on his/her device 
- Provide other ways to cross-check the quality of data thus creating more trust in our tools in general

# Next steps 
- answer if this is valuable and feasible --> @Kiarii, @valllllll2000 and @muloem what are your thoughts?
- if yes how will we visualise this data with the photo on the app, in the Data tab, push the data to Lumen, in Data analysis export

**Comment by Kiarii** [comment]
It sounds like an opportunity worth exploring, to be of value, we should make it easy for Petra to deduce the time differences. Would that need doing on the data view or data analysis end? On the analysis side of things, would the end goal be for Petra to identify outliers i.e. photos whose timestamp are from a distant past in contrast to a form's submission time? I also assume we have had some research data on photo analysis, is there a link to such?
