### ISSUE TITLE
When offline it seems you can still download an offline map 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#1499]
# Context 
With 2.8.0 we release a new feature - Offline maps, that allows Al to download a map to his device and use it when offline and in the area. Since its release, it has been picked up by 200 users already confirming the value of this extra feature.

Our goal is to make the use of the Flow app as easy and clear as possible to our users. This also means to inform our users when something will not work because of connectivity issues. 

# Opportunity 
Picture the situation that Al turned his phone to 'airplane' mode when in the field. He is now back in the office and is preparing for another data collection round. When he tries to download data points (for example) we show that it is not possible as he is offline. 

![Screenshot_2019-10-02-11-52-05](https://user-images.githubusercontent.com/12456965/66035795-179c5380-e50c-11e9-8d63-ab3784a110f9.png)

But when if he tries to download a map (and the tiles are still cached in his phone) we show him that it is possible and start downloading. But he is offline, so downloading should not be possible. Then it can appear that it takes forever to download... Should we inform Al that he is offline? Will the download of the map resume automatically once connected? 

![offline maps](https://user-images.githubusercontent.com/12456965/66035923-5af6c200-e50c-11e9-886c-6a99249587a7.gif)

# Next steps 

This issue is not a blocker for the release, but a next improvement to handle if we have some free time in the next weeks/months. 

The next thing to do is to agree on how to inform the user that she cannot download a map as she is not connected to a network. @Kiarii and @valllllll2000 can you two connect on this?

**Comment by Kiarii** [comment]
I will revisit the earlier work we had done in the mockups and post, I think we had a notification for this particular case..

**Comment by Kiarii** [comment]
Making a note so I dont forget it. So, obviously if Al's device is offline, he shouldn't be able to go from the offline maps screen to the New map screen; the check for connectivity should be done on hitting the [+] create new offline map button and Al is informed of the lack of connectivity via a snackbar and cannot go to a New offline map screen until the device has a data connection.. 

But in the case that the device was connected and the connection was lost during downloading, a snackbar reading "Download failed. No connection" with an action "RETRY" Should be shown

**Comment by valllllll2000** [comment]
Ok let me try to explain... If there is not internet the user will not see a map to download, it will be blank so I do not think he will try to download it. On the other hand, when user presses download it actually creates the map but mapbox will decide when it downloads it in the background (plus there are several parts, not just one chunk). I do not have much control over it. In Android it's a bit hard to know if the device is online or not, so for example, before opening the map, if I check, the device may be temporarily offline dues to low connectivity. 
My proposal:
Once we create the offline are, show message that the area was created and will be downloaded in the background. Maybe say if we are offline. We already do not allow to use an offline map if it has not been downloaded. What do you guys think?

**Comment by Kiarii** [comment]
If I understand things correctly, it seems like we are talking about 2 different use cases - airplane mode & lost connectivity - which merit specific handling in their own right:
#### 1. Airplane mode (WiFi & data disabled)
Which I think Jana described; the challenge is to figure out how to handle “Airplane” mode across offline map download functionality; if this is the case, 
- the device should not load a map, in the “New map” screen
- the “Download map” should either be disabled or a notification should be shown if it is tapped. This would save us from having to handle the map download processes that follow..

#### 2. Connection lost after hitting “Download map”
This is how I understand Valeria’s description.. This means we need to 
- tell the user that the map will download when the connection stabilizes; not sure if this example (which is definitely outside my league) helps us e.g. https://developers.google.com/web/fundamentals/instant-and-offline/offline-ux but
- we cannot make the user wait indefinitely for the download; assuming that they are setting up the device for new field work. There should be some “timeout” check after which we can simply say the download failed (as with the data points) and the user can try to sort out the connection and Retry
 
@valllllll2000 and @janagombitova confirm if my understanding is correct or not..

**Comment by valllllll2000** [comment]
@Kiarii @janagombitova in my opinion, we use Airplane mode for testing offline but I think it's unlikely the use will have it on and if they do they probably know about it. The lost connection in theory should work exactly as described in that document but in this case, mapbox handles it, I will check their documentation and see how I can get information about download status.
