### ISSUE TITLE
Navigate to data point

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#1505]
# Context 
When we changed to mapbox on the Flow app, we heard from our users from the SNV Biogas Programme what they 'lost' a functionality. It appears that for some of the users (depending on their Android version and app version) they had to option to `Navigate to this location`. When they were looking at data points on the app map or one data point on the app map, Google maps had the option to navigate to the selected data point. In practice they selected the data point, hit the Navigate button, Google maps were opened automatically with the data point coordinates and the route on how to get to the data point was set in the Google maps app. 

We did not know this was possible, so it came as a surprise. When talking to the users, we learned on how and why they used the feature and I thought it might be interesting to talk about and to see if we want to provide something similar. 

## Current status quo
Today in the Flow app you see the location of your data point(s) and then a blue dot indicating where you are located. Data point location and the Flow map are used for monitoring data collection exercises. This means that the enumerator goes back to the field to submit another round of data to the data point. 

# Opportunity 
## Why do we have this issue? What are we trying to solve? 
Today we provide the point location details to the enumerator, her location and the previous submissions to help her figure out which point she is going to update now and ensure she is at the right data point. But what if this is her first time in the area? What if the points are located off the main track? How will she know how to get there? 

Secondly, data collection is quite a costly exercise so the faster an enumerator can get to the data point, the more cost savings she creates. 

## The idea 

**Could we help our enumerator find the way to a specific data point?** 

Here is how a parking booking app I use supports a similar case
<img width="893" alt="Screen Shot 2019-10-29 at 15 04 10" src="https://user-images.githubusercontent.com/12456965/67778631-beb8d000-fa63-11e9-85ea-eb50d71a330e.png">

## How will this benefit users? 
* It will **not** benefit all of them, as not everyone is using monitoring and some might be going back to the data points that they created themselves, so they know how to get there
* it will benefit users who are going to monitor for the 1st time 

## How will this benefit Akvo? 
* it will give us a market edge as this is another functionality that supports scaling data collection and making it easy to do so 

# Next steps 
- brainstorm how we could solve this 
- decide if it is a problem worth solving

**Comment by valllllll2000** [comment]
Interesting idea: how different would it be from our currently showing the single point on the map? 
![Screenshot_20191028-093415](https://user-images.githubusercontent.com/923280/67663875-bc248080-f966-11e9-910d-71b99d325748.png)
![Screenshot_20191028-093452](https://user-images.githubusercontent.com/923280/67663882-bf1f7100-f966-11e9-926f-00a9dabd72b4.png)

Would it be a feature where we allow using google maps app to navigate to that data point from the current user location, ie "show me the way to get there"?

**Comment by janagombitova** [comment]
Hahaha @valllllll2000 you are too fast ;) 
I was still in Draft mode. I will try to specify the idea in more detail today/tomorrow.

**Comment by janagombitova** [comment]
@valllllll2000 I updated the description
