### ISSUE TITLE
Error syncing forms, but syncing works 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#1512]
I noticed since we released the new assignments on Flow that I now get an error on the Flow app `Error syncing forms` but the forms assigned to my device actually sync in well. @valllllll2000 can you take a look if you can reproduce it? 

Steps to take: 
1. Create a new assignment with survey forms you do not have on the app 
2. Reopen the app
3. Survey forms download but you see the error

**Comment by valllllll2000** [comment]
I have seen some errors in sentry with this format:
```
retrofit2.adapter.rxjava2.HttpException: HTTP 403 Forbidden
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:54)
```

**Comment by valllllll2000** [comment]
## Test plan
There was a fix on the dashboard for this so forms which are not published cannot be assigned
There may be some forms which were assigned but are not published they still may give errors.
A part form that what has been done is adding more logs to track where exactly the error happens in s3 or google app engine

**Comment by valllllll2000** [comment]
After the latest fixes on backend this should no longer happen
