### ISSUE TITLE
Monitoring: Inform/Warn about submitting another monitoring form for the same data point 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#1519]
# Context 

Our goal for F+L+C is to be a simple data tool that works on scale. One of our unique functionalities is monitoring and more and more it is being used on national levels. This means we need to make sure it is easy to use on a scale. By easy to use we mean, easy to capture data on a large scale, but also easy to analyse the data. 

## Current status quo

One of the many problems we start to see with large monitoring data exercises is that monitoring form submissions do not match the data point (the registration form). The most common issue (and the easier one to see) is for cases when each data point should be monitored once in the data collection exercise. We see more and more, that often more than one submission is made to one data point to its monitoring form and then another data point misses the monitoring form submission. So then the data analysis does not know which of the two submissions is for the data point and which other data point that submission should go to.

Today Al follows these steps: 
* goes to monitor data points 
* selects the right data point 
* submits monitoring form 
* sees the list of forms with an indication that the monitoring form was recently updated
* then he needs to select another data point and go through the entire workflow

![Monitoring](https://user-images.githubusercontent.com/12456965/68937149-32fdae00-079c-11ea-9322-2ebd6fa65031.gif)

# Opportunity 

## Why do we have this issue? What are we trying to fix? 
Often more than one submission is made to one data point to its monitoring form and then another data point misses the monitoring form submission. So it seems Al after submitting the monitoring form to data point A, does not go to data point B to submit the form again, but just click on the monitoring form in data point A and does another submission. 

We do not know why this happens. It seems the indication `Last submission: Moments ago` is not enough. We only know from analysing the data that it happens often, that some data points have more monitoring submissions than they are supposed to have and some miss the submissions. 

We assume by assigning specific points to Al, will reduce this issue from happening. We will only know once the change is out there and partners start using it. We also know applying strick rules (you cannot submit more data after this deadline, or you can only make one submission to this monitoring form in this timeframe) may work in theory but in practice, data collection projects get delayed. So applying hard rules is something we need to research well before we consider this option. 

So the question is **can we somehow make Al aware that he is adding another submission to the same form to the same data point?** 

## The idea 

Instead of enforcing strong restrictions (for now) can we in a subtle way inform/warn Al that he is going to make another submission to the same data point (for the same form) - is he sure this is what he wants to do? Or should we bring him to the list of data points after hitting submit, instead of to the list of forms for the data point? Is there anything else we can do? 

## How will this benefit users? 
* might (big guess) reduce the cases of monitoring forms not being submitted to the right data points 
* if this assumption holds true, then it will reduce time on data cleaning and analysis 

## How will this benefit Akvo? 
* support our monitoring feature and show we listen to scalability issues and work on supporting scale in an easy and mistake-free way

# Next steps 
@Kiarii and @valllllll2000 - let's talk about this opportunity. I am aware we are jumping a few steps here, but if we can push out a small addition to the app, and add usage tracking to it we might learn a bit more about the issue at hand to then look at further solutions to it 

The idea is to see if we can come up with a solution that will not take more than **one week of work** (for Kiarii and Valeria together). If not, we do not do it and push resolving the problem for later with proper research

**Comment by valllllll2000** [comment]
@janagombitova @Kiarii 

#### Option 1
taking the user back to the datapoint list is quite easy to do and I think may be a good idea, we already do that when there is only one form.

#### Option 2
Another option could be after submitting (pressing submit button) we display a Submitted screen where we offer 2 options:
* Submit another
* Go back to datapoint list

<img src="https://user-images.githubusercontent.com/923280/81374105-c0440e80-90fe-11ea-9504-7b251c5a70c3.png" width="200" />

**Comment by Kiarii** [comment]
I think for now what we might aim to do is to make Alphonso explicitly confirm that he wants to make another form submission. 

Without changing where he user ends up - in the app - after submitting the form (for now), because he can as easily reopen the same datapoint and the recently submitted form and start filling it again, we can just present a dialog where he has to confirm that he indeed intends to make another submission of the same monitoring form (to the same datapoint)

A small issue opens up on the side though; what time frame, if any, should apply to determine when not to show the dialog? Or what other mechanisms can we use to deduce that a new monitoring (for the same assignment) need not be confirmed?

**Comment by valllllll2000** [comment]
I think the reason he resubmits for the same datapoint is we take him not to the list but to the list of forms which is maybe not useful unless he needs to fill up either another monitoring form for the same datapoint or the same monitoring form, that is why I was suggesting the solutions above.
The solution with the dialog adds complexity to the issue but can be done, I think. The rule would be once he already submitted one form and selects the same one, ask him if he is sure. I would not know how to phrase the request though?

**Comment by janagombitova** [comment]
I am talking with Geert on Wednesday and will ask about this issue as he raised the problem originally. 

**Why do we bring the user back to the list of forms for monitoring surveys?**
We do so because often a monitoring round is not just for one form, but for multiple. So this means that when Al is updating the data point next month, he needs to fill in more than one form. By keeping him in the list of forms we ensure he stays on the right data point and can fill in the next form.  

**The problem: He submits THE SAME form to THE SAME data point repetitively**
But indeed, because we bring Al to the list of forms, there is a higher chance he will submit the same one to the same point. Thus the idea to ask him if he is sure that he wants to do that rather than changing the workflow that supports most of the cases. 

**What time frame** 
24h?

**Comment by valllllll2000** [comment]
@janagombitova @Kiarii So here is how I understand what needs to be done:
User opens the list of forms and clicks on that form, from that point:
- First submission for that form: we let him fill it as usual
- This is not the first submission but the last one has been made more than 24 hours ago: we let him fill it as usual
- This is not the first submission and the last submission to that form (and that datapoint) has been made less than 24 hours ago, we show a dialog asking him to confirm he really want to fill that form. What could the text be:
"There is already a recent submission for the same form, do you wish to submit another?"
What would happen if he says yes and then asks presses the same form once more (say he needs to fill the same form 5 times) he will see the dialog again? or does it never happen?

**Comment by janagombitova** [comment]
@valllllll2000 yes, I think that is a comprehensive summary. 

> What would happen if he says yes and then asks presses the same form once more (say he needs to fill the same form 5 times) he will see the dialog again? or does it never happen?

I think for starters we would keep on asking (and being annoying) and then we will hear that we are annoying and thus learn if this actually happens. From what I know today, submitting the same form to the same data point in a 24h limit does not happen. 

Now the question is, is this something small to do (a week's worth of work besides your RQG and security work)?

**Comment by Kiarii** [comment]
I think Jana's approach more than suffices for now..
The issue is a bit sticky but am glad it took my mind off RQG stuff for now.. so I took the liberty to envision two options how the dialog might look; I think we ought to mention the form name in the dialog, in case there is more than 1 monitoring form - in which case we are not ambiguous about what form we are referring to in the dialog (not sure if we have such instances though) 

![image](https://user-images.githubusercontent.com/12692444/81898091-a56f0f80-95c0-11ea-84ad-68186f3efb7f.png)

**Comment by valllllll2000** [comment]
I like both versions :top: ! Not sure which one to pick, though, I like A for being shorter but B gives more info to the user :roll_eyes:

**Comment by janagombitova** [comment]
Let's go for B as it gives more info. I would add a space between the two sentences to make it easier to read.

**Comment by valllllll2000** [comment]
<img src="https://user-images.githubusercontent.com/923280/82071161-02a8b500-96d6-11ea-85f2-12a5e8c9cbb9.png" width="200" />

**Comment by janagombitova** [comment]
Since its launch, we see an uptake in the number of times users are shown the dialogue. We can conclude that indeed, cases when users were to submit the same form to the same data point happen more often than wanted. Unfortunately, we do not have a way to monitor if the quality of monitoring has increased. We can only assume that because of this dialogue, fewer cases happen when submissions were wrongly made, thus increasing the quality of monitoring exercises. 

Ideally, we aim to see these initial uptake numbers to decrease. By improving the app and how users monitor - we aim to have less of these cases. 
<img width="1009" alt="Screen Shot 2020-08-11 at 13 14 34" src="https://user-images.githubusercontent.com/12456965/89891276-111f4380-dbd5-11ea-9f14-63e2e6f28467.png">
<img width="393" alt="Screen Shot 2020-08-11 at 13 15 54" src="https://user-images.githubusercontent.com/12456965/89891278-11b7da00-dbd5-11ea-8028-0ce10478fafa.png">

**Comment by janagombitova** [comment]
Since its launch, on average 25 times for 998 users, preventing possibly 23,972 wrong submissions. What is a great success of such a small change 👏 

![Screenshot 2021-01-13 at 10 44 47](https://user-images.githubusercontent.com/12456965/104435206-6698bb80-558c-11eb-8cb9-02a058b814ae.png)
![Screenshot 2021-01-13 at 10 44 30](https://user-images.githubusercontent.com/12456965/104435216-68fb1580-558c-11eb-8828-5a5739a36bea.png)
