### ISSUE TITLE
In app language modification setting

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1527]
The objective here is to discuss the necessity to support language change on app level.
Normally in Android, user changes the language on device level and the apps are modified automatically. By default, the apps use the language set on their device. 
In flow app, we provide a way to change the locale but it's a bit "hacky" and can stop working at any time #1526. Shall we continue to provide support for this language change?

* The app supports these languages: es,fr,hi,id,km,ne,pt,vi,nl
* Android 4 provides all these languages except km (Central Kmer) and ne (Nepali)
* Android 5.1 has all the languages we support

Is there a use case where we want users to have the app in a different language than the phone?

Whether we continue supporting the language change or not, I would definitely encourage switching language on the device level, except for the case where the language is not available.

Update: by default we support the language change automatically and it works, the issue is once you set a different language than the device locale, the devices changes will then be ignored.

**Comment by janagombitova** [comment]
@valllllll2000 my initial thought is - what we can simplify we should. So if the user has their device in Vietnamese and Flow app supports the language, we should just show the right language 'automagically'. 

Can you and @Kiarii and @muloem pick this up once the assignments and tasks in To do are done. I think it is a worthy improvement

**Comment by Kiarii** [comment]
> Update: by default we support the language change automatically and it works, the issue is once you set a different language than the device locale, the devices changes will then be ignored.

My assumption would be that this is okay, as long as the user is able to go into the app settings and change the language as desired.. and if they make a fresh install (we could consider this as a reset of sorts) the app could default to device language.. lets revisit this in its time though

**Comment by janagombitova** [comment]
@valllllll2000 the confusion on how the app language is set is creeping in again. (https://akvoo.reamaze.com/admin/conversations/changing-languages-does-change-language) As we seem to agree here, we should remove the language setting on app level and simply follow what setting the user has on the device level. 

How much effort do you need to make this happen?

**Comment by valllllll2000** [comment]
I think using the device setting definitely makes more sense. I suspect when this setting was added, there were not many languages available but nowadays language support is very extended. Luckily removing is much easier than adding so it will not take too much effort.

**Comment by janagombitova** [comment]
OK. Will add it to the To Do list on Zenhub then
