### ISSUE TITLE
Move crashes to firebase crashlytics

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1531]
Lately we have experienced rate limitations in sentry and are no longer receiving any new crashes for this time period.
When 3 years ago we took the decision and chose sentry, crashlytics belonged to Fabric https://github.com/akvo/akvo-flow-mobile/issues/551 but now it has been bought by google and is integrated into firebase. We already use firebase analytics and firebase test lab so I think it makes sense to discuss the possibility to move crash reporting for the app there too.

###### Advantages:
Do not block the rates for other projects that are on sentry as the app receives many events.
Better insight in crashlytics, analysis, device information, what led to the crash. Sentry could have that too but we have to write the code whereas Crashlytics has it by default.
Free
The change is only a few lines of code

###### Drawbacks
Not open source and belongs to Google

**Comment by janagombitova** [comment]
@valllllll2000 can you discuss this with @dlebrero and @muloem and decide what is the best for us? If we move the app to Firebase, we should do the same for all the apps - so also the Caddisfly app.

**Comment by valllllll2000** [comment]
> @valllllll2000 can you discuss this with @dlebrero and @muloem and decide what is the best for us? If we move the app to Firebase, we should do the same for all the apps - so also the Caddisfly app.

I just checked the caddisfly and it is nowhere near the limit on sentry so I would maybe start with flow first and if we really like it we can move caddisfly.

**Comment by valllllll2000** [comment]
Here is a link with more info about it https://firebase.google.com/docs/crashlytics?authuser=0

**Comment by dlebrero** [comment]
I am happy with whatever @valllllll2000 decides, but please make sure that we are solving the right problem. 

I do not see "rate limitations" as the problem to be solved. 

Couple of considerations:
1. Firebase is not free. It has "Generous limits for hobbyists" as a starting point.
1. I am ok with depending on Firebase as I assume the dependency is not intrusive given that "The change is only a few lines of code"
1. Given that "The change is only a few lines of code", then we can always experiment and rollback with minimal effort.

**Comment by valllllll2000** [comment]
Ok over the weekend, i have experimented with Crashlytics but also I have found this article that explains it https://medium.com/letsenvision/effective-logging-in-production-with-firebase-crashlytics-9fb3af9f242d

**Comment by valllllll2000** [comment]
crashes received by crashlytics
