### ISSUE TITLE
Remove the need for password on Flow app 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#1532]
There are a few tasks in the Flow app where Al needs to input the Flow app password (generic one for all users) to do the action. Over time we see that the role of this password is redundant as we either provide secondary warnings or Al needs to have specific information from the Flow online workspace to complete the action. The password complicates the workflow and no longer plays a 'warning' role. Thus it is time to remove the password. 

# Download form with the Form ID
There are three ways Al can get a form to his device: via an assignment, via manual transfer, by typing in the form ID. To know the Form ID he needs to have access to the survey form on the online workspace or someone with access needs to give him the ID. 

Today when downloading a form via ID he selects the action, needs to type in the generic password and then needs to type in the ID. As there is a small chance he can guess a form ID and he either needs access to Flow's online workspace or has someone who tells him the ID, there is no need for the password. To get a form in via the ID input is complicated enough. 

# Delete everything & Delete collected data and images
Today when on the app Al can `Delete everything`. This deleted his user name, all the surveys and collected data on the device. He clicks to delete everything, he then needs to input the password and then he also needs to read the warning message and confirm the action. 

Having him input the password is redundant here as we have the validation of the action clearly in the screen to make sure he is sure he wants to proceed. 

Same goes for Delete collected data & images.

# Reload all surveys 
Similarly to the cases above, Reloading all surveys requires Al to input the passcode and then also to confirm that he is sure he wants to delete and re-download all surveys. We should skip the password step.

**Comment by valllllll2000** [comment]
tested download forms, download form, delete everything and delete collected all works without password
