### ISSUE TITLE
Crash when trying to submit a signature question

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1533]
When trying to add a signature, the app crashes while trying to open the SingatureActivity:
```
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.akvo.flow/org.akvo.flow.presentation.signature.SignatureActivity}: android.util.AndroidRuntimeException: requestFeature() must be called before adding content
```

**Comment by valllllll2000** [comment]
## Test plan
This issue due to the language change.
Change the language to a different one than on your phone
Test submitting: Signature, Image, Video, Barcode, Caddifly (with image even better), Geoshape
Make sure the answer to these is saved correctly.

**Comment by janagombitova** [comment]
All works fine, I did not find any issues 👍
