### ISSUE TITLE
Outdated form version is used if the form is updated while drafts were already started

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow-mobile#1544]
The version number of the form against which responses are submitted becomes outdated if the form is updated while the responses are still in draft mode after having started with a previous form version. Since we intend to use the form version to identify when issues arose out of having a problematic form definition, this issue may result in misleading conclusions when trying to chase down form version related issues

Steps to reproduce
1. Create a new data point and start answering questions regarding that datapoint.  Save the draft responses.

2. Update a question in the survey definition and publish it again on the dashboard. Confirm that the version number is increased. 

3. Update the survey version on the device and the reopen the draft and continue editing.  The version in the draft doesnt change to the latest version.

**Comment by muloem** [comment]
_Version number shown correctly before editing draft response_
![Screenshot_20191204-124556_Akvo Flow](https://user-images.githubusercontent.com/533336/70141506-7a8aa200-1697-11ea-95f6-d96ddfa02e75.jpg)

_Outdated version number shown_
![Screenshot_20191204-124617_Akvo Flow](https://user-images.githubusercontent.com/533336/70141510-7cecfc00-1697-11ea-871d-c675aba55789.jpg)

**Comment by valllllll2000** [comment]
The problem is the form (questions) is loaded from xml but the saved form instance has its own form version in the local database.
Since the form xml is automatically replaced we need to:
* Update the form version of the submission 
* Display the updated form
* Notify the user the form version has been updated
