### ISSUE TITLE
Improve question groups view display

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1563]
We already have this issue https://github.com/akvo/akvo-flow-mobile/issues/1201
for the design but in a support issue there has been a remark:

> while we repeat the repeat group questions for more than 30 times, Flow software and mobile phone gets very slow to continue the survey. We are using Samsung Galaxy J2 Pro for this survey. The survey is about water taps within a schemes, and 1 schemes can have as many as 60 taps so in some places we may have to repeat TP group for 60 times or more. Kindly also let us know how can we solve this issue.

I was not able to reproduce the issue on my phone but one reason could be linked to the fact that we use regular LinearLayout inside ScrollView to display all the views. This should be no problem if there are few question in a given group but in the case of many repeated groups or many questions, all the views are in memory even if they do not need to be displayed on the screen. In this case, it would be much better to use a RecyclerView to display those views.

**Comment by Kiarii** [comment]
(dropping ideas here for when we might address this)
 
I had considered the use of a [backdrop component to better support orientation and navigation](https://invis.io/ZQYQSWY64E5#/325763659_Form-_QG-_Group_Reveal) in the question group.. From Material documentation it appears [Google has not rolled out the backdrop component](https://material.io/components/backdrop) maybe @valllllll2000 you can confirm this. 

The alternative would be to use a [Bottom sheet](https://material.io/components/sheets-bottom#anatomy) component.
