### ISSUE TITLE
Walkthrough for new datapoint changes

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1569]
The way datapoints are assigned and retrieved will change with #1470 we need to display a short message in the walkthrough to replace the current offline maps one https://github.com/akvo/akvo-flow-mobile/issues/1436

How about:
"Data point assignment"
"You can now assign individual data points to a device via the dashboard. When you press 'Download' only the assigned data points will be downloaded"

The image should also be replaced by something else.

![Screenshot_1579082610](https://user-images.githubusercontent.com/923280/72424696-b0d33b00-3786-11ea-9c0b-28dcdbf3af62.png)
@Kiarii @muloem what are your thoughs on this?

**Comment by Kiarii** [comment]
> "Data point assignment"
"You can now assign individual data points to a device via the dashboard..." 

@valllllll2000 am a bit lost on the context here, the suggested text seems more appropriate for the dashboard than the app; may be I am missing sth. could you describe the context more..

**Comment by valllllll2000** [comment]
@Kiarii  see the comment by Jana here https://github.com/akvo/akvo-flow-mobile/issues/1470#issuecomment-537361272

**Comment by valllllll2000** [comment]
@Kiarii via slack

> Since this affects “monitoring surveys” (if I am right) the screen could be titled as you suggest “Datapoint assignment” and the text could say “For monitoring surveys, when you press ‘Download’, only specific datapoints assigned to your device will be downloaded”.

**Comment by Kiarii** [comment]
Or should it say “When you download monitoring forms, only specific datapoints assigned to your device will be downloaded”?

**Comment by valllllll2000** [comment]
No because we download datapoints in this case, not forms, forms are downloaded automatically

**Comment by valllllll2000** [comment]
“Datapoint assignment” and the text could say “For monitoring surveys, when you press ‘Download’, only specific datapoints assigned to your device will be downloaded”..
maybe we could consider the move_to_inbox

**Comment by valllllll2000** [comment]
Here is the final result
<img src="https://user-images.githubusercontent.com/923280/73856108-44070a00-4835-11ea-8e79-11be9f817e69.png" width="200">

**Comment by Kiarii** [comment]
looking good 👍 
Perhaps we could gray-out the download icon a little bit so it doesnt look (too much) like an interactive element. For the text, we could shorten it; "In monitoring surveys, when you press 'download' only datapoints assigned to the device will be downloaded"

**Comment by valllllll2000** [comment]
<img src="https://user-images.githubusercontent.com/923280/73944453-e46f3400-48f2-11ea-80dd-77e8ff262553.png" width="200">
