### ISSUE TITLE
Disable adding image from the phone image gallery for photo questions

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow-mobile#1576]
# Context 
## Why do we create this issue 
From the issue https://github.com/akvo/akvo-flow-mobile/issues/1136#issuecomment-412509193 we changed the functionality of the photo question to enable an image to be added to a survey form the image gallery on the phone, in addition to the usual way i.e. taken with the camera.

In some cases, though, Salim would like to enforce that Alphonse is not able to add images from the phone gallery in order to validate that the image was taken in the location at which is is supposed to be taken, and not added later on or taken in a different location.

When we enabled the gallery option we discussed whether or not this should be considered based on user requests.
> On your question if we should allow the survey creator to limit where the photo comes from, I to be honest do not know. But I do think we will learn from our users once this possibility is out, if they want more limitations or not. I can imagine it may improve the quality of the data if you can enforce that the photo has to be taken on spot, but that is just a guess. We can always first release these changes to the app and then learn about the limitations. 

## If this change is successful what might we observe?
* Alphonse is only able to take photos if a photo question has disabled adding gallery images.
* Salim is sure that a photo was taken rather than added from any location.  Complemented with the photo geo coordinates, we can verify that the photo was taken in the location expected.

## Current status quo
Photo questions come by default with the two options to either take a photo or add from the image gallery. 

# Opportunity 
For the cases where Salim needs to validate that photos were actually taken, we allevaite these concerns, while still providing the possibility for other uses who do not mind having photos added from the gallery.

## How will this benefit our users 
* Improved trust in the photos that are submitted with the forms submissions.

## How will this benefit Akvo 
* Improve the trust in our tools and possibly lead us on a path to shape our tools such that users can trust the quality of the data coming out of them even more.

# Next steps 
* @Kiarii, @valllllll2000 any thoughts on this? 
* Should we also consider this for videos?

**Comment by valllllll2000** [comment]
I am not sure I fully understand: you want the survey have a setting such as:
- [ ] Enable photos added from the image gallery
Should the setting be enabled or disabled by default? If so, this should be added to the survey definition xml.
Or do you mean to disable the gallery pictures altogether?

**Comment by Kiarii** [comment]
If I understand the issue correctly, the question is whether we can for both video and images provide options in the survey editor: a) upload from gallery or from camera and b) upload only from camera; in the case of b) providing GPS tag to enable data quality verification..

The ideas seem okay to me, just wondering how much of an effort this would be to implement on the survey editor and even more, is it something that our partners really need, or is it just a nice to have? 

Would it be worth to poke around with the partner team and see if there is a need around these or should we focus effort at some other issues?

**Comment by muloem** [comment]
@valllllll2000 so by default we have the current situation that a user is able to either take a photo or upload from the gallery. 

But incase the survey managers do not want to allow the users to add photos, we want to have an option that is _Disable gallery images_ or something like that to hide the option to upload from the gallery.

@Kiarii yes thats correct except that we already provide the GPS tag. It would just be a question of ensuring that the user cannot upload a photo from the gallery

**Comment by janagombitova** [comment]
Reading the issue, should it not live in the Flow repository considering this is a setting Salim will add to the form question when defining it?

**Comment by valllllll2000** [comment]
@janagombitova yes there should be an issue in flow repo but we need this one also for the app to be able to process the setting and enable/disable gallery for each question

**Comment by janagombitova** [comment]
@valllllll2000 All right. Will create and issue in flow repo too.
