### ISSUE TITLE
Flow lists theme

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1593]
### Scope
This issue tackles the list items styling in a general sense. We have them common to Datapoint list, Form list and Response list.

### Background
> btw had there been a special reason to use different backgrounds for the list items? I think a white background for all datapoints or if need with dividers for list items would make list items visually clean; I am referring here also to list items under Forms and History tabs.. but may be this is an different issue for another day

_Originally posted by @Kiarii in https://github.com/akvo/akvo-flow-mobile/issues/1592#issuecomment-594347929_

Currently, the lists of items in flow app are displayed with alternate backgrounds:

<img src="https://user-images.githubusercontent.com/923280/75770860-197f7280-5d49-11ea-9478-088c85114a98.png" width="200" />

### TODO
Remove alternate backgrounds, list backgrounds should be white
Add a small divider to the lists

**Comment by valllllll2000** [comment]
Here is a screenshot @Kiarii what do you think
<img src="https://user-images.githubusercontent.com/923280/76081477-78dbbd80-5fa9-11ea-9e08-d52751d57199.png" width="200" />

**Comment by Kiarii** [comment]
@valllllll2000 we can bold just the datapoint name, to make the text easier on the eye; sth like this
![image](https://user-images.githubusercontent.com/12692444/76201386-d9623900-61fb-11ea-89bb-5d97dd47e0cd.png)

**Comment by valllllll2000** [comment]
@Kiarii we bold the new datapoints as per issue https://github.com/akvo/akvo-flow-mobile/issues/1592

**Comment by Kiarii** [comment]
I've copied my comment over to #1592

**Comment by valllllll2000** [comment]
Here is the updated screenshot for the datapoint list

<img src="https://user-images.githubusercontent.com/923280/76405587-a600e500-6388-11ea-8503-9845f1410aa5.png" width="200" />

**Comment by valllllll2000** [comment]
Here are the updated screenshots
<img src="https://user-images.githubusercontent.com/923280/76427327-7368e380-63ac-11ea-80b6-9af048029763.png" width="200" /><img src="https://user-images.githubusercontent.com/923280/76427504-ac08bd00-63ac-11ea-919a-be218f777e87.png" width="200" /><img src="https://user-images.githubusercontent.com/923280/76427512-af03ad80-63ac-11ea-870c-0cd671c9a199.png" width="200" />

**Comment by Kiarii** [comment]
Looking good :)

However, it seems that for the Forms screen - the screen in the middle - there is no divider between the Registration and Monitoring form..

**Comment by valllllll2000** [comment]
Fixed that issue
![Screenshot_1584371189](https://user-images.githubusercontent.com/923280/76771787-2916a680-67a0-11ea-9b0d-a077b2ec7edb.png)

**Comment by muloem** [comment]
👍 I like what I am seeing!
