### ISSUE TITLE
Geoshape creation save

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1643]
Right now we will automatically saved if the user presses the back button see https://github.com/akvo/akvo-flow-mobile/issues/1199 but we do not save while editing.

What should be the way to go while saving:
Save every time a shape is added/removed/moved?
Then we would not need a save button, we can just use "back"?
Shall we display "saved"?

**Comment by janagombitova** [comment]
<img width="1018" alt="Screen Shot 2020-06-04 at 16 19 50" src="https://user-images.githubusercontent.com/12456965/83768573-3ea0bb80-a67f-11ea-9a16-ec543fb60498.png">

*Image above is just to have a visual on how things look today* 

Do I understand you well, that we are heading towards a "full" autosave mode? If yes, then here is my take on your comments: 
* Save every time a shape is added/removed/moved? --> Yes. Every edit should be saved, regardless of what that edit is. 
* Then we would not need a save button, we can just use "back"? --> Yes. Then `Save` button is obsolete
* Shall we display "saved"? --> Yes. If we remove the `save` button we do need to show the user that we are doing the saving for her, somewhere and somehow.
