### ISSUE TITLE
Autoselect the last created shape

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1645]
When coming back to a saved geoshape, the user has to click on it for it to be "editable". It would be better to autoselect the last created shape and the last created point.
Current
<img src="https://user-images.githubusercontent.com/923280/83865733-e8875300-a726-11ea-9511-c4769dd3a4e1.png" width="200" />

Nice to have
<img src="https://user-images.githubusercontent.com/923280/83865769-f50bab80-a726-11ea-9e3e-1b381fec8464.png" width="200" />

**Comment by janagombitova** [comment]
Great idea. 

Could we also - in this case of coming back to `edit` - hide the `select geoshape` icon (the shape icon in the top right corner)? This way the user is not prone to click on it to "select" the shape as it is already selected and we remove the chance of him/her creating a 2nd shape.

**Comment by valllllll2000** [comment]
@janagombitova after giving it more thought, the part about

> hide the select geoshape icon (the shape icon in the top right corner)


should be in another issue, see https://github.com/akvo/akvo-flow-mobile/issues/1649
