### ISSUE TITLE
Hide 'select geoshape' once we have one shape selected

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1649]
Great idea. 

Could we also - in this case of coming back to `edit` - hide the `select geoshape` icon (the shape icon in the top right corner)? This way the user is not prone to click on it to "select" the shape as it is already selected and we remove the chance of him/her creating a 2nd shape.

_Originally posted by @janagombitova in https://github.com/akvo/akvo-flow-mobile/issues/1645#issuecomment-640412301_

**Comment by valllllll2000** [comment]
In this case, I think we should hide the menu option as soon as a shape is selected. If all points/shapes were deleted, we should re-nenable this entry. I am not 100% sure of this. What if Alphonso starts adding a shape, realizes it's the wrong type... cannot change his mind

**Comment by janagombitova** [comment]
>> What if Alphonso starts adding a shape, realizes it's the wrong type... cannot change his mind

For this reason, I thought to start with hiding the select option for `editing` cases first. We still need to research if there are cases where Alphonso decides about the shape type in the field, or is this always defined by Salim with the survey definition. But when editing, the decision has already been made, so I see no harm in hiding the icon.

**Comment by valllllll2000** [comment]
I will do the work for editing shape in the other issue. This is for possible disabling the possibility to change shape types once one type is selected.
