### ISSUE TITLE
Increase minimum api to 16

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1658]
Currently our  minSdkVersion is 15 (Android 4.0.3) but in order to be able to publish to google play and update to the new crashlytics SDK we need to update to 16 (Android 4.1)

Another reason to update https://android-developers.googleblog.com/2018/12/google-play-services-discontinuing.html

**Comment by janagombitova** [comment]
@valllllll2000 I checked the sheets you shared on the devices we have and their Android versions. If I get it correctly, we know of only 5 devices that will not be able to update their app anymore. I think that is an ok number to proceed with the change. We do not need to do any special communication, besides the regular channels we use (internal update, akvo.org and adding it to the next bulletin)
