### ISSUE TITLE
Investigate realtime location tracking for shape mapping

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1660]
#### Partner Request: 
Creating geoshapes as you walk (as running apps track your run)

A prototype already exists of this using mapbox.

Currently the goeshapes can be created manually adding a point to the map by long pressing it or pressing the "add point" which used the current user location.

The issue is to explore the idea further and try to forsee any possible issues.

#### Know issues that may arise:
* GPS accuracy (too low? not precise enough?)
* Too many points added: how to limit the points added
* Partner suggests to limit the number of points based on area of the shape known in advance

> You could check the ODK shapemapping tool which has a tracing option. You can see here that there are options to limit the number of points, such as:
>1) Entering a frequency based on distance 
>2) Entering a frequency based on time

> Good intention, but I am afraid this tool is too complex and not fully dummy proof. So the question is how to limit the number of points for the database (Excel only accepts around 32,000 characters) and also limit the upload sizes. I am thinking about a dummy proof setting such as a pop up question before starting the tool: For example: How big is the estimated area that you want to map; < 5 hectares, >10 ha (etc) and based on that set a distance parameter (the bigger the area, the larger the distance parameter).

* Getting device location in the background (Android 8.0 ++) https://developer.android.com/about/versions/oreo/background-location-limits
* Too many events drawn too often -> OOM crash... etc ... How efficient is mapbox for drawing big shapes?

#### Document describing all the steps
https://docs.google.com/document/d/1ilHHCDfVwg83pP1FjIAqjo5qjvXVmzY74OZTXKjtycg/edit?usp=sharing

**Comment by janagombitova** [comment]
Just to add a bit of context on **why ** we are considering this addition to the app:

# How will this benefit our users?
* time saving - creating geoshapes is one of the most time consuming parts of data collection
* easier task - today you have to add each point one by one, by having the app do this for you we make the task easier to do and thus decrease the threshold on picking up using the geoshapes question type
* accuracy of shapes - as a partner put it: “Tracing is important for us (not critical right now, but it would be a big improvement) for mapping areas more accurate (also with a future automated area calculation in mind). What you now often see is that partners enter a few points to map an area that are often very curved or much more complex than the few points that are used. This will create errors in area calculations.“

# How will this benefit Akvo?
* better support for agri projects that are one of our key strategic sectors
* market edge
