### ISSUE TITLE
Datapoint creation / edit workflow

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1667]

**Comment by Kiarii** [comment]
**Why do we create this issue**
(so we can improve it when time allows)
The workflow for creating and editing (draft) datapoints is 'broken' and unnecessarily long:

1. tap (+) datapoint icon
2. view form(s) list
3. select Reg form 
4. view form input fields > complete form & submit
5. Go back - takes user back to form selection screen; to go back to dp list during drafting (completing form) requires 2 back action..

**Suggestion** 
Ideally the workflow shd go as follows:

1. tap (+) datapoint icon
2.  view form input fields > complete form & submit
3. go back (during an edit) - take user back to dp list - not to form(s) screen - during datapoint creation & edit there is only one action possible here - selecting the Reg form - which shd be done by the app and the user shd therefore not see that screen.. It is only in monitoring that the form screen shd be presented

I will also try to handle the last point in ideating the datapoint profile screen
