### ISSUE TITLE
Cannot download many data points to the device 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#1670]
# Context 
In Flow, you can now assign specific data points to devices for monitoring (https://github.com/akvo/akvo-flow/issues/2796). This new feature aims to address the cases when partners had to download hundreds of data points to their devices, making monitoring specific data points hard, messy and very error-prone (submitting a monitoring form to the wrong data point became quite the norm).

But, some partners still want to have all data points on their devices. We learned that some enumerators are not assigned to specific areas and might randomly monitor points and thus need to have all the data points on their phone to then search for the specific one they're at. So not only can you assign specific data points to a device, but you can also assign all (the default setting).

However, the feedback we received over the last weeks is that **downloading hundreds of data points to a device does NOT work, regardless is they are specifically assigned or all**.

# The issue & explanation
In the past, when downloading many many many points to the Flow app, how things worked was that we downloaded the data points in batches of 30. It could take forever, but it did work. With the new feature to assign specific data points, we also changed how the download to the app works, using a new API. Now the app tries to get all the data points at once, as the assumption was that there will never be more than 50 or so, with the new assignments feature. What happens today is that with too many points, the request times out and does not download them.

# The ‘temporary’ solution
We need to look at how to handle downloading a lot of data points to the device (either if all data points are assigned or if there are many data points selectively assigned). The current implementation will not work long term. But we need some time to figure out the best approach, as a technical implementation would differ if one needs to download a hundred points or a thousand.

So while we try to figure out the solution, we have a temporary “fix” – using the app version 2.8.5 (downloading data points in batches of 30) and not updating.

So the user who needs all data points on their phone can use this app version. He/she needs to uninstall the current Flow app and install this one. As we build the app for each instance, every time we share an app for with the partner, we need to make sure it is the right one.

# Solution
Today @valllllll2000 and @muloem and I spoke about the options on how to solve this situation. We discussed: 
* using the new API but implementing back the logic to pull the data in batches 
* the backend bundling all the data points first and then sending them all to the app --> but this is limited by the 1 minutes rule and thus we still may not be able to handle large datasets 
* using the old API with the old logic --> but we want to remove it 
* the backend sends all data points to the app but only the "shell" and then the app pulls in batched the responses --> but this can be quite error-prone as how you ensure all data points get all data and it adds more implementation effort 
* creating the possibility to not only download survey forms offline via manual survey transfer, but also data points (https://github.com/akvo/akvo-flow/issues/3558). We agreed this is something to be handled in a separate issue

We agreed to **implement the pulling in batched logic using the new API**. This requires changes on both the app and the backend.

**Comment by muloem** [comment]
@janagombitova  @valllllll2000  With the changes to the backend, it means that for devices that use the new version of the API (i.e. since the new assignments were introduced) but do not update the app, they will only get the first 30 datapoints when the user tries to download datapoints.  This is something the support team will probably have to deal with to inform these users about this limit.

**Comment by janagombitova** [comment]
@muloem that is good to know. Will handle the communication once we are closer to a release.

**Comment by muloem** [comment]
@valllllll2000 with the latest changes (also based on feedback from @iperdomo ) we no longer even need the lastUpdateTime.  The app queries the backend and will get back a limited set of results and an end cursor.  The app needs to store that cursor and whenever the user presses download, the next request to the backend will include that cursor to start from where the user last downloaded. 

We also need to agree on a HTTP code that tells the user that all the existing datapoints have been downloaded. @iperdomo proposed a `204`

**Comment by valllllll2000** [comment]
@muloem sounds good!
1) Cursor
The cursor is only saved for the next download and otherwise the field is skipped correct?
The cursor is a string?
Will the cursor field be in the json reponse, example:
`{
  "resultCount": 16,
  "message": null,
  "code": "200",
  "offset": 0,
  "dataPointData": [....]
}`
2) HTTP code
after reading this https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
204 is "No content" which means after getting all the datapoints we need this extra request to say there are no more. This could work but also I was wondering if maybe we should use 206 (partial content) and then it means one less request, what do you think? Or maybe another code we should use either in the last request saying there will be no more or the partial ones indicating there are more to load and have the last one return 200

**Comment by muloem** [comment]
>  The cursor is only saved for the next download and otherwise the field is skipped correct?
The cursor is a string?

The cursor is a string.  it will be returned with every request that you make. i.e  for downloading 50 datapoints, you make two requests. The first will return 30 and a cursor to identify where to start the next request.  The next request will return  20 datapoints and a cursor as well.

The next time user selects download datapoints, the last cursor returned should be sent along with the request.  that means they would start e.g from the datapoint number 51 onwards.  if no cursor is sent with the request then the results returned will start from the beginning all over again.
