### ISSUE TITLE
Hide/indicate reason for empty group

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#1678]
# Context
We have the best app in the market, seen as simple to use. To continue building on this strength we want to remove workflows and elements that can confuse users, also self-taught users as we see that happening more and more. 

# Opportunity 

## Current status quo
During a research call with a partner, he mentioned interesting confusion enumerators have when working with the app. Questions in the form can depend on an answers to a question before. Sometimes, all questions in a group can depend on an answer, resulting in this question group showing empty in the app as the questions are hidden. 

The partner mentioned that this can be confusing as you do not know why your questions are hidden. Usually, you are not the one who created the survey. 

## The idea 

To avoid our enumerators being confused, how might we handle this case? Shall we hide the group fully? Shall we show it but indicate it is empty because the questions are not relevant? 

# Next steps

**Comment by valllllll2000** [comment]
As a first step we could have a generic message:
"This group does not contain any available questions"
Or we could have either:
* This group is empty
* This group's questions will be displayed if their dependencies are met

**Comment by janagombitova** [comment]
Sounds good. Shall we go with the last option? It is nice and explains why the group is seemingly empty.

**Comment by valllllll2000** [comment]
@janagombitova the last option you mean have both cases for empty groups and dependencies not met right?

**Comment by janagombitova** [comment]
Yes.
