### ISSUE TITLE
Accuracy when capturing geolocation data

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#1680]
# Context
We have the best app in the market, seen as simple to use. To continue building on this strength we want to remove workflows and elements that can confuse users, also self-taught users as we see that happening more and more. 

# Opportunity 

## Current status quo
During a research call with a partner, he mentioned issues with capturing data for geolocation questions. 

> With point location Akvo requies 20 m accuracy. If this is not reached, the app does not allow a recording. This can be frustrating if no point can be captured. The app should aim to record a point with <20m accuracy, but if not reached, the system should ask the user after X minutes of trying to record the point anyway with less than 20m accuracy. 

> In that case better to capture anything, despite the mapping is of low accuracy. What would be ideal is to make a first attempt to capture a signal of 20 meters accuracy and after 1 or 2 attempts (or 1 minute) enable the enumerator to capture the signal with less than 20 meter acuracy.

## The idea 

* How can we: do the accuracy check, but still allow to proceed even if the location accuracy is not 'good enough'
* Do we submit the accuracy data with the geolocation data? We should, and then, of course, show the values in the data.

# Next steps

**Comment by Kiarii** [comment]
I think performing the GPS accuracy check and logging it will not be an issue; the main challenge will be how to inform/advice Salim/Alphonso about the necessary (app) requirements (incl. 3rd party GPS calibration app if necessary) during App set-up.. i.e.
-  What to advice on
- When: a) at what step during the setup, b) at what time in the field (e.g. when accuracy drop below a certain threshold)
- ..

**Comment by janagombitova** [comment]
Let's keep this issue to its main goal: handling capturing location data even if accuracy is low, and see how to inform/advise Al about the GPS needs in a separate task.

**Comment by Kiarii** [comment]
Capturing gps accuracy metadata we could do as we do with images; perhaps we can start as follows: 
- for points do as with images - a single meta string for each point
- for line and shape - a single aggregated average for all points in the line or shape (this would keep the resulting meta easy to deal with; and enable Salim/Petra to deduce the accuracy of the shape, or for Alphonso to deduce whether to remap the line/shape
- the gps meta shd be presented on the shape question response - i think we do this with images..

**Comment by janagombitova** [comment]
Just spoke with Kiarii to clarify that this issue is to solely focus on capturing location and accuracy for geolocation questions, not geoshapes. Those we will handle separately once we get to them

**Comment by Kiarii** [comment]
hopefully I got the intent; here is a first shot at the issue: https://www.figma.com/proto/Bx2vabgHDUGHgNRoSZYBgP/GPS-Shape-capturing?node-id=40%3A43&viewport=465%2C-1307%2C1&scaling=min-zoom

Notes
- Geolocation is actually one word :)
- Present geolocation as a single string (there is not much for Al to interpret from having multiple strings) For him to make any meaningful interpretation of captured location, we should use a map snippet and show the actual location on the map (sth to consider in the future)
- I omit altitude; havent seen that info in lumen (i could be wrong)
- If geolocation capturing is auto-capture; then we dont need to present it in input fields
- changed from 'check' to 'capture' assuming Al is capturing not checking
- (skipped the recapture and delete dialogs in the mockup)

**Comment by janagombitova** [comment]
@Kiarii 
I think we are still missing the solution to the actual problem. Let me try to explain once more: 
* The problem is when accuracy is not good enough, above 20m 
* Today for mandatory questions in the Flow app this happens: 
   * click to capture location data 
   * data is shown with the accuracy being too high, in red 
   * when wanting to submit the data, you cannot as it is mandatory and highlighted as a question that needs to be filled in
* Today for non-mandatory questions in the Flow app the same as above happens, but you can submit the data as Flow does not care too much about the accuracy in this case 
* So the need to is allow Al to someone say, this accuracy is ok enough for me, let me submit. OR we show the accuracy but remove the restriction 

I checked the mockups and have a few extra questions:
* What would be the point of 'delete'? 
* Can you show how it should look with the map? We have the issue here and can consider handling them together: #1284 
* How will this new layout (which looks very good by the way, work for the case when a manual entry is allowed (so users can type in the coordinates themselves)?

**Comment by Kiarii** [comment]
Good points;
- no need for delete
- for manual input am assuming it has to be specified in flow or via an explicit button on the app (as we do with images: camera, gallery) in which case the actual input might look like [this](https://www.figma.com/proto/JuINKMpRo4ltSKvSIvGtnH/Location-manual-capture?node-id=4%3A30&scaling=min-zoom).
- still reworking the [auto-capture](https://www.figma.com/proto/JJ1PFfhInEfbsDZ4fDiCxv/Location-auto-capture?node-id=4%3A30&viewport=911%2C867%2C2&scaling=min-zoom) option; one thing we could consider is replacing coordinate digits with an actual address whenever this is available - this would be human readable for Al - we would still parse the coordinates to the backend/server

**Comment by janagombitova** [comment]
@Kiarii thanks for the review. A few points: 

* if manual entry is allowed (yes, this is defined on the survey level and once allowed on the app Al can either use the GPS to capture the data or input them manually) are you suggesting that there will be a **2nd** button next to the `capture geolocation` button for the manual entry? 
* I would like to suggest we keep manual entry to field inputs (as you designed). I am stating this as there is a discussion to use the map - what may be more intuitive but I would like to keep that change separate for now #1562 
* I like the idea of showing addresses where possible, but we need to keep in mind that the locations our users capture are usually in remote areas where addresses are not relevant. So I wonder if this is worth the effort. @valllllll2000 if showing the address or the coordinates (if an address is not available) is not too much of a hassle to implement, let's do it. If it is too much of an effort, let leave it for now.

**Comment by Kiarii** [comment]
In response to your first point @janagombitova we can support [GPS Auto & manual entry options](https://www.figma.com/proto/3A3zZ1XgqIGIcgv8AZgM2B/Loc-and-Img-capture?node-id=31%3A112&viewport=654%2C418%2C0.25&scaling=scale-down), keeping in mind that
- Auto-capture taken as a default
- The selected option is visually explicit (unlike what we atm do with images)
- After entering geolocation in whichever way, switching would require a dialog to confirm replacing entered values
- texts subject to refinement

this change if carried forward should inform the presentation of image attachment options; camera and gallery..

**Comment by valllllll2000** [comment]
Here is my suggestion, without changing the way geoquestion works since that would be another issue if we require a full layout redesign.
For now, when we capture the location and it's covered by a progress dialog but you can see sometimes an inaccurate reading was taken so the reading is endless. We could allow less accurate readings but add a text underneath to says something like "For improved accuracy try getting location again".
We already show the accuracy in red if not accurate, maybe we should explicitly say Accurate/Not accurate?
We should allow submitting inaccurate values
Shall we send the accuracy to flow?
For now we send latitude|longitude|altitude

**Comment by janagombitova** [comment]
@valllllll2000 thank you for the reminder of keeping the issue small and to their core problem. So we have a few issues here: 
* redesign that Kiarii has been working on (new issue # )
* allow submitting geolocation data even if accuracy is higher than 20m 
* send accuracy data to Flow (Flow issue https://github.com/akvo/akvo-flow/issues/1761. Does this need a separate app issue?) 
* reconsider the need of sending altitude (new issue #) 

On the details of **allow submitting geolocation data even if accuracy is too high**
> We could allow less accurate readings but add a text underneath to says something like "For improved accuracy try getting location again".

* That is a good suggestion. Could the text be: 'To improve the geolocation accuracy, recapture.'
* Can the button change once data is captured to `Recapture`
* I think showing the data in red when the accuracy is too high is quite telling and if we add that extra sentence to it, I think we do not need to make a change on this point

**Comment by valllllll2000** [comment]
Ok so here is what will be done in the scope of this issue:
* Allow submitting even if accuracy is more than 20m (means less accurate)
* Once a location was captured automatically manually, change to "Recapture geo location"
* Since we are changing the wording, we should maybe replace current text "Check geo location" by "Capture geo location"
* If the accuracy is not good enough add text: "To improve the geolocation accuracy, recapture." under the the values

**Comment by Kiarii** [comment]
Agree :) as I had mentioned above, geolocation is one word.. However, I think using "location" should suffice since there is only one kind of location to be captured so being specific and technical might not necessarily add value for Al

**Comment by valllllll2000** [comment]
Found 2 issues:
1) If location disabled why capturing is done, the location is still being loaded and timeout never happens, we should let user know
2) While capturing location, the "to improve location accuracy..." is displayed which is strange
