### ISSUE TITLE
Inform better about autosave

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#1681]
# Context
## Why do we have this issue? What are we trying to solve? 

The Flow app autosave data. But this is not visible to the user. 

We want the app to be user friendly, and making the autosave more explicit can avoid confusion and bring in more comfort when filling in long surveys, as users know they can close the app and come back to it without losing data. 

## How will this benefit the users?
* improve the understanding of what is happening with their data and what the app handles for the user 
* more trust in the app 
* do no need to worry about the data 

## How will this benefit Akvo? 
* another step towards a more user-friendly app means more delighted users and thus a stronger position in the market

# Opportunity 
## Current status quo
Currently when Al fills in an answer to the question (offline or online) we save the data automagically. But there is no indication of that. If Al goes back to the data point list or closes the app the submission is saved as a draft and he can go back and edit it. Once he `submits` the data, he cannot make any further changes. 

When researching how the app is used with a partner, we learned that autosaving is not obvious to our users (especially those that we did not train). They submitted the form complaining they cannot go back and edit the data before it is uploaded. They did not know that the data is saved and they can keep on editing the form submissions until they hit `submit`. 

## The idea 
How can we make it more explicit that data is being saved? 

# Next steps

**Comment by valllllll2000** [comment]
We could either 
* display something at the top "all answers will be automatically saved"
* after each save display "saved"

**Comment by janagombitova** [comment]
Both great suggestions, I trust you pick the most feasible and usable one 👍
