### ISSUE TITLE
Location permission related bug

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1722]
**Describe the bug**
There is some annoying issue when the user did not enable location on devices with Android 6.0+
It was not introduced in a recent release but I think it should be fixed ASAP.

**To Reproduce**
1. Have location disabled on device and revoke location permissions
2. Go to a location question, try getting location
2. When asked, allow permission only while using the app
3. You will see the location is being "aquired" but that is not the case. Press cancel and you will see the message to enable location and only when enabled will you be able to aquire a location

**Expected behavior**
Dismiss the loading dialog and display the message about enabling location setting

**Device (please complete the following information):**
 - Device model: Pixel 3
 - OS: Android 11
 - App Version 2.9.4.1 or 2.9.5

**Comment by iperdomo** [comment]
Steps tested with Huawei P9 / Android 7.0 / App version 2.9.5
