### ISSUE TITLE
Create assignment profile to better support field work

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-flow-mobile#1738]
#### context
Introduce the concept of assignments to devices to bring some consistency between Flow db and App e.g.
- Devices show Assignments' name not Surveys

Introduce the concept of assignment profile to devices - to enable Al to better understand his workload
- Assignments have tentative start and end dates; how much time remains - this might also make Alph. proactive in the sense that he can request a time extension if he sees that the allocated time is no longer enough..
- Monitoring assignments have a number of datapoints; 1000 assigned
- Provide some idea of assignment progress e.g. x datapoints / y monitored, or whatever.. or 54 datapoints created/collected so far..
- Provide way for handling assignment ends - what happens? no more submission, ..

Some ideas from our parallel world
<img width="566" alt="Screen Shot 2018-09-21 at 12 17 38" src="https://user-images.githubusercontent.com/12692444/95335265-de818680-08b7-11eb-8885-cce75651de5b.png">

**Comment by janagombitova** [comment]
@Kiarii I really like the idea and great work on explaining it. A few pointers to think of to take this further: 
* Where would the assignment live in the app? 
* How will the user access it? 
* How will Al know there is a new assignment for him? 
* Will this replace the concept of 'surveys' in the app?

**Comment by Kiarii** [comment]
> Where would the assignment live in the app?
> Will this replace the concept of 'surveys' in the app?
- More or less; Alp would see assignments in place of surveys, 
- Assignment names are more descriptive than survey or form names..
- And yes, we can replace the survey concept in the app since in reality what Salim gives to Alp via the app is an assignment not the survey per se. The assignment is always a small 'instance' of the survey; akin to how a teacher may assign to students a reading exe for page x on the text book; in which case, they need not refer to the whole book.

> How will Al know there is a new assignment for him?
> How will the user access it?
- This can be handled as we handle new survey/form downloads, and accessible in the same manner

Assignment profiles, coupled with [datapoint profiles](https://github.com/akvo/akvo-flow-mobile/issues/1661) might improve Alp.'s work processes as important information and concepts are prioritized and readily accessible.. a lot of cognitive effort is reduced or removed altogether.
