### ISSUE TITLE
Improve submitted data view

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-flow-mobile#1746]
Currently we use more or less use the data entry view to present submitted data: which even though presents user input as 'disabled' gives the impression that the user is looking at a form. Points for improvement might include: 
- Deemphasize question labels
- Capitalize question groups labels (remove all caps)
- Emphasize submitted input
- For option question show only the submitted option e.g. for a question "Gender" if response is "Female" we do not need to show all other provided option (the informed assumption being that Alp. is concerned with a response and not analysis) 
- Determine how we denote no response for non-mandatory questions and design accordingly
- Remove 'form' view - since no edit can be performed
- Tabulate question groups into expandable sections..To simplify orientation and navigation among question groups, also to improve legibility of the labels 

Ideas from the parallel world:
<img width="385" alt="Screenshot 2020-10-28 at 9 59 05" src="https://user-images.githubusercontent.com/12692444/97403264-2b7bda00-1905-11eb-93cd-af3281972781.png">

**Comment by valllllll2000** [comment]
I like it. One thought: we have to distinguish between different question groups (current tabs) from repeated question groups which are shown in the same tab but have these sections. I think having expandable sections is a good idea for repeated groups.

**Comment by janagombitova** [comment]
I like it too. If we are going to change how we present groups when submitting data: https://github.com/akvo/akvo-flow-mobile/issues/1201#issuecomment-717738826 and https://github.com/akvo/akvo-flow-mobile/issues/1563#issuecomment-717735926 then why not unify this screen with the same group navigation?

**Comment by Kiarii** [comment]
There are some differences between data entry and data viewing modes thus the difference in their presentation; 

- In one, you as Alph. are likely to take a linear route - taking in all the question details and filling in responses - so every question group takes a screen and you go to the next simply with a next button at the end of one group; the view here also enables you to have an overview of the form and where you are at in the process of filling it, and an easier way to jump back and forth if that were to be needed

- In the other if - at all - you are looking to see sth specific so we enable quick glance and quick dive.. This mode might even be less used once we factor in a datapoint profile in which datapoint identifying information will be available without having to dive in into submitted data..thus the data is collapsed by default..
