### ISSUE TITLE
Indicate in main menu that new survey forms are downloaded or updated 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#1754]
With https://github.com/akvo/akvo-flow-mobile/issues/636 we now bold the changed surveys in the Surveys list. By 'changed' we mean any newly downloaded surveys or any surveys where the form version has been updated. 

However, with the change, we did not implement adding `notification dot to the main menu, right Valeria? 

In this comment Kiarii further described how the dot should behave and look: 
> Myself and Loic have felt that the icon can be of the same color as the toolbar elements - it is not an ever-present element on the screen so it need not be additionally coded with color - it is visually: a user can already discern something is different on the toolbar even from peripheral vision (when they are not looking directly at it). The illustration gives a context:

<img width="433" alt="screen shot 2017-03-03 at 12 15 52" src="https://cloud.githubusercontent.com/assets/12692444/23547518/17a7d422-000c-11e7-8d85-f501c67248e2.png">

_Originally posted by @Kiarii in https://github.com/akvo/akvo-flow-mobile/issues/636#issuecomment-283918977_

**Comment by valllllll2000** [comment]
![Screenshot_1609842814](https://user-images.githubusercontent.com/923280/103641520-2a44da00-4f52-11eb-8320-beee652455e2.png)

**Comment by janagombitova** [comment]
@Kiarii can you review this with @valllllll2000 please? Thanks

**Comment by valllllll2000** [comment]
@Kiarii has reviewed it on his device and this is the feedback I got _the icon then works fine, and also reverts to normal when all new surveys have been opened_
