### ISSUE TITLE
Answers not being saved and thus not being able to submit

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#1787]
Reported via support: https://akvoo.reamaze.com/admin/conversations/form-does-not-save-and-information-is-erased

![screenshot of case 1_form does not send and is not saved](https://user-images.githubusercontent.com/12456965/112271688-87ac1580-8c7b-11eb-8679-8e743b04afa3.jpeg)

What has happened according to the user: 
1. Have completed entire surveys
2. Arrived at the "submit" section (see screenshot attached)
3. Selected "submit," and then receive the message explaining. "Error submitting form, please try again." (see screenshot attached)
4. Selects the back button in order to try to re-enter the survey and send, and then realizes the has not been saved at all.

I checked Sentry and there are no errors there. I have contacted Eric for more information. For now we wait.

**Comment by valllllll2000** [comment]
Here is a list of problematic devices:
* emelyrojas_iDH 
 Galaxy A71 device
Android 10

* elmerposadas_idh
Galaxy A8(2018)
Android 9
 
* luisperez_IDH
???

Steps:
I have found error stacktraces on which say: "survey instance [id] not found" for 2 of the devices on firebase.
When we open a new datapoint, we create an empty surveyinstance and datapoint and then proceed to the screen called FormActivity. In the datapoint list view we have logic which retrieves datapoints and there's also logic which cleans up empty datapoints so they are not shown. 

Hipothesis: there must be something happening where for some reason that survey instance gets deleted. I am not sure yet how it can happen but there seems to be a race condition where the datapoint and survey instance are considered as "empty" and end up being deleted before user has the chance to add any answers

**Comment by valllllll2000** [comment]
Steps:
- [ ] Take user directly to registration form when creating a datapoint
- [ ] Remove the logic of deleting datapoints and survey instances
- [ ] Create datapoint/survey instance once the first answer is submitted
- [ ] If the user leaves FormActivity and there is no answer, delete the survey instance
- [ ] Upon pressing submit, verify answers/survey instance/datapoint once more just in case
