### ISSUE TITLE
User submitting data from different version of the form in different days 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#1828]
@valllllll2000 just to put it out there, I am not sure this is the best way to describe and name this issue, so please rename it if you think there is a better way 

When researching a support issue on why some answers to a mandatory question show and why some are missing I noticed one odd thing. I am not sure if this is a bug, if we should worry or what to do, but I would like to hear your opinion. 

One device has first made submissions to the form version 2 (in red) and then to form version 3 (in black) and then to form version 2 again chronologically. 

<img width="632" alt="Screenshot 2021-05-17 at 13 39 05" src="https://user-images.githubusercontent.com/12456965/118491586-70d7eb80-b71f-11eb-9ecd-fd90ffc89000.png">

How could this be possible? 
My expectation is that once you have version 3, the enumerator does not go back to version 2

**Comment by valllllll2000** [comment]
This is quite curious indeed but what if they are actually 2 users, I have found 2 devices with the same name in our datastore

![Screenshot from 2021-05-17 15-53-13](https://user-images.githubusercontent.com/923280/118500542-29099200-b728-11eb-820e-e323ec87e5bc.png)

**Comment by janagombitova** [comment]
Ohh well that could indeed explain it
Thanks, Valeria. Will close the issue then and if I stumble upon it in the future we can reopen and investigate more
