### ISSUE TITLE
Add new language

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow-mobile#1865]
**Describe the bug**
Languages that are added to the surveys normally come with a 2 letter code to indicate which language it is.  However, there are certain languages that do not have a 2-letter language code in the ISO 639-1 standard.  However, these languages do have a 3-letter code but are not supported by the app currently.

**To Reproduce**
1. create a survey and simple form in the survey editor, 
2. add a translation langauge to it Bemba that has a 3 letter code,
3. publish the survey and assign it to a device. 
4. Download on the device and create a new response
5. Try to change the language to Bemba. its not in the list

**Expected behavior**
It should be in the list of languages.

**Comment by valllllll2000** [comment]
The languages are added manually here https://github.com/akvo/akvo-flow-mobile/blob/develop/database/src/main/res/values/languages.xml
It's not about 2 or 3 letters it's juste right now they need to be in the list

**Comment by valllllll2000** [comment]
will add https://github.com/akvo/akvo-flow/commit/e1065b407db4a9764005d0b81327b940ef2b8789
