### ISSUE TITLE
Lao language integration

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#189]

**Comment by ichinaski** [comment]
@joycarpediem what's the status of this?

**Comment by janagombitova** [comment]
@joycarpediem is this still relevant? The current status on transifex is 59% and will there be someone who will maintain the language later on in the future?

**Comment by joycarpediem** [comment]
Nope. It can be closed.
We don't have any active demand for the Lao app right now 
On 5 Oct 2016 6:04 pm, Jana Gombitova <notifications@github.com> wrote:@joycarpediem is this still relevant? The current status on transifex is 59% and will there be someone who will maintain the language later on in the future?

**Comment by janagombitova** [comment]
ok Joy, closing this issue for now then - we will reopen it if needed later
