### ISSUE TITLE
Geographic shape questions

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#236]
**Properties:**
* Standalone feature (no survey dependent)
* GeoJSON data
* Browse and review collected plots

**Comment by mtwestra** [comment]
@Mark the geoshapes APK at dev2 is the latest version available. The main changes are:
- warning dialogs (on point or feature deletion)
- (experimental) point dragging: I'm not sure whether or not there's any added value on having this functionality. You need to be somewhat accurate while selecting the appropriate point, otherwise a new one will be created.
- No "Clear all map" option.
- Show/Hide available features, depending on question definition.

Note: The question UI is still outstanding, for it just displays the GeoJSON response for now. We'll need to rethink this along with Loic.

There's a Survey/Form @ dev2 you can use to check out the feature: Geographic Shapes > Geoshapes (form id 117932013)

**Comment by mtwestra** [comment]
@ichinaski, some comments:
1) I think it mostly works fine now, further improvements should be done through user testing in the field. I'll contact Peter and see what we can set up. 
2) One think I consistently get wrong is when I want to add a point in between two other points. Somehow, it is hard to guess where the new point will be connected to. Perhaps this merits some further thought.

**Comment by ichinaski** [comment]
> 2) One think I consistently get wrong is when I want to add a point in between two other points. Somehow, it is hard to guess where the new point will be connected to. Perhaps this merits some further thought.

This is very tricky indeed... I recall discussing the highlighting of the ancestor point of the currently selected one, so it gives the user more feedback on where the feature will expand from. Perhaps we could give this a try.

**Comment by mtwestra** [comment]
@ichinaski Ah, so it would basically show two points selected, and if you add one it will go inbetween. Yes, I think that would certainly help.

**Comment by ichinaski** [comment]
> @ichinaski Ah, so it would basically show two points selected, and if you add one it will go inbetween. Yes, I think that would certainly help.

The original idea was to insert the new point **after** the selected one. Highlighting the ancestor is just a hint to display the track orientation. Note that the selected point is slightly bigger than the rest, so it would remain clear that distinction between those highlighted points.

If I understand it correctly, your suggestion is to highlight the *descendent* point to the selected one (if any), right? The behaviour is pretty much identical, the main difference is what points to highlight, so the feature orientation is clear enough.

**Comment by mtwestra** [comment]
@ichinaski I've been playing with it a bit, and I think this makes sense:
1) when no point is selected, a new point is added as a new endpoint to the line
2) when a midway point is selected, the user needs to know where a point will be created when she clicks somewhere. For this, I think it makes sense to indicate the descendent point, as then she will know that if she clicks somewhere, the new point will be created in between the selected point and the descendent point.

**Comment by ichinaski** [comment]
Some feedback from first iteration (v.2.1.1):

Bugs or defects. To be handled now
----------------------
* On rotation, map clears
* Back soft icon (FLOW logo) not ready yet

New issues (based on feedback) approved to be implemented now
-----------------
* Satellite layer. Toggle between map and satellite layers
* Center map at start.
* Feature info (point number, area, perimeter, etc)?
* Disable manual input? (force GPS readings)

To be discussed further
-------------------
* Aulia expected the question response (feature collection) to be present in the Map tab.
* Dragging points can be tricky if not accurate enough while selecting a point.
* Manual geoloc input?

Other ideas
----------------
* Accuracy indicator. An enumerator might need to know when to delete and recapture a point.
* <3 points in an area should not be allowed -- this is tricky as we should allow users to save a partial response and resume it later on.

**Comment by ichinaski** [comment]
**Test plan:**
* Check the feature hiding works ok. This can be managed in the question creation (dashboard), by unchecking the points, line, area checkboxes.
* Ensure feature saving and resuming works fine. Collect some data, click save, and carry on with the collection afterwards. This should be done for all 3 feature types.
* Once the response is submitted, check out the answer value in the dashboard, and ensure the GeoJSON is valid with the help of http://geojsonlint.com. This should be done for all 3 feature types.

**Comment by rumca** [comment]
@ichinaski not sure if it's worth adding here or in a separate issue, but perhaps when a user goes back to a shape they've been working on - it should be easier to tell what the the currently selected feature type is? For example when I create an area feature, then go back to edit it after saving - the feature type seems to have reverted to point (at least I see different behaviour between adding a point straight away versus changing to area type and then adding a point).

**Comment by rumca** [comment]
I think everything else listed in the test plan works as expected. The only other comments I would make are:

* Perhaps it would be more difficult than it sounds, but it would be nice if we had a "do you wish to save" prompt when a user clicks back when editing a shape - at the moment it just scraps everything.
* Not sure what the logic is for displaying area types (so please disregard if this is working as intended), but in the following situation:

![screenshot_2015-02-02-22-28-48](https://cloud.githubusercontent.com/assets/3003031/6010672/7cf3f9dc-ab2c-11e4-8117-c2f1659ec7d3.png)

I was expecting if I add another point in between the bottom two, that I would see an enclosed area however I get the following:

![screenshot_2015-02-02-22-28-57](https://cloud.githubusercontent.com/assets/3003031/6010671/7747bff0-ab2c-11e4-950c-887dc1a84c7d.png)

**Comment by rumca** [comment]
@ichinaski also having just checked the geojsonlinter - are we supporting mixing of feature types at the moment? A few of the responses I submitted don't seem to be valid.

**Comment by ichinaski** [comment]
@rumca,

> when a user goes back to a shape they've been working on - it should be easier to tell what the the currently selected feature type is? For example when I create an area feature, then go back to edit it after saving - the feature type seems to have reverted to point (at least I see different behaviour between adding a point straight away versus changing to area type and then adding a point).

When going back to a saved, ongoing shape, no feature appears selected. Is up to the user to select a point (and therefore a feature), and carry on with the data collection. That is, selection status is not maintained across *sessions*.

Now your second part has puzzled me a bit... what do you mean by *changing the area type*? A feature cannot change its nature (type). Adding a new feature (through the action bar menu) results in a complete new feature being added, not changing the type of the selected one.

In regards to the type being reverted: is this happening consistently? Is there a pattern I can follow to reproduce this behaviour?

**Comment by ichinaski** [comment]
On the aforementioned image... Unlike lines and points, a polygon needs to maintain a specific order in which the points are added, so the concavities of the resulting angles are maintained. A polygon (area) must be collected either clockwise or counterclockwise, but no with an inconsistent orientation, for this ends up in the polygon having an invalid perimeter shape. When the polygon is invalid, the inner area is not displayed (as in your example).

**Comment by ichinaski** [comment]
**Test plan (2.1.3):**
* Manual entry of points should display a confirmation dialog.

**Comment by rumca** [comment]
Tested and works as expected on 2.1.2
