### ISSUE TITLE
Dependent questions are not populated properly

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow-mobile#239]
Sometimes, the dependent questions are not populated correctly when a user leaves a form and returns to it. 

How to reproduce:

1) create a survey with a number of dependent questions, where the dependent questions are at different tabs than the question they are dependent on.
2) in a formInstance, select the options that make the dependent questions appear. verify by going to the required tab.
3) leave the app
4) enter the formInstance again, and go to the tab with the dependent questions
5) the dependent questions are now not populated.

**Comment by ichinaski** [comment]
A single dependent question in a separate tab does **not** show this error. Example: form 20533004 in akvoflowsandbox.

I will now check out other scenarios (multiple dependencies, nested dependencies, etc).

**Comment by ichinaski** [comment]
I found the problem. The dependency check is erroneously implemented. The issue only arises when multiple dependencies occur. It's a mystery how this hasn't showed up ever before...

**Comment by ichinaski** [comment]
**Test Plan:**
* Create an option question with multiple values allowed.
* Create a dependent question (on the aforementioned one), on any of its values.
* Download the form and answer multiple values on the parent question (among those values the selected one should be present). This will trigger the dependent question's visibility.
* Exit and re-enter the form. The dependent question should keep the visibility on.

**Comment by rumca** [comment]
@ichinaski I don't think something is quite right with this one. Following the test plan above - dependent questions now don't appear at all when the relevant dependencies are selected on v2.1.0.1

**Comment by rumca** [comment]
works as intended now :+1:
