### ISSUE TITLE
Minor cleanup

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#241]
- [ ] Make ActionBar initialization consistent throughout the app (see https://github.com/akvo/akvo-flow-mobile/blob/master/app/src/main/java/org/akvo/flow/ui/adapter/SurveyTabAdapter.java#L64-L66)
- [ ] Update wording:
  - Record -> Datapoint
  - Plot question -> Geoshape question
  - etc

**Comment by janagombitova** [comment]
@valllllll2000 is this still relevant?

**Comment by valllllll2000** [comment]
No longer relevant
