### ISSUE TITLE
App crashes when keyboard is changed during use

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow-mobile#243]
I can't see this happening regular with normal usage of the app, but when the following steps are performed with v2.1.0:

* Open flow app, navigate to a form
* Select a field and click to focus on it
* Change the device keyboard (e.g. from swiftkey to samsung default etc)
* Try to type anything in field

The application crashes.

**Comment by ichinaski** [comment]
(Apologies for picking up this issue 1+ year later!)

Unfortunately, I have not been able to reproduce this error with the current version of the app. Do you think it's still relevant @rumca ?

**Comment by rumca** [comment]
Just tried to replicate this also and it is no longer an issue.
