### ISSUE TITLE
Alphabetically order surveys and forms

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#244]
Surveys and Form have no ordering policy at the moment (except for the registration form). Instead, we will order them alphabetically.

**Comment by ichinaski** [comment]
**Test Plan:**
* Surveys should be alphabetically ordered
* Forms should be alphabetically ordered, except for the registration one (always at the top).

**Comment by rumca** [comment]
@ichinaski I think this is working as intended. Just to double check though - on the Survey list should it be numerical first, then plain alphabetical, then anything with symbols?

**Comment by ichinaski** [comment]
The app performs a plain text sort (in SQLite). I believe this means 1 < 10 < 2 when it comes to sorting numbered prefixes.
