### ISSUE TITLE
Alphabetically order cascade values

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#245]
A cascade level values are currently not ordered. They need to be sorted alphabetically.

**Comment by ichinaski** [comment]
Discussed with @iperdomo the requirement of an extra index, in order to sort the values alphabetically. The existing index is being used in the query, and little improvements could be done with the current configuration. Therefore we will leave the DB structure as it is now.

**Comment by iperdomo** [comment]
Some proof:
````
sqlite> EXPLAIN QUERY PLAN SELECT DISTINCT id, name FROM nodes WHERE parent = 510 ORDER BY name;
0|0|0|SCAN TABLE nodes USING COVERING INDEX node_idx
sqlite> CREATE INDEX test ON nodes(name);    
sqlite> EXPLAIN QUERY PLAN SELECT DISTINCT id, name FROM nodes WHERE parent = 510 ORDER BY name;
0|0|0|SCAN TABLE nodes USING COVERING INDEX node_idx
````

**Comment by ichinaski** [comment]
**Test plan:**

* Cascade values should be alphabetically ordered in the level dropdown widget.

**Comment by rumca** [comment]
Test plan passes
