### ISSUE TITLE
Add shortcut to question from within submit tab

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#251]
With the presence of many question tabs and questions in a survey, it gets too cumbersome to figure out where a particular missing question might be located.

A quick workaround would be to add a shortcut to the relevant question tab (and perhaps to scroll down to the question). This way a user would check out the missing questions in the submit tab, and simply click them (or an extra `open` button) in order to browse the corresponding tab.

**Comment by ichinaski** [comment]
![screenshot_2015-01-23-12-22-53](https://cloud.githubusercontent.com/assets/1754343/5874518/b21990fc-a2fa-11e4-971f-c1891d9c71aa.png)

**Comment by ichinaski** [comment]
**Test plan:**

* In a form with a bunch of missing, mandatory - or invalid - questions, navigate to the **submit tab** right away.
* From within this screen, the *edit* button should take you to the corresponding question group (tab), and scroll down to the relevant question.

**Comment by rumca** [comment]
Tested with v2.1.1 and test plan passes
