### ISSUE TITLE
Identify devices by ANDROID_ID property

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#259]
Currently, the Android ID seems to be the most trustworthy way of identifying a particular device.

http://developer.android.com/reference/android/provider/Settings.Secure.html#ANDROID_ID

**Docs:**
* https://github.com/akvo/akvo-product-design/issues/73
* https://github.com/akvo/akvo-flow/issues/998

**Comment by ichinaski** [comment]
**Test plan:**
* Trigger the following app-backend connections:
    * Sync surveys through both assignment
    * Update device id (*Settings > Preferences*) so the location beacon is explicitly called
    * Submit data
* (Obvious step, nonetheless worth to be mentioned) All those actions are performed without any noticeable regression
* Open the dashboard logs in the appengine console, and check the HTTP request query for those connections:
    * /processor (data submission)
    * /locationBeacon (location beacon + id update)
    * /surveymanager?action=getAvailableSurveysDevice (assignment download)
    * /surveymanager?action=getSurveyHeader (manual download)
* All those requests should include the androidId parameter (16 character hex string)

**Comment by rumca** [comment]
Android ID is present on all the above requests (also on the ``/devicenotification?`` request)

I also crosschecked the ID in the requests against that of my device and it all looks good :+1:

**Comment by ichinaski** [comment]
Reopening issue as SurveyedLocale hash is not being effectively generated (due to extra param).

**Comment by ichinaski** [comment]
*Note: commit https://github.com/akvo/akvo-flow-mobile/commit/adf61fc164a75d88f9bc99ada0439a261c49370f was meant to be referencing this issue*

**Comment by rumca** [comment]
looks good for tagging v2.1.2
