### ISSUE TITLE
Question dependencies do not match on trailing spaces

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#261]
# Overview
When trailing spaces are present in the option values, the dependencies are not matched correctly.

Survey XML parsing process takes care of removing these characters for option values, but not for dependency values. The straightforward solution is to always trim each string before the comparison.

Additionally, the back-end will take care of automatically trimming all values for future surveys: https://github.com/akvo/akvo-flow/issues/1123

**Comment by ichinaski** [comment]
**Test plan:**
* Create an option question with trailing spaces in some of the values.
* Add a question dependent on any of the previous question's values.
* Ensure the latter question is triggered appropriately.
* Check out the behaviour for both single and multiple answer option questions.

**Comment by rumca** [comment]
The above test plan passes fine (though I'm no longer able to create surveys which have trailing whitespace on the options since it's been fixed in the dashboard) :+1:
