### ISSUE TITLE
Handle lack of GPS more gracefully

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#262]
# Overview

Flow app is crashing when no GPS is present in the handset. Note that this doesn't affect the deactivated status of the GPS, only the lack thereof.

*Note: Issue marked as defect (not bug) as this is a minimum requirement for the usage of FLOW.*

**Comment by ichinaski** [comment]
@mtwestra Perhaps we could allow the app to handle the best location provider available. That is, if the GPS is present it will be used as the first option. Otherwise, if the system finds an accurate enough location provider, we could use that one, instead of hard-coding the necessity of GPS. 

The threshold criteria is measured by some Android constants, see https://developer.android.com/reference/android/location/Criteria.html

**Comment by ichinaski** [comment]
**Test plan:**
* Disable the GPS from within the system settings
* Open the app and navigate to the datapoint list screen (any survey)
* No crash should happen

**Comment by rumca** [comment]
Application doesn't crash when following the above test plan on 2.1.2
