### ISSUE TITLE
Unauthorized device when no SIM card is present

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#270]
# Overview

The datapoint sync servlet receives the phone number within the query, among other attributes. When no phone number is fetched, the app reports the MAC address. This attribute is not URLEncoded, whereas the servlet does encode it in order to calculate the authentication hash.

The solution is to URLEncode **all** the attributes (a regular phone number won't be modified at all)

**Comment by ichinaski** [comment]
**Test plan:**
* Remove the SIM card from the device, if present.
* Sync datapoints in a monitoring survey. No authorization issue should happen.

**Comment by rumca** [comment]
Test plan passes successfully also form submission and fetching of previous media assets remains unaffected :+1:
