### ISSUE TITLE
Display accuracy indicator in geoshapes editor

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#272]
# Overview

We currently warn the user when the read location is not accurate enough, but we are not giving any feedback prior to that *add point* attempt.

To go past this problem, we'll display an accuracy indicator in the bottom right/left corner, with the current GPS accuracy, as well as a meaningful text color associated to the accuracy (green: ok, red: not accurate enough)

**Comment by ichinaski** [comment]
Reviewing this new addition, I realised there is no *read-only* mode for geoshape questions. That is, when a form is submitted, and the user browses the form thereafter, the geoshape question simply says *shape captured successfully*, but there's no way to view the (non-editable) feature.

I suggest we also handle this small change for this release.

cc/ @mtwestra @loicsans

**Comment by mtwestra** [comment]
@ichinaski, you can't continue to edit the shape, by going back to it?

**Comment by ichinaski** [comment]
Well if the form is submitted that should not be possible. The current version doesn't allow you to go back to the geishape editor, it just displays *shape captured successfully*.

**Comment by loicsans** [comment]
@ichinaski Would it be possible to capture the shape and display a image of it below the  shape captured successfully message?

**Comment by ichinaski** [comment]
@loicsans I was recently looking into programmatically taken screenshots. Perhaps we could capture the screen once the user clicks *save feature* and display it instead of the *capture shape* button... that will require some extra thoughts however.

**Comment by loicsans** [comment]
@ichinaski that sounds perfect, can you capture just the map area of the screen, no matter what screen resolution you're looking at?

**Comment by ichinaski** [comment]
Yes that's not a big deal I think. One of the challenges will be to deal with synced points -- that is points collected in a different device. Syncing these images/shots is something we probably want to avoid.

I think for the short/mid term, the proposed solution is more than enough.

**Comment by ichinaski** [comment]
**Test plan:**

* Upon geoshape feature edits, GPS reading accuracy should be displayed in the upper left corner.
* On submitted forms, geoshape responses can be viewed, but not edited.

**Comment by rumca** [comment]
Tested and works as expected on 2.1.3 :+1:
