### ISSUE TITLE
trim starting hyphen

### ISSUE THREAD

**Issue by JosjeS** [akvo/akvo-flow-mobile#273]
Hi All, 

This issue is related to a tender discussion as there is an extra hyphen in front of the data point name on the phone and in the excel. 

Here is a link to the issue in FLOW tender: http://flowhelp.akvo.org/discussions/problems/3525-fwd-re-vraagje-akvo

And in an internal comment I noted the following: 
We thought that it might be an question that had been ticked at data point name but had no responses.
But when looking into it this was not the case.
We found the following that might provide an answer:
There are 3 categories in the data point name
1. village 2. household nr. 3. name head household

And sometimes the data point name is:
village - household nr. - name head household

But sometimes it is:
- village - household nr. - name head household

The problem seems to lie in the first data point name the 'village'.
This one is generated from a depend question.

I noted it here in a example:
Question 1: Community (NO data point name) this has 5 options:
- community 1 - community 2 - community 3 - community 4 - community 5

Question 2: Village (in community 1) and is a data point name
- dependent on selecting community 1

Question 3: Village (in community 2) and is a data point name
- dependent on selecting community 2

Question 4: Village (in community 3) and is a data point name
- dependent on selecting community 3

Etc..

What now happens, if the village is in community 1 you will get the following data point name:
village - household nr. - name head household

But if the village is in community 2, 3, 4 or 5 you will get the following data point name:
- village - household nr. - name head household

(so then with an extra hyphen at the front)

All the dependencies of the questions are set correctly and all the questions are mandatory.

Best,
Josje

**Comment by ichinaski** [comment]
**Test plan:**

* Create a form with multiple *datapoint-name* flags enabled.
* In the app, check out a few different combinations, leaving the first question blank most of the times.
* Ensure resulting datapoint name never contains leading (nor trailing) hyphens.

**Comment by rumca** [comment]
Have tried various combinations of datapoint-name question answers and can't find a combination whereby there are trailing or leading hyphens :+1: 

( @ichinaski trailing/leading spaces are a different story though - perhaps we should strip these from datapoint names?)

**Comment by ichinaski** [comment]
@rumca did you manage to insert leading/trailing spaces in the datapoint name?

**Comment by rumca** [comment]
yep - see below

![screen shot 2015-03-16 at 15 40 24](https://cloud.githubusercontent.com/assets/3003031/6669795/d23230da-cbf2-11e4-898d-3763052b5b9e.png)

**Comment by ichinaski** [comment]
Good point @rumca. Those values are being trimmed, but only at data serialisation time (`data.txt` generation). Will make sure datapoint names handle those values properly :+1:

**Comment by CharlotteSoed** [comment]
Hi guys, 

so what can I reply to the partner explaining that the issue is solved?

Cheers

**Comment by ichinaski** [comment]
@CharlotteSoed Yes, please. The fix will be part of the next release though, it's not yet deployed. We expect to release the app tomorrow.

**Comment by JosjeS** [comment]
@ichinaski will the release automatically delete the extra hyphen of already collected data? Or should we run a script to rename the data points?

**Comment by ichinaski** [comment]
@JosjeS not really. The fix applies only to newly collected data. There's currently no way of regenerating submitted datapoint names. If the issue is pretty severe we can discuss the implementation of a script to deal with that.
