### ISSUE TITLE
restrict length datapoint name answer to 500 chars

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow-mobile#278]
The datapoint name response of a formInstance should be restricted to 100 chars, to avoid problems in the dashboard. If a response is longer, we should replace the last part with the elipsis character (...) or three dots, to indicate that it has been shortened.

**Comment by ichinaski** [comment]
@mtwestra Truncating that value should be an exercise for the view handler, right? The dashboard in this case. The stored data should be as accurate as possible IMHO, as long as the datastore handles the value size nicely. If we integrate this kind of logic in the datapoint name computation, it'll also require us to apply the same logic in the testharness counterpart.

**Comment by ichinaski** [comment]
As agreed with @mtwestra and @muloem the maximum length of a generated name will be 500 chars. If the concatenation of name-flagged responses is larger than 500 characters, the value will be truncated.

**Comment by ichinaski** [comment]
**Test plan:**
* Provide a huge value (500+) to a datapoint-name flagged question.
* Submit responses and ensure the name has been truncated (datastore viewer for example)

**Comment by rumca** [comment]
test plan passes as described on v2.1.4
