### ISSUE TITLE
Large fontsize option

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#279]
# Overview

This issue was brought up a couple of times last week. App font size setting is not as intuitive as it should, for the font scales up/down according to the device font setting. That is the user needs to set this up in the handset settings and preferences.

We should provide an in-app way of handling this

**Comment by janagombitova** [comment]
With @valllllll2000 we both disagree with the idea that this is needed in the app. It is a general device setting that the user should handle there and not in the app.
