### ISSUE TITLE
Single app

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#286]
# Overview

Dynamically configure any arbitrary instance (based on dashboard-generated codes), having a single app to manage any FLOW instance.
### Features:
- Allow multiple setups, potentially changing from one instance to another
- Verify codes -- https://github.com/akvo/akvo-flow-services/issues/88#issuecomment-88532272
- Bootstrap setup (TBD)

**Comment by valllllll2000** [comment]
Closing this one as a new issue was made #1179
