### ISSUE TITLE
JSON serialization

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#291]
# Overview

https://github.com/akvo/akvo-product-design/issues/80

**Comment by ichinaski** [comment]
**Test plan:**
* Create a form with all different types of questions included: text, image, video, barcode, geo, geoshapes, etc
* Submit a few instances of such a form
* Ensure all the data properly reaches the dashboard.
* Perform a bulk upload as well, expecting the same behaviour.

**Comment by rumca** [comment]
the above test plan passes as expected
