### ISSUE TITLE
Date responses mutable after form submission

### ISSUE THREAD

**Issue by andrewmolo** [akvo/akvo-flow-mobile#295]
**Problem**
Responses/values attached to question type date are mutable even after the form has been submitted to the dashboard

**Solution**
Values should be immutable after form submission
![2](https://cloud.githubusercontent.com/assets/1729842/7495148/c4ef5eee-f414-11e4-80eb-6bc4e07d2a1c.png)
![1](https://cloud.githubusercontent.com/assets/1729842/7495149/c4f15618-f414-11e4-86b4-9e480e37ef6e.png)

**Comment by ichinaski** [comment]
**Test plan:**
* Submit a form containing a *DateQuestion* response
* Browse the submitted form, and ensure the date cannot be modified

**Comment by rumca** [comment]
the above test plan passes as described :+1:
