### ISSUE TITLE
Support bluetooth barcode reader

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow-mobile#299]
The FLOW app already supports the reading of barcodes through an external app. However, this is quite cumbersome as it takes quite long, and is hard to do in low-light conditions.

The idea is to use a bluetooth barcode reader, such as the Unitech MS912 laser barcode reader: http://www.ute.com/products_info.php?rbu=0&pc1=3&pc2=296&pid=1160.

These devices use the HID protocol, meaning that they act as a keyboard, and don't need any special software integration: as long as an input field has focus, the codes read by the device are input in the field as if they were typed on a keyboard.

The bluetooth device can usually be configured to insert a separation character when multiple barcodes are read. In the case of the MS912, these are CR, LF, CR+LF, none, SPACE, TAB. We should support all of them.

As we don't know if the user wants to read a barcode using a barcode reader or a barcode app, the user interface should support both options.

The proposed interaction is:
1) for a barcode question, have two buttons: 'barcode app', 'bluetooth reader'
2) the 'barcode app' button fires the barcode reader app
3) the 'bluetooth reader' simply puts the focus in the input field, and perhaps performs a check to see if the barcode reader is already connected through bluetooth, and perhaps perform some sort of activation of the link.
4) the user scans a barcode. The app listens for a separation character, and as soon as it is put in, the value is taken and put into the list as a separate item.

**Comment by ichinaski** [comment]
Already integrated.
