### ISSUE TITLE
Refactor dependencies management

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#302]
# Overview

Although this is not a priority right now, we should consider refactoring this component at some point, aiming at having a simpler, more maintainable codebase.

**Comment by ichinaski** [comment]
I've been looking into [EventBus for Android](http://greenrobot.github.io/EventBus/), and after some testing, it seems to be a very string candidate for solving this problem. Its lightweight subscription-based messaging system can easily replace the current implementation, and the resulting code will also be way more maintainable.

**Comment by ichinaski** [comment]
Another possibility is [RxJava](https://github.com/ReactiveX/RxJava).

**Comment by valllllll2000** [comment]
Refactoring has started on specific components to use RxJava so closing this more general issue.
