### ISSUE TITLE
Handle form deletions

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#304]
# Overview

Since a survey/form can be deleted after the app has downloaded it, we want to prevent such a form from being submitted and therefore sent to the server.

The feature is twofold:

* The app will provide the form ID to which the zip file is associated, and GAE will respond with a failure message (404) if the form doesn't exist anymore.

* In order to prevent this forms from being responded at all, the app will provide a list of synced forms to the API, which in turn will respond with a list of any form that has been deleted.

Relevant issue in GAE: https://github.com/akvo/akvo-flow/issues/1183

**Comment by ichinaski** [comment]
Client side proposal:

Once the app receives the list of deleted forms, it needs to communicate such action to the user, and prevent the submission of these forms.

A friendly approach would be to *soft delete* the form, and instead of not displaying it in the available forms list, we'll disable (grey out) the item, adding a *This form has been deleted* description.

**Comment by mtwestra** [comment]
@ichinaski But when will it then be really deleted?

**Comment by ichinaski** [comment]
Never (unless they're manually deleted by the user). They will simply be **marked** as deleted with a flag, but the user won't be able to access them.

**Comment by mtwestra** [comment]
@ichinaski, I'm not sure if that is the right user interface... Perhaps we should ask Loïc for an idea?

**Comment by ichinaski** [comment]
:+1:

**Comment by ichinaski** [comment]
As discussed with @loicsans, the less intrusive and simple way to proceed is by displaying a notification that, upon dismissal, will remove the form from the device.

**Comment by ichinaski** [comment]
A small nuisance I notice after deleting some forms, is that the survey group is not deleted, since the removal happens at the form scope. This situation is particularly noticeable in non-monitored groups. This can be fixed by removing any group that hasn't got a form associated, but given this is an edge case already, we might not want to invest more time than necessary on it.

**Comment by ichinaski** [comment]
**Test plan:**
* Download a few forms, either with assignments or direct downloads.
* Delete the forms in the dashboard.
* Reopen the app and wait until the forms are synced:
    * Each deleted form should trigger a notification
    * Dismissing the notification will fully remove the form from the device

**Comment by muloem** [comment]
@ichinaski you may have mentioned it and I missed it but did we try this scenario?
* Download test form
* Take phone offline
* Gather data
* Delete form on dashboard
* Reenable wifi and wait for sync

**Comment by ichinaski** [comment]
@muloem indeed this is the other action taken to solve this issue. It's fixed in both app and backend. I'll add those steps to the test plan though.

**Comment by ichinaski** [comment]
## UI/UX issues

After some testing with @muloem, the current notification approach has proven to be somewhat misleading, as the form is accessible until the user dismissed the notification. At the same time, immediately removing the form upon receiving the message from the server might be a bit harsh in terms of UX (we don't know if the user is aware of that action).

The alternatives are:

* A) Leave the notification, and immediately delete the form.
* B) Implement a friendlier UX, with the forms being displayed, but disabled (greyed out) and showing an extra message (i.e. "This form has been deleted in the FLOW dashboard"). This flow involves no notification at all, which can easily be ignored.

cc/ @loicsans @mtwestra @muloem

**Comment by Kiarii** [comment]
Option B feels like the better way to go about it. We might further consider whether the user should be able to remove/hide a form/survey if they can no longer use..

**Comment by muloem** [comment]
@ichinaski @Kiarii @loicsans @janagombitova 

The graying out and the line mentioning the disabled survey goes where? 

1. On the initial screen i.e one containing the list of surveys,
2. On the screen with the list of data points? i.e after selecting the survey, 
3. On the *create data point* screen when trying to create a new data point

**Comment by ichinaski** [comment]
> The graying out and the line mentioning the disabled survey goes where? 

> On the initial screen i.e one containing the list of surveys

We cannot disable surveys. The deletion happens at the *Form* scope.

> On the screen with the list of data points? i.e after selecting the survey

Same as above. Surveys and datapoints might contain more (valid) forms.

> On the create data point screen when trying to create a new data point

Here. This is the list that displays all the forms for a single survey. Once the form is deleted, it will be marked as deleted in this screen.

**Comment by Kiarii** [comment]
I think this notification should appear next to the respective form (that
has been deleted); in the forms' list. In other screens it would be a bit
removed from the context it applies to and would therefore require more
cognitive effort to comprehend..

**Comment by rumca** [comment]
Both the test plans detailed above pass :+1:
