### ISSUE TITLE
Add unit test support

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#305]
Although an ongoing process, this work resides in the https://github.com/akvo/akvo-flow-mobile/tree/feature/257-repeat-question-groups-2 branch. 

The idea is to merge this isolated changes into develop, so other feature branches can immediately make use of this integration

Documentation:
This is not user documentation but for devs, but here are some basic instructions about tests:
https://github.com/akvo/akvo-flow-mobile/wiki/Unit-Tests

Test Plan:
Nothing to test manually here. Unit tests can be run with ./gradlew test

**Comment by janagombitova** [comment]
👍
