### ISSUE TITLE
Data editable after submission

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-flow-mobile#307]
Steps:
1. Create a form with a numeric question and requires double entry
2. Fill data in the form and submit it
3. Open the submitted data point

Issue:
The text field where the repeat value was entered in changeable.

**Comment by ichinaski** [comment]
Fixed. It is worth noting that this glitch was not letting the user update the data in the DB, just in the screen.

**Comment by ichinaski** [comment]
**Test plan:**
* Open a submitted form (containing a double entry question): The field should not be editable.

**Comment by rumca** [comment]
test plan passes as described
