### ISSUE TITLE
Add `Hindi` translations

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow-mobile#308]
Adding Hindi translation files to app

**Comment by muloem** [comment]
@joycarpediem how is this going?

**Comment by joycarpediem** [comment]
@muloem we are looking into it . A few translations are still a bit 'awkward'.

**Comment by joycarpediem** [comment]
@ichinaski , the translations have been updated

**Comment by ichinaski** [comment]
Great, thanks. I will add them to the repository :+1:

**Comment by ichinaski** [comment]
This issue is now manged in #312
