### ISSUE TITLE
Handle registration form updates

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#310]
Issue description: https://github.com/akvo/akvo-flow/issues/1078

**Solution:**

The app should automatically handle registration form updates. At the moment only when the form version has been updated will the survey group modify/update its properties (i.e. registration form).

The solution is to always update the form data, regardless of the form version being updated.

**Comment by ichinaski** [comment]
**Test plan:**

* Create a monitored survey with a couple of forms
* Create an assignment and sync the survey
* Update the registration form and save the survey
* Restart the app: The changes should be reflected

**Comment by rumca** [comment]
test plan passes as described

**Comment by rumca** [comment]
Hmm actually after some further testing, I think we're missing something with this one. When I submit a response from a Monitoring Survey after updating the registration form, I'm experiencing some strange behaviour on the data > monitoring tab.

When I click to delete any of the data which I've submitted **after** the registration form has been updated, it appears to be removed successfully - but reappears later when I fetch responses. Steps to reproduce:

* Create a monitoring survey with a couple of forms
* Submit some data using this survey
* Update the the registration form
* Submit some more data using the updated survey
* Visit the data > monitoring tab
* Fetch all the responses
* View the latest response (data appears as expected)
* Delete the latest response (data seems to be deleted)
* Fetch all the responses again
* Latest response is back again - only when you click to view it, it returns an empty popup:
![screen shot 2015-07-07 at 00 02 50](https://cloud.githubusercontent.com/assets/3003031/8535206/8d23bb20-243b-11e5-99f7-84cb1b75cff6.png)


Another comment in case it helps diagnosing what's going wrong - when I fetch the data report for the monitored survey it doesn't return any empty responses like the above does. Complete and utter guess - but do we need to delete the surveyedlocale or something now that we've updated which is the reg form?

**Comment by ichinaski** [comment]
> Another comment in case it helps diagnosing what's going wrong - when I fetch the data report for the monitored survey it doesn't return any empty responses like the above does.

Does this mean the report includes the seemingly deleted data?

**Comment by rumca** [comment]
The report doesn't contain the deleted data, it's just the monitoring tab that displays the deleted stuff.

**Comment by ichinaski** [comment]
Roger
