### ISSUE TITLE
Replace pipes with hyphes in datapoint names

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#316]
Issue discussed at https://github.com/akvo/akvo-flow/issues/1011

**Comment by ichinaski** [comment]
See https://github.com/akvo/akvo-flow/issues/1333

**Comment by ichinaski** [comment]
**Test plan:**
* Datapoint names with cascade values should display hyphens instead of pipes

**Comment by rumca** [comment]
test plan passes as described
