### ISSUE TITLE
Add codes to cascade questions

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#317]
# Overview

See feature description and format options at https://github.com/akvo/akvo-flow/issues/1323.

**App actions:**

* Once the aforementioned format is determined, the app will need to
    * Read the codes from the SQLite database.
    * Serialize path codes as part of the cascade response

**Comment by ichinaski** [comment]
# Cascade values format

The new values will be JSON-encoded, as define at https://github.com/akvo/akvo-product-design/blob/master/FLOW/arch/ADR-004.md

# Backwards compatibility in the app

Since previously collected values may exist in the app, we need to be wary and not take the JSON formatting for granted. This means existing responses parsing will:
    1) Attempt to load the JSON response. If this fails,
    2) process the former pipe-separated format, and load the response.

New responses, or values being saved after being loaded, will always use the new formatting.

**Comment by muloem** [comment]
@ichinaski can you write up a test plan for this?

**Comment by ichinaski** [comment]
**Test plan:**
1) Regular responses
* Create a cascade question, making sure the resource definition contains codes, and sync the form in the app.
* Fill in the question, and check the response format in the backend.
* Ensure the app can load existing (saved, submitted) values.

2) Backwards compatibility
* Using an old version of the app, provide some values for a cascade resource.
* Update the app, and attempt to open previously collected values.
* Values should be properly displayed. If the form was not submitted yet, the response will be saved using the new format.

**Comment by rumca** [comment]
@ichinaski when are planning on releasing this - presumably this coming week? Noticed something that I'm not sure is intended with the new code changes:

![screen shot 2015-11-01 at 22 51 04](https://cloud.githubusercontent.com/assets/3003031/10871840/27bf9e2c-80eb-11e5-9d69-0f5b9b45d7ff.png)

(the cascade question is set to be part of the datapoint name)

**Comment by rumca** [comment]
the above is addressed in #373
