### ISSUE TITLE
Show full length of notifications on mobile

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow-mobile#318]
At the moment, notifications on the android device are not word wrapped, which renders them unreadable if they are long.

The idea is to show the full message.
Apparently, this is how that is done:
http://stackoverflow.com/questions/16470583/android-notification-display-full-message

**Comment by ichinaski** [comment]
This has been in the pipeline for a while... unfortunately the proposed solution, which I was aware of, is only valid for Android 4+ devices, therefore not valid for our most common use cases.

I will look into this in more depth, see if there is an alternative.

**Comment by ichinaski** [comment]
**Test plan:**
* Check out any notification in an Android 4+ device (or emulator :wink:).
* Notifications in Android < 4 should remain visible (yet cropped)

**Comment by rumca** [comment]
The "Data has been exported to S.."(D Card) notification is the only one I can see which isn't fully readable - however you can read it if you rotate the device. 

@ichinaski given this isn't a critical notification, I guess we can close this issue? (also given the tests on emulator for < 4 version pass too)

**Comment by ichinaski** [comment]
There some additional changes related to notifications, which will be tackled for the next release. We can probably use a new issue though, so feel free to close this one :+1:
