### ISSUE TITLE
Investigate analytics and error tracking system

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#321]
# Overview

Since Caddisfly app also needs to implement some sort of error reporting system, we should ideally have an homogeneous solution for both apps.

The current solution (report errors to GAE and store them in the datastore) is far from being optimal, and many times stacktraces are clipped and not fully displayed.

We could well take this opportunity to investigate other solutions for analytics and error reporting tools in both FLOW and Caddisfly.

**Comment by orifito** [comment]
`flowapp` sentry project has been created. 
Instructions on how to configure clients: http://sentry.support.akvo-ops.org/flowapp/test/docs/java/

**Comment by valllllll2000** [comment]
Sentry added in #551
