### ISSUE TITLE
Display error when incorrect geoshape is captured

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-flow-mobile#322]
Currently a user can save an Area geoshape with area=0.00sq. m (generally in case of less than 3 points) or save a Line with length=0.00m.
The app should display an error message if such shapes are captured because
1. So that the user is only able to save valid shapes
2. Cleaning these kind of data is very painful

**Comment by janagombitova** [comment]
Closing this issue as it will be handled in #1283
