### ISSUE TITLE
Remove 500 char limit

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#326]
# Overview

[500 char limit](https://github.com/akvo/akvo-flow-mobile/issues/48) is not needed any more.

We need to remove such a constraint in free text question responses.

If we are to allow lengthy responses, we need to slightly adapt the UI, since long texts won't be easily readable in a single line item (horizontal scroll). A quick fix is to automatically adapt the text area according to the value.

**Comment by ichinaski** [comment]
*TODO: Line breaks are being displayed in the datapoint name. We need to replace them with spaces*

**Comment by ichinaski** [comment]
**Test plan:**
* Text question should not have the 500 char limit any more
* Input field grows as text response gets longer.

**Comment by rumca** [comment]
Test plan passes as described
