### ISSUE TITLE
Improve notifications readability

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#328]
# Changes

* Display exported form name (instead of form instance ID)
* Display deleted form name (instead of form ID)

**Comment by ichinaski** [comment]
**Test plan:**
* Submit a form. Notification displays exported form name (instead of form instance ID)
* Delete an assigned form in the dashboard. Notification displays deleted form name (instead of form ID)

**Comment by rumca** [comment]
Test plan passes as described with v2.1.10
