### ISSUE TITLE
Nepali translations

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#330]

**Comment by ichinaski** [comment]
@joycarpediem is this language still required?

**Comment by stellanl** [comment]
According to Jana and Jigmy, they are.

**Comment by stellanl** [comment]
The Nepali resource file does not have translations for the "Navigation drawer" strings. Otherwise it works fine.

**Comment by janagombitova** [comment]
According to Transifex Nepali is 100% now and ready for use https://www.transifex.com/akvo-foundation/akvo-flow-mobile/dashboard/

**Comment by janagombitova** [comment]
@stellanl and @valllllll2000 Nepali translations are not showing on the latest apk. I can select the language in the dropdown, but after restarting the app everything is in English. I tried moving from English to Nepali, app remained in English and I tried switching from Vietnamese to Nepali and the app showed in English.

**Comment by stellanl** [comment]
What version of Android are you using to test?

**Comment by janagombitova** [comment]
Nepali showing fully 👍
