### ISSUE TITLE
Synced files are re-uploaded (hotfix)

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#332]
# Overview

Certain image files are getting re-uploaded each time the sync cycle runs. This is caused by a regression introduced in https://github.com/akvo/akvo-flow-mobile/commit/f2a36fa6e2a82eff3e8c9e7a5c0b68ed8b5f5ca7

# Solution

Each time a file is submitted, the corresponding FileTransmittion status needs to be updated, reflecting the outcome of the upload operation.

**Comment by ichinaski** [comment]
**Test plan:**
* Start with a 2.1.9 installation suffering from this issue.
* Install 2.1.9.1
* Notification will be displayed once, but the issue will be gone from now on.
* Submit a new form containing images. Ensure the problem does not persist.

**Comment by rumca** [comment]
Test plan passes as described :+1:
