### ISSUE TITLE
Simplified UX

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#336]
# Overview
https://github.com/akvo/akvo-product-design/issues/114

# Actions

* Implement side menu to enclose all surveys. Surveys will remain selected across sessions.

**Comment by ichinaski** [comment]
### Test plan
a) **General Workflow. Ensure:**
* Users, surveys remain selected when closing/opening the app.
* Non-monitoring surveys take you directly to the form responses. Monitoring ones keep intermediate *forms/history* screen.
* Map is accessible from the ActionBar menu (within the data point), and data point is accordingly displayed. Note: Make sure the registration form is set to have a location question flagged with this property.
* Users can be edited, deleted when long-clicking the usernames in the side menu. Deleting the selected user results in no user being selected.
* History tab shows the reg. form first, then any other form, ordered by submission date (desc).

b) **App upgrade**
* 1) Install app v2.1.11, and sync a few surveys, both monitoring and non-monitoring.
* 2) Upgrade the app, and check everything works as expected for these forms. Collected data should be accessible in the new format.
* 3) If users were created in the previous version (this should almost always be the case) the *Add new user* screen shouldn't be displayed on the first run of the app.

**Comment by rumca** [comment]
Test plans pass as described - can't seem to find anything obviously broken in the new app :+1:
