### ISSUE TITLE
Minor UI Issue - Can we make the new coloured buttons more obviously disabled?

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow-mobile#348]
As per Skype discussion the other day - the new coloured UI buttons aren't as obviously disabled as the previous grey ones used to be. We now change the colour to grey when they're disabled - but they still look like they are clickable. Perhaps we could do something similar to the old button whereby the text was also greyed out/more obviously disabled. Old ones looked like below:

![screen shot 2015-10-05 at 17 45 42](https://cloud.githubusercontent.com/assets/3003031/10287062/f1a7980c-6b88-11e5-9574-c0cf436b5955.png)

**Comment by stellanl** [comment]
If we want to be innovative we could use -strikethough- text.

**Comment by janagombitova** [comment]
nice idea @stellanl - lets consult this with Loic and Kiarii

**Comment by janagombitova** [comment]
This is no longer an issue. We should consider removing buttons in the History view of a submitted form, but that should then have its separate issue. Closing this one.
