### ISSUE TITLE
The app allows deletion of repeat groups for submitted forms

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-flow-mobile#349]
The app allows deletion of repeat groups for submitted forms
v 2.1.11

**Comment by ichinaski** [comment]
Thank you. Will incorporate this fix for the next release.

**Comment by ichinaski** [comment]
**Test plan:**
* Submit a form containing repeatable question groups
* Upon submission, ensure the group cannot be deleted

**Comment by rumca** [comment]
Test plan passes as described :+1:
