### ISSUE TITLE
Geoshapes - Minor app fixes

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#350]
**Suggested changes**
- add a order number to each newly created point on the map. This is for the users to keep track on which point they added as last and create the shape they want. (Many times users loose track when creating complicated shapes and eventually end up with an odd shape, simply because they connected the wrong points - issue mentioned by Aulia)
- automatic zooming -  auto zooming the map to the correct scale once the user starts adding point. Currently it is difficult for the user to see the shape as it is being created. Zoom to such depths manually is pretty awkward on the phone (issue mentioned by Joy)

**Comment by ichinaski** [comment]
From Joy:


>
>Current scenario
>When a user clicks on capture geoshape, the map is generally at a zoom level of 14/15.
>As the user starts collecting points, which are inter-spread at about 15-20 m, he has to change the >zoom level to 21 to be able to "resolve" those points else they appear on top of each other .
>Also it is difficult to detect when one of the points "falls off the track" because of higher GPS error.
>
>Possible solution:
>The map can auto zoom to the max level so that the whole shape is visible

**Comment by janagombitova** [comment]
We are going to look at how users create geoshapes as a whole to try to resolve and simplify this question type https://github.com/akvo/akvo-product-design/issues/267

Smaller issues will then be created again
