### ISSUE TITLE
User creation defects

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#357]
**Changes:**
* Automatically select new users
* Prevent blank usernames

**Comment by ichinaski** [comment]
**Test plan:**
* Install the app from scratch. Initial set up screen (first user) should disable *Next* button when the username is left empty.
* Username cannot be blank when adding users from the side menu.
* New users are automatically selected.

**Comment by rumca** [comment]
Test plan passes as described.

Perhaps it would be preferential to leave the side menu open when a new user is added? At the moment it automatically selects the user, dismisses the side menu, and goes straight in to the last active project - which could be a bit disorientating?
