### ISSUE TITLE
Add form version to non-monitored surveys

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#365]
The form version is used to check whether the latest form is synchronised to the device. This is always checked before new data is collected. For monitoring surveys we show the form version in the list of forms - right before the user selects a form to collect data.  

The form version is not shown for non-monitoring surveys. As the user wants to check it before data is collected, we need to find a simple solution that does not clog the new design.

Options: 
- In the overflow icon when the user is in the list of data points. The issue here is, that the overflow icon hold actions related to data points, and the form version is a different subject.
- In the side menu, next to the name of the survey
- other

@ichinaski @Kiarii What do you think is the best solution here?

**Comment by ichinaski** [comment]
> In the overflow icon when the user is in the list of data points. The issue here is, that the overflow icon hold actions related to data points, and the form version is a different subject.

Indeed, the list of datapoints hols information related to the survey, not the form. If we were to use an overflow icon, it must be the one at the *form* level (question/answers screen).

> In the side menu, next to the name of the survey
This is also not optimal, since the side menu items are *surveys*, not *forms*. Version numbers are associated with the latter.

An alternative, that goes perhaps more in line with the simplified mindset (i.e. fewer actions/options available) is to display the version number below the form name, in the *form* screen.

Something like this:
![Action Bar](http://i.stack.imgur.com/Qrtbr.png)

**Comment by janagombitova** [comment]
I like this suggestion Ini. A few related questions: 
- When I am in the list of data points, the header holds the survey name. This would mean that the users sees the form version after clicking on the '+' icon. right? 
- Will this subtitle be shown for all forms then, when collecting the data and viewing the submitted data? (also for Monitoring surveys)

**Comment by ichinaski** [comment]
> When I am in the list of data points, the header holds the survey name. This would mean that the users sees the form version after clicking on the '+' icon. right?

Correct. The version will be shown in the next screen. We cannot display it below the survey title (datapoint list screen), as this version is not related to the survey at all.

> Will this subtitle be shown for all forms then, when collecting the data and viewing the submitted data? (also for Monitoring surveys)

It's really up to us, but that will provide consistency.

**Comment by ichinaski** [comment]
Deal! :+1:

**Comment by ichinaski** [comment]
**Test plan:**
* Ensure version is displayed in every form, below the form title.

**Comment by rumca** [comment]
Test plan passes as described :+1:
