### ISSUE TITLE
Option codes

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#367]
# Overview
https://github.com/akvo/akvo-product-design/issues/34

TODO:
* [x] Clean up and refactor option management
* [x] Parse and store option `code`s
* [x] Serialize/Deserialize JSON-formatted responses
* [x] Handle *OTHER* values
* [x] Backwards compatibility: Support pipe-separated responses.
* [x] Fix dependencies management
* [x] Adjust display name computation
* [x] Unit tests

**Comment by ichinaski** [comment]
**Test plan:**

* Run unit tests: `$ ./gradle connectedCheck` (You need a device/emulator plugged in)
* Create a form with the following option questions:
    * Single-choice (no other allowed)
    * Single-choice (other allowed)
    * Multiple-choice (no other allowed)
    * Multiple-choice (other allowed)
* Provide answers for all of the above combinations, making sure responses are properly saved and loaded (either for *saved* or *submitted* forms.
* Backwards compatibility check: Install the app overriding the previous version, after having submitted responses for some of the questions described above. Ensure all responses are loaded and properly displayed.
* Sync check (**Dashboard dependent**): Synchronise any survey containing option questions (you can simply turn on monitoring in the newly created one). All option responses should be loaded and displayed without issues.

**Comment by rumca** [comment]
Dependcies on option questions no longer seem to be working - I think it's related to the option codes but I could be wrong. If it helps with debugging there is a test survey on UAT under 1.9.4 UAT Folder/1.9.4 Non MF Surveys/1.9.4 Dependent Survey.

**Comment by ichinaski** [comment]
@rumca good catch. This problem was mainly associated with the format change we introduced halfway through the implementation. I have fixed the issue and am now adding some unit tests.

**Comment by rumca** [comment]
dependencies no longer an issue, work as intended :+1:

**Comment by rumca** [comment]
all of the above test plans pass as described

**Comment by rumca** [comment]
@ichinaski I was trying to break something else, and found a smallish issue. I'm not even sure it's related to the option codes - might just be a RQGs issue. When you set up an option question with allow other enable, it works as expected in a regular group. However in a repeatable group the other option is repeated twice:

![screen shot 2016-01-06 at 14 26 42](https://cloud.githubusercontent.com/assets/3003031/12144719/96af994e-b481-11e5-9650-c748fd89e5c5.png)

**Comment by rumca** [comment]
It also appears 3 times in the second repeat, 4 times in the third etc etc.

**Comment by ichinaski** [comment]
I was not aware of such issue in previous versions. Will put this at the very top of my list and fix it asap. I think it's well worth a fix prior to the deployments of 2.2.2.

CC/ @janagombitova @muloem

**Comment by ichinaski** [comment]
Fixed issue described in https://github.com/akvo/akvo-flow-mobile/issues/367#issuecomment-169337708

The problem was that each iteration of the repeatable group was adding the option *OTHER* to the original map. The solution to address this has been to deep-copy the options map when cloning the question for each iteration. See https://github.com/akvo/akvo-flow-mobile/commit/4daca75fd00c4d382dd546a5e0740618c6b504df
