### ISSUE TITLE
Add some indication of version the form is on non monitored things

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow-mobile#368]
Please disregard this if there's already a way of viewing this in the simplified app, but it would be useful if there was a way of viewing what version of a form you are filling out for non-monitored surveys. With the monitored ones there's a nice indication beside each form.

**Comment by ichinaski** [comment]
This was handled in #365

**Comment by rumca** [comment]
Whoops! Sorry, I should have checked existing issues.
