### ISSUE TITLE
Question Group translations

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow-mobile#369]
For forms that have translated question groups, the question group translations do not show up when languages are switched.

**Comment by ichinaski** [comment]
I'll hijack this issue for a somewhat related glitch I just found: *FORMS* tab is not properly translated under the datapoint view. At least in Spanish, it uses the term *ENCUESTAS* (surveys) which can be confusing.

**Comment by ichinaski** [comment]
@muloem Come to think about the original request, if we display question group translations the same way questions are translated, the tabs will be barely readable, since multiple languages can be enabled, and all translations are displayed at the same time (I never dig this feature myself. I believe one language should suffice). Also, having different colors in tab tiles will be tricky, and somewhat ugly, UI-wise.

**Comment by muloem** [comment]
Would it take a lot more effort to only display one language at a time based on the selected translation?
We should consult with @loicsans and @Kiarii about the UI/UX side of such a change.

**Comment by Kiarii** [comment]
@muloem (If I understand the concern correctly) one language per usagetime should be more than enough (as long as it is clear to the user that they can switch languages) it simplifies things; no repetitions, no looking out for text to ignore (second language), less cluttered screen space, shorter scrolling, no color coding or styling, ...

**Comment by ichinaski** [comment]
Languages management is rather complex right now, as it takes into account this multiple selection feature. Furthermore, languages can be selected from the app settings, which just displays every available language within all surveys, and users can select as many as they want. I too think a single language selection and display per survey is more than enough. IIRC from previous discussions, there was a reason for this. @mtwestra Do you perhaps remember the reasoning behind this?

**Comment by ichinaski** [comment]
To add more context: Currently the language selection is handled application-wide, and a single setting is stored for all surveys (multiple choice). The alternative would be to have one selection per survey (single choice).

**Comment by joycarpediem** [comment]
@ichinaski,  sometimes there is a requirement to display it in 2 languages . There are some terms that don't translate well from English . So they like both the languages displayed to that they can refer incase of such terms . But more than 2 languages  is almost never  used

**Comment by janagombitova** [comment]
Related to: https://github.com/akvo/akvo-flow-mobile/issues/428
