### ISSUE TITLE
Cascade resource compatibility issues

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#371]
# Overview

Old cascade resources do not have the *code* column in the SQLite database, which makes some devices throw an Exception when explicitly querying such property.

The solution is to query all available columns, and check the existence of such property in the resulting Cursor.

When using old resources, the generated levels' response will contain a **null** code property in the JSON-formatted response.

**Comment by ichinaski** [comment]
**Test plan:**

* Get hold of an outdated cascade resource (no codes in the SQLite DB). For this you can either use an existing DB, or modify an existing one, dropping the *code* column.
* Using such resource in a cascade question (flagged as datapoint name), use the app and fill in the form.
* Ensure:
    * Needles to say, that the app doesn't crash.
    * You can save cascade responses, and come back to them, while the data is preserved.
    * Submit responses.
    * Response is JSON-formatted, while having a *null* code in the properties. You can either check the response in the dashboard, or in the data store.
    * Response is formatted

**Comment by rumca** [comment]
@ichinaski submitted an old cascade from the apk and the below is the value in the qas:
```
[{"code":null,"name":"France"},{"code":null,"name":"Île-de-France"},{"code":null,"name":"Paris"},{"code":null,"name":"Paris, 17e arrondissement"},{"code":null,"name":"Paris, 17e arrondissement"},{"code":null,"name":"Paris, 17e arrondissement"}]
```

I think that's correct? I mentioned to @jonase that there's currently a slight formatting issue in the reports for such values but think that's OK for now :+1:

**Comment by ichinaski** [comment]
From my point of view, that is correct. When no code is specified, the code is `null`. If this is not breaking any other part of the system, I think this is okay.

**Comment by rumca** [comment]
:+1:
