### ISSUE TITLE
Vietnamese translations

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#372]

**Comment by ichinaski** [comment]
**Test plan:**

* Switch language to Vietnamese. Ensure app UI is translated.

**Comment by rumca** [comment]
Everything looks good for this, I noticed that "search" under the dotted option menu is still "search" in vietnamese - not sure if that's a missed translation or loan word?

**Comment by rumca** [comment]
closing this - will reopen if the above is an issue
