### ISSUE TITLE
Datapoint name on JSON-formatted responses

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#373]
# Overview

With the introduction of new response types, we can no longer dump the values into the datapoint name, since this can result in barely readable texts.

We need to handle each response type separately, parsing/translating the stored response, and fetching only the human-readable components.

First implementation will contain cascade values, wherein the JSON-formatted response will provide us with the *values*, that will in turn be separated by hyphens.

**Comment by ichinaski** [comment]
**Test plan:**

* Create a registration form with a cascade question, flagged as datapoint name.
* Additionally, throw in a few other questions (free text) with the flag, non-mandatory. This will serve for having different combinations and ensuring the concatenation of values works as expected.
* Provide some values and make sure:
    * Values are separated by hyphens.
    * Cascade responses are split into individual tokens, separated by hyphens.
    * Empty values are not used in the datapoint name.

**Comment by muloem** [comment]
@ichinaski 
* Perhaps also include a test for when the display name is over the xter limit?
* Does this change in any way affect data points that are freshly synchronised from the data store?

**Comment by ichinaski** [comment]
> Does this change in any way affect data points that are freshly synchronised from the data store?

Nope. Downloaded datapoints will keep their names. This only applied to newly created datapoints.

**Comment by rumca** [comment]
The above test plans pass as described :+1:
