### ISSUE TITLE
Delete survey from list by long-clicking on the survey name

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#378]
Before we introduced the 'simpler' app the user could delete a survey from her list simply by long clicking on that survey name in the Survey list. This is not possible anymore and we have received feedback from trainings that it is a very used feature and needs to be implemented asap.

**Comment by akvotender** [comment]
Assigned to [Tender discussion #6249](http://flowhelp.akvo.org/discussions/problems/6249-difficulties-to-delete-a-survey-on-the-phone).

**Comment by ichinaski** [comment]
**Test plan:**
* Delete a few surveys long-clicking the items in the side menu
* Assigned forms will be re-downloaded, therefore they will reappear in the list upon restarting the app.
* Manually downloaded forms will be permanently deleted

**Comment by rumca** [comment]
Test plan passes as described.

One minor comment - when you delete a currently selected survey, the project view thing isn't cleared. So you still see all of the previously submitted responses and have the option of creating a new data point (which just take you to a blank screen you can't do anything on). Is it straightforward to just clear the view if the deleted survey is the currently selected one?

**Comment by rumca** [comment]
above comment has been addressed :+1:
