### ISSUE TITLE
Signature question type

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#380]
# Overview

https://github.com/akvo/akvo-product-design/issues/117

**Comment by ichinaski** [comment]
**Test plan**

* Run unit tests: $ ./gradle connectedCheck (You need a device/emulator plugged in)
* Create a form containing a signature question. Ensure:
    * *Clear*, *Cancel*, *Save* actions in the signature pad work as expected.
    * Response remains invalid (cannot submit) until both signature **and** name are provided.
    * Save/Load existing responses. Everything should be populated/displayed as usual.
    * Data reaches the backend. You can either preview the data in the dashboard or simply check out the datastore.

**Comment by rumca** [comment]
Test plan passes as described - also checked out syncing signature responses in monitoring surveys and that works too :+1:
