### ISSUE TITLE
Handle invalid cascade questions more gracefully

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#382]
# Overview

Cascade questions lacking a cascade resource result in an app crash. We need to make the error more user friendly and display a more helpful message.

**Comment by akvotender** [comment]
Reported in the training of Guatemala by Laura.

**Comment by ichinaski** [comment]
**Test plan:**

* Create a cascade question, but do not define a cascade resource, and publish the form. If this is not allowed, copy a form from any other instance. The cascade question should lack the resource property.
* Ensure the app displays and error (without crashing).

**Comment by rumca** [comment]
@ichinaski I'm not really sure how to test this one, I tried copying a survey across instances but that's apparently broken currently and I can't create a survey without a resource specified in the dashboard. Do you know if I can just delete the property from the data store or anything? Alternatively do you have an example somewhere?

**Comment by ichinaski** [comment]
The only known scenario that can cause this is the *copy* action. A hacky though effective way to test this would be to fully remove the reference from the datastore, then publish the form.

**Comment by rumca** [comment]
I'll give that a go now then.

**Comment by rumca** [comment]
Huzzah, that worked & test plan passes :+1:
