### ISSUE TITLE
Disable (remove) location beacons

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#384]
# Overview

Every 30 minutes, the app sends a location beacon (latitude, longitude) to the dashboard. This can be disabled in the app, although it's active by default, and unless you explicitly access this setting, the service will be running in the background. 

This feature was originally used for tracking devices within a particular organisation, since the *devices* tab in the dashboard used to display the last known location for each device.

As this information is not displayed any more, and taking users' privacy into consideration, we are discussing the idea of fully removing this service.

**Comment by joycarpediem** [comment]
@ichinaski i've never heard of a robust enough usecase for this feature other that some over zealous project managers thinking  of track people. Given the privacy and battery consumption considerations i absolutely think this should be turned off by default. I think we can also remove it altogether without much backward compatibility issues as nobody has till now asked for us to display this data on the dashboard

**Comment by ichinaski** [comment]
It is certainly good to hear that @joycarpediem :+1:

**Comment by janagombitova** [comment]
@ichinaski and @joycarpediem I spoke with @mtwestra this morning. We can set the setting by default as **disabled** and leave it there for now, for the user to decide whether they want to be tracked or not.

**Comment by ichinaski** [comment]
Why not removing it altogether? It is not used at all, and will only imply unnecessary battery draining. Also it adds complexity on the user side for an option that has no visual nor practical feedback in the system.

**Comment by janagombitova** [comment]
For now, lets just disable it by default. 

If it is not used, then the battery drainage will not be an issue nor confusion will arise. This way we will not remove a option which is existing in the app. Before we delete an existing feature we need to be sure that the legacy of it is fully gone to avoid having the need to bring the feature back which will cost more time in the end. For now, simply understand it as an inherited feature.

**Comment by ichinaski** [comment]
> Before we delete an existing feature we need to be sure that the legacy of it is fully gone to avoid having the need to bring the feature back which will cost more time in the end. And moreover, when changing/ removing an existing option it is always safer to do it small steps at a time. 

This is where Git comes into play. Nothing is *fully* gone.

But it's okay, let's just disable it for now :+1:

**Comment by ichinaski** [comment]
**Test plan:**

* Ensure location beacons (Settings > Preferences) are disabled after a fresh install

**Comment by rumca** [comment]
test plan passes as described :+1:
