### ISSUE TITLE
Add order numbers to multiple barcode scans 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#389]
When you user scans multiple barcodes within one question - sometimes users need to scan 50 per question - it is hard to keep count. The idea is to add an order number to each scanned barcode within the app as a visual indication of the amounts of barcodes.

This will have **no** implications on the response format, dashboard implementation or reports.

**Comment by ichinaski** [comment]
**Test plan:**
* Ensure order is displayed in multiple barcode responses.

*Note: Single value barcodes do not have numbers*

**Comment by rumca** [comment]
@ichinaski is it expected that when we delete previously entered barcodes that the order remains unchanged? So for example add five barcodes, delete the fourth added one, then we have numbers 1 2 3 5?

(I'm assuming so since this is the same behaviour as RQGs)

**Comment by janagombitova** [comment]
@rumca it is expected to change, so you would have 1 2 3 4 (even if you deleted 4th). Why the counter was added is to show the enumerators how many scans he has taken, so the number order needs to be correct.

**Comment by ichinaski** [comment]
Good catch @rumca! I'll fix this.

**Comment by rumca** [comment]
Fix looks good :+1:
