### ISSUE TITLE
Geoshape questions are not properly initialised in repeatable groups

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#394]
# Overview

When repeatable groups are being loaded, the question `reset()` method is not getting called, thus some internal variables don't get initialized. This is the case for geoshape question's response view.

## Quick bug-fix

SImple fix for version 2.2.2 is to explicitly reset the question inside the `init()` method.

## Long-term fix

Question group loading and reset methods need some small refactor. Though tempted to tackle this now, I'd rather leave it for the next release, as it will require some thorough testing.

**Comment by ichinaski** [comment]
**Test plan (v2.2.2):**

* Create a survey with:
    * A geoshape question within a repeatable group
    * A geoshape question within a regular group
* Ensure both groups are initialised correctly (*Shape captured correctly* is not displayed until the answer is provided)

**Comment by rumca** [comment]
test plan passes as described
