### ISSUE TITLE
Configure device id in set up screen

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#395]
# Overview

Setting up the device id is an action every user must perform upon app install. I believe it makes sense to include it in the 'Set up' screen (first app run), along with the username.

**Comment by ichinaski** [comment]
@loicsans what do you think about just adding a 'Device ID' field below the username, without the need of introducing a whole new step/screen for this?

The validation mechanism could take care of ensuring both fields are filled in, otherwise displaying an (individual) error message.

![flow_setup](https://cloud.githubusercontent.com/assets/1754343/12109946/5ad360c2-b387-11e5-9e82-dc80e76ece93.png)

**Comment by ichinaski** [comment]
<img width="200" alt="flow_empty" src="https://cloud.githubusercontent.com/assets/1754343/12550092/c2bda64a-c361-11e5-82c5-e7b4d0cec368.png"> <img width="200" alt="flow_name" src="https://cloud.githubusercontent.com/assets/1754343/12550093/c2c44b08-c361-11e5-9381-a49f02e0bdcc.png"> <img width="200" alt="flow_nameid" src="https://cloud.githubusercontent.com/assets/1754343/12550094/c2c47d76-c361-11e5-8bbd-d97bd868e44b.png">

CC/ @loicsans, @janagombitova

**Comment by janagombitova** [comment]
I like it! Do the same validation rules apply for the Device ID as for the username? As you have to type in at least one character to enable 'next'?

How does this change affect the behaviour in the Settings - Device ID?

**Comment by ichinaski** [comment]
@janagombitova Correct. Unless you fill in both fields, the *Next* button won't be enabled. The deviceId property can be updated later on in the settings, screen. They refer to the very same attribute.

**Comment by janagombitova** [comment]
Perfect!

**Comment by ichinaski** [comment]
**Test plan:**

* Ensure you cannot proceed to the home screen until both the username and device identifier are filled in.

**Comment by muloem** [comment]
@janagombitova you will add the extra step of configuring the device in the documentation, right?

**Comment by rumca** [comment]
test plan passes as described :+1:
