### ISSUE TITLE
Image Geotagging

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#402]
Issue described at https://github.com/akvo/akvo-product-design/issues/74

**Comment by ichinaski** [comment]
**Test plan:**

* Create a form with one (or more) image question.
* With the device GPS enabled:
    * Take a photo, and wait for the GPS location to be displayed.
    * If the location does not come in before exiting the app, the location will **not** be added the next time the app runs. (*Unknown location* is displayed).
    * Location, if added after the image is taken, is saved and loaded when restarting the app.
    * Images without location show the unknown location text.
    * Downloaded images (monitoring form) do display the location, if saved
* With the GPS turned off:
    * After taking the image, the text immediately shows the unknown location text.
    * Previously captured and downloaded images (monitoring form) do display the location, if saved.

**TODO:**
    * I need to come up with a simple yet efficient way to check out the location information after storing the image in S3, since the app will not disclose the location details.

**Comment by rumca** [comment]
Might be the intended functionality, but I've set up a test survey with two picture questions which can result in slightly unexpected behaviour:

* Take a picture for the first question
* Save it
* Whilst the text still indicates that it is reading the location, click to take a picture for the second question
* The second question will get a location and the text updates accordingly, however the first never gets a location and always says "unknown location"

**Comment by ichinaski** [comment]
Thanks @rumca 

The reason seems to be the camera app taking over, which stops any location updates in FLOW (this is explicitly requested to avoid battery drains when the app is not in use)

After discussing the issue with @muloem we decided to run the location updates for up to one minute, rather than relying on system callbacks.

This same scenario is also affecting Geo Questions.

**Comment by ichinaski** [comment]
I've implemented a more generic *location listener* with the following characteristics:

* Uses GPS locations only
* Runs up to 1 minute
* Can be explicitly stopped (i.e. when the app is closed)
* Provides a simple interface to be notified upon location arrivals, GPS disabling, and timeouts

The idea is to replace both the *Media* and *Geo* questions' custom solutions, so they can use a more reliable interface, rather than implement the same behaviour in multiple places.

This helper class can easily be extended to support custom attributes (accuracy threshold, timeout settings, location sources, etc), though for now it just has the same settings we had in the GeoQuestion.

@muloem Since the main issue to address is to fix the defect described at https://github.com/akvo/akvo-flow-mobile/issues/402#issuecomment-182817743, perhaps we can use this utility in MediaQuestions for this release, and replace the GeoQuestion one for the next one.

**Comment by rumca** [comment]
fixes seems to look good :+1:

**Comment by ichinaski** [comment]
### Response format serialization test plan (WIP)

**Note: For the following test plans you'll need a monitoring form with media questions**

**App upgrade (start with an old version, eg v.2.2.3.1):**

* Collect (media) data prior to app upgrade
* Upgrade to v.2.2.4
* Ensure app functions as expected (browse old responses)

**Synchronisation:**

* Collect data with both the old and new apps, sending different formats to the dashboard
* Check all data is displayed in the dashboard (media links)
* Synchronise this survey in both versions of the app. Ensure all image responses can be browsed regardless of original app version.

**Comment by rumca** [comment]
Test plan passes as described.
