### ISSUE TITLE
Date question GMT offset

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#403]
# Overview

Although date question picker is using whatever default time zone is set in the device, the response is saving the timestamp in GMT. This generates a very subtle bug, that may decrease the user date by a day.

**Comment by ichinaski** [comment]
Created via Reamaze:

Link: https://flowhelp.reamaze.com/admin/conversations/error-cascade-files-not-downloaded
Assignee: Jana Gombitova

Message:
Dear Sirs,

We are undertaking a survey today and some of our devices are not able to download the survey forms. This happened after the AKVO update of last night. Please urgently address this.
1.    Link- SSH4A
2.    Folder- Kenya
3.    Survey- 15/12/2015 SSH4A HH questionnaire Kenya

Regards,

Fanuel Nyaboro
Country Project Leader, SSH4A Results Programme
SNV Netherlands Development Organisation
Ngong Lane off Ngong Road,
P.O. Box 30776 - 00100, Nairobi
Kenya
T  +254 20 263 3426 / 2405 955 / 2450 983
    +254 725 335640 / 734 425466
M +254 733 608040

Email: fnyaboro@snvworld.org<mailto:fnyaboro@snvworld.org>
Skype: f.nyaboro
Twitter: @fnyaboro

www.snvworld.org<http://www.snvworld.org/>

Subscribe to our newsletter here<http://www.snvworld.org/subscribe>

DISCLAIMER: This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. Any views or opinions presented in this email are solely those of the author and do not necessarily represent those of SNV. SNV accepts no liability for any damage caused by any virus transmitted by this email.

**Comment by ichinaski** [comment]
**Test plan:**
* Create a form containing a Date question
* Fill in the question an ensure:
    * The text date is displayed accurately in the input field
    * Date is accurate in the dashboard & reports

**Comment by muloem** [comment]
@ichinaski the comment above that was created above was accidental right?  If so please delete, otherwise please edit to only display relevant info for the issue. We should probably avoid sharing user data here.

**Comment by ichinaski** [comment]
Good point. The text was automatically copied from Reamaze upon linking the issue.

**Comment by rumca** [comment]
I can't seem to get the datepicker to play ball, when I set my device timezone to Fiji - which pushes the date along - the datepicker in the app is still giving me the GMT date. Could someone else verify this is fixed if possible?

**Comment by ichinaski** [comment]
@rumca Let me look into this. I think the solution of using GMT **everywhere** was too drastic after seeing your comment. We'll probably need to deal with local times for user facing widgets, then GMT for data serialization.

**Comment by muloem** [comment]
@ichinaski can you update the test plan to include the steps that created the original issue?

**Comment by ichinaski** [comment]
@muloem how do you mean? The bug appeared simply filling in a date question (part of the test plan)

**Comment by muloem** [comment]
I understood that the bug occurs for example when I fill in a response at a time when the GMT would be a day behind. e.g if I filled in a date question at 01h00 in a GMT + 2 timezone, the GMT would result in the time from a day before at 23h00.

**Comment by muloem** [comment]
So a step to make sure this is the test case setup

**Comment by ichinaski** [comment]
The bug occurs by simply not having GMT TZ. I updated to test plan to reflect that :+1:

**Comment by rumca** [comment]
Test plan passes as described.
