### ISSUE TITLE
Auto zooming while collecting geoshapes

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-flow-mobile#405]
Current scenario 
When a user clicks on capture geoshape, the map is generally at a zoom level of 14/15.
As the user starts collecting points, which are inter-spread at about 15-20 m, he has to change the zoom level to 21 to be able to "resolve" those points else they appear on top of each other .
Also it is difficult to detect when one of the points "falls off the track" because of higher GPS error.

Possible solution:
The map can auto zoom to the max level so that the whole shape is visible

**Comment by ichinaski** [comment]
Continuing this discussion on #350
