### ISSUE TITLE
Research alternative communication protocols

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow-mobile#41]
For the communication between the device and the backend, we need a common communication protocol. Some of the alternatives include

* JSON 
* Apache Thrift
* Google's protocol buffer
* Apache avro

Some characteristics that need investigation are:
* Android support
* Language agnostic
* Schema support
* Debuggable / human readability
* Robustness, fault tolerant
* Effort to serialize  / deserialize (time, cpu, memory)
* Binary support to support compressed datasets
* AGPL compatible license

**Comment by ichinaski** [comment]
Closing this and tackling any relevant protocol on https://github.com/akvo/akvo-product-design/issues/
