### ISSUE TITLE
Bahasa Indonesia and Portuguese translations

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#410]
From the Android documentation:

> Note that Java uses several deprecated two-letter codes. The Hebrew ("he") language code is rewritten as "iw", Indonesian ("id") as "in", and Yiddish ("yi") as "ji"

**Comment by ichinaski** [comment]
**Test plan:**

* Switch to *Bahasa Indonesia* language in the app settings
* Ensure the language is used in the UI

**Comment by rumca** [comment]
Test plan passes as described
