### ISSUE TITLE
Repeatable cascade questions - FLOW app hotfix release 2.2.2.3

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#419]
From support:

> This is an urgent issue as 40 enumerators are in the field spread in DRC and we need a quick solution while this is a bug from the system.
>
>http://m3p-eva-rdc.akvoflow.org/admin/
>
>We are in the folder: Enquete M3P finale in sub folder :
>* Questionnaire Ecole : survey E1B_dossiers EA, E3_CAP PC EA, E4_Qualité CAP EA
>* Questionnaire Village : survey V1B_Dossiers VA, V0B_Qualité CAP VA, V0C_CAP PC VA
>
>Those 6 surveys have similar construction :
Group 1 with 1 cascade question
Group 2 is repetitive with 1 cascade question
>
>Problem is on the device the 2nd cascade doesn't show : after the question text, the options doesn't show (see screen shot attached, question 1)
Cascade ressources are working well as they are also use is other survey without problems
>
>We tried to delete the First cascade, the second cascade was still not showing on the device.
We tried to make the group 2 non-repetitive, the second cascade was visible on the device.
>
We would expect that when a cascade question is used in the repetitive group, the cascade question show as usual.
>
Let us know if a quick fix is possible or if we need to redesign the surveys to have non repetitive group
>
Cheers

**Comment by ichinaski** [comment]
**Test plan:**

From the bug report:

> * Group 1 with 1 cascade question
> * Group 2 is repetitive with 1 cascade question
>
> * We would expect that when a cascade question is used in the repetitive group, the cascade question show as usual.

**Comment by rumca** [comment]
Test plan passes as described :+1:
