### ISSUE TITLE
Caddisfly question type

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#421]
Formerly known as _External source question_, Caddisfly will now have its own question type: https://github.com/akvo/akvo-flow/issues/1577

**Comment by janagombitova** [comment]
As explained above, we have implemented a new question type for Caddisfly water quality tests (fluoride, EC and strip tests). The user adds a specific test to his survey as a question, in the app the user click on the start tests button that brings him into to Caddisfly app and the test. After a test is successfully completed the app opens Flow nicely, but in the answer field we only show: "Test captured successfully" 

It would be useful to show the value captured instead. It does not have to be the full image and value as shown in the Data tab, but the value itself will tell the user more about the water sample.

**Comment by muloem** [comment]
@janagombitova this was already integrated in the app in version 2.2.4 but requires testing along with the dashboard implementation

**Comment by janagombitova** [comment]
@muloem all right, will test it once UAT and the app are ready for testing 👍 

## Test plan

1. Create a survey in the dashboard that holds the new Caddisfly question. Create a question for each test type. Add the survey to an assignment for your phone.
1. Download the Caddisfly apk and make sure you have all the extras needed to run the Caddisfly tests.
1. Open the Flow app, start the survey with the Caddisfly questions in it. 
1. Once you reach the question and button should be shown to run the test
1. Click on it and the Caddisfly app should open immediately on the test for your question
1. Run the test. 
1. After the test is completed you should be brought back to Flow app and the result should be indicated in the answer field 
1. Continue with the other questions, skip one mandatory Caddisfly question and try to submit the form
1. You should not be able to do so, go back to the question and run the test 
1. Submit the form 
1. Make sure you can view the form submission on the app and all answers are shown properly
1. Make sure answers were properly synced to the dashboard

**Comment by janagombitova** [comment]
## Notes from test 1 

All current tests available for the users to select render on the Flow app properly with the Go to test button. The test triggers the Caddisfly app with the proper test selected. 

I could not run the actual EC tests as my phone does not support OTG and neither the strip tests as the initial quality check stops at 10 out of 15 and it seems as the shadows are not being checked at all. I informed Nischal about the issue. 

So for now we cannot consider this issue fully tested yet
