### ISSUE TITLE
Read images from Caddisfly question results

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#422]
Feature description: https://github.com/akvo/akvo-flow/issues/1577

**Comment by ichinaski** [comment]
Handling this issue in the previous thread #421

**Comment by mtwestra** [comment]
We have decided to support multiple images in a single answer. This means that on the Caddisfly app side, we will make the following changes:

In the intent, the image property will be an array of paths to images, in which the strings are escaped:
["\/storage\/emulated\/0\/Akvo Caddisfly\/result-images\/7416c217-b2b5-4670-8626-628dd16c2f05.png"]

In the answer, the image property is an array of image names:
{"result":[{"name":"Total Chlorine (ppm)","value":10,"unit":"ppm","id":1},{"name":"Free Chlorine (ppm)","value":0.5,"unit":"ppm","id":2}],"type":"caddisfly","name":"Chlorine and Free Chlorine","uuid":"bf1c19c0-9788-4e26-999e-1b5c6ca28111","image":["5a59a588-056b-4750-99bb-fd655c7105bb.png"]}

The FLOW app needs to parse the image property in the intent, and upload all images.

**Comment by mtwestra** [comment]
We will handle this later.
