### ISSUE TITLE
Change colour of action button for SNV branded app

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#423]
SNV requested to change the green colour used for the action icons as ‘Next’, ‘Take Photo’, ‘Submit’, etc to a dark blue. Based on the SNV brand book I assume that the colour in mind in SNV Purple - C100 M100 - R79 G35 B100. Once the colour is confirmed we can make the change. 

<img width="892" alt="screen shot 2016-02-26 at 16 46 18" src="https://cloud.githubusercontent.com/assets/12456965/13356986/7e089df6-dca8-11e5-9815-9047b995c72a.png">

**Comment by janagombitova** [comment]
@ichinaski Will this change happen for both SNV apps?

**Comment by ichinaski** [comment]
> Will this change happen for both SNV apps?

Yep, they share the same branding settings (except the name)

**Comment by janagombitova** [comment]
Ok.

**Comment by ichinaski** [comment]
@janagombitova is this issue still relevant?

**Comment by janagombitova** [comment]
@ichinaski nope, not right now as they were not able to agree on a colour. Closing the issue.
