### ISSUE TITLE
Add Khmer translations to app

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#447]
Add Khmer translations to app provided by @joycarpediem in Transifex from a partner in Cambodia. In language dropdown in app use "Khmer" as language name.

**Comment by joycarpediem** [comment]
All khmer translations are now in transifex

**Comment by joycarpediem** [comment]
The partner had asked for a few changes. The changes are now in transifex

**Comment by osg74** [comment]
Test plan is missing.

**Comment by janagombitova** [comment]
Khmer will only be added to the app once the translations are 100% completed. 

## Test plan 
1. Open Flow app
1. In Settings change the language to Khmer 
1. Go through the app and make sure all of the strings are translated 
1. Go back to language Settings and make sure the current language is shown as Khmer. 
1. Change back to English

**Comment by janagombitova** [comment]
👍  passes test plan
