### ISSUE TITLE
Hotfix: Do not report MAC address if phone number is not known

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#448]
# Overview

Starting with 6.0, MAC address can no longer be read from the device. This is causing a serious bug in the backend, wherein devices cannot be properly identified when the phone number is unknown.

The solution should apply to both ends. In the app, the proposal is to _not_ send any property in the `phoneNumber` param if the phone number cannot be read.

**Comment by ichinaski** [comment]
As discussed with @muloem, we will based the filter on the Android OS version, simply not reporting MAC addresses on Android > 6.0. This will allow existing devices without IMEI (tablets mostly) to reliably be updated and identified based on the `androidId`

**Comment by stellanl** [comment]
This fix was not quite right. The test for Marshmallow is >Build.VERSION_CODES.LOLLIPOP (Android 5.0:22) but API version 23 was also Lollipop (Android 5.1).
Therefore Android 5.1 phones are not reporting MAC address as DevicePhoneNo even though it is available.

**Comment by janagombitova** [comment]
Link: https://flowhelp.reamaze.com/admin/conversations/device-keeps-downloading-not-assigned-forms
