### ISSUE TITLE
Multiple sequential connections to Location Beacon service

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#45]
Some instances are reporting logs showing devices with several sequential connections to this service (i.e water for people, sandbox):

This is an extract from sandbox:

>    **2013-11-15 17:42:39.007** /locationBeacon?action=beacon&phoneNumber=5104685075&imei=A0000030E96BD5&lat=37.8074278&lon=-122.3004525&acc=872.0&ver=1.11.0&osVersion=Android+4.0.4&devId=Neha+SII
>    **2013-11-15 17:42:37.955** /locationBeacon?action=beacon&phoneNumber=5104685075&imei=A0000030E96BD5&lat=37.8074278&lon=-122.3004525&acc=872.0&ver=1.11.0&osVersion=Android+4.0.4&devId=Neha+SII
>    **2013-11-15 17:42:37.149** /locationBeacon?action=beacon&phoneNumber=5104685075&imei=A0000030E96BD5&lat=37.8074278&lon=-122.3004525&acc=872.0&ver=1.11.0&osVersion=Android+4.0.4&devId=Neha+SII
>    **2013-11-15 17:42:36.021** /locationBeacon?action=beacon&phoneNumber=5104685075&imei=A0000030E96BD5&lat=37.8074278&lon=-122.3004525&acc=872.0&ver=1.11.0&osVersion=Android+4.0.4&devId=Neha+SII
>    **2013-11-15 17:42:29.189** /locationBeacon?action=beacon&phoneNumber=5104685075&imei=A0000030E96BD5&lat=37.8074278&lon=-122.3004525&acc=872.0&ver=1.11.0&osVersion=Android+4.0.4&devId=Neha+SII
>    **2013-11-15 10:40:52.603** /locationBeacon?action=beacon&phoneNumber=5104685075&imei=A0000030E96BD5&lat=37.8125348&lon=-122.3003528&acc=1110.0&ver=1.11.0&osVersion=Android+4.0.4&devId=Neha+SII

After some research, it seems that this bug is caused by java's Timer class (used [here](https://github.com/akvo/akvo-flow-mobile/blob/master/survey/src/com/gallatinsystems/survey/device/service/LocationService.java#L113)), having known problems when the system time is changed and some tasks are scheduled: http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=4290274

**Comment by valllllll2000** [comment]
location beacon has been removed
