### ISSUE TITLE
Change in submission not reflected in point History

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#451]
After a data point submission is made to the dashboard the user can edit the answers either via data cleaning or via the edit option in the data tab. After a change to an answer is made this change is reflect in the submission preview on the data tab and in a raw data report. After synchronising the point back to the app, however, the change is not reflected in the History preview of the submitted form on the app.

Even for cases where the answer builds the data point name, the point name is change after syncing but the History form still shows the old version. After deleting everything from the app and re-syncing the point back to the phone, the History form is still showing the old version.

This issue is relevant only for monitoring points that can be synchronized to the device.

![screen shot 2016-11-07 at 14 21 39](https://cloud.githubusercontent.com/assets/12456965/20059271/a747fd90-a4f5-11e6-83e2-5c82e2d07c5d.png)

*Example of a data point, where the 1st question is free text. The original answer was "uat" but I changed that via data cleaning to "AHOJ". The data point name got built properly, but when I check the History of the data point on the app, the submitted form still shows 'uat' as an answers (even after deleting all data from the app and re-syncing everything again)*

**Comment by valllllll2000** [comment]
I have been testing this and the issue seems to be coming from the api which still returns the old value. Will open issue in akvo-flow project.
