### ISSUE TITLE
Update to vietnamese translation for GPS accuracy

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-flow-mobile#452]
The translation for "Acc" has been updated in transifex

**Comment by osg74** [comment]
Test plan is missing.

**Comment by janagombitova** [comment]
## Test plan 
1. Open Flow app
1. In Settings change the language to Vietnamese 
1. Go through the app and make sure all of the strings are translated, also the accuracy when capturing geolocation
1. Go back to language Settings and make sure the current language is shown as Vietnamese. 
1. Change back to English

**Comment by janagombitova** [comment]
👍  passes test plan
