### ISSUE TITLE
Display keyboard after 'other' is selected 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#459]
When the user is filling in a option question that has 'other' allowed and selects 'other', the keyboard does not show right away on the screen. The user needs to know that he/she has to click on the text input field to reveal the keyboard. 

![screenshot_2016-07-21-09-39-25](https://cloud.githubusercontent.com/assets/12456965/17014931/93965720-4f27-11e6-8478-84a2f14a38e0.png)

To ease the way of filling in other, to decrease the number of steps taken by the user and to also give a visual indication that the option can be specified, we should show the keyboard at the same time with the text input field.

**Comment by stellanl** [comment]
Be aware that if you do this you somewhat break the Android input model. All popup text fields require you to tap in them before the keyboard shows up. You are supposed to be able to see the form before the keyboard obscures half the screen...

**Comment by janagombitova** [comment]
@stellanl thanks for explaining. I was not aware of the fact that we may break the Android input model. This is not a priority item and before taking any steps we need to run this by the design team first to get their input. It can wait for the time being
