### ISSUE TITLE
Remove text input field for barcode questions if manual input is disabled

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#460]
There are two ways of filling in barcode questions on Flow: manually and with a scanner. The survey designer can decide whether, he/she wants to 'disable manual editing of values on device'. If this flag is triggered the app user cannot type in the barcode and must you a external scanner to get the answers. 

![screenshot_2016-07-08-18-35-17](https://cloud.githubusercontent.com/assets/12456965/17015174/fa4f16e0-4f28-11e6-973e-37594342900e.jpg)

Currently the way **barcode questions with disabled manual editing** is displayed on the app shows both the text field and the scanner button. Seeing the text input field makes it confusing as the user tries to tap in the field, but it is disabled. To make it more clear that the user cannot manually type in the barcode but **must** use the scanner button the idea is to remove the text input field for these specific cases.

![img_3182](https://cloud.githubusercontent.com/assets/12456965/17015145/c82dbf22-4f28-11e6-9c8b-5fa71583bc78.JPG)

**Comment by valllllll2000** [comment]
## Test plan:

Create a survey with a barcode and disable manual editing.
Make sure barcode is displayed as required before inputting the data, after and also after submitting.

Try the same with manual editing enabled.

**Comment by janagombitova** [comment]
👍  implementation passes the test plan. Works like a charm!
