### ISSUE TITLE
Use new Flow app icon

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#466]
The Comms team was working on consistent icons for all our products to follow the branding guidelines.Up until now our icons only had the word Akvo, on a supporting background colour. That worked well, as none of the apps shared the same background colour, which is based on whether the product is Capture, Understand or Share. With the introduction of the Caddisfly app, we suddenly have 2 orange products, which means we need to differentiate in a different way. The new icons now all include the full product name. Even though the logo’s are quite small, it’s enough to differentiate between different products.

Here is the new Flow icon. Please replace the old one with this new on in the app. 

![flow_app-icon_512px](https://cloud.githubusercontent.com/assets/12456965/17844935/93c9e2ea-683e-11e6-9be0-7fc2ff1a7bff.png)

**Comment by stellanl** [comment]
Just as with the RSR Up icon, this is only 8 bit deep. We don't put the Flow app in Play Store yet, but there it needs to be 32 bit deep. Also, for the app itself, it needs to be 120x120 pixels.  I tried resizing it with Gimp but it comes out a bit ugly...

**Comment by janagombitova** [comment]
@stellanl thanks for checking, I can forward Linda your comments and ask her for the right sized icon. Will keep you posted

**Comment by janagombitova** [comment]
@stellanl new app icon from Linda 
![flow_app-icon_120px](https://cloud.githubusercontent.com/assets/12456965/19520080/21bf1d06-960f-11e6-8417-57f3d01e76ec.png)

**Comment by janagombitova** [comment]
New icon shows nicely. 👍  passes test plan. The distinction between Flow and Caddisfly apps also looks good
