### ISSUE TITLE
Change the query type for the data point search

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-flow-mobile#467]
The user can perform search operations on the data points list.
The query type is currently "startWith" .
Most display names are generally of the structure
ADM1-ADM2-ADM3-ADM4-Name

A workable list of points can only be obtained if the user can search with ADM3 or ADM4.
In the current scenario , the user needs to enter ADM1-ADM2-ADM3-ADM4 to get the list which is cumbersome.
An extra degree of complexity is added because the ADM's generally comes from cascades and cascades do not support translations. So a cascade entry looks like ADM1-<ADM1 in local lang>,
which makes the display name search string look like 
ADM1-<ADM1 in local lang>-ADM2-<ADM2 in local lang>-ADM3-<ADM3 in local lang>-ADM4-<ADM4 in local lang> which now goes beyond the realm of usability.
The workaround of sorting the list by name also does not work because if you have a few few thousand records on your phone, which is not very uncommon as all points for the survey are now synced to the phone, one has to keep scrolling forever to get to the list.
Sort by distance will only work when the data collector is physically in ADM4, and hence will not help .

**Comment by janagombitova** [comment]
## Current set up

When using the search option on the app, the user can search by name or ID. However, the set up is currently `startWith` thus the user needs to know the exact name or ID of the data point he is searching for. 

## Background 

Our users collect thousands of data that are referenced in data points. With monitoring projects, the users synchronise data points from their colleagues onto their own devices to be able to collect the 2nd (3rd or 100th) round of extra information for that household, school, farm yield, water pump, etc. However, this means that uses can end up with thousands of data points on their phone, or even with tens. Each enumerator is instructed to monitor only a particular set of data points. Sometimes it depends on where he is located, he just gets a list to complete, or he simply goes to the water pump or household and has to find it in his list. 

## Search
He has different ways of finding the data point he needs in his list on the app. He can **sort** or **search**. He can search in the list of points by **data point name** or by **data point ID**. 

### Searching by data point ID
If the user knows the data point ID and uses it to find the data point in the list, it usually means that he has it written down somewhere and starts typing the ID in the search box staring the with first character. For this case it works fine.

### Searching by data point name
The data point name story and search relationship is different. Usually the data point names are build from answers about location, a special ID, or name. There might be one particular information in that array of strings that the enumerator knows by heart. If the data point name consist of 4 items and this information is on the 3rd place, he cannot use the search option. As he does not know the 1st item that builds the data point name.

Example: I am standing at a water point and see that the well is tagged as number 50. The well's data point name is build of: Village name - Name of responsible organisation - tag number - type. I know my well is number 50, but I cannot search for it, just by typing in "50". I would have to type in: "Hrusov - CWSA - 50" and then it will show in the search. 

![screen shot 2016-11-25 at 15 10 42](https://cloud.githubusercontent.com/assets/12456965/20627614/7b1da078-b321-11e6-8b87-156ce33e6ff4.png)

## Need
We would ease up the search for data points in long lists. If the user can type in any part of the data point name (not necessarily having to start with the first letters of the name or ID) and we can filter through the list, it will very much ease their experience in the field.

**Comment by valllllll2000** [comment]
Test plan:
Create a simple monitored survey and assign it to your device.
The survey first question is text and use as datapoint name is checked
The second question is a number and also used as datapoint name.
Fill in the survey answering 
Q1              Q2

- Barcelona - 50
- Madrid -      50
- Berlin -       60

Press search. Try searching 50, you should get Barcelona - 50  and Madrid - 50

**Comment by janagombitova** [comment]
👍  implementation passes test plan. The user can search on any item that build the data point name and the search happens across the full string.

**Comment by janagombitova** [comment]
I thought I was a bit too quick with writing my comment. After testing the implementation on my dinosaur phone (Android version 2.3.6) all works fine as well 👍
