### ISSUE TITLE
Improve app notifications

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow-mobile#468]
The app at the moment inserts individual notifications in the notifications drawer for various actions that take place. This results in clogging the device's notifications drawer. More recent versions of Android enable aggregating the notifications for the same app or same actions into a single set. We would like to take advantage of this feature in the later versions of Android.

**Comment by janagombitova** [comment]
Relevant for https://github.com/akvo/akvo-flow-mobile/issues/125 and vice versa

**Comment by janagombitova** [comment]
We are changing how we are using notifications in the Flow app and moving towards almost no notifications and more in screen indication as toasts, snack bars or visual updates. More details can be found here: https://github.com/akvo/akvo-product-design/issues/218 Thus closing this issue
