### ISSUE TITLE
Fit keyboard with log in screen to remove overlap

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#469]
When a user opens the Flow app for the 1st time, she needs to enter her user name, device ID and hit Next. When entering the User Name the keyboard pops up but overlaps with the Next button. Users then need to figure out how to hide the keyboard to see the Next button again and this causes confusion and struggle as many of our users do not know how to hide the keyboard. 

Please check the implementation with different devices and screens as well as screen orientation. Thanks. 

![screen shot 2016-09-26 at 14 02 04](https://cloud.githubusercontent.com/assets/12456965/18833621/e09e91fa-83f1-11e6-929b-922cb309f147.png)

_(image of issue on a Samsung GT-19301l)_

**Comment by valllllll2000** [comment]
After talking to Jana, it has been decided to include the Action Done in the keyboard for now so when user presses done does the same as pressing the next button.

**Comment by valllllll2000** [comment]
Test Plan:

On a device without any users logged you will get the user creation screen.

Create user and use the keyboard only to navigate from first text input to the next and the tick or save (depends on keyboards you may see either a "done" or just an image with a tick.
Make sure the user is created correctly
Restart the same procedure but using the old next button (should still work the same way as before).

**Comment by janagombitova** [comment]
Fix passes both cases perfectly, using the keyboard and also the original Next button 👍
