### ISSUE TITLE
Show Caddisfly result in more meaningful way

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#470]
We have implemented a new question type for Caddisfly water quality tests (fluoride, EC and strip tests). The user adds a specific test to his survey as a question, in the app the user click on the start tests button that brings him into to Caddisfly app and the test. After a test is successfully completed the app opens Flow nicely, but in the answer field we only show: "Test captured successfully"

It would be useful to show the value captured instead. It does not have to be the full image and value as shown in the Data tab, but the value itself will tell the user more about the water sample. If we can implement the full answer (value and image) as in the Inspect data tab, that would be even better. This information needs to also be shown when viewing submitted forms for monitored data on the device (or non-monitored surveys as well) as the user might want to see the captured value for the data point

![screenshot_2016-11-02-09-12-44](https://cloud.githubusercontent.com/assets/12456965/19963447/be8db094-a1bc-11e6-85cb-fabf5b27a87f.jpg)

Here is an example of how we show the result in the "old" Caddisfly implementation and how we show the "new" Caddisfly question results. Already showing the value would be a step forward to the current way of only showing the tex.

**Comment by valllllll2000** [comment]
Here is what the dashboard displays

![screenshot from 2017-03-22 11-47-13](https://cloud.githubusercontent.com/assets/923280/24194419/4ff0dc22-0ef6-11e7-8165-24ac633c84c2.png)

**Comment by valllllll2000** [comment]
@janagombitova this what I have got so far, what do you think?
![screenshot_20170322-173631](https://cloud.githubusercontent.com/assets/923280/24209376/57661046-0f26-11e7-90c9-af67b746704e.png)

**Comment by janagombitova** [comment]
@valllllll2000 it looks perfect 👍

**Comment by valllllll2000** [comment]
## Test plan
If you have some datapoints created (ej the iceland form) sync and view them on your device, make sure it looks like on the screenshot above.
Also test adding new datapoints, it should look similar to the screenshot as well except for the button color of course.

**Comment by janagombitova** [comment]
👍  beautiful
