### ISSUE TITLE
Problem with syncing of re-published surveys

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#471]
After the user makes a new survey and publishes it, she creates an assignment that sends the survey to the app. The problems seem to occur once the user makes changes to the survey and republishes it. The app user needs to close the app on the phone and reopen it to establish connection. However in some cases ([see support issue](https://flowhelp.reamaze.com/admin/conversations/akvoflow-support-request-number-28990-from-nikki-at-akvo-dot-org)) many of the changes that were made are not reflected in the published survey version on the phone (checked version number, matched the dashboard and phone v6).

To re-trigger the survey download the app user has to delete everything off the devices, close the app, re-opened it and that triggers the syncing of the assigned survey and the changes come through.

**Comment by stellanl** [comment]
Are we sure the survey as published to S3 is correct?

**Comment by janagombitova** [comment]
No, I do not know. I think we need to investigate this properly and try to reproduce it first to understand what is going on.

**Comment by stellanl** [comment]
Yes. Of course, if doing massive fiddling with the device fixes it, the problem is most likely on that end. I'll take a quick look at the update logic just to be able to ask better questions.

**Comment by janagombitova** [comment]
Just to clarify, in the current user experience set up (where in order to get a republished survey on to the phone the user has to be connected to the internet, have an assignment created on the dashboard and has to fully close the app from running and then reopen the app) the two goals that we aim to achieve with this issue are: 
1. ensure that upon reopening the app the new versions of the form are downloaded 
1. ensure that all changes in the new versions are downloaded

**Comment by janagombitova** [comment]
This issue is related to the problem when the form version does not update and then thus the newly published version of the form has the same version number as the previous one. This issue is documented in flow-repo
