### ISSUE TITLE
Surveys with same form name fail with manual transfer

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#476]
**Issue needs further investigation**

A user wants to use manual survey transfer and selects two surveys she wants to install to the device. Both surveys are non-monitored ones but both have identical names of the forms "New form". The two zip files are generated properly and adding the files to the folder on the device is no problem either. Both surveys appear properly on the list of surveys on the app. The user opens one survey, the questions are rendered properly. She opens the other survey and the questions shown are from the 1st survey. 

After deleting all files from the app, changing the name of one of the forms and regenerating the zip file, we repeated the manual transfer and cross check both surveys on the app. This time both surveys opened with their questions as expected. 

For more details check: https://flowhelp.reamaze.com/admin/conversations/surveys-4
Support documentation: http://flowsupport.akvo.org/article/show/manual-survey-transfer

**Comment by valllllll2000** [comment]
Test plan:
Create 2 surveys with the same form name (leave the defaults names for instance) but with different set of questions and then upload them manually to device. Make sure both surveys display their corresponding questions.

**Comment by janagombitova** [comment]
I tested the case for non monitored surveys with the same form name as well a monitored surveys with 3 forms with all the same form name, and the issue passes the test and all works perfectly now. 👍
