### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow-mobile#478]
See akvo/akvo-flow#1798
- [x] Spanish
- [x] French
- [x] Portuguese
- [x] Vietnamese
- [x] Bahasa Indonesia
- [x] Hindi (Not 100% ready in Transifex)
- [x] Nepali (New, #477)
- [x] Khmer (New, #330)

**Comment by janagombitova** [comment]
## Test Plan
1. Select each language in the add and cross check that the Caddisfly questions are translated. 
1. Cross check that other parts of the app do not show in English but in the selected language
1. Switch the languages 

## Test results 

### Languages that render properly
Bahasa Indonesia; Spanish; French, Portuguese; Vietnamese 

### Hind
- there should be only 3 strings translated 
- Some stings are translated in Transifex but keep showing in English on the app: 
   -  Add signature 
   - Go to test
   - Stats 

### Nepali 
Nepali does not load at all but that is handled in another issue  #477
