### ISSUE TITLE
Non translatable strings should be moved to a separate strings file

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#480]
I have noticed that some strings do not need to a translation but the are not marked as translatable="false" and they are actually translated with the same string in all language versions. The best way would be to move them to a separate resource file so that they are not submitted for translation and they should also be marked with translatable="false". 
Benefits:
- Save translation times.
- If one of these strings are modified we do not need to modify it 100 times (in each language file) and avoid errors if we forget one of the files.

**Comment by valllllll2000** [comment]
Test plan:
There is not much to test here as strings were just moved.

**Comment by janagombitova** [comment]
Regarding testing: Ok. Then we can consider the issue ready for release as the code was reviewed.
