### ISSUE TITLE
Do not check for notifications before deviceId is set

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow-mobile#484]
This is the other half of #454, addressing akvo/akvo-flow#1731.
DataSyncService does the same thing as SurveyDownloadService, so should be delayed the same way.

**Comment by stellanl** [comment]
Test plan: same as for #454;
install the app on a device, Wait several minutes before pressing Next on the Add User screen. The device should not appear in the device list until after you do.

**Comment by janagombitova** [comment]
👍  issue passes test plan. I have one question though looking at the referenced issues: Is this change supposed to fix the missing version info in the Device list @stellanl ?

**Comment by stellanl** [comment]
The only connection is that I discovered this while researching #1819.

**Comment by janagombitova** [comment]
👍  all clear. Ready for release
