### ISSUE TITLE
Error notification icon is shown as empty white circle

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#486]
## The issue:
Turns out as the icon id is passed as null for the notification when there was an error downloading forms.

When this id is null, R.drawable.info is used, but it is only defined for drawable-hdpi.

After talking to @janagombitova it has been decided we should use the akvo icon. 

## What has been done:
Modify the way notifications are shown.
Added new akvo icon.
Informative/progress notifications shown in orange.
Error notifications are in red.
There is a difference between how they are shown in different android versions (see screenshots below).
Older devices will only show a white icon (no color available)

## Test plan:
Ideally test all case where the notifications are displayed, either success or error.
If possible test on older devices (< android 5) and also android 5/6 and 7.

**Comment by valllllll2000** [comment]
![screenshot_20161107-141030](https://cloud.githubusercontent.com/assets/923280/20059237/698e2b28-a4f5-11e6-9433-2f48a0fdd3e6.png)

**Comment by valllllll2000** [comment]
@janagombitova after looking at the other icons used (see for example the one on the screenshot for Downloading forms, we should use a white icon, the akvo app icon cannot be used here. The proposed icon to use is android.R.drawable.ic_dialog_alert, see my screenshot below of how it will look:

![screenshot_20161107-144112](https://cloud.githubusercontent.com/assets/923280/20059916/ebc8d23e-a4f8-11e6-831a-97a7b679db01.png)

**Comment by valllllll2000** [comment]
after talking to @loicsans it has been decided to use the same icon for all notification icons:

![imgpsh_fullsize](https://cloud.githubusercontent.com/assets/923280/20063653/4b899ef6-a508-11e6-91a6-4ce287ecd4d5.png)

**Comment by muloem** [comment]
@loicsans Shouldn't we distinguish between the kinds of notifications based on what the error actually is?  if it is simply informational notification, I agree that we can use the Akvo icon but I think error notifications could perhaps stand out more.

Also is it possible for the icon to be coloured or does that look weird at that small size?

@valllllll2000 @janagombitova

**Comment by valllllll2000** [comment]
@muloem the icon has to be black and white as it is used for the status bar. A colored icon just shows an empty white square.

**Comment by muloem** [comment]
ok.. and having an orange background?

**Comment by valllllll2000** [comment]
I can try @muloem, this usually works on lollipop and on Nougat the icon can be colored as well but no background, I will try now and upload some screenshots to see how it looks.

**Comment by valllllll2000** [comment]
![notifications_nougat](https://cloud.githubusercontent.com/assets/923280/20352524/d28700a4-ac17-11e6-98db-04532affbce5.png)
![notifications_lollipop](https://cloud.githubusercontent.com/assets/923280/20352523/d2862f3a-ac17-11e6-82e5-32e592afcb64.png)

**Comment by valllllll2000** [comment]
@loicsans @muloem I have an idea: maybe for error notifications, we could put the color red instead of orange to make a distinction, so only issue is old phones will not be able to see that.

**Comment by muloem** [comment]
I agree.  But I guess @loicsans view holds more weight here

**Comment by loicsans** [comment]
Making the distinction between the 2 types of notification is a good idea. Let's try red for errors.

**Comment by valllllll2000** [comment]
For devices with Android <3.0 we need to show different icons (grey color and diferent sizes) here is how it will look like:

![screenshot_2016-11-28_1135](https://cloud.githubusercontent.com/assets/923280/20665526/50671fda-b560-11e6-9f6c-80fdfc1a38e5.png)

**Comment by janagombitova** [comment]
@valllllll2000  can you specify the test plan a bit and clarify if the notifications are to be of a colour or not? if the icons differ? etc? Thank you

**Comment by valllllll2000** [comment]
Updated test plan:
The look of the notifications will be diferent according to Android version (there is no way around that).
* < 3.0:
Small grey akvo icon, no color, error and normal notifications are shown the same way.
Here is a picture:
![img_20161212_155436](https://cloud.githubusercontent.com/assets/923280/21104023/351f5c44-c085-11e6-9cc7-3c698cab683b.jpg)

* All others the notifications have colors (orange for ok and red for error). The look will change between 7.0 and the rest of them but the colors are still the same.

**Comment by janagombitova** [comment]
@valllllll2000 my Akdroid 4.4.2 is showing all notifications ins grey. Besides that comment the Akvo icon is shown ok as well as the notifications themselves.

**Comment by valllllll2000** [comment]
@janagombitova sorry I have no android 4.xx phone but yes it is correct, the color has been added in 5.0 not 3.0 as I initially specified, sorry about the mistake, I have corrected the test plan.

**Comment by janagombitova** [comment]
@valllllll2000 ohh ok. Then all is clear and works as expected. 👍
