### ISSUE TITLE
Allow debugging directly from Android studio

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#491]
I will be nice to have a way to debug the app directly from android-studio.

In order to do that I will create some instructions in the wiki and add a new file to .gitignore.

Instructions: https://github.com/akvo/akvo-flow-mobile/wiki/Running-and-debugging-the-app-with-Android-studio

**Comment by valllllll2000** [comment]
Test plan:
Make sure the app can be opened and that is connects to the right dashboard.

**Comment by janagombitova** [comment]
@osg74 could you test this issue? Thanks

**Comment by janagombitova** [comment]
App opens and works properly and is connected to the right dashboard from the user point of view. If this is all that needs to be checked, then the implementation passes the test plan. 👍
