### ISSUE TITLE
When device is rotated user is logged again and the toast is shown

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#498]
The toast "logged in as ---username" should not be shown each time the user rotates the screen but it still should be show every time the app is started.

See screenshot:
![screenshot_20161110-162227](https://cloud.githubusercontent.com/assets/923280/20183380/60f326e0-a765-11e6-9c5a-7dde8a61d619.png)

**Comment by valllllll2000** [comment]
Test plan:
Login user, make sure the toast "Logged in as xxx" is shown.
From the hamburger menu select another user than current one, make sure the toast "Logged in as xxx" is shown.
When rotating the screen the toast should not be shown.

**Comment by janagombitova** [comment]
@valllllll2000 I tested this issue and found the following: 
- when switching users the toast shows properly 
- when closing the app and reopening it again the toast does **not** show at all
- when rotating the app, the toast does not show as expected

**Comment by valllllll2000** [comment]
Jana, about this one:
- when closing the app and reopening it again the toast does **not** show at all. 
Should it show?

**Comment by janagombitova** [comment]
@valllllll2000 yes it should show. The need is, that you might have more users using one device but you need to keep track on who is inputting the data. So upon opening the app (after fully closing it) the toast shows. It should not show when rotating the app when having it open.  

So same as in your description of the issue.

**Comment by janagombitova** [comment]
👍  implementation passes test plan. Well done!
