### ISSUE TITLE
When device is rotated user is shown the download update dialog again

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#499]
Steps to reproduce:
Install an app for which there should be an update
Open app
you will see the dialog of the screenshot
Press no
Rotate device
You will see the dialog again 

This could be annoying of the user does not want or cannot update now so we have decided with @janagombitova that we will display the dialog only once every 24 hours if the user pressed "no".

Of course for the user to be able to update later we need to add a way to update from the settings screen (see issue https://github.com/akvo/akvo-flow-mobile/issues/500)

See screenshot:
![screenshot_20161110-162227](https://cloud.githubusercontent.com/assets/923280/20183380/60f326e0-a765-11e6-9c5a-7dde8a61d619.png)

**Comment by valllllll2000** [comment]
Test plan:
Open the app that has not yet been updated (we will probably need a special build for that), the dialog will be shown, press no, rotate the device, make sure the dialog is not shown a second time. Come back after 24h and open the app. The dialog should be shown.

**Comment by janagombitova** [comment]
@valllllll2000 is this not handled with the implementation in the other issues? or in the apk that I tested?

**Comment by valllllll2000** [comment]
@janagombitova this is not finished. I made some changes but there is a class present in newer google api which would be perfect for this case so I am waiting on some decision to be taken on that other task.

**Comment by valllllll2000** [comment]
This ha been developed as discussed previously with @janagombitova but after talking to @muloem he has suggested we should maybe not block the user at all but display a notification and that maybe a check once a week will be sufficient. In the meantime this is still an improvement over what is currently there.

**Comment by janagombitova** [comment]
I can confirm that nothing extra is shown to the user when the device is rotated. Will cross check this issue once more after I have the 2.2.9 build to be able to update the version. Leaving the issue in `ready for testing` for the time being

**Comment by janagombitova** [comment]
👍  all ready to go
