### ISSUE TITLE
Add possibility to update the app from the settings screen

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#500]
It would be nice for the user to update the app himself when he wants to.

With @janagombitova we have decided to add an entry to the settings screen to be able to manually update the app. For now it has been decided to add this update right above the "about" entry.

![screenshot_20161110-170007](https://cloud.githubusercontent.com/assets/923280/20183956/61613e12-a767-11e6-955b-36764bda772a.png)

## Test Plan:
Go to settings and find the entry to update the app. Press update. 

- If no update is available you should see "You already have the latest version". 

- If there is an error you should see: "There was an error when trying to update the app, please try again." 

Put device in flight mode or disable 3G/wifi. Try updating again. You should see the message:
"There was an error when trying to update the app, you are not connected to the internet".

For actually testing an updatable app, please follow instructions I sent by email. 
you should see the same "dialog" as for when there there was an update available previously.

**Comment by janagombitova** [comment]
@valllllll2000 can you please add the test plan here? Thanks

**Comment by valllllll2000** [comment]
@janagombitova test plan added in the issue description above

**Comment by janagombitova** [comment]
## Notes from testing.

@valllllll2000 can you please change the copy to: 
- "There was an error when trying to update the app, you are not connected to the internet" to `"There was an error when updating the app. You are not connected to the internet."` 
-  "There was an error when trying to update the app, please try again" to `"There was an error when updating the app. Please try again."` 
- "You already have the latest version of the app". to `"You are running the latest version of the app."`

Besides this, the app works perfectly, changes happen smoothly and all is clear. 👍

**Comment by janagombitova** [comment]
👍  perfect!
