### ISSUE TITLE
Reorganize the settings screen in a logical way

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#501]
For now the settings are not organised in sections that make sense.

For example preferences are all in one screen but other settings may still benefit from some kind of grouping.

We could for example create an admin section where you could perform all the "admin" tasks.

This should be discussed further.....

**Comment by janagombitova** [comment]
@valllllll2000 I agree we should think of a better way of grouping settings items. We have many settings, so we should prioritize the ones most likely to interest users. What were your thoughts on potential groups? 

We need to also look at the description and names of the items to make them more clear and unify the use of capital letters in the labels. 

## Current Settings items and structure 

- Preferences 
   - Keep Screen on During Survey Input 
   - Sync data over mobile network
   - App language
   - Survey language 
   - Send Location Beacons
   - Data server (only change if instructed)
   - Device identifier 
   - Resize large images 
- Sync Data 
- Reload all surveys 
- Download Form
- Power Management 
- GPS Status 
- Delete Collected Data and Images 
- Delete Everything (users, surveys, and all collected data) 
- Check SD Card State 
- Check for updates 
- About 

## Potential groups 
*(this list does not hold how the items should be labeled and explained)*
- Items that relate to actual data collection tasks: 
   - Sync Data 
   - Reload all surveys (admin task)
   - Download Form (admin task)
   - Delete Data and Images (admin task)
   - Delete Everything (admin task)
   - Survey language 
- Items that affect how data collection is done: (usually set once and not changed frequently)
   - Keep Screen on During Survey Input 
   - Sync data over mobile network 
   - App language
   - Resize large images 
- Other (not sure how to group these)
   - Data server (only change if instructed)
   - Device identifier 
   - Send Location Beacons  
   - Power Management 
   - GPS Status 
   - Check SD Card State 

## About 
I was following this guideline https://material.google.com/patterns/settings.html#settings-usage and they suggest moving information about the app out of Settings and into a Help screen or another, as Settings are made to allow the user to set how the app should behave and hold controls that are infrequently used. What do you think of creating another placement for About the app? Should this one also hold Check for updates?

**Comment by janagombitova** [comment]
Based on the discussion today with @valllllll2000 we will also find a place where to share the link to GH release notes for Flow mobile and remove the Location beacon from the list as we are fully removing this feature https://github.com/akvo/akvo-flow-mobile/issues/550

**Comment by valllllll2000** [comment]
So for now we will have in the lateral hamburger menu:
Settings as we have now
About -> this one will be added

About will contain:
- Current about dialog information
+ Below the the check update entry
+ (New) An entry which will take you yo release notes in Github (via a WebView)

For Settings it seems to me we have 3 main categories:
- Survey settings
  - Sync data
  - Survey language
- Device settings
  - Keep Screen on During Survey Input
  - Sync data over mobile network
  - App language
  - Resize large images
  - Power Management
  - GPS Status
  - Check SD Card State
- Admin tasks
  - Device identifier
  - Data server (only change if instructed)
  - Reload all surveys (admin task)
  - Download Form (admin task)
  - Delete Data and Images (admin task)
  - Delete Everything (admin task)

Not sure if this makes sense?

**Comment by Kiarii** [comment]
it would be nice to also consider the relevance of these individually, perhaps to automate if not remove some altogether..

**Comment by valllllll2000** [comment]
The following:
Reload all surveys (admin task)
Download Form (admin task)
will be removed see https://github.com/akvo/akvo-flow-mobile/issues/660

which leaves:
- Items that relate to actual data collection tasks: 
   - Sync Data 
   - Delete Data and Images (admin task)
   - Delete Everything (admin task) 
- Items that affect how data collection is done: (usually set once and not changed frequently)
   - Keep Screen on During Survey Input 
   - Sync data over mobile network 
   - App language
   - Resize large images 
- Other (not sure how to group these)
   - Data server (only change if instructed)
   - Device identifier  
   - Power Management 
   - GPS Status 
   - Check SD Card State

**Comment by janagombitova** [comment]
I have added some comments to the items you listed: 

   - Sync Data
      Current Location: Settings
      Action: launches DataSyncService to sync collected data + closes Settings
      - If this action only gets in submitted data and users do that per survey, do we need this one? --> will ask a group of partner team members working closely with Flow and our users. 
   - Data server (only change if instructed)
     Location: Settings -> Preferences
     Backend url, not sure if this is useful since the key still comes from the app so changing this would just break the app.
      - I agree that switching the instance using this option is not recommendable, but before we remove the option to switch, I am going to cross check with partner team. 
      - This feature is used to cross check if a user has the app linked to the correct instance. So we should keep it but more as a information - showing the instance URL + we should not show the current url, but the one users are familiar (custom domain we create) with if possible. 
   - GPS Status 
      Location: Settings 
      Is this still used? What is the purpose of this?
      - We used to suggest to also install a GPS app. This was then user to calibrate the GPS.  But as you point out here https://github.com/akvo/akvo-flow/issues/1749 it is not working anymore on new devices. I think we should consider if we want to continue with supporting the app or not. Asking partner team on their opinion as well. 
   - Check SD Card State
      Location: Settings 
      For now this calculates device's available space and displays a dialog. Most devices now have a setting in device preferences which displays information about device internal storage (ACTION_INTERNAL_STORAGE_SETTINGS) so we could either redirect the user there or just display the value directly without the user have to press this setting. I would suggest move this inside about page in that case.
      - I like your suggestion on showing the value directly without having the user to press the button. This is something as the currently called Data server, that the user simply needs to check

If we eventually agree to make changes on these separate items, then let's create separate issues for them. 

On the riddle on how to organise this, I will put a 2nd comment here shortly - doing a small user/expert testing in the office

**Comment by janagombitova** [comment]
![screen shot 2017-07-07 at 15 44 13](https://user-images.githubusercontent.com/12456965/27960342-38c6f1d8-632b-11e7-8b4b-b05a26ef8cd1.png)

I did a little exercise here in the office and gave 4 partnership members the remaining Settings items in a random pile and asked them to organise them, based on their preference. 

On the green post-its are their explanations (sorry about my horrible handwriting). The grouping criteria were:
- image 1: this is what you change; actions you do; this is information; these are checks
- image 2: this is about settings on your phone; this is about data 
- image 3: these are practical settings; about syncing; at the bottom because they are "dangerous" to do
- image 4: organised from most important to least important; sync; delete; check things 

Items as App language; Keep screen on..., Resize images are in 3 out of 4 grouped together because they fall under "what you change" or "what is about settings on your phone" or "practical settings". I agree with this grouping and would add here also Sync over mobile network.... This fits with your suggestion as well. And then the two checks: SD card status and GPS (if we keep it) 

If we change the Data server item (based on the feedback that is on its way) to only an information item, we can bring it together with the Device identifier. Three out of the four put the Data server below because they do not use it, or tell it to the users. But all highlighted the importance to easily see the Device ID. This could then be the 2nd group (or 1st) as we ask the app users to cross check this sometimes when supporting them and the Device ID is something they must set. 

Then we are left with the "actions": syncing and deleting.

We have all together 11 items now to organise. We could follow the 9-10 rule of the material design where we should: Group related settings under one or two section dividers. For settings that can't be grouped: If important, list them at the top without a section divider. Otherwise, list them at the bottom with a section divider called "Other," in order of importance. 

Once we figure out the order of items we need to look at the texts and labels. 

@valllllll2000 what do you think?

**Comment by valllllll2000** [comment]
Here is another way we could organise them, based on the images:
* Settings:
    - Language
    - Keep screen on
    - Resize images
    - Sync data over mobile
* Configuration:
   - GPS status -> this is because here we use an external app to configure the gps
* Information: **maybe this group items should be moved to the About screen??**
   - Data server (will become the dashboard name for example uat1)
   - device identifier, **I have a doubt about this one, shall we allow to edit it? What is the purpose of editing the identifier? If we can edit it, it should be moved out of information and into Settings???**
   - sd card state will be displayed directly
* Data
   - sync data -> **maybe this could be moved to be a menu option where the survey datapoints list is displayed? In that case the sync would happen only for the selected survey??**
  - delete collected data and images
  - delete everything

**Comment by janagombitova** [comment]
I like this, let's talk more today

**Comment by janagombitova** [comment]
After our meeting with @valllllll2000 we agreed on this order
* Settings: 
    - label: Keep screen on during form input, 2nd text: none -> in support page add the risks of keeping the screen on, battery drainage
   - label: Enable usage of mobile data, 2nd text: none 
   - label: App language, 2nd text: [chosen language]
   - label: Image size, 2nd text: [chosen size]
* Configuration:
   - label: GPS fixes, 2nd text: none  -> opens the external app if installed 
   - label: Available storage, 2nd text: none -> https://github.com/akvo/akvo-flow-mobile/issues/803, opens the Settings of the phone 
* Information: 
   - label: Device identifier, 2nd text: [is the defined identifier] -> in the future we can reconsider the interaction around this one too 
   - label: Instance name, 2nd text: [instance url] -> the previous Data server, will become the dashboard name for example uat1.akvoflow.org
* Data
   - label: Send submitted data points to Flow instance, 2nd text: none -> previous Sync data, later we will consider moving to menu option where the survey data points list is displayed. In that case the sync would happen only for the selected survey
  - label: Delete collected data and images, 2nd text: same as now
  - label: Delete everything, 2nd text: same as now -> https://github.com/akvo/akvo-flow-mobile/issues/790

**Comment by janagombitova** [comment]
There are two items that we have not discussed Download forms and Reload all surveys as we have a new design and workflow in plan form these two items, but we have agreed with @valllllll2000 that for the mean time, we will reorganise the settings with these two items and then remove them from the list once the new design changes are in place. 

Download form and Reload all forms will go under the **Data** section. I suggest we rename it "Forms and data"

**Comment by valllllll2000** [comment]
Here are screenshots of how it looks now:
![screenshot_20170908-140255](https://user-images.githubusercontent.com/923280/30210949-1997c490-949f-11e7-9908-fa719de053ef.png)
![screenshot_20170908-140355](https://user-images.githubusercontent.com/923280/30210948-1996fd1c-949f-11e7-8499-7e9e4e90bd3f.png)

On the second picture you can see the toolbar is collapsed to allow more items to be visible but as soon as you scroll all the way back up the toolbar is revealed again.
What do you guys think @janagombitova @Kiarii

**Comment by janagombitova** [comment]
I like it! 👍  

Have two small comments: 
- Can we reorganise the groups? 
   - proposed order: Settings, Data, Configuration, Information 
   - I know users use the Settings and Data actions quite often, and I worry that by having Data at the end it will require unnecessary scrolling (sorry, realised this just now)
- I know we agreed to keep the download form and reload all surveys as they are for now, as we have the UI and UX changes coming up. But, can we change the text a bit for Download form for the time being till the new changes are in place? 
   - title: Download form using form ID  
   - text: Only run if instructed

**Comment by janagombitova** [comment]
So I found two issues for far related to Settings: 

**1) Languages change does not work** 
Once I select another language and restart the app it actually does not change the language and I get everything in English. 

**2) Languages and image size seems disabled** 
The font colour is light grey in the pop ups and it seems as if you cannot select the given options, even though you can. 
![screenshot_2017-10-10-13-58-47](https://user-images.githubusercontent.com/12456965/31387949-9ca56478-adcc-11e7-90e4-6ec2f9f7aac4.png)

**Comment by valllllll2000** [comment]
@janagombitova 
here are the latest screenshots
![screenshot_20171010-175338](https://user-images.githubusercontent.com/923280/31396587-0f74d71a-ade4-11e7-88ae-7f625a9cea65.png)
![screenshot_20171010-175301](https://user-images.githubusercontent.com/923280/31396589-0f9e831c-ade4-11e7-8fac-d75632e9d8e9.png)
I have fixed the language too, just one detail: some translations are missing in most languages

**Comment by janagombitova** [comment]
👍  Works like a charm
