### ISSUE TITLE
Take user to play store when Barcode Scanner is not installed

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#512]
While working on the issue [#460] I have noticed that if the user does not have the app installed, we should show a dialog saying the app is not installed. 

![barcode2](https://cloud.githubusercontent.com/assets/923280/20436607/35cbadc8-adb1-11e6-8088-09d1b831a563.png)

In my opinion it would be better to ask user if he wants to download it and if yes take him to the play store page where he can directly press install for that app. 

![barcode](https://cloud.githubusercontent.com/assets/923280/20436620/3aabba22-adb1-11e6-9428-f297d529a25f.png)

**Comment by janagombitova** [comment]
@valllllll2000 it is good to keep in mind that we have users who use external barcode scanners that have their own apps and do not necessarily use this one from the Play Store. I think it would be better if the message was more general in this case. What do you think?

**Comment by valllllll2000** [comment]
@janagombitova you are right, then in that case it would be possible to use this url:
http://play.google.com/store/search?q=Barcode Scanner

more info about this [here](https://developer.android.com/distribute/tools/promote/linking.html#android-app) 

This url would take the user to play store and make a search of apps that correspond to Barcode Scanner.
When we show a dialog we can use the following text.
"No Scanner app is not installed on this device. Would you like to go to the play store now and install one?" Then we have cancel button and ok button. Cancel does nothing but ok takes to the play store and shows a list of apps that correspond to this request. 

GPS Status can either be the same or just use one particular app. Maybe I can separate these issues.

What do you think?

**Comment by janagombitova** [comment]
Definitely 2 separate issues (as we need to make a larger decision around the GPS status app we currently promote - see https://github.com/akvo/akvo-flow/issues/1749). You can use the linked issue actually for this as this might be a good solution for the questions raised there. 

Regarding the Scanner apps: I like the idea of giving the user the options to choose from or disregard the message. I also think like the link to Play Store so the user does not have to get there himself (as it is currently). One comment on the copy though. We should keep the format consistent and make sure it is short and clear. How about: 

- copy: "No Scanner app installed on this device. Do you want to install one now?"
- options: "Install" and "Cancel"  

@loicsans and @valllllll2000 What do you think?

**Comment by valllllll2000** [comment]
@janagombitova I have created a separate issue: https://github.com/akvo/akvo-flow-mobile/issues/517 for gps status. 

As for the scanner I think your copy sounds great.

**Comment by valllllll2000** [comment]
## Test plan
uninstall all barcode scanners from phone and try scanning barcode, make sure all works as expected

**Comment by janagombitova** [comment]
Nice, it even opens on a list of app scanners. I like it! Well done. 👍
