### ISSUE TITLE
Small ui style issue on experia device

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#515]
On my sony experia with android 2.3.7 I see this styling issue:
![little_ui_problem](https://cloud.githubusercontent.com/assets/923280/20440465/7f9e2ae8-adc0-11e6-9af7-60c90fe103fa.png)
Not sure if this is device specific, needs more investigation.

**Comment by janagombitova** [comment]
@valllllll2000 is this still an issue? I have not seen it before on the devices I am testing Flow with

**Comment by valllllll2000** [comment]
@janagombitova it does still happen on mine, not sure if there are more devices which have the issue
