### ISSUE TITLE
What to do when GPS Status is not installed

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#517]
When Gps Status app is not installed we show:

![gps_status](https://cloud.githubusercontent.com/assets/923280/20436648/51f9bdc8-adb1-11e6-9049-ea7ac220baec.png)

On the other hand it seems the Gps Status app no longer works for recent phones, see https://github.com/akvo/akvo-flow/issues/1749

**Comment by janagombitova** [comment]
I have cross checked with some more Akvonauts on their experience with the GPS app and here are their comments: 

- Yes this feature/application is highlighted well in the training and is used in the field a lot. This is a very helpful application for many trainees to understand how GPS works technically, and why it can be slow in the field sometimes. If a device is giving trouble getting a fix, we usually recommend clearing the agps state and downloading it again from this app.
- We recommend our partners to download and use the app 
- This is one of the most common things my partners do when in the field. 
- We recommend to partners to calibrate their GPS with GPS Status each time they arrive at a new data point and to capture their coordinates in open air and avoid any obstacles. If the precision doesn’t attend an error margin of max. 5 meters to move around a little bit

From what I understand that issue in flow repo is about the fact that we add the apk build for the GPS status app to each instance (xx.akvoflow.org/gps). The apk version we add is 4.4 and the latests version on Play Store is 7.6

We can follow the pattern as we have with the Barcode questions and bring the user to Play Store the the GPS status app.

@valllllll2000 What do you think?

**Comment by valllllll2000** [comment]
That is a good idea. I need to test and see if our app works with the newest version of the gps status and also if the new gps status is compatible with older devices.

**Comment by valllllll2000** [comment]
After talking to Jana we have decided:
1) Fix issue of new version of the GPS status app not working with our app. If you install the app from the play store and then try to call it from our settings, we do not get any errors but the app will not open.
2) If the fix is not possible we will need to look for an alternative
3) If the app is not installed, take the user to the play store with the search term "GPS Status"

Issue:
The play store app https://play.google.com/store/apps/details?id=com.eclipsim.gpsstatus2&hl=en is only available for devices 4.0 onwards. What shall we do for our older < 4.0 devices?

**Comment by valllllll2000** [comment]
Update: I can fix the app to work with both the new and old version of GPS status but the issue arises on what to do if the app is not installed, here is what I suggest:
Display dialog saying app is not installed, would you like to install it?
if yes:
- Android 4.0 and higher -> take user to playstore 
- < 4.0 take user to our install link dashboardurl/gps
what do you think @janagombitova?

**Comment by janagombitova** [comment]
@valllllll2000 I like the idea but I cannot imagine the solution for < 4.0 users in practice. 

Would the Flow app then open the browser on a specific url? If yes, then we need to bring the app user to a "universal" url or each app will show the link based on the instance url it is linked to? 

Or would we display a message on what the user needs to do?

**Comment by valllllll2000** [comment]
@janagombitova for the <4.0 devices we could either 
1) link the user to the download url which is:
dashboardurl/gps, he will then use his browser to download and then install
2) ask if they want to download the app and while downloading show a progress dialog and then proceed the same way as for our own app (update)

**Comment by janagombitova** [comment]
@valllllll2000 so if I understand correctly: 
- for Android 4.0 and higher we take the user to Play Store to install the app 
- for lower than 4.0 we trigger the download of the app "automagically" 

If yes, then I think this is a good solution to the problem, we just need to make sure we are clear that the user agrees to download the app now

**Comment by valllllll2000** [comment]
## Test plan
* On android < 4.0 device
Uninstall GPS Status
Go to Settings from hamburger menu and press 'GPS fixes'
You should see a dialog asking you if you want to install GPS status
Pressing cancel should do nothing but dismiss the dialog
Pressing install you should be taken to the browser where you download the gps.apk and the you have to install it.
Once installed try 'GPS fixes' again, it should open GPS Status app.

* On a device with android >= 4.0
Uninstall GPS Status
Go to Settings from hamburger menu and press 'GPS fixes'
You should see a dialog asking you if you want to install GPS status
Pressing cancel should do nothing but dismiss the dialog
Pressing install you should be taken to the play store and the you have to install the GPS Status app.
Once installed try 'GPS fixes' again, it should open GPS Status app.

**Comment by janagombitova** [comment]
👍  all works good and the workflow is clear.
