### ISSUE TITLE
Form name does not wrap

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-flow-mobile#521]
![screenshot_2016-11-22-08-13-16](https://cloud.githubusercontent.com/assets/4419787/20507223/e8bc5478-b08b-11e6-9786-766d280fd8b7.jpg)

**Comment by valllllll2000** [comment]
@joycarpediem Thank you for reporting this. Could you please tell me on which device and android version you found this?

**Comment by joycarpediem** [comment]
@valllllll2000 Android 5.1.1 Language English(UK)

**Comment by janagombitova** [comment]
Wraps well, in both menu and also list of forms. 👍 passes test plan perfectly  

![screen shot 2017-01-02 at 15 39 23](https://cloud.githubusercontent.com/assets/12456965/21591143/afd09598-d101-11e6-9a9c-2321cb8f9a0a.png)
