### ISSUE TITLE
Syncing imported data points

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#526]
For monitored surveys the app user can sync data points collected by other users. This functionality works fine. However, data points can also be created via the Data cleaning functionality. The app user can also sync these, the same way he would sync points collected via the app. He should not see the difference on the device. 

## Example case:
- uat1.akvoflow.org > 1.9.12 UAT folder > 1.9.12 UAT test > 1.9.11 MF Survey copy > registration form 
   - 6 data points uploaded via data cleaning 
- uat1.akvoflow.org > 1.9.12 UAT folder > 1.9.12 UAT test > 1.9.11 All questions survey copy > All questions form 
   - 3 data points uploaded via data cleaning 

All points work fine on the dashboard and Flow services 

## Steps take on the app
1. After uploading the data points I selected the survey on the app
2. Clicked on Sync
3. Data points synced is successfully based on notification message
4. Data points appear in the list of points but have the icon "saved" 

![screenshot_2016-11-23-17-11-31](https://cloud.githubusercontent.com/assets/12456965/20569694/428ab0ce-b1a1-11e6-9d77-9638082467b9.png)

5. If I click on one of the points, it seems as no forms are submitted 

![screen shot 2016-11-23 at 17 22 21](https://cloud.githubusercontent.com/assets/12456965/20569747/7976e9b8-b1a1-11e6-8cf1-0e9bf25cca57.png)

6. After a few seconds the points disappear from my list on the phone

**Comment by janagombitova** [comment]
After a few more attempts with @valllllll2000 we learned that the issue happens, if the user syncs right after the upload is finalised. In that case the issue occurs. If he waits a minute longer, the sync is completed without problems

**Comment by valllllll2000** [comment]
To provide more info here is what we get from the api in this case:
`{"surveyedLocaleData":[{"id":"e57u-g3hq-m79d","displayName":"","identifier":null,"lat":null,"lon":null,"surveyInstances":[],"surveyGroupId":98729115,"lastUpdateDateTime":1479985176732,"keyId":null}],"message":null,"offset":0,"code":"200","resultCount":1}`
As you can see there are no actual answers to that survey but there should be.

**Comment by valllllll2000** [comment]
With @janagombitova we have decided that in the app what can be done is to not display a datapoint which does not have any answers and display an error message for the user to attempt sincing again.

**Comment by valllllll2000** [comment]
This is the message that would be displayed:
Some items were not synced correctly. Please sync again.

Is that correct @janagombitova?

**Comment by janagombitova** [comment]
@valllllll2000 Sounds good. Will this appear as a notification?

**Comment by valllllll2000** [comment]
I was thinking about a toast message since at this point we already show the syncing notification and it may be confusing, what do you think?

**Comment by janagombitova** [comment]
The toast sounds like a good option, but the worry I have if that we are informing the user about syncing in two places. So the steps would be: 
1. Users clicks on Sync
1. Data syncs and the 'empty' ones do not show in the list. What does the notification show? 
1. We show a toast with this message

**Comment by valllllll2000** [comment]
You are right, we should show the notification error then. Plus the users are used to seeing it there.

**Comment by valllllll2000** [comment]
## Test Plan:

1. Create a survey or use an existing one and assign it to your device.
2. Using the data cleaning tool insert some data and make sure the data is imported correctly
3. Immediately sync on device
4. You should see an error notification
5. The new datapoints will not show and you will have to sync again to get them.

**Comment by janagombitova** [comment]
👍  implementation passes test plan. All work smoothly. The error is show and no points are synced as expected. After successfully syncing in the points the data is shown properly.

**Comment by janagombitova** [comment]
@valllllll2000 one comment on this issue and perhaps we need to create a new issue in the repo - the error notification does not fully show

![screenshot_2016-12-12-10-53-38](https://cloud.githubusercontent.com/assets/12456965/21098263/b1796c16-c068-11e6-9a0a-81948b5d32bc.png)

**Comment by valllllll2000** [comment]
@janagombitova yes this is a separate issue, since we have to consider what to do with the long text as we did for the issue #519

**Comment by janagombitova** [comment]
@valllllll2000 great! then we can consider this implementation complete and deal with the notification in the new issue 👍
