### ISSUE TITLE
Change using the word "dashboard"

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#527]
In the beginning of 2017 we will move away from using the word "dashboard" in the context of Flow. The main reason is that the meaning of the word "dashboard" does not fit properly with what is done on the web app. Secondly, with Akvo Lumen taking shape the end product of Lumen will be dashboards with data visualisations. To avoid confusion in documentation, sales, and users we will select a different word in Flow context. 

The aim of this issue is to find all places on the Flow web interface where the word "dashboard" is user visible, and then change it to the new word. 

## New word to use: 
(to be determined - Jana and Comms team started the effort)

## Locations that need to be changed (plus items to cross check in testing)
* [ ] Assignment in Akvo FLOW dashboard required
* [ ] You have no surveys assigned. Surveys are assigned in the FLOW dashboard
* [ ] Form assignments could not be read from the FLOW dashboard.
* [ ] Form %1$s could not be read from FLOW dashboard.

**Comment by valllllll2000** [comment]
For the app, I have checked in the code and the only usages of the word dashboard are where you say plus in the hindi translations, in some comments of our code (invisible to the user) and also of course in the release notes.
