### ISSUE TITLE
Add initial Travis CI config for automated builds

### ISSUE THREAD

**Issue by osg74** [akvo/akvo-flow-mobile#541]

**Comment by osg74** [comment]
Test plan:

1. The https://travis-ci.org/akvo/akvo-flow-mobile CI page should have a basic build.
1. Build should pass basic compilation of the mobile app code.

**Comment by osg74** [comment]
Some useful notes for advanced build issues: https://github.com/codepath/android_guides/wiki/Setting-up-Travis-CI

**Comment by valllllll2000** [comment]
## Test plan

Nothing to test manually, see travis for build status

**Comment by janagombitova** [comment]
@osg74 can you please assess if this issue and work here is completed? If so, can you please comment and close the issue? If not, can you please share what is still pending. Thanks

**Comment by valllllll2000** [comment]
work has been completed
