### ISSUE TITLE
"About Akvo" is outdated

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#545]
As you can see on the screenshot, the About us text is outdated:

![screenshot_2016-12-01_1044](https://cloud.githubusercontent.com/assets/923280/20834093/8b45127a-b893-11e6-818c-876e2507b157.png)

The text should be 2010-current year. 

## Test plan:

Go to settings and press the about entry. You should now see 2010-2017.

**Comment by valllllll2000** [comment]
A decision has to be made on how we will present the data to the user:
Currently we have been just displaying a 2010-year. Year had to be updated by hand. The change that has been merged gets the year from the system dynamically so if we are in 2016 it will show 2010-2016 or 2017 if we are in 2017.
It has been suggested to use a configuration file and in that case we can have the build script update the year and the app would read it from there at runtime.

**Comment by valllllll2000** [comment]
We have decided for now the date will be set statically to 2017.

We will create a new task to add the year in a config file and use the build script to update that each time.

**Comment by valllllll2000** [comment]
I realised there was a mistake and the app was crashing, will create a new pull request with the fix

**Comment by janagombitova** [comment]
About works well and the app does not crash at all. Version number is updates and well as the copyright/left date 👍
