### ISSUE TITLE
Remove location beacon sending

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#550]
After discussing with @janagombitova  the increased costs of google app engine it has been decided to study the possibility to remove the location beacon sending feature.

Right now, the location beacons are only sent every 30 minutes if the user enables the feature in the settings. The questions is: is the data useful to someone and is it being used. Can we safely remove this?

We should check the "expensive" instances and see if some location data being sent recently may be the culprit.

**Comment by janagombitova** [comment]
Here are some old issues that touch upon the topic of location beacon and tracking the location of apps: https://github.com/akvo/akvo-flow-mobile/issues/384 and https://github.com/akvo/akvo-flow-mobile/issues/19

The purpose of the location beacon was originally to track the location of all phones at all times. 

Considering: 
- we do not have any active users asking for this information anymore 
- the information of location of apps is stored but not used or shown anywhere anymore
- many users are not even aware of this 
- we have deactivated the setting a year ago as a 1st step to remove this feature (a year ago we were reluctant to fully remove it) 
- we should take users' privacy into account as many have the Flow app installed on their private devices 

I think we should remove this feature fully from the app. @valllllll2000 @stellanl @muloem and @LarsSjogreen What do you think?

**Comment by valllllll2000** [comment]
I agree to remove it if nobody is using it. If we need location for a survey it can be added as a question by users.

**Comment by valllllll2000** [comment]
It has been decided to remove the location beacon sending.
Remove the LocationBeaconService and all its dependencies.
Remove the setting in the app to allow activating the location beacon sending.

**Comment by valllllll2000** [comment]
## Test plan:
Just go to Settings -> Preferences, the beacon setting should be gone.

**Comment by janagombitova** [comment]
Beacon gone! Well done everyone, this is a big step towards simplification and confirming it is good to remove elements we make no use of anymore 👍
