### ISSUE TITLE
Improve crash reporting

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#551]
Currently all the crashes in the app are all sent to google app engine. They are sent every 5 minutes and if the sending fails, we retry again and again. The problem is there was a bug in the backend https://github.com/akvo/akvo-flow/pull/1835 where on those phones it constantly failed and retry is every 5 minutes. 

The alternatives:
- Make crash reporting less frequent say every 24 hours
- Replace sending to GAE by using crash reporting tool: Crashlytics or Sentry

**Comment by valllllll2000** [comment]
@iperdomo recommends [Sentry](https://sentry.io/welcome/) 

Here is a commit where Iñigo added sentry:
https://github.com/akvo/akvo-flow-mobile/commit/bf1380521687a89dafcca541b3ca65d16d6c5cfe

I will create a sample app and try them both and post screenshots here.

**Comment by valllllll2000** [comment]
After experimenting with a sample app I have created the following document to see how the tools compare: https://docs.google.com/spreadsheets/d/1pfO6nTm0ilMKxl68H8uW1jC6pS15lu0lqlqvKrNycJA/edit?usp=sharing

**Comment by janagombitova** [comment]
I personally think that if there are better tools out there for reporting, that can give us more information and we can take quicker action to improve the app, we should choose one of the two and move reporting away from GAE. There is nothing holding us back. 

Which of the tool is more of a technical decision. I would be interested in knowing opinions of others and also why did we start with Sentry in the first place.

**Comment by osg74** [comment]
@janagombitova: We decided on Sentry mainly because it's open source and has good quality reporting already.

**Comment by stellanl** [comment]
I have no objections to Sentry.

**Comment by valllllll2000** [comment]
Sentry wins  :rocket:

**Comment by valllllll2000** [comment]
When it was supposed to be easy: I have run out into this issue:
https://forum.sentry.io/t/android-raven-and-self-hosted-sentry/672

Akvo's version of Sentry is outdated 6.4.4 versus 8.11.0 so all the libraries for Android do not work. It is possible to use an old library but we may consider updating.

**Comment by osg74** [comment]
Let's speak to @orifito about an upgrade when he's back.

**Comment by valllllll2000** [comment]
@osg74 @orifito knows but this involves other teams updating their clients so we have to make sure they know and agree.

**Comment by valllllll2000** [comment]
## Test plan

Using uat1 build, one way to trigger exceptions is maybe reconfigure your device time or try downloading survey that does not exist or you can also rename the backend server to something that does not exists.
Go to http://sentry.support.akvo-ops.org/flowapp/uat/
You will need a user.
You should start seing some crashes / log reports. 
At the right of the dashboard you can see there are some tags such as appId, Os, device. You can use them to filter out your device.

**Comment by janagombitova** [comment]
@valllllll2000 I followed all your steps, but can you please cross check if all on Sentry's side is working properly? I do not feel comfortable evaluating that yet. Thanks

**Comment by valllllll2000** [comment]
@janagombitova I have checked and your issues were received on sentry.
