### ISSUE TITLE
Move Version code and name to properties file

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#555]
Version code and name are now in the manifest but should be in a version properties file.
Version name and code should be read by build.gradle

Also target SDK and minimum SDK are both in the manifest and then they are overriden in build.gradle, they should be removed from the manifest.

## Test plan:
Nothing to test here, really, if you managed to get the app and it has the expected version, then everything worked as expected.

**Comment by janagombitova** [comment]
@valllllll2000 download worked perfectly fine via the link. One thing that I noticed, if I wanted to update the app via the new Settings option you added, it told me I have the latest version even though I was running one the _aplha apk. Is that ok? I had to uninstall the app and install from the browser

**Comment by valllllll2000** [comment]
@janagombitova yes unfortunately the _alpha breaks the logic of the update code as only numbers are recognised. Also version code is ignored so there is no way at the moment to differentiate between 2 different 2.2.10 versions. We would have to modify the backend code to include the version code as well when comparing apk versions.

**Comment by janagombitova** [comment]
@valllllll2000 I see, then if the updating works on the live apks for the users it is fine. I just wanted to make sure all is as it is expected to be. No need to make changes. We can consider this issue ready for release then
