### ISSUE TITLE
Error notification too long for unsuccessful syncing of data points

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#560]
The error notification does not fully show when syncing data points is unsuccessful and the user needs to retry. https://github.com/akvo/akvo-flow-mobile/issues/526 

We should also consider unifying the wording of notifications related to synching of points. We wanted to do an overall improvement here: https://github.com/akvo/akvo-product-design/issues/218

![screenshot_2016-12-12-10-53-38](https://cloud.githubusercontent.com/assets/12456965/21098263/b1796c16-c068-11e6-9a0a-81948b5d32bc.png)

**Comment by valllllll2000** [comment]
Here is what we currently have:
title
Syncing Data Points...
subtitle
Some items were not synced correctly. Please sync again.
Shall we replace it by:
title:
**Data Points Sync failed**
subtitle
 **Please sync again.** or **Please try syncing again.**

@janagombitova what do you think?

**Comment by janagombitova** [comment]
@valllllll2000 I think we can go with: 

Data Points Sync failed 
Please sync again

**Comment by valllllll2000** [comment]
## Test Plan:

1. Create a survey or use an existing one and assign it to your device.
2. Using the data cleaning tool insert some data and make sure the data is imported correctly
3. Immediately sync on device
4. You should see the new error notification message

**Comment by janagombitova** [comment]
👍  works like a charm
