### ISSUE TITLE
Use newer SDK and build tools

### ISSUE THREAD

**Issue by osg74** [akvo/akvo-flow-mobile#562]
We're currently building with SDK 21 and build tools 21.1.2, which is falling behind the latest version 25 SDK and build tools.

**Comment by osg74** [comment]
The latest Gradle 2.2.3 build tools need JDK 8 to build, which should be fine since we have target and source set to 1.7 already.

**Comment by osg74** [comment]
Related to #541

**Comment by osg74** [comment]
Support library revisions: https://developer.android.com/topic/libraries/support-library/revisions.html

**Comment by valllllll2000** [comment]
I think we can consider this as done. In the released version this is the setup:
compileSdkVersion 25
buildToolsVersion "25.0.1"
minSdkVersion 10 
targetSdkVersion 21

support library version: 25.0.1

gradle:2.2.3
what do you think @osg74 ?

**Comment by osg74** [comment]
Those versions look fine, thanks @valllllll2000.

**Comment by valllllll2000** [comment]
Closing as these changes have already been released
