### ISSUE TITLE
Upgrade target SDK

### ISSUE THREAD

**Issue by osg74** [akvo/akvo-flow-mobile#563]
We currently target SDK 21, which is fairly out of date now.  We could aim for 23 or a more recent version like 25.

**Comment by osg74** [comment]
To upgrade to 23 or higher, we'll need to change the permission handling as per https://developer.android.com/training/permissions/requesting.html

**Comment by valllllll2000** [comment]
Also, updating will probably imply also updating support library:
https://developer.android.com/topic/libraries/support-library/revisions.html

Some style adjustment may be necessary.

**Comment by valllllll2000** [comment]
This has been already addressed in https://github.com/akvo/akvo-flow-mobile/pull/569
