### ISSUE TITLE
Code cleanup: remove old and/or unused code

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#571]
This issue is to track what can be removed because it is no longer used.
Unused classes should be removed.

- [x] Find and remove unused drawables, layout resources, strings, colors
 ----> use lint
- [x] Remove app/build.properties.template which was used for ant builds
- [x] Remove util/scripts/release_notes.py as it has been moved to https://github.com/akvo/akvo-android-common
- [x] Remove occurances of "stacktrace" folder

**Comment by janagombitova** [comment]
@valllllll2000 is there something specific to test here? Or just make sure all works?

**Comment by valllllll2000** [comment]
@janagombitova regression testing should catch bugs if any, nothing to test specifically

**Comment by janagombitova** [comment]
The app passed all regression tests - we are ready to roll!
