### ISSUE TITLE
Languages: When switching surveys the previous survey languages are displayed

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#575]
Steps to reproduce:
Have 2 surveys with each at least a form in diferent languages assigned to your device, for example survey 1 is in English and French and survey 2 has only English.
Select survey 1 -> select form -> in the FormActivity you have menu option for "languages".
You will then see in our case:
English
French

Now select survey 2 -> select a form -> menu option languages
You will see again
English
French
Yet survey 2 has only English available. Language preferences are handled wrong in a way that the languages for all the surveys are saved in preferences. We should use language preferences per survey.

**Comment by valllllll2000** [comment]
This issue happens because all the available survey languages are available to select without taking into account which survey is selected. After talking with @janagombitova we have decided:
- Remove the settings -> preferences -> survey languages entry which does not make sense since we do not know which survey we are talking about. 
- For each survey, inside FormActivity, display which languages are available for this survey only.

A table for languages must be created and should have the following columns;
survey id / language 
this means a given language has been selected for a given survey
If user unselects a language we delete that entry from the table

**Comment by valllllll2000** [comment]
the test plan is similar to https://github.com/akvo/akvo-flow-mobile/issues/576
also survey language setting has been removed from preferences

**Comment by janagombitova** [comment]
👍
