### ISSUE TITLE
Languages: Find a better way to handle languages

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#576]
For now the survey languages are handled in a very confusing way.
When downloaded from the backend languages are represented as language codes ej: 'es' or 'en'....

One survey can be available in one or more language and there is always a default one.

In the app we have 2 string arrays which represent languages. Here is how the look (actual arrays are much larger, here are just examples
```
    <string-array name="alllanguagecodes">
        <item>en</item>
        <item>ab</item>
        <item>aa</item>
        <item>af</item>
        <item>ak</item>
        <item>sq</item>
`    </string-array>`

  <string-array name="alllanguages">
        <item>English</item>
        <item>Abkhaz</item>
        <item>Afar</item>
        <item>Afrikaans</item>
        <item>Akan</item>
        <item>Albanian</item>
`    </string-array>
```

When we display the available languages to the user we use the array alllanguages. Its languages have to be in the same order than the one from alllanguagecodes. 

Then once user has selected a preference we take the index of the language (as int) and save it as list of strings in the database. For example for english and french you would get something like '0,40'. This implies the usage of multiple arrays and constantly having to map between indexes, first array items and second array items. 

Possible solution:
Create an object like SurveyLanguage which would contain 2 fields: language code and language.
```
SurveyLanguage {
String languageCode;
String language;
}
```
Available languages for each survey should be saved in the database, this will be handled by the task  https://github.com/akvo/akvo-flow-mobile/issues/575

**Comment by valllllll2000** [comment]
## Test plan
Create at least 2 surveys in different languages
Send them to the app
Open each one of the surveys, then go to the form filling
in the menu press "languages" option
In each of the surveys you should see only the languages available for that specific survey

**Comment by janagombitova** [comment]
👍 very nice improvement. Works as expected
