### ISSUE TITLE
How to notify user of available updates

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#578]
While working on the issue #499, @muloem has suggested we should reduce the frequency the user is displayed the update "dialog" from 24h to 7 days. Also we could instead of blocking the user by a dialog we could display a notification and from there offer the possibility to update.
Points to decide:
* How often shall we ask the user if he wants to update the app:
  - Every 24 hours
  - Every 7 days
* Which UI widget shall we display: 
  - Notification: can be displayed even if the user is not currently using the app, does not interrupt the user
  - Dialog as we already have now:  interrupts what the user is doing but is displayed only if the application is in the foreground (is being used)

**Comment by janagombitova** [comment]
Great thoughts guys! 

**Frequency:** I think asking every 7 days is an ok time frame. As far as I know users usually go out into the field for a day or a set of days. Thus reminding daily is less that what we have now, but maybe too frequent, if we think of a person collecting data for 3 days in a row. He will most likely not need to be reminded every day. So I would go for every 7 days. Do you count the days from the release of the latest version? 

**Regarding how to display:** We have agreed that we prefer our users to update their app version as frequently as possible I think we should keep the dialog as we have now. I am thinking of our less smartphone skilled users and am not sure how comfortable they are with notifications. I am worried by putting this important information there will "hide" it from them and we will loose the strength of the reminder.

**Comment by valllllll2000** [comment]
@janagombitova No I have no way to know the date of the release. I just ask the task to run every 24 hours. I could increase it to 7 days if needed, that does not take long.

**Comment by janagombitova** [comment]
@valllllll2000 ohh ok. I was just wondering how the timing works. If you agree with the 7 days and keeping the display as it is, then we have a solution.

**Comment by stellanl** [comment]
Alternatively, we could check every 24 hours, to get the info out to the users quickly, but wait 7 days before reminding them about it if they decline to update, so that they do not get annoyed...

**Comment by valllllll2000** [comment]
yes but why checking if you are not going to use it?

**Comment by stellanl** [comment]
To minimise the delay between a release and when users become aware of it. Not everyone will postpone the update.

**Comment by valllllll2000** [comment]
That is a good idea @stellanl, so each time an update arrives: display the dialog within the 24hours and then only remind every 7 days if they declined updating, what do you think @janagombitova ?

**Comment by janagombitova** [comment]
@valllllll2000 the only thing I can confirm now is that with rotating the device no toast is shown. That works. Can you build the 2.2.9 version for UAT1 for me to test? I want to make sure that the update the the new version will happen smoothly in the 24h and also do the cross check with the user manually updating via Settings. For the 7 days limit - I can test that once we release with one of the stock phones we have. If the manual update and 24h message works, I think we can postpone the testing of the 7 day interval to the live candidates. What do you think?

**Comment by valllllll2000** [comment]
@janagombitova I have sent you the apk by email.

**Comment by janagombitova** [comment]
@valllllll2000 so I have waited for 24 hours since installing the 2.2.9 apk and still did not receive a message to update the app. I have re-opened and force quite the app many times, collected data and kept it running but still no request. Am I doing something wrong?

**Comment by valllllll2000** [comment]
No, you are doing everything right so probably there is something wrong, I will take a look, which device did you test it on?

**Comment by janagombitova** [comment]
I tested on the newer Samsung phone - Android 4.4.2

**Comment by valllllll2000** [comment]
@janagombitova should be fixed now.

**Comment by janagombitova** [comment]
👍  app now updates as expected, we are good to go
