### ISSUE TITLE
Direct info to user about not filled in mandatory question

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#582]
### Background
Currently in the app we show the user there is a mandatory field using a black asterisks. If he attempts to submit a form where mandatory fields are missing, or a cascade is not fully selected (all the levels) we show a summary of all these missing fields. The user can click on them and is back in the group to fill them in. 

### Idea
The question is can we inform the user sooner that there is a mandatory field he missed out? Can we show him/her an input error directly and visibly if he/she skips a question and also still keep the summary at the end of the form?  

My thinking is to use the common design practice of a visual clue (red underline - https://material.io/guidelines/patterns/errors.html#errors-user-input-errors) when the user passes the question

**Comment by muloem** [comment]
The tricky thing about our situation is that the enumerator will encounter the same mandatory questions several times so it may become annoying to keep having reminders visible that these are mandatory questions.  I believe in some cases the enumerators deliberately skip these questions to come back and answer them later on. We could review whether we want to highlight the mandatory questions in a different way (i.e. other than asterisk)

**Comment by janagombitova** [comment]
All good points mentioned by Mulo above. Closing this issue as the way we handle mandatory questions currently is ok.
