### ISSUE TITLE
Data sync notifications phase 1

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#584]
The of notification is not correct in the mobile app and does not follow [google design guidelines](https://material.io/guidelines/patterns/notifications.html) at all and needs to be improved.
Here is the original issue where all the notifications have been discussed
https://github.com/akvo/akvo-product-design/issues/218

For data sync we have decided on the following specs:

- No notification will be used while syncing files or when syncing ended. In the datapoint list we can already see the status of the datapoint whether it is synced/saved ...etc

- For now, the other notifications related to the DataSyncService will stay the same.

- See https://docs.google.com/spreadsheets/d/1ONmVlA9TYHCDEkglfWqIbJse64DNmOyhrl7fFwdEReU/edit for more details and exact text specs.

**Comment by valllllll2000** [comment]
## Test plan
Create and fill a survey and press send, you should no longer see any notifications for either progress or success. If there is an error you should still see the error notification.

**Comment by janagombitova** [comment]
👍  no notifications in my screen, the data point status informs about the situation.
