### ISSUE TITLE
Change screen change animation to left-right movemement

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow-mobile#59]
Currently, the animation that is used when the user moves from screen to screen is either a zoom-in or a zoom-out, depending on the direction. However, the carets suggest a left-to-right navigation logic. 

Would it be possible to adapt the navigation animation to a left-to-right movement as well?

**Comment by janagombitova** [comment]
Do not think this is relevant anymore due to the age of the issue. Closing it for now.
