### ISSUE TITLE
Languages inconsistencies between app and Transifex

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#590]
I have found the following inconsistencies between the app and Transifex translations.

In the app:
es
fr
hi
**in** -> missing in Transifex
km
ne
pt
vi

In transifex
fr
es
pt
vi
ne
km
hi
**id** --> Missing in the app
**lo**  --> Missing in the app
**bn**  --> Missing in the app

Should in be added to Transifex? 
Should we add id, lo and bn to the app?
If these are not used shall we delete them?

**Comment by janagombitova** [comment]
@valllllll2000 as far as I can contribute the **id** is Bahasa Indonesia and that is a language selectable on the app from the users perspective. Could it be that it stands under the **in** in the app? 

**lo** (Lao) is not fully translated yet and not expected to be used anytime soon. **bn** (Bengali) is not even started with and I am not aware of the need for this language at this moment or any projects aiming to translate the app into Bengali. So Lao and Bengali do not need to be available on the app for the users so far.

**Comment by valllllll2000** [comment]
@janagombitova Oh that is right id is in in the app! So the languages not used in the app, shall we still leave them in Transifex?

**Comment by janagombitova** [comment]
@valllllll2000 I think they do no harm by being there, if there is not complexity that it adds to the implementation

**Comment by valllllll2000** [comment]
Ok, closing this issue then
