### ISSUE TITLE
Update repo license to GPL

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow-mobile#592]
We need to change the license of the mobile app code to GPL and include the correct license files and headers.

**Comment by valllllll2000** [comment]
@muloem Do you have a link as an example where I get them? Or is it just replacing the licence name?

Here is the current text:
`/*
 * Copyright (C) 2010-2017 Stichting Akvo (Akvo Foundation)
 *
 * This file is part of Akvo FLOW.
 *
 * Akvo FLOW is free software: you can redistribute it and modify it under the terms of
 * the GNU Affero General Public License (AGPL) as published by the Free Software Foundation, either version 3 of the License or any later version.
 *
 * Akvo FLOW is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License included below for more details.
 *
 * The full license text can also be seen at <http://www.gnu.org/licenses/agpl.html>.
 *
 */`

Shall I replace AGPL by GPL and that is it?

**Comment by muloem** [comment]
So for now, 

* [ ] we need to replace two things _FLOW_ with _Flow_, and AGPL with GPL
* [ ] remove the "Affero"
* [ ] replace the AGPL link with the link to GPL

**Comment by muloem** [comment]
>     This file is part of Akvo Flow.
> 
>     Akvo Flow is free software: you can redistribute it and/or modify
>     it under the terms of the GNU General Public License as published by
>     the Free Software Foundation, either version 3 of the License, or
>     (at your option) any later version.
> 
>     Akvo Flow is distributed in the hope that it will be useful,
>     but WITHOUT ANY WARRANTY; without even the implied warranty of
>     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
>     GNU General Public License for more details.
> 
>     You should have received a copy of the GNU General Public License
>     along with Akvo Flow.  If not, see <http://www.gnu.org/licenses/>.
>

**Comment by stellanl** [comment]
So:
* [ ] Drop in the GPL file in the source root.
* [ ] Change the copyright headers of all the Java files (and any other source)

**Comment by janagombitova** [comment]
@stellanl is there something I need to test here?

**Comment by valllllll2000** [comment]
@janagombitova this is not included in the release build

**Comment by stellanl** [comment]
Not really, none of it is visible in the product, just in the repo...
