### ISSUE TITLE
New About page 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#595]
After discussing the motivation to align all Akvo Android apps we decided to start with Flow and Caddisfly. As part of this initiative we will use the design of the Caddisfly's About page and change the current Flow one to meet this structure. 

![screenshot_20170112-102001](https://cloud.githubusercontent.com/assets/12456965/21974807/4a04f3e4-dbc9-11e6-81fd-4e3cd711dcd9.png)
**Current Flow About page** 

![0-weu-d3-eba314a1f44b456bf77a1e1989141500](https://cloud.githubusercontent.com/assets/12456965/21974809/4f2fb110-dbc9-11e6-9a21-6dab507c1d86.jpg)
**Current Caddisfly About page**

@valllllll2000 do you need any particular copy from me or documentation to proceed with this issue?

**Comment by valllllll2000** [comment]
@janagombitova I think I will start by creating an android library which will contain code common to all akvo apps and then all can use it. I can "steal" the screen from Caddisfly code. Just need some confirmation on these points:
* Line 2: instead of "WATER QUALITY SYSTEM" shall I put "DATA COLLECTION TOOL"
* Line 5: "Copyright ... " shall I put "Copyright © 2010-{current.year} Stichting Akvo or leave the year out similar to Caddisfly?
* Line 6: Legal information is clickable and leads to a dialog:
![notices_page](https://cloud.githubusercontent.com/assets/923280/21975926/a93179c2-dbcf-11e6-93e3-b915f54ecd11.png)
There is included the list of all the licences of all the libraries used in the app which we really should also include in Flow

**Comment by valllllll2000** [comment]
For the version, we display the version name but not the version code, shall we also display the version code? For example Version 2.2.10 (12).

**Comment by janagombitova** [comment]
@valllllll2000 to your questions: 

- version  >> I would go for only the version name without the code. The users do not know what the code means 
- Line 2: instead of "WATER QUALITY SYSTEM" shall I put "DATA COLLECTION TOOL" >>here I would use the tag line we have on akvo.org as well `Capture better quality data, faster`
- Line 5: "Copyright ... " shall I put "Copyright © 2010-{current.year} Stichting Akvo or leave the year out similar to Caddisfly? >> go for as we have it currently in Flow with the year
- Line 6: Legal information is clickable and leads to a dialog...There is included the list of all the licences of all the libraries used in the app which we really should also include in Flow >> I agree 
- In this issue #501 we decided that about us would also contain the check for updates entry and a link to release notes. I would place those 2 below the version and have: >> sounds good to me
   - clickable TextView "Check for updates" (similar look to the one "Legal Information")
   - clickable TextView with link to release notes on GH

@loicsans do you agree or have any suggestions?

**Comment by janagombitova** [comment]
@valllllll2000 I have one question - we should also add a link to the **Terms of use** to the app and perhaps this is a good place to do so

Here are our Terms of use http://akvo.org/help/akvo-policies-and-terms-2/akvo-flow-terms-of-use/

**Comment by valllllll2000** [comment]
@janagombitova yes this is a good place, I will add it also

**Comment by valllllll2000** [comment]
Here are screenshots of how it looks now:
About us screen:
![screenshot_1494862519](https://cloud.githubusercontent.com/assets/923280/26065734/22ba1678-3995-11e7-9969-4ca8cc3b07d5.png)
Legal notices
![screenshot_1494862512](https://cloud.githubusercontent.com/assets/923280/26065745/2b7102f4-3995-11e7-93cc-937c620bad08.png)

**Comment by valllllll2000** [comment]
## Test plan
Go to settings and select "about" entry. You should see screen with about information. Make sure all links (in blue) work as expected.

**Comment by janagombitova** [comment]
@valllllll2000 here is a screen shot from my dinosaur phone. The About page is not well aligned. On the newer phone model it looks good.  

![img_4670](https://user-images.githubusercontent.com/12456965/27271533-95ec714a-54c5-11e7-8481-3a4172036b56.JPG)

One thing I noticed, when you click on the links, there is no indication you tapped well. The link does not change colour or highlight. I know this is how links behave in other apps as well, but there is a but.. to me I was not sure if I clicked well enough and knowing our users I think they can be unsure as well. 

Second notice, the links are quite small. Could you enlarge the font a bit? What do you think

**Comment by valllllll2000** [comment]
@janagombitova I have updated the links and the font, and fix the alignment, the access itself will be handled in issue #771

**Comment by janagombitova** [comment]
👍 ready
