### ISSUE TITLE
Change colour in geoshape editor

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#597]
I believe this issue relates to the other changes in the apps UI we experienced with the last updates. In the test 2.2.10 apk the geoshape edit icons look grey and seem to be disabled even thought that is not the case. 

![screenshot_2017-01-16-14-45-28](https://cloud.githubusercontent.com/assets/12456965/21985386/aabce3fa-dbfa-11e6-8214-09f40838825b.png)

Before the change the icons in the bottom of the screen were better visible. Can you please change this? 

![screenshot_2017-01-16-15-40-04](https://cloud.githubusercontent.com/assets/12456965/21987037/2adb3a8a-dc02-11e6-80d3-64d3da6bda08.png)

**Comment by valllllll2000** [comment]
Test plan:
* Create a survey which requires geoshapes
* Open it on your device and go to "capture shape"
* Chose the menu option for shapes and chose between Line/Points or Area

**Comment by janagombitova** [comment]
👍  passes test plan, ready to go
