### ISSUE TITLE
Answers in repeated groups not shown in point History

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#600]
After syncing data points to a device, the points sync successfully. The user opens a data point and opens the points History to see the submitted forms. She opens a form that have a repeated questions group in it. The answers for this question group to not show in the submitted form. 

When saving a form with repeated groups, reopening and checking the History the answers are still shown. When submitting a new form and then checking the History of the data point and form, the answers to the questions in the repeated group show. But once syncing the data points to the device, the answers to the repeated groups do not show in the History. 

The expectation is that all answers are shown in the History of the data point, regardless of the fact they they are part of a normal question group or a repeated one.

**Comment by janagombitova** [comment]
Just crossed check the implementation on the current live version of the Flow app 2.2.9 and learned that this is an existing issue, not connected with the release candidate. 

In the attached spread sheet there is a data point with answers to a repeated group. After syncing this data point to my phone I get the answers from the other questions groups, but the repeated one is shown empty in the History view even thought there should be three repetitions with all questions answered.

<img width="938" alt="screen shot 2017-01-18 at 19 10 35" src="https://cloud.githubusercontent.com/assets/12456965/22076781/d44c2a2e-ddb1-11e6-9f67-cc35c7f829b4.png">

[Repeated group.xlsx](https://github.com/akvo/akvo-flow-mobile/files/714636/Repeated.group.xlsx)

**Comment by valllllll2000** [comment]
## Test plan 
Create repeatable question group
Add datapoint with at least 2 repetitions and submit
Check that both repetitions are displayed correctly.
Sync and check again if all repetitions are displayed correctly

**Comment by janagombitova** [comment]
After submitting a data point and checking it back again on the phone, the answers show correctly. The same works well for only saved data points. But as we discussed yesterday, data point syncing is not working on the 2.4.0 version so I cannot test the remaining part. Will do so once we get the syncing resolved.

**Comment by janagombitova** [comment]
Works as expected and the repetitions as well as answers show correctly. Ready to go
