### ISSUE TITLE
Security flaw: S3Api.java

### ISSUE THREAD

**Issue by MelEnt** [akvo/akvo-flow-mobile#603]
Currently, the class S3Api.java is holding the survey.property data, which contains the authentication required to access the sandbox site.
What S3Api then does is save these values to String variables, which is where the problem is.

See [this](https://github.com/akvo/akvo-flow-mobile/blob/develop/app/src/main/java/org/akvo/flow/api/S3Api.java#L62)

Mentions in:
http://docs.oracle.com/javase/6/docs/technotes/guides/security/crypto/CryptoSpec.html#PBEEx

http://javarevisited.blogspot.se/2012/03/why-character-array-is-better-than.html

Basically, String variables are immutable. This means they cannot be modified in any way, except when the garbage collector swoops it away. Until then, they stack in a String pool which persist in the memory and that's where a moderately skilled hacker can breach and access.

**Solution**
Use char[] instead

P.s. this issue could be argumented against, and may even be contradictory to fix if the original developer intended them to be String in the first place. 
More research would be required before tackling this.

EDIT: Most keyspec objects (which encrypts data as keys, passwords etc.) accept char[] or byte[] vars, not String.

**Comment by valllllll2000** [comment]
S3Api will be removed once all the code is refactored
