### ISSUE TITLE
Basic survey question test

### ISSUE THREAD

**Issue by MelEnt** [akvo/akvo-flow-mobile#613]
Using expresso, add tests to the following question types:

- [x]  Free text
- [x]  Date
- [x]  Number
- [x]  Option

**Comment by valllllll2000** [comment]
Update: 
FreeTextQuestionTest has already been added
We currently have the branch issue/613-automated-test-1
which contains DateFormTest, NumberSurveyTest, OptionSurveyTest
Tasks left to do:

- [ ] Make sure these tests pass and are deterministic
- [ ] Make sure they work on travis builds

**Comment by valllllll2000** [comment]
Update: most tests work, only left to fix the OptionQuestion test

**Comment by valllllll2000** [comment]
## Test plan
Nothing to test here manually
