### ISSUE TITLE
Offline survey export: files folder missing

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#614]
From remaze request # 41,280.
Filled surveys should be located in the folder akvoflow/data/files for offline transfer to PC.

With the version 2.2.10 this folder is missing.

There is no error displayed instead the notification shows "data exported to sd card...".
Users are unable to find the .zip file with the filled survey.
Reproduced on Samsung J7 with android 6.0 and Nexus 6 with android 7.1.1. 

Steps to reproduce:
Delete the akvoflow folder
Install the app
Make sure you have at least a survey assigned.
Put device in flight mode.
Fill the survey and press "send".
Connect device via usb to PC. You will see that the folder akvoflow/data/files is missing.

Update: It seems this issue is not about what we originally expected.
After connecting to the partners device, the folder akvoflow/data/files is actually mising. The transmission history is empty:
![screenshot from 2017-02-02 13-42-42](https://cloud.githubusercontent.com/assets/923280/22586514/7691f708-e9fd-11e6-813b-6ffb48930a13.png)
The surveys seem in an exported state:
![screenshot from 2017-02-02 13-41-24](https://cloud.githubusercontent.com/assets/923280/22586546/a90c2352-e9fd-11e6-8f4d-6636938980fe.png)
User is able to view the collected surveys on the device.
In total 11 devices have the issue of missing folder:
[phone issues.xlsx](https://github.com/akvo/akvo-flow-mobile/files/750038/phone.issues.xlsx)

**Comment by valllllll2000** [comment]
Update: there is no error logs and connecting to the device via usb the files are there:
angler:/sdcard/akvoflow/data $ ls
files media 
angler:/sdcard/akvoflow/data $ cd files/                                       
angler:/sdcard/akvoflow/data/files $ ls
02c3ff8a-b36f-4192-b239-5128f6217bb2.zip 
30a7149d-07cd-4431-a5dc-f3a608630fb0.zip 
58f99c58-ec5e-45a3-8386-90e012bba185.zip 
5eb9ed91-064d-48ba-836f-68bfcb58fbee.zip 
9db4743d-fba6-4745-83e6-9196e2feb226.zip 
d6eba5d7-e092-43fa-8304-faa2ce9fb1fc.zip 

They just do not seem to be visible when browsing the device filesystem but it does work if I try to actively pull the .zip file from device, for example:
adb pull /sdcard/akvoflow/data/files/02c3ff8a-b36f-4192-b239-5128f6217bb2.zip 
[100%] /sdcard/akvoflow/data/files/02c3ff8a-b36f-4192-b239-5128f6217bb2.zip

**Comment by valllllll2000** [comment]
```
 case SurveyInstanceStatus.SUBMITTED:
 case SurveyInstanceStatus.EXPORTED:
                    statusRes = R.drawable.record_exported_icn;
                    statusText = context.getString(R.string.status_exported);
                    break;
```
both submitted and exported files will be shown as "exported" !!!!!!

**Comment by valllllll2000** [comment]
The zip files seem to not be generated due to an error shown in this stacktrace:
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.akvo.flow.domain.Survey.getName()' on a null object reference
	at org.akvo.flow.service.DataSyncService.formZip(DataSyncService.java:229)
	at org.akvo.flow.service.DataSyncService.exportSurveys(DataSyncService.java:157)
	at org.akvo.flow.service.DataSyncService.onHandleIntent(DataSyncService.java:132)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:158)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by valllllll2000** [comment]
This issue uncovered another issue: bootstrap file has a diferent folder structure than expected and due to that the survey name is used as surveyId and once the zip files are generated there is no way to find which survey they belong to.

**Comment by valllllll2000** [comment]
## Test plan
Create 2 simple surveys
Your device should be offline
For simplicity delete all surveys 
Delete `akvoflow/data/files` and `akvoflow/data/media` folders
1) Get bootstrap files sent to yourself
2) Open the zip and extract the first survey
 Make sure the file structure is of type `surveyId/survey.xml`
For this one we will use the zip file as is.
3) Open the zip file for the second survey
 Make sure the file structure is of type `surveyId/survey.xml`
created a folder named test_data
move test_data folder inside surveyId folder
move the survey.xml inside tests_data folder
zip the new folder which now has 2 levels surveyId/survey_data/survey.xml, this is the zip file you will be using for testing
4) Place the zip files on your device 
5) Start the app
6) With the surveys loaded, create at least one datapoint for each survey
7) Make sure datapoints data is correctly exported to sdcard, espcially the survey which had the extra survey_data folder created
8) Go online and make sure the datapoints are synced correctly with backend

**Comment by janagombitova** [comment]
Implementation works like a charm for me testing out the 2.2.10 apk on a newer Android phone. I could not test the 2.2.6 apk as it crashes and then you cannot even open up the app to update. The 2.2.10 apk I used was the one @valllllll2000 you shared that was modified to ignore the crashes.
