### ISSUE TITLE
Fine tuning of sentry settings

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#615]
Sentry has been added and can now be tested using the uat1 build.

There 2 fronts to consider:

1) sentry.io settings 
Privacy has to be taken into consideration: https://docs.sentry.io/learn/sensitive-data/
What information has to be scrubbed?
What can be sent in email notifications and which should not?
2) device settings:
Which information to send? Check if all the tags currently sent are necessary.
Need to be added: deviceId (if available)

**Comment by muloem** [comment]
Just to add a little more: as far as possible lets look into having the scrubbing done at the app side rather than server side.

**Comment by valllllll2000** [comment]
@muloem I have looked at both libraries and I have not found any way to remove sensitive data in either Sentry-Android or raven-android, although raven-android is in current development and they may add it in the future. As for now here is the information that we send:

_data:  example_
appId: akvoflow-uat1
Device: Moto G (4)
device: athene
device.family: motorola
level: error
os: Android 6.0.1
os.name: Android
OsVersion: 6.0.1
Platform: Android
release: 2.2.11
transaction: org.akvo.flow.util.HttpUtil.getStatusCode(HttpUtil.java:136)
VersionCode: 14
VersionName: 2.2.11

**Comment by valllllll2000** [comment]
## Test plan

The test plan is the same as for https://github.com/akvo/akvo-flow-mobile/issues/551

**Comment by janagombitova** [comment]
👍
