### ISSUE TITLE
Confusing dialog after survey submission

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#617]
The message is confusing because even if you are offline it still says the surveys will be sent but it is not true:
![screenshot_20170203-145608](https://cloud.githubusercontent.com/assets/923280/22594644/408d1aee-ea24-11e6-98f8-c0a148981e45.png)
This dialog does not make sense to me, we should either show nothing or a toast but not a blocking dialog.

**Comment by janagombitova** [comment]
I agree that the submission page needs improvement. @Kiarii and @loicsans let's put this down on the to do list. 

Besides revisiting the dialog (content and interaction the user has) I would also like us to revisit the text shown before the user hits submit as well.

**Comment by janagombitova** [comment]
@Kiarii and @valllllll2000 we can reuse this issue once we complete the work on this one https://github.com/akvo/akvo-flow-mobile/issues/977 and the walkthrough, to reconsider what we say here

**Comment by valllllll2000** [comment]
@janagombitova shall we just remove this dialog then?

**Comment by janagombitova** [comment]
@valllllll2000 I am very inclined to say: yes, just do it. :) But I feel we then need to reconsider the text above the Submit button. Do we explain that submitting means no more editing or is that clear?

**Comment by valllllll2000** [comment]
@janagombitova here is what the user sees:
![screenshot_20180301-111247](https://user-images.githubusercontent.com/923280/36839428-59297eec-1d42-11e8-8a17-7891ba57d7eb.png)

I would still need to update the submit button after pressed, disable it and maybe show some kind of "loading" while data is being sent.

**Comment by Kiarii** [comment]
Here is what i thought regarding the form submission screen:
- datapoint syncing is separate from form submission
- there shd be a natural flow of work i.e. on hitting Submit, the app shd move the user along the 'workflow'. 
- the edition or viewing shd refer to the responses
- a snackbar could suffice to give feedback on the submission - without requiring user dismissal or standing in the way of other tasks
- since there is 2 cases for this: single form & multi form surveys a bottom anchored snackbar may be preferred for consistency of where the feedback appears. In the case of a single form survey, the FAB shd be raised so its always in view [https://material.io/guidelines/components/snackbars-toasts.html#]
- 

And here is the mock:
![image](https://user-images.githubusercontent.com/12692444/37597813-1ebeee4a-2b89-11e8-89b6-564ff45d1576.png)

**Comment by valllllll2000** [comment]
Screenshots
![screenshot_20180418-204304](https://user-images.githubusercontent.com/923280/38951567-63ef464a-4349-11e8-95c0-dfd42fbf4a4d.png)
![screenshot_20180418-204254](https://user-images.githubusercontent.com/923280/38951568-6410e3cc-4349-11e8-9bbe-3e78dd5e3da9.png)
I did not take the snackbar as it is the same snackbar we already have everywhere

**Comment by janagombitova** [comment]
@valllllll2000 Once Alphonso hits Submit what happens? Does he just goes to the list of data points or to the list of forms (for monitoring surveys)? I am a fan of less is more and if we believe that Alphonso will have enough info on the submission of his form through the data point list and the icons status, then we can take this approach. 

Secondly I am looking at the text for the submission screen and find it very impersonal. What about: 'You can view but not edit submitted responses.'

What do you two think?

**Comment by valllllll2000** [comment]
@janagombitova fist will happen just as described in the mockup so the form screen is dismissed and you are taken back to where you came from, ie list of datapoints if there is just one form or list of forms for multiple forms.
second: I will update the description to yours then.

**Comment by janagombitova** [comment]
@valllllll2000 found a first round of issues: 

Even if all answers are provided the Submit button seems disabled, but I can actually click on it and submit

![screenshot_2018-04-24-09-14-05](https://user-images.githubusercontent.com/12456965/39171704-e46d3912-479f-11e8-802d-93ce6a3da8d3.png)

Validating the geolocation input does not prevent from submitting
![screen shot 2018-04-24 at 09 15 18 2](https://user-images.githubusercontent.com/12456965/39171751-010a29c2-47a0-11e8-99dd-9f97f76acaf0.png)

**Comment by valllllll2000** [comment]
@janagombitova I have tested the issue 2 on app version 2.4.5 and it happens too. Created an issue https://github.com/akvo/akvo-flow-mobile/issues/1101

**Comment by janagombitova** [comment]
@valllllll2000 I figured out the issue in more detail (also happening on the apk you sent me via email). Here are the steps: 

1. Fill in a form with mandatory questions, leave a mandatory question empty
2. Go to the Submit page, you cannot submit. 
3. Go to the missing answer, fill it in 
4. Go back to the Submit page. Now the Submit button should be visibly enabled (green), but it still appears disabled (grey) but you can actually click on it and submit. 

In our skype chat we agreed you will keep the changes to the copy and the snackbar but revert back the changes made to the button to be able to release

**Comment by janagombitova** [comment]
Tested the apk with the Reverted new button styling changes, and all works fine now. Submissions and validating before the submission is all ok. Once reviewed, this will be ready for release
