### ISSUE TITLE
Inconsistent datapoint states

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#618]
For now we have 5 states in the app:
- Saved
- Submitted
- Exported
- Synced
- Downloaded

They are represented with 3 icons/states
- Saved -> floppy orange image + "Saved"
- Submitted & Exported -> wifi orange image + "Exported"
- Synced and downloaded -> green image + "Synced"
If another state or not state is found, then there would not be any text, nor image (I have not encountered yet any cases of this)

![screenshot_20170206-125042](https://cloud.githubusercontent.com/assets/923280/22646315/043947b2-ec6c-11e6-8215-aba239494e4b.png)

I think we should improve these states and have more icons in order to cover all the cases and even have one for error, it would help us to track syncing issues and also not confusing users into thinking the data has been exported when it has not.

**Comment by janagombitova** [comment]
I agree there is place for improvement but would like to steer changes in the way that it does not create more information for the users to process, but makes it easier to understand what has happened with a submission. I agree we need a better way of showing if something has failed. 

Users currently "live for the green tick" (quote from user in Fiji). 

**There are three cases of how people work when capturing data as far as I know**
1) They either collect data, but not submit it yet as there is more information they need to gather, they need to relocate, wait for someone to bring in extra data. So then they have the form in an "in progress state" or as we have it currently called "saved"
2) Users submit the data but they do not have internet so then the submission is not in the dashboard yet, but they have finished the form fully. Here they need to know that they still need to connect their phone to a network to get the data fully in.
3) Data has fully and successfully reached the dashboard

They need to be able to see the difference between the statuses of a submission. 

Lets talk further about the options here also with @loicsans and @Kiarii

**Comment by valllllll2000** [comment]
@janagombitova Ok I uderstand but maybe just separate the "exported" state from "submitted". The reason for that is in the case of our bug with WFP we and the client thought the files were being exported where they actually were not. If they would have seen saved after the first survey they may have contacted us earlier before collected a lot of data and we would have had a better insight on where to look for the issue, we could use another orange icon with the state "submitted".

**Comment by janagombitova** [comment]
All fair points. Lets find time to discuss this with the rest as well, I always find talking about an idea/problem a great way to come up with a good solution ;)

**Comment by janagombitova** [comment]
@valllllll2000 and @Kiarii we can use this issue to later reconsider the states of data points in light of the changes here: https://github.com/akvo/akvo-flow-mobile/issues/977

**Comment by valllllll2000** [comment]
With @janagombitova we have decided the following:
1) There will be 3 states: Saved, Submitted and Synced
* Saved: some responses added, user did not press submit
* Submitted: user pressed submit and the data zip file has been generated (see 2 for more on this)
* Synced: datapoints have been sent to the server (or datapoints were synced in from backend)

2) Once the user presses submit, the zip file will be generated. If that part fails, he will be shown an error SnackBar and the datapoint will remain in "saved" state and we do not leave the form screen.
-> **Error message TBD**
While data zip is being generated we show a "loading" UI item.

**Comment by valllllll2000** [comment]
Here are the screenshots
![screenshot_20180419-142308](https://user-images.githubusercontent.com/923280/38991339-ab686a26-43dd-11e8-8b68-a9ad8522b211.png)
![screenshot_20180419-142107](https://user-images.githubusercontent.com/923280/38991340-ab8def08-43dd-11e8-95ac-a8d32673d031.png)

**Comment by muloem** [comment]
If I may barge into the discussion here for a bit.  I think we could separate between what we can call internal states that are relevant for us to know what kind of processing to do with a datapoint, vs the external states which are visible to a user.  My hunch is that user's don't really care about differentiating between whether there is an export file correctly generated or not.  They would want to enter data into a form, save it and have it sent correctly to the backend.  Therefore if its possible to simplify this even more I would cut out the submitted state from the frontend part, or rename it to something more user centric like "completed" meaning that data collection has been completed for that particular datapoint.

**Comment by valllllll2000** [comment]
@muloem the issue here is there are 2 possible "completed" states:
* Synced -> means datapoints were sent to the dashboard
* Submitted -> datapoints are submitted but they still need to be exported by the user manually using his PC
For the submitted ones we need to make sure the user knows he still has work to be done which is not the same as synced.

**Comment by valllllll2000** [comment]
@janagombitova really? I just checked and for me it did... I tested on android 8.1, which device did you use?
