### ISSUE TITLE
Imported data shows "null" for submitter 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#620]
If a user imports new data points via data cleaning, we give the submissions a standard submitter (user name) - IMPORTER. If anyone syncs these data points to the app, in the history of the submission the submitter is shown as `null` this can be confusing. We should maintain consistency and also use `IMPORTER` here. 

![screenshot_2017-02-09-12-19-42](https://cloud.githubusercontent.com/assets/12456965/22781326/4b838f9e-eec2-11e6-908e-72b062927dbd.png)

**Comment by valllllll2000** [comment]
@janagombitova should IMPORTER be translated to other languages or should it be always the same?

**Comment by janagombitova** [comment]
It can always stay the same

**Comment by valllllll2000** [comment]
## Test plan

Create some datapoints with data cleaning tool
Sync datapoints
Open one of the imported ones.
In the history tab you should see IMPORTER as user name.

**Comment by janagombitova** [comment]
looking good 👍
