### ISSUE TITLE
New screen for empty surveys

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#621]
Today we have decided to improve the screen users see if he opened a survey, that has no data points yet. See the changes in the comment below

**Comment by valllllll2000** [comment]
The icons can be obtained here https://github.com/google/material-design-icons/ or here https://material.io/guidelines/resources/sticker-sheets-icons.html#sticker-sheets-icons-system-icons

**Comment by janagombitova** [comment]
We have agreed to create two new empty screens: one for non-monitoring surveys and one for monitoring surveys. The empty screens will hold an icon, title "You have no data points" and a sub title (different for each screen depending if it is a non-monitored survey or a monitored survey as for monitored surveys you can also sync in data) to tell the user how he can create a new point or sync existing ones. The empty screens will always be the same, even if the user has already collected a point and then removed it. @Kiarii will share mock ups on how the screens will look like.

**Comment by Kiarii** [comment]
empty states for non monitored and monitored surveys
![image](https://cloud.githubusercontent.com/assets/12692444/22882098/38d79934-f1f2-11e6-8289-d8550adb49cc.png)

**Comment by Kiarii** [comment]
Monitored survey Sync progress and error states:
![image](https://cloud.githubusercontent.com/assets/12692444/22882604/adfecc80-f1f4-11e6-8c16-ad66a31babc8.png)

**Comment by valllllll2000** [comment]
Here is what I have so far:
![screenshot_20170302-181740](https://cloud.githubusercontent.com/assets/923280/23518792/ee87bf68-ff74-11e6-859a-2f423b2f5628.png)
@Kiarii could you have a look and see if the colors are ok and if the icon is of the correct size, thanks!

**Comment by loicsans** [comment]
Hello, one thing that needs to be done is to change the header background color, also the survey title should be white instead of orange.

**Comment by Kiarii** [comment]
the + icon size could do as it is (enlarging it might introduce a confusion which one shd be used); since we dont intend it to be interactive, it should bear the same color as the rest of the text as we have it now

(Loic also mentioned that there will be a larger styling issue where the colors throughout the app shd align closely with Android guidelines)

**Comment by janagombitova** [comment]
We should tackle the changes for the header background colour and font in a separate issue. 

@Kiarii So from what I understood, the empty screen is ok as it is for now (regardless of the header)?

**Comment by Kiarii** [comment]
@Jana, yes

**Comment by valllllll2000** [comment]
Here are the empty screens layout:
![screenshot_1499250095](https://user-images.githubusercontent.com/923280/27861280-7c32636e-6180-11e7-82fc-abf984443223.png)

![screenshot_1499250127](https://user-images.githubusercontent.com/923280/27861284-8228fef4-6180-11e7-9c37-076504d7039e.png)

![screenshot_20170705-123124](https://user-images.githubusercontent.com/923280/27861293-89cf2ef8-6180-11e7-86d9-649270f2494f.png)

**Comment by valllllll2000** [comment]
## Test plan:
The objective here is to test how the empty screens look (they are displayed above in the screenshots)
1. Install the app and login: you should see the screen with the message "You have no survey selected..." 
2. Select a monitored survey and then a non monitored one. Make sure the empty screen message is still the same. 
3. Try syncing a survey for which there are no datapoints yet, you should still see the empty screen.

**Comment by janagombitova** [comment]
👍  Beautiful
