### ISSUE TITLE
[MINOR] Deleted survey still displays its name on SurveyActivity top label

### ISSUE THREAD

**Issue by MelEnt** [akvo/akvo-flow-mobile#632]
How to reproduce:
1. Add a survey
2. Select the survey 
![Survey selected](https://puu.sh/ubvrF/f437225e22.png)
3. Go into settings and press Delete everything 
4. Go back and close the drawer and observe the label still showing the deleted survey
![Survey selected](https://puu.sh/ubvrF/f437225e22.png)

**Comment by valllllll2000** [comment]
Once we fix #790 this is no longer relevant.
