### ISSUE TITLE
Review some exceptions being sent to sentry

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#633]
Some exceptions are useless and should be removed.
For example lots of useless exceptions come in the line https://github.com/akvo/akvo-flow-mobile/blob/develop/app/src/main/java/org/akvo/flow/util/HttpUtil.java#L61

* java.net.ConnectException
* javax.net.ssl.SSLHandshakeException
* java.security.cert.CertificateNotYetValidException
* javax.net.ssl.SSLProtocolException
* java.net.SocketTimeoutException
* Containing message "Connection timed out"
* https://sentry.io/akvo-foundation/flow-android/issues/223048591/
needs to be removed when forbidden since it is expected

Needs to be improved as for now as it is now it does not help:
https://sentry.io/akvo-foundation/flow-android/issues/222967325/

Make this one more explanotary (add more details):
https://sentry.io/akvo-foundation/flow-android/issues/222966993/

**Comment by valllllll2000** [comment]
## Test plan
I wrote unit tests for the first part (the removed exceptions).
For the rest make sure you have surveys assigned.
Kill and reopen the app and make sure they are synced correctly.
Try syncing a non assigned form (using settings -> download form). 
Try using the app in flight mode (syncing, creating datapoints)
If possible, try to test using 2G networks having the mobile sync settings enabled in preferences.
Try changing the dashboard name using preferences

Write here you device id and device model and I can check in Sentry if these exceptions arrived as expected.

**Comment by janagombitova** [comment]
@valllllll2000 my device ID is: jana and as far as I can tell the app works as it should, can you please cross check if all on Sentry side is as expected as well? I followed your test plan

**Comment by valllllll2000** [comment]
@janagombitova I have checked on sentry and everything is as expected, thanks!
