### ISSUE TITLE
Survey bootstrap notifications

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#634]
The survey bootstrap notifications have to be reviewed, text updated, behaviour improved.

**Comment by Kiarii** [comment]
![image](https://cloud.githubusercontent.com/assets/12692444/23502310/0aaf45c4-ff40-11e6-9272-7710d87c8bda.png)

this is the mockup we had a look at and settled for, for now.

**Comment by janagombitova** [comment]
Today we agreed to not use notifications for the bootstrap loading action, but toasts instead: 
- progress: Loading forms from SD card
- success: no toast, indication on the menu (dot) and the highlighted surveys in the list. If we see that we need to also tell the user about a successful loading, then we will add it.
- failure: Failed to load forms from SD card
