### ISSUE TITLE
Visually show that surveys have been updated or loaded 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#636]
Today we agreed with @valllllll2000 and @Kiarii that we will make a change to the app UI to visually show that there is something new regarding the surveys. 

One of the common questions/confusions users (Alphonso) have is that they say: 
- How do I know if my survey got updated or not? 
- with the data points I see that something is happening, with the survey I don't > "Users live for the green tick" (syncing a data point) 

We agreed to make these following changes to give the users more indication of change: 
- to the drawer add a little dot when a survey has been loaded or updated 
- in the list of surveys bold each survey that is new or updated (new version of a form has been added) 

<img width="690" alt="screen shot 2017-03-02 at 09 56 37" src="https://cloud.githubusercontent.com/assets/12456965/23502689/f557cf86-ff38-11e6-8974-fa80d9d2dea7.png">

These changes will happen for both cases of loading in new surveys or updating existing ones: via bootstrap or via network. Once a user selects the survey from the list it will not be bolded anymore. 

We also considered to somehow specify what has changed with the survey as there are multiple cases: 
- if a survey is fully new in Alphonso's list; 
- if only one form is added to the survey; 
- if multiple forms were added to a survey; 
- if one or multiple form versions were updated.  

The setbacks for also specifying these details are that if the survey name is too long there might not be enough space; if the phone has a small screen there might not be sufficient space; it might be too much information to share. More is less. We agreed that for now the dot indication and the bolded survey names is a sufficient change to show.

**Comment by Kiarii** [comment]
[As a note or point for later improvement, we could consider a toast on a respective survey screen to explicitly tell the user what change took place in the survey (except for New surveys - which might be self explanatory..), maybe bold new/reloaded forms, etc]

**Comment by muloem** [comment]
@janagombitova @Kiarii Did we have an issue for getting rid of the drawer menu altogether?

**Comment by muloem** [comment]
With the assumption that we are not going to remove the drawer menu, how about changing its color to indicate that there is something new?  You probably discussed that but just confirming.

**Comment by Kiarii** [comment]
the little dot above it was intended to indicate changes in the menu items (surveys to be specific) and bolding as the styling for new/reloaded surveys.. @muloem see the sketch at the top of this issue

**Comment by Kiarii** [comment]
About restructuring the menu inorder to alleviate the UX issues with the hamburger icon, am happy to dig into it, so whenever it is put into the roadmap, i will be ready when you are :) - we have also noted the survey list doesnt really belong in the navigation drawer (side menu)

**Comment by janagombitova** [comment]
There has been no issue to remove the hamburger icon for the menu or thoughts on that, as far as I remember. Users appreciate the navigation as it is a pattern used in other Android apps. This information is however not from targeted user research on the app, but from diverse feedback. 

I personally think we need to look at the menu itself and how to make navigation there more easy and add items to better places. But that is a different issue we already have in place

**Comment by valllllll2000** [comment]
@janagombitova @Kiarii @muloem i am trying to follow between here and the chat so if i understood correctly the issues that arose are:
1) Shall we remove the navigation drawer? If so where will we show the list of surveys? It did cross my mind that showing surveys in the navigation drawer is not the best place but I have no better idea yet of where to show them so I would leave the current setup as is for now.
2) The drawer menu button (the one you press to open the drawer menu). This can be done no problem and I have seen it on other apps. The only point that have just occurred to me is maybe the black dot indicating that there are new surveys should in fact be red?
3) Survey list: showing it in bold is fine but @muloem suggestion of using color is good too, which color though?

**Comment by janagombitova** [comment]
I agree. @Kiarii could you specify the colour palette for this work? The dot cannot be black as the background colour of the header is dark.

**Comment by Kiarii** [comment]
Myself and Loic have felt that the icon can be of the same color as the toolbar elements - it is not an ever-present element on the screen so it need not be additionally coded with color - it is visually: a user can already discern something is different on the toolbar even from peripheral vision (when they are not looking directly at it). The illustration gives a context:

<img width="433" alt="screen shot 2017-03-03 at 12 15 52" src="https://cloud.githubusercontent.com/assets/12692444/23547518/17a7d422-000c-11e7-8d85-f501c67248e2.png">

**Comment by janagombitova** [comment]
@loicsans and @Kiarii just to clarify I get your comment: you suggest to change the survey font colour to white (as the icons) and the extra dot to indicate something is new should be white (same colour) as well? 

I am personally used to a red dot indicating I have something new in my apps.

**Comment by Kiarii** [comment]
@Jana yes, that is our suggestion, we are reserving the double coding (dot + color) for simplicity; [Double coding is definitely a pattern in iOS, in Android its a bit subtle]; If I may refer to some examples even though the context is a bit different:

<img width="357" alt="screen shot 2017-03-06 at 11 40 23" src="https://cloud.githubusercontent.com/assets/12692444/23604511/d6739a1a-0261-11e7-942f-d713427af8be.png">

<img width="438" alt="screen shot 2017-03-06 at 11 41 06" src="https://cloud.githubusercontent.com/assets/12692444/23604524/e67e8a32-0261-11e7-8efe-0403d15b350b.png">

**Comment by janagombitova** [comment]
@Kiarii 👍  sounds good. Hearing your reasoning why we decide to go for one path or another helps me to also explain if questions arise.

**Comment by janagombitova** [comment]
Today we have discussed with @valllllll2000 and @Kiarii the communication around downloading forms to the device. Either the download is triggered automatically by opening the app, or the user triggers the action himself by using **Reload all surveys** or **Download form** actions, currently placed in the Settings. 

We agreed that this location is not the best choice for these actions and that we should bring them closer to the surveys to make it easier for our Alphonso's to get new forms, versions of forms into his device. 

Kiarii will consider placing these two actions in the side menu panel where the surveys are listed. We will not change the behaviour of these two actions at the moment. The initiative right now is to find them a more user friendly location. We will change their naming for improving consistency: 
- Reload all surveys >> to **Reload all forms** (@kiarii did we say reload or download?) 
- Download Form >> to **Download specific form**

We have also discussed the case, where if a survey is added to an assignment, Alphonso has to close and reopen the app to trigger getting the survey into his device. We considered a few ways how to improve this and further ideation will happen in this issue: https://github.com/akvo/akvo-flow-mobile/issues/659

**Comment by valllllll2000** [comment]
I have been experimenting on how it could look so here are some screenshots:

1) Navigation drawer expanded
You can see at the right of survey, there are 2 buttons one to download all forms and the other to download one, obviously some nicer icons would be needed.
![screenshot_20170321-181220](https://cloud.githubusercontent.com/assets/923280/24160565/8194a978-0e62-11e7-8f82-3b12d314fc58.png)

2) after clicking the user
The overflow black menu could use some redesign.
![screenshot_20170321-181226](https://cloud.githubusercontent.com/assets/923280/24160616/a18303e2-0e62-11e7-8634-f83eb8f20160.png)

3) General screen
- I have changed the toolbar color to the same as the caddisfly app, this is optional
- The plus sign from menu to add datapoints could be moved to bottom right, using the floating action button, also optional.
- If we decide to keep the orange toolbar then we would need to use another color for the tabs, not sure which one.
![screenshot_20170321-181230](https://cloud.githubusercontent.com/assets/923280/24160770/09170eea-0e63-11e7-882d-9f966193c22f.png)
@janagombitova @Kiarii what do you guys think?

**Comment by janagombitova** [comment]
@valllllll2000 before I dive into smaller points, should be maybe break these changes down into separate issues? 

Here is my take on the changes 

## 0. Highlighting a new form is dowloaded/loaded

Do you have a screen shot on how Kiarii's mock ups will look like in practice for this improvement? 

## 1. Navigation drawer expanded

So here we are talking about how to easily allow users to either reload all their forms or how to manually download a specific form in this location. Both actions currently live under Settings. 

I do agree with placing them in the Surveys part of the menu, but I have a few things I want us to keep in mind: 
- consistency when it comes to working with the elements in the menu - expanding items, use of icons, colours, highlighting the "labels" of the different parts of the menu, etc
- the two actions need to be clear to the users on what they mean and what they do 

I am curious to see @Kiarii 's drawings 

## 2. User expanded 
On my devices I do not get a black menu. Why is my experience different from yours (different devices and Android versions) and how can we make sure it is unified? 

It looks like this for the newer phone: 
![screen shot 2017-03-22 at 11 21 43](https://cloud.githubusercontent.com/assets/12456965/24193371/54b2f442-0ef2-11e7-8eb9-fda64d094850.png)

For the old dinosaur: 
![screen shot 2017-03-22 at 11 23 13](https://cloud.githubusercontent.com/assets/12456965/24193372/56a77bd8-0ef2-11e7-9491-6abebc88aaff.png)

## 3. General screen

### Toolbar colour change 
I personally like that the toolbar holds our Flow branding colour and that the title (Akvo Flow and I then assume also the selected survey title) are in white as the icons. I know @loicsans wanted to make this change, so I am curious to hear his take for this and also what to do with the tabs. 

### Plus icon
I really like this improvement. But, there is always a but.. ;) the colour should match with our branding. We should use either the button colour we have in submissions or orange. I am not actually sure, but I do not want us to introduce another colour. I assume @loicsans will have a way forward. 

Regarding the icon in itself, how will it look like and work, if there are many submissions on the screen? Will it work for also very old Android phones (our old dinosaurs). If yes, then we should make this change.

**Comment by valllllll2000** [comment]
Here are new propositions for displaying the surveys in the navigation drawer with or without icons:
![screenshot_1490286947](https://cloud.githubusercontent.com/assets/923280/24258861/531f790e-0fef-11e7-9df5-9e4db24ba269.png)

![screenshot_1490286835](https://cloud.githubusercontent.com/assets/923280/24258860/531deaa8-0fef-11e7-9a97-0c3ae555b93f.png)

**Comment by valllllll2000** [comment]
@janagombitova I have read your comments and separated the diferent proposals into diferent tasks and here are replies to the points you raised

0) New surveys
See above the 2 options I came up with. Basically the surveys that have new staff are in bold.

1) Download form(s) 
You can also see the option in the screenshot above, I am not sure how to add the 2 extra options so I just added them in bold right before the survey section title. I think maybe having them in text is better than with some icons which you have to guess what they mean.

2) User
I have created a separate issue for that https://github.com/akvo/akvo-flow-mobile/issues/670

3) General:
Toolbar: here is the issue https://github.com/akvo/akvo-flow-mobile/issues/668
+ Button: https://github.com/akvo/akvo-flow-mobile/issues/669

**Comment by janagombitova** [comment]
@valllllll2000 wonderful! Thank you very much, I think this will make it easier for us to decide on the separate parts. Regarding the item remaining in this issue, **new survey** and **download form(s)** let's wait for @Kiarii and his designs

**Comment by Kiarii** [comment]
- what we have discussed so far:

![image](https://cloud.githubusercontent.com/assets/12692444/24549165/b9cb8a9e-1620-11e7-82cf-b5d982acc278.png)

**Comment by muloem** [comment]
One comment on these: we have been trying to move away from the notion of users being aware of the form id since its an internal storage concept.  Infact we are trying to move away from that in general all over the app and backend.  Could we already avoid having that here?  i.e a user has just one button that is the equivalent of download and all surveys that have been assigned should be received. 

The _reload all forms_ is something that I believe was added because of issues regarding stability of the form download.  I think we should move away from it and just focus on ensuring that when a user / device is assigned a form, its correctly delivered.

Finally regarding the color highlight that I was mentioning earlier, I was actually referring to highlighting the drawer menu with colour i.e. the drawers would be coloured or not to show that there is something new.

**Comment by janagombitova** [comment]
@muloem I agree that we need to move away from showing users internal IDs. However in this case, downloading a form via the form ID is actually used by our users. The most common case is to test out a survey before the "real" data collection. The get the survey forms on their phone a click around to see how the survey renders on the phone and how question link to each other, sometimes even submit mock data to see how the data is rendered. Before the actual data collection they delete the survey from the phone and delete the test data. A second case is in training (Akvo training or partner training colleagues and data collectors) where they quickly get the surveys on the phones without the hassle of creating an assignment. Third case, is us testing ;) So before we figure out how to satisfy these needs in a different way, we will keep it here, as we have bundled these actions into one shared location. 

On the reload all forms we are changing the behaviour in a way to also cross check for new surveys in assignments and not only new survey versions. See here: https://github.com/akvo/akvo-flow-mobile/issues/660 This action will enable the user to get in all the forms she is supposed to have. The idea is to replace the current behaviour of force closing and reopening the app. So it is basically the one button you refer to in your 1st paragraph.

What would be worth reconsidering is - Does the user need to fill in the admin passcode to be able to receive surveys she is supposed to receive? @valllllll2000 and @muloem What are your thoughts and risks? 
  
On the highlighting of the drawer menu, wed decided to follow the commonly known indication on android apps where you have the little dot indicating something new or extra is in that location.

**Comment by janagombitova** [comment]
@valllllll2000 I have the feeling we have two major changes in this issue: 
- visually indicate that a new survey form or a new version has been downloaded to the phone 
- change how a user can trigger the surveys to download. 

I would like to suggest we keep the visual changes to the list of surveys in this issue and deal with the downloading of the forms here:https://github.com/akvo/akvo-flow-mobile/issues/660 to keep things organised. Do you agree?

**Comment by janagombitova** [comment]
Commenting so the GitHub/StaleBot Gods do not close the issue

**Comment by valllllll2000** [comment]
<img src="https://user-images.githubusercontent.com/923280/92468019-c80ddf80-f1d2-11ea-9dfe-b72f4bd3eb37.png" width="200" />

**Comment by iperdomo** [comment]
Tested on Huawei P9 / Android 7.0 / App version 2.9.5 ... the updated forms are shown in **bold**
