### ISSUE TITLE
DatabaseHelper upgrade method

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#646]
The DatabaseHelper upgrade method is very confusing and before adding any more updates, it needs to be refactored

**Comment by valllllll2000** [comment]
## Test plan

This is a bit tedious to test as I do not know which versions of the database correspond to which version of the app that is why I have added unit tests.
Here are a few manual steps:
Install version 2.2.9
-Modify some preferences
-Go offline
-Create some datapoints
-Go online and update to latest version
-Make sure settings and datapoints are all there and are correct.

**Comment by janagombitova** [comment]
All works as expected 👍
