### ISSUE TITLE
Repeated groups delete button can delete the questions of the whole group

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#651]
Repeated groups have a delete button which deletes the entry but if we no longer have any repetitions it deletes the whole question group, see screenshots for example:
before pressing delete:
![screenshot_20170314-133834](https://cloud.githubusercontent.com/assets/923280/23901024/c80a9734-08bb-11e7-9b5b-fc24f4c7d5d9.png)

after pressing delete:
![screenshot_20170314-133843](https://cloud.githubusercontent.com/assets/923280/23901034/d85007b4-08bb-11e7-859f-7e01129a0bad.png)

As you can see, the question can no longer be filled since the question has disappeared.

This is reproduced with app version 2.2.10.1

**Comment by valllllll2000** [comment]
## Test plan
Created a survey with repeated group
Add datapoint and 1 repetition
Try deleting the repetition
Make sure the question fields are still displayed

**Comment by janagombitova** [comment]
I really like how you made this work. Well done. The deletions behave as expected 👍

**Comment by janagombitova** [comment]
Created via Reamaze:

Link: https://flowhelp.reamaze.com/admin/conversations/akvoflow-support-request-number-74971-from-geert-at-akvo-dot-org
