### ISSUE TITLE
Crash when attempting to display the gps dialog

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#656]
https://sentry.io/akvo-foundation/flow-android/issues/233957473/

```
BadTokenException: Unable to add window -- token android.os.BinderProxy@38fdf7fc is not valid; is your activity running?
    at org.akvo.flow.util.ViewUtil.showGPSDialog(ViewUtil.java:65)
    at org.akvo.flow.ui.view.GeoQuestionView.onGPSDisabled(GeoQuestionView.java:202)
    at org.akvo.flow.event.TimedLocationListener.onProviderDisabled(TimedLocationListener.java:114)
...
(13 additional frame(s) were not displayed)

Unable to add window -- token android.os.BinderProxy@38fdf7fc is not valid; is your activity running?
```

**Comment by valllllll2000** [comment]
##Test plan
Use some old samsung device if possible.
Disable location on device.
Create a survey which requires location. Press "obtain location" button.
You should see a dialog telling you to enable location.
Rotate the device a couple of times while the dialog is showing.
There should be no crash.

**Comment by janagombitova** [comment]
tested on a newer and old dinosaur device and none of them crash when following your instructions 👍 

I do have one step that we have further improve on this. After dismissing the pop up (either by the phone's back button or clicking cancel) I still see on the form screen that Flow is `searching` for the geolocation. This should not show as Flow cannot obtain the location information and the pop up + searching info on the screen are then two clashing information messages we give to Alphonso
 
![screenshot_2017-03-27-11-57-38](https://cloud.githubusercontent.com/assets/12456965/24351075/bd1bc900-12e4-11e7-8cfa-aa30c7e984dc.png)

I am not sure whether this needs a separate issue, but would it be possible for these cases to stop showing `searching` in the screen? 

Two more visual improvements that I assume need separate issues: 
- information shown in the pop up dialogue is too long and not straightforward regarding the actions given https://github.com/akvo/akvo-flow-mobile/issues/672
- the UI around `searching` for location can use some improvements https://github.com/akvo/akvo-flow-mobile/issues/673

**Comment by valllllll2000** [comment]
@janagombitova I will open a separate issue for the "searching" problem as this issue is clearly about the crash of the gps dialog itself

**Comment by janagombitova** [comment]
My last comments are handled in separate issues, thus this one is ready to go 👍
