### ISSUE TITLE
Date Picker using GMT formatting by default

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#662]
Steps to reproduce:
Place yourself in a timezone where you know it in another day than where you are located, say I am in GMT + 1 timezone and it is 10am, I placed myself in GMT-10 (Hawai) and there it is 23.00 March 19th. When I select the current data, March 19th, the marked date is March 18th.

**Comment by janagombitova** [comment]
Created via Reamaze:

Link: https://akvoo.reamaze.com/admin/conversations/date-mistake

**Comment by valllllll2000** [comment]
Created via Reamaze:

Link: https://flowhelp.reamaze.com/admin/conversations/date-mistake
Assignee: Jana Gombitova

Message:
Hi Guys, 

I'm having trouble again with date questions in Flow. When I select a date on the phone the app registers the previous day than the one I selected. I took a short video to illustrate. 

AECOM  is using a ton of date questions in a survey so I've suggested they used free text until this date thing is fixed. Please keep me posted. 

Have a great weekend. 

Ethel

**Comment by valllllll2000** [comment]
## Test plan
In order to test the issue you need to change your phone's timezone to one that has a diferent date than your location, good candidates, depending on the time of day maybe either Hawaii or Australia. Once you change the date, create a survey with a date and use the date picker to select the date. Make sure that when you select the date that it is displayed correctly to the user and press submit. Also after submitting make sure the date is displayed correctly when viewing the datapoint

**Comment by janagombitova** [comment]
👍  works like a charm
