### ISSUE TITLE
Sentry improvements

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#666]
There still can be more improvements to the sentry crash reporting:
- Remove sending of reports when we are in debug mode since we can see the logs in the console already.
- See if more exceptions can be filtered.
- Use raven-android library instead of https://github.com/akvo/Sentry-Android

**Comment by valllllll2000** [comment]
## Test plan
Assign at least one survey to your device.
Try syncing a non assigned form (using settings -> download form).
Try using the app in flight mode (syncing, creating datapoints)
If possible, try to test using 2G networks having the **mobile sync settings enabled** in preferences.
Try changing the dashboard name using preferences and then sync.

You can check in sentry.io if the exceptions arrived or write your device id and model so I can check.

**Comment by janagombitova** [comment]
my device is: jana and the model is: Samsung GT-l9301l

all worked fine, besides switching the instance name. I have the feeling that has not worked properly for quite some time now, as we always advise that it is better to uninstall and reinstall the app if you want to use it for another instance. But it might be worth checking what is up.

**Comment by valllllll2000** [comment]
@janagombitova instance name changing is not possible because there are some password attached to it and we only update the instance, not the passwords so it will not work.
