### ISSUE TITLE
App ToolBar color change

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#668]
Here is a screenshot for the proposed new toolbar look:

![screenshot_1490283484](https://cloud.githubusercontent.com/assets/923280/24256043/731f6a00-0fe7-11e7-890c-c18a0e855d7c.png)

**Comment by janagombitova** [comment]
Looking good. I like it  :) 

We will need to change the text for the empty screen as the plus is no longer on the top of the users screen

**Comment by loicsans** [comment]
The toolbar colour looks much nicer. For the tabs we could spread the look: 
![731f6a00-0fe7-11e7-890c-c18a0e855d7c](https://cloud.githubusercontent.com/assets/1717219/24703406/c33d7954-1a0b-11e7-91d9-745484e9ecce.jpg)

**Comment by loicsans** [comment]
Clearly, the orange is off on my screenshot

**Comment by valllllll2000** [comment]
## Test plan

Please test the following:
Main screen with datapoints list
Creating new monitored and non monitored forms
Settings
Preferences
GeoShape question
View map of a single datapoint

**Comment by janagombitova** [comment]
@valllllll2000 the Marcomms team released out new brand book, and I just want to make sure we are using the correct orange in Flow. Regarding the other colours in the app, we need to discuss that further. 

Here are the details on the orange from the brand book that can be found here under Branding - https://peak.akvo.org/comms-resources/

HEX #DE8929

**Comment by valllllll2000** [comment]
@janagombitova I have changed the orange to #DE8929 it was slightly diferent

**Comment by janagombitova** [comment]
![screenshot_2017-04-21-11-46-49](https://cloud.githubusercontent.com/assets/12456965/25272524/835bdf4a-2688-11e7-8a91-11ac794877d2.png)

Can we make the tabs a different shade of orange? If find it hard to see the distinction between the toolbar and the tabs. This may be because I am used to the old look. @loicsans what are your thoughts?

**Comment by janagombitova** [comment]
Ok. after talking to @loicsans he made me understand :) that this is a good thing. Orange power! Plus indeed it simplifies the app. So ignore my comment above

**Comment by loicsans** [comment]
Cool, I think it looks much better now, we could though add a drop shadow right below the tabs to emphasis the tabs / content separation:
![screen shot 2017-04-21 at 13 40 51](https://cloud.githubusercontent.com/assets/1717219/25274395/868c4654-2698-11e7-94ae-df036f82f3b9.png)

**Comment by janagombitova** [comment]
All looks good to me on my device 👍  the more I look at it the more I am liking the orange
