### ISSUE TITLE
SurveyActivity move "+" menu entry to FAB

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#669]
The FAB or Floating Action Button would act the same way as the "+" menu entry and would only be visible if a survey is selected.
Here is a screenshot of how it could look:
![screenshot_1490283484](https://cloud.githubusercontent.com/assets/923280/24256225/e1b5c9be-0fe7-11e7-97a1-7ba6cbbe9598.png)

![screenshot_1490284365](https://cloud.githubusercontent.com/assets/923280/24256706/2efe36a6-0fe9-11e7-9468-7b70c47beae2.png)

**Comment by janagombitova** [comment]
Looking good.

In the previous issue I made a comment that we would need to change the text of the empty screen, but then I realised we have a new empty screen coming up (https://github.com/akvo/akvo-flow-mobile/pull/640) and the text is ok

**Comment by valllllll2000** [comment]
@janagombitova I have realized that since we are going to move the add entry to the fab button, its previous "spot" will be left free and hence we could move another entry there so the candidates are:
-search
-sort
-stats
-sync -> that one is only there for monitored surveys
I would say "search" is a good candidate or "sync", what do you think?

**Comment by janagombitova** [comment]
@valllllll2000 interesting thought.

From my understanding the actions that are shown in the toolbar should be things users do often, where the menu icon (on the right) holds the secondary actions. If we go for another action there, besides which one to choose, we will also need a good icon to illustrate the action. We can also go for no action. 

I feel we need design input and this is conversation needs to grow. Can you create a separate issue and we can think more about it there?

**Comment by stellanl** [comment]
I'm sorry I did not comment earlier, but I did not see this issue.
If we have to have FABs I think there are more cheerful colours. Something more "Akvo"; or we could use the toolbar colour to emphasize that the button is part of the surrounding UI.
What do you think, @janagombitova , @muloem ?

**Comment by janagombitova** [comment]
I personally like that we use the colour that we already have in the app on other buttons. 

When it comes to the question if this is the best colour - @loicsans this is your domain. I fully agree that we should make sure it is in line with the overall akvo brand (https://www.dropbox.com/s/y90e5q96getjeqi/brandbook%2005-04-2017%20-%20COMPLETE%20DOC.pdf?dl=0) as @stellanl mentioned. And secondly, to keep the number of different colours in the app to minimum

**Comment by janagombitova** [comment]
Giving this a longer thought, I would suggest - if @loicsans would like to do a colour clean up - then we should handle it separately and the changes we make now, should follow the existing colour pattern.

**Comment by loicsans** [comment]
Agreed with @janagombitova. Overall the colours in the app should be dealt with in a separate issue.

**Comment by valllllll2000** [comment]
## Test plan
Please test without any surveys selected, monitored survey and non monitored surveys. Make sure clicking on the + button you are taken where you should.

**Comment by janagombitova** [comment]
I like this improvement very much! 👍  plus works good!
