### ISSUE TITLE
Simplify dialogue for failed GPS search

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#672]
![screenshot_2017-03-27-11-57-07](https://cloud.githubusercontent.com/assets/12456965/24351296/73c44c5e-12e5-11e7-925d-f481f4eb7c06.png)

If the user asks Flow to "Check geo location" and GPS is not enabled on the phone we show a dialogue telling the user that GPS is not enabled and he needs to change the setting on his device. This dialogue is however too long and the action items are not clear. We need to reconsider how we deliver this error message and make it simple and understandable as possible

**Comment by valllllll2000** [comment]
![all_apps_screenshots](https://cloud.githubusercontent.com/assets/923280/24357529/3f6746b4-12fe-11e7-83c7-2a57d0634078.png)

Here is how it looks on other apps.

**Comment by janagombitova** [comment]
I think we can use the "Please enable location settings" in combination with Cancel and Settings

**Comment by valllllll2000** [comment]
## Test plan
Disable location on device.
Assign a survey with location question.
Press "check geo location".
You should see a dialog like in this screenshot. 
![screenshot_1490709886](https://cloud.githubusercontent.com/assets/923280/24410507/863bd2c8-13d3-11e7-889b-c361bdbc9870.png)

**Comment by janagombitova** [comment]
👍  much nicer, well done
