### ISSUE TITLE
Improve UI for when searching for location

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#673]
![screenshot_2017-03-27-11-57-38](https://cloud.githubusercontent.com/assets/12456965/24351383/c57d06e4-12e5-11e7-80eb-d9c448571e21.png)

When adding location information to a form the user can either fill it in manually or get the GPS info via the device by clicking on "Check geo location". After selecting this second option there is a small indication telling `Searching...` to show the user Flow is trying to capture the location info. This is not the most ideal way of showing this as the message is hidden in the side of the screen. 

Can we improve this? @Kiarii and @loicsans

**Comment by valllllll2000** [comment]
@janagombitova @Kiarii @loicsans I think in this case the "searching" indicator should be attached to the button so users do not try to press again: so maybe an alternative would be to set the button text to "obtaining location..." and disable the button until either:
1) A timeout occurs and location retrieval fails
2) A location is successfully obtained
3) We detect user disabled location 
An extra bonus would be to add some kind of animation to the button to show movement

**Comment by janagombitova** [comment]
@valllllll2000 that sounds like a good idea! And I also like the idea of an animation, but have no suggestions on it besides the loading either sinning circle or horizontal bar 

Maybe we can simply say: Getting location

**Comment by Kiarii** [comment]
Following the suggestions made so far, it seems that the button shd be labeled "Get Geo Location" and be replaced by a "Getting location details [loading dots]" (+ manual entry of lat/lon is disabled) - in which case the button is returned upon the 3 states  described by @valllllll2000 ..

**Comment by valllllll2000** [comment]
Good point @Kiarii what to do while we wait for location? Disable manual input? What if the use decides to provide manual input while we are already waiting for location? or shall we still allow manual input in which case if user starts manual input we ignore the automatic location?

**Comment by janagombitova** [comment]
Currently if the users clicks to Get location and then starts inputting it manually and the automatic location comes in, it overwrites the manually input location. So we have two options for the case if user asks for automatic location: 
1. disable manual input 
2. stop checking for location once the user starts manually inputting location 

I am in favour for the 2nd option, as checking for location might take a few more seconds and Anthony becomes impatient, or he realises that where he is currently standing is not the correct location he needs to capture and needs to stop the automatic location. 

Maybe we then have a third option: 
3. disable manual input but allow to stop the searching for location 

Then I would be in favour for the 3rd one. But this is my opinion and I would like to hear yours @valllllll2000 and @Kiarii  before we make the call.

**Comment by valllllll2000** [comment]
There is another option as well:
4) If user inputs manually and then we get automatic location, ask the user if he want to override the previous one (we have a way to check with the accuracy value if the data are from manual input or from gps).

**Comment by Kiarii** [comment]
I have been giving it a bit of thought as it does appear a bit tricky; I think the workflow shd be such that the app takes input from one 'system' at a time (3.) so if its fetching it automatically, the manual entry shd be disabled, and if a manual entry is made, it has to be visually obvious to the user that the app will override the manual entry - so the auto-fetched shd not appear in editable fields. In addition there shd be a way to stop the auto-fetch (while it is in process) and do the manual entry..  

Ideally, the app shd give preference to the most reliable source (i.e. to "auto" if validity and reliability of readings is high, else manual) - but this I think is not feasible technically

**Comment by valllllll2000** [comment]
@janagombitova @Kiarii after reading your input I have created the following screenshots with options as to how we can display this view.
Initial layout (same as before):
![screenshot_1490778510](https://cloud.githubusercontent.com/assets/923280/24447923/d1c343da-1472-11e7-8402-d05f377355e6.png)
After pressing the "check geo location" button, here are 3 options:
Option 1 (only text):
![screenshot_1490778514](https://cloud.githubusercontent.com/assets/923280/24447956/f4d64dfe-1472-11e7-8d33-91ab3423e5f5.png)
Option 2 vertical progress bar (the wheel is moving, progress bar color can be changed too)
![screenshot_1490779268](https://cloud.githubusercontent.com/assets/923280/24447985/097d69b8-1473-11e7-9a8b-24ee7d6e5c4f.png)
Option 3 horizontal progress bar (this looks much nicer when the animation is visible, try to imagine the blue line color changes). The animation is similar to the indeterminate progress bar here https://material.io/guidelines/components/progress-activity.html#progress-activity-types-of-indicators
![screenshot_1490779580](https://cloud.githubusercontent.com/assets/923280/24448016/2030cf42-1473-11e7-9250-17272cbced64.png)

**Comment by janagombitova** [comment]
I prefer option 3 with the horizontal indeterminate progress bar. I have some improvement points: 
- language: If we say in the initial button `Check geo location` we should use the verb talking about the progress. I would suggest: `Checking for device location. Press cancel to enter manually.` 
- @loicsans are you ok with how this overlay looks? I have the feeling 

And an extra question: By disabling manual entry of location, the user will still be able to fill in answers for other questions while the location is fetched, right? 

And an extra UI improvement: Can we find a different position for the Accuracy? The 1st time I saw the app I thought it was the accuracy of the longitude and I found that weird :P

**Comment by loicsans** [comment]
@janagombitova I had a discussion with @Kiarii yesterday, and he has an alternative idea that we've agreed upon, him and I

**Comment by janagombitova** [comment]
@loicsans and @Kiarii Nice! Looking forward to seeing it

**Comment by valllllll2000** [comment]
@janagombitova @loicsans after viewing the options that @Kiarii showed us I have come up with this option:
![screenshot_20170331-180527](https://cloud.githubusercontent.com/assets/923280/24558849/e93d4db4-163c-11e7-843c-ed93a417edb9.png)
So here the user can scroll the map and once he taps a point on the map, the location is selected.
He can also press the location button on the right and then we would wait for gps location and once it is there the same red marker would appear.
We could also add manual input as well with another button and in that case a dialog/pop up would appear with text fields to write latitude and longitude but I am thinking maybe selecting on the map would be easier for the user?

**Comment by janagombitova** [comment]
I do not think the map idea will work because of cases where data is collected in the field without any connection so the map will not load. From Kiarii's drawings I liked the distinction between typing in the coordinates manually and getting them automatically via the device. We also need to consider the situation that the location data is read in automatically, but the user wants to adjust the coordinates (I am not sure if this has even happened, but worth a thought)

**Comment by janagombitova** [comment]
We had a quick call with @valllllll2000 on this issue. Considering adding the map does not fit the cases of offline data collection, we only have some experimental designs and the release is due this week and this issue ties to other already merged changes, we decided that we will move forward for this release with her Option 2 from this comment. 

The text will be shorter to only tell about the loading, without the cancel sentence, as that is understandable by the button below. We will use the spinning wheel icon. The Accuracy will be moved under the Lat, Long, Height and shown as a 4th value. We have taken this course of action, to continue moving forward with the improvements. 

The next steps will be, once @Kiarii is back from holiday, to take the designs further and look into showing the location on the map. This discussion will happen in this issue, so we can consider all scenarios and come to a better design. https://github.com/akvo/akvo-product-design/issues/256

**Comment by valllllll2000** [comment]
## Test plan
Create survey which requires location and allow manual field editing.
Try editing fields manually, getting data from gps, try disabling gps
Also test when manual field editing is disabled, make sure then manual input is disabled.

**Comment by janagombitova** [comment]
Found one funny thing here: 

![screen shot 2017-04-04 at 13 59 24](https://cloud.githubusercontent.com/assets/12456965/24655569/08c72240-193f-11e7-8ffc-d49511989aff.png)

1. I click to search for geolocation 
1. The app starts getting the location 
1. If I click on the new area I can start manually inputting the location

**Comment by janagombitova** [comment]
Manual input no longer possible. Ready to go 👍
