### ISSUE TITLE
Remove "searching" textView

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#674]
found by @janagombitova while testing https://github.com/akvo/akvo-flow-mobile/issues/656:

After dismissing the pop up (either by the phone's back button or clicking cancel) I still see on the form screen that Flow is `searching` for the geolocation. This should not show as Flow cannot obtain the location information and the pop up + searching info on the screen are then two clashing information messages we give to Alphonso
 
![screenshot_2017-03-27-11-57-38](https://cloud.githubusercontent.com/assets/12456965/24351075/bd1bc900-12e4-11e7-8cfa-aa30c7e984dc.png)

For these cases we need to stop showing `searching` in the screen

**Comment by valllllll2000** [comment]
## Test plan
Create a location question view and assigne the survey to device. When filling the survey, press "Check geo location". Make sure the "searching" textview is gone.

In another task, we will display some UI that the location is being acquired.

**Comment by janagombitova** [comment]
👍  all good
