### ISSUE TITLE
GeoQuestion Location Invalid Input

### ISSUE THREAD

**Issue by MelEnt** [akvo/akvo-flow-mobile#679]
Longitude and Latitude values should have a range of +180 to -180 and +90 to -90, respectively.

Currently, it's possible to manually enter and send a lon/lat value that surpasses this range. 
This may get problematic if a user types a value above or below the range and then sends out tasks and/or resources to that place only to find him or herself in no-mans land.

![Input](https://puu.sh/v3ejR/8ca8e79a57.png)

![Submit](https://puu.sh/v3ek7/c2f58d44a7.png)

**Comment by valllllll2000** [comment]
## Test plan
Valid coordinates have to be: latitude +90 to -90 and longitude: +180 to -180, altitude has been fixed at -15000 to 15000.
Create a form that requires geo location and allows manual input.
Try inputting invalid values for either latitude, longitude and height and see what happens.

**Comment by valllllll2000** [comment]
Not Ok in the following case:
After filling location data manually if we request automatic location and fields get erased, the edit texts are shown with errors but empty fields should be ok especially since we are waiting automatic location.
