### ISSUE TITLE
Add code coverage reports

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#681]
Codecov can be easily added tot ravis builds to view code coverage and its evolution:
see here:
https://codecov.io/gh/akvo/akvo-flow-mobile/commits

**Comment by valllllll2000** [comment]
## Test plan
Nothing to test here, only changes to buildscripts

**Comment by muloem** [comment]
We should configure the code coverage with codacy.

**Comment by valllllll2000** [comment]
No manual tests needed
