### ISSUE TITLE
Transmission History screen is ugly

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#695]
Here is a screenshot of the Transmission history screen:
![screenshot_20170405-162200](https://cloud.githubusercontent.com/assets/923280/24710098/5ce454dc-1a1c-11e7-9a46-3384d0adbb39.png)

I suggest we add a toolbar containing title with a back button?
@janagombitova what do you think?

**Comment by janagombitova** [comment]
@valllllll2000 make it happen 👍

**Comment by janagombitova** [comment]
To take is a step further maybe we can add some spacing between the status, the item (zip file or photo url) and the times? 

![screenshot_2017-04-05-04-38-28](https://cloud.githubusercontent.com/assets/12456965/24710774/608f5760-1a1e-11e7-9a90-3674e1dd05d7.png)
![screenshot_2017-04-05-04-41-58](https://cloud.githubusercontent.com/assets/12456965/24710966/f13233b4-1a1e-11e7-9a26-dc3a668344c3.png)

**Comment by valllllll2000** [comment]
@janagombitova good idea, you mean vertical spacing between each text item for example separate Failed and the name of the file a bit?

**Comment by janagombitova** [comment]
@valllllll2000 yes. So a space between the status, the file name and then the time

**Comment by valllllll2000** [comment]
@janagombitova Here is what I have so far:
![screenshot_2017-04-18_1351](https://cloud.githubusercontent.com/assets/923280/25129409/385e3df4-243e-11e7-8fd9-3378b2df81d2.png)
what do you think?

**Comment by janagombitova** [comment]
Looking good 👍 I think this is a great 1st improvement 

@valllllll2000 can you make the title in the header "Transmission History" not bold?

**Comment by valllllll2000** [comment]
## Test plan

Create and sync datapoints if possible in diferent states (some synced others exported only).
Open datapoint and select "transmission history" in the menu.
This is what you should see:
![screenshot_20170419-093821](https://cloud.githubusercontent.com/assets/923280/25168596/77849482-24e4-11e7-96fc-fc9314fda221.png)

**Comment by janagombitova** [comment]
👍  beautiful
