### ISSUE TITLE
Remove validation code for free text question types

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow-mobile#709]
Validation rules are setup for free text and number type questions in order to validate the input.  However, the free text validation currently only checks for camel case in the question name.  In addition, the validation rule itself is never generated in the survey (see https://github.com/akvo/akvo-flow/issues/2053).  Therefore, we will remove the validation code for free text questions.

**Comment by valllllll2000** [comment]
## Test plan:
Create a survey with a number question which has a maximum and minimum value. Make sure when you try putting numbers smaller or bigger than these values on the phone, you get the appropriate error messages.

**Comment by janagombitova** [comment]
Works as expected. Well done 👍

**Comment by janagombitova** [comment]
I found one issue on the old dinosaur phone with the validation error message is not readable. See screen shot (sorry about the quality of the image) 

![fullsizerender 3](https://user-images.githubusercontent.com/12456965/26837026-a90044de-4adc-11e7-9dcf-296313efe1fa.jpg)

**Comment by valllllll2000** [comment]
@janagombitova I have created another issue for this because it is not related to the change described in this issue: https://github.com/akvo/akvo-flow-mobile/issues/750

**Comment by janagombitova** [comment]
Thats ok, then this fix is ready to go
