### ISSUE TITLE
Sorting by distance does not show the distance

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#710]
We can sort data points by date, distance, status and name. When sorting by distance the data points not only reorganise in the list by having the one closest to you on the top, but you also see in the list of points the distance information. Users use this data in the field to then navigate to the data points they are to monitor. 

<img width="355" alt="screen shot 2015-10-16 at 17 13 13" src="https://cloud.githubusercontent.com/assets/12456965/25478883/2927a882-2b43-11e7-9e3f-3bcde73e5966.png">

In the current (and most likely previous versions) something broke on this sorting. When sorting by distance, the points still shuffle around but you cannot see the distance information anymore. 

We need to make sure: 
- the sorting is still working
- we show the distance information in the screen

**Comment by stellanl** [comment]
The list-displaying code was never told about the position, assumed it was unknown, and did not show it. The sorting code was not changed recently.
