### ISSUE TITLE
Code cleanup discovered by lint

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow-mobile#712]
These translated strings are not used: (exist in most if not all languages, except English)
`<string name="accuracy">Prec</string>`
`<string name="searching">Buscando...</string>`
`<string name="ready">Listo</string>`
`<string name="timeout">Tiempo de espera</string>`
`<string name="caddisfly_response">`

and this:

SettingsActivity.java:324: Error: The WIFI_SERVICE must be looked up on the Application context or memory will leak on devices < Android N. Try changing  to getApplicationContext().getSystemService(...)  [WifiManagerLeak]

**Comment by valllllll2000** [comment]
Done in previous release
