### ISSUE TITLE
App icon is huge

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#722]
The app icon is 512 by 512 pixels and is placed in the drawable-hdpi folder. There is no need for such a big size. App icons should be in mipmap folders and should have alternative sizes for multiple device screen resolutions. Due to this, I cannot use it for about page (issue #595) without providing express sizes for the image view.

**Comment by valllllll2000** [comment]
## Test plan
install app
make sure the icon has same look as before in the device's home screen

**Comment by janagombitova** [comment]
👍  looking good
