### ISSUE TITLE
Display captured geo shape in a nicer way

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#729]
When user captures geoshape, once saved he sees the shape was captured successfully but not the shape itself, see screenshot:
![screenshot_20170518-185809](https://cloud.githubusercontent.com/assets/923280/26215503/da5f682e-3c00-11e7-8555-f0a6a0a6c7ce.png)
It may be interesting to display a small map with the captured geoshape?

**Comment by janagombitova** [comment]
I like that idea. It would save the user the step of going to the geoshape page. This would apply for viewing the shape once saved but also once submitted right? And we will still restrict editing of the shape only in the editor page, not in the little map that would show in the form, correct?

**Comment by valllllll2000** [comment]
@janagombitova yes, editing the geoshape has to be done on the big map as we currently have
