### ISSUE TITLE
Transmission history after datapoint is synced

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#737]
After syncing the datapoint, its transmission file gets duplicated:
![transmission](https://cloud.githubusercontent.com/assets/923280/26671463/e4334ab8-46b5-11e7-8804-6c1368336a01.png)

**Comment by valllllll2000** [comment]
## Test plan
Create a monitored survey with an image or video with one registration form and at least one other form
Fill in a datapoint and submit, then fill the other form
Check the transmission data, make sure all is as expected
Sync the datapoint (let a few seconds pass so you can compare sync date), make sure all the records transmission date has been updated (in the transmission screen).

Create a datapoint on another device for the same survey. Make sure to sync it with the device 1 and check the transmission screen.

**Comment by janagombitova** [comment]
👍  passes test plan. Ready to go
