### ISSUE TITLE
Saved forms disappear

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#738]
Users have reported saved form answers disappearing after some time.

User Story: The first time the enumerator did was only save, but not submit. And then the second time he visited, the data from the saved form was gone, so he has to restart. This second time it was then submitted

**Comment by janagombitova** [comment]
Hi @valllllll2000, so as we agreed I have tried a few odd tests cases. I will share them below with the results so we can keep track of things. For each case I made sure I have the form saved with some answers to it. 

**Saving a form, syncing in other points** 
- saved form shows as well as the answers 

**Saving a form, reloading all surveys**
- forms still show on the device as well as answers 

**Saving a form, removing the answers from the form** 
- saved a form and then clicked on Clear - the confirmation asked me if I am sure I want to clear the responses and I confirmed
- all answers were gone 
- clicked on the arrow back 
- form still shows in the History list 
- clicked on the arrow back to the list of data points and data point shows the status of synced 
- opened up the data point again and the previously saved empty form is gone 

TO DO: make sure the form does not show, if I clear all and there are no answers, in the list

**Editing the saved form and syncing it to the device, while data collection is going on** 
We thought what if, the user saved the form but someone made a change to the form version that was then re-synced to the device. 

A) Deleted an option from an existing question
- the new form version synced in properly
- the saved form shows the new version and its changes 
- the deleted option is gone 
- answers still show in the form (also in repeated groups) 

B) Deleted an entire question 
(I had to delete the existing answers for the question)
- the new form version synced in properly
- the saved form shows the new version and its changes 
- the deleted question is gone 
- answers that were only saved still show 

**Adding a translation to the saved form** 

A) Survey does NOT have the problematic option questions with no options 
- form syncs properly 
- saved form is shown, also the answers, but the form version is still the old number (not v4 but v3) 
- when in the saved form I selected the new language (so the version number update is a small glitch), the translation loads and answers remain  

B) Survey has the problematic questions with no options 
- form syncs properly
- form is show
- I also tried changing the language when filling in a form 
- after changing the languages, Flow crashes as expected
- the form is saved, the answers show  

**updating the Android version with having a saved form on the device** 
- form is still saved and answers show

I am running out of ideas a bit on how to reproduce the problem...

**Comment by valllllll2000** [comment]
@janagombitova I have created a separated issue for the problem you found https://github.com/akvo/akvo-flow-mobile/issues/742

**Comment by valllllll2000** [comment]
**Data failing to be saved**
I have reproduced the following: 
* A survey with text question (used as datapoint name) and geolocation question. If I fill only the text question, it gets saved fine. If I only edit the geoquestion then I the altitude is not being saved when pressing back. A

**Comment by janagombitova** [comment]
Created via Reamaze:

Link: https://flowhelp.reamaze.com/admin/conversations/ichns-data-collection-update

**Comment by janagombitova** [comment]
@valllllll2000 I think we can close this issue? All the above ones are resolved and we have not heard any info form the partner with more details.
