### ISSUE TITLE
After removing form answers, the datapoint still shows if the back button is pressed

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#742]
**Saving a form, removing the answers from the form**

Saved a form and then clicked on Clear - the confirmation asked me if I am sure I want to clear the responses and I confirmed
all answers were gone
clicked on the arrow back
form still shows in the History list
TO DO: After the form is cleared, pressing back should remove the entry also from the responses tab (RecordActivity)

**Comment by valllllll2000** [comment]
## Test plan
Requirements: assigned to device, monitored survey with one registration form and another form. Device connected to wifi or mobile network (with mobile sync enabled in this case).
Create 1 datapoint and fill registration form and submit.
For the same datapoint submit answers or the other form.
For the same datapoint start filling some answers for the other form but do not submit.
Press back and see that in the responses tab now contains 3 entries, one of them in saved state.
Press the saved one and open it.
In the menu option select "Clear" and then confirm. Answers will be deleted.
Press back.
You should now see only 2 entries in the response tab, both of them synced (green).

**Comment by janagombitova** [comment]
all good 👍
