### ISSUE TITLE
Empty geoshapes allowed

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#745]
For mandatory geoshapes questions, if you do not provide any geoshape but just press save, you still get the message:
"shape captured sucessfully" but there is not geoshape. Shall we show error? Are empty geoshapes allowed? @janagombitova what do you think?

**Comment by janagombitova** [comment]
Empty goeshapes should not be allowed. It can cause unneeded confusion and also issues with the export of shapes. 

It is good that the user can open the geoshape editor and go back, using the navigation arrow. But saving should not be enabled, if not at least one point is added to the map. I agree.  

How would you go about the validation? At least one point needs to be added or also validate depending on the shape type (as polygons should have at least 3 points and lines at least 2)?

**Comment by valllllll2000** [comment]
@janagombitova I am not sure yet but what you are suggesting seems reasonable. I know the drawing of shapes does not work until you select the kind of shape you want, so we can follow your logic afterwards.

**Comment by valllllll2000** [comment]
## Test plan
Add a geoshape question to a survey. Try filling a shape. You should see that if there is not at least one point in the map, save is hidden. Try playing around and adding shapes/lines... make sure save is enabled/shown when there is at least one point. Make sure save is hidden when all points are deleted
