### ISSUE TITLE
Geolocation manually edited text fields do not get properly saved for unsubmitted forms

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#747]
Steps to reproduce:
Create a survey with geolocation question
create a datapoint and fill the fields manually.
If you fill lat/lon/altitude -> only lat and lon get saved.
If you fill lat and lon nothing gets saved

**Comment by valllllll2000** [comment]
## Test plan
Create a geolocation question 
start filling fields manually: you need to file at least lat and lon otherwise the values will not be saved.

Make sure all 3 values are properly saved.
After submitting check that the datapoint is displayed correctly the location data.
Make sure synced datapoints filled on other devices and make sure the geolocation is displayed correctly.

**Comment by janagombitova** [comment]
👍  all good.
