### ISSUE TITLE
Signature question not properly saved in unsubmitted forms

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#748]
**Steps to reproduce**
Create survey with signature question.
Fill the form by also adding the "signed by" text field but do not submit
Press back and see the datapoint has been created
Go back to the datapoint: you will be able to view the signature image but the "signed by" field will be empty.

**Comment by valllllll2000** [comment]
## Test plan:
Create a signature question. When filling the form:
* make sure both name and image are saved
* view saved form
* try clearing saved form, check everything is deleted correctly
* make sure that correctly submitted and can be viewed in read only mode.

**Comment by janagombitova** [comment]
👍  ready to go
