### ISSUE TITLE
Manually entered barcode does not get saved for unsubmitted forms

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#749]
Steps to reproduce
Create a barcode question survey
Fill out the form by inputting the value manually
Go back: datapoint will be gone if that was the only question you filled

**Comment by valllllll2000** [comment]
## Test plan
Create at least 4 barcode question types:
1. Multiple entry 
2. Multiple entry disable manual input
3. Single entry 
4. Single entry manual input disabled

**Comment by janagombitova** [comment]
👍  works like a charm, well done
