### ISSUE TITLE
On some old devices, error messages have white text over white background

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#750]
This makes them unreadable.
See screenshot:
![issue_error message_white](https://user-images.githubusercontent.com/923280/26866177-49c3c0de-4b60-11e7-9b5a-25bc74c5aa33.jpg)
This happens in test version 2.3.4 but also in 2.3.2. 
Reproduced on my experia with android 2.3.7 and also on Jana's old Samsung device

**Comment by valllllll2000** [comment]
## Test plan
Please test on device with android 2.3 and also a more recent device
1) Create a form with at least one mandatory question. Go to the "submit" tab. Go back to the form tab. You will see "red" circle for empty question. Touch the red circle and you should see the error message.
2) Create a double entry text question, enter 2 diferent values, make sure error is displayed correctly
3) In geo question, try entering a longitude with 4 digits or more, you should see an error message

**Comment by janagombitova** [comment]
👍  all visible now. ready to go
