### ISSUE TITLE
Signature question view design

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#751]
While working on #748 I realized that the name cannot be entered together with the signature which may seem a bit confusing and also the name being underneath the button, it is easy to forget adding it. This little issue contributes to the fact that if the form is saved, only the signature is saved, not the name.  I will attempt to add the possibility to write the name underneath the signature so it will be saved at the same time.

**Comment by valllllll2000** [comment]
Here are the 2 options:
![screenshot_20170607-113138](https://user-images.githubusercontent.com/923280/26872831-3c08b3d8-4b78-11e7-9d1d-ff2f9a1d4fda.png)
![screenshot_20170607-114112](https://user-images.githubusercontent.com/923280/26872841-42ad9064-4b78-11e7-9d80-424ef81759e0.png)

**Comment by valllllll2000** [comment]
and this is how one of them would look like on an old device:
![screenshot_2017-06-07_1153](https://user-images.githubusercontent.com/923280/26872868-57cd1d52-4b78-11e7-9118-5e96b0d0c368.png)

**Comment by valllllll2000** [comment]
and this is how it would look like in the form view:
![screenshot_20170607-120528](https://user-images.githubusercontent.com/923280/26873345-cdafcc4e-4b79-11e7-9fc8-fd7b51de4733.png)

I would make name input not editable in this view. Instead once there is a signature I would change the button text to "edit signature" so user can go there and change the name. What do you think @janagombitova?

**Comment by janagombitova** [comment]
That looks great and can definitely work, not taking away too much space from the signature canvas. I would go with the view where the name input field is in its own line and the descriptive text under it. 

To your second comment: brilliant! Good that you moved the name field above the button. I agree it should only be editable in the separate signature page. And yes changing the button to edit (if a signature) is added it a smart move

Why is the canvas in your last screen shot showing the signature image so small? Previously it was full screen width

How would the validation work? Can I move away from the editor page if I have one of the two (image or name) added?

**Comment by valllllll2000** [comment]
@janagombitova 

> Why is the canvas in your last screen shot showing the signature image so small? Previously it was full screen width
This has always been like this, as this is the view that just displays the signature, not the one where you can draw.

**Comment by janagombitova** [comment]
I thought it was show till the full screen, but I see now on my phone the same. Must have been my mistake.

**Comment by valllllll2000** [comment]
> How would the validation work? Can I move away from the editor page if I have one of the two (image or name) added?

I think we can disable the save button until the name has not been written and at least something drawn (it is harder to detect the drawing but as long as he draws a dot we can enable the save button).

**Comment by valllllll2000** [comment]
## Test plan
Add a signature question and try filling it. Make sure you can submit and save the question. After saving the question go back to it and make sure all data is there.

**Comment by janagombitova** [comment]
All works well, but I have a few comments to how it looks. 

![screenshot_2017-06-19-08-24-52](https://user-images.githubusercontent.com/12456965/27272203-4e193b74-54c9-11e7-867d-cb75ff6d82ec.png)

This is the signature question on the device. I was trying to type in the name, after which I realised I need to click on the button first. Would it be possible to hide the name field in the beginning? So the user will only see the `ADD SIGNATURE` button, and then once she saves the signature in the editor, she will see both the image and the text field with "Signed by:"

<img width="1073" alt="screen shot 2017-06-19 at 08 30 56" src="https://user-images.githubusercontent.com/12456965/27272279-b1d5c38a-54c9-11e7-9b92-8d9a32cbe3e0.png">

Can you change from `Modify signature` to `Edit signature`? We do not use the word modify in Flow and our users are more familiar with edit. 

Another thing, if I decide to make changes to my saved signature and I open the editor, I do not see the saved signature image nor name, so I do not know what I am editing. I might want to only fix a type in the name, or re-draw the image. Can this be adjusted? So if I hit the button I see what is saved?

**Comment by valllllll2000** [comment]
@janagombitova I have addressed the issues you mention in your comment

**Comment by janagombitova** [comment]
@valllllll2000 the UI looks great! 

But I found an issue: 
1. I create a signature, draw the signature (save is grey) and type in the name (save becomes enabled) 
2. I save the signature 
3. I click to edit signature 
4. I add a bit of more text to the name and save does **not** become enabled 

Save only gets enabled if I clear the image and redraw it. But any changes made to the text do not trigger the save to be enabled again

**Comment by janagombitova** [comment]
@valllllll2000 I think it is all good now. I do not mind that the `save` button is enabled at all times when editing the signature. It is not restrictive and works well. We are ready to go

This overall change, is a subtle but really good improvement. I like it!
