### ISSUE TITLE
Search - no results found

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#752]
When the user searches for a data point we show the matching results based on her search. But when se types in something that does not match any of the data points, we do not tell her anything. This can be unclear to some of our users. 

![screen shot 2017-06-07 at 12 27 16](https://user-images.githubusercontent.com/12456965/26875283-72817324-4b81-11e7-8a6f-7a275b9d1c7a.png)

A common patter in to show under the search field "No results found" to tell our user what is happening with her search. 

What do you think? 

Secondly, is it needed to have the Flow icon in the search field? In the image below is how it looks like on the app currently and what the Google material design shows. Its our choice on what to do

![screen shot 2017-06-07 at 12 27 25](https://user-images.githubusercontent.com/12456965/26875282-6ec42a9c-4b81-11e7-9c33-6c3c81faed13.png)

**Comment by valllllll2000** [comment]
@janagombitova 
1) I think we should remove the app icon and replace it with the "back" navigation arrow like in gmail, see screenshot:
![screenshot_20170623-085959](https://user-images.githubusercontent.com/923280/27470096-8488d468-57f2-11e7-9c75-e7e48a75ed13.png)
2) As for when there are no search results I would definitely display the error message: "No results found" in red

**Comment by valllllll2000** [comment]
After discussing with @janagombitova we have decided the following:
+ Search will only be available in the list tab, not in the map
+ Once we confirm the search (enter button in the keyboard), the displayed datapoints list will be filtered and only the datapoints that match the query will show
+ If no datapoints match the query, the message "No results found" will be shown
+ When in searched results screen, pressing back will return us to the "full" non filtered list.

**Comment by valllllll2000** [comment]
Initial view
![screenshot_1498748307](https://user-images.githubusercontent.com/923280/27729081-aef53c2c-5d84-11e7-8e4f-519ea99c82e5.png)

Search button 
![screenshot_1498808591](https://user-images.githubusercontent.com/923280/27729093-b857b07e-5d84-11e7-9035-7b826634e846.png)

**Comment by janagombitova** [comment]
@valllllll2000 I have a question about the view (2nd and 3rd screen shot shared in you last comment) when you start searching for a data point. Do I understand it correctly, that if I type in "2" the list of data points will filter out to show me only those with "2" in their name, but I will also see a list of possible results under the search bar? 

The fact that the search bar has to be in view is ok, if you can make sure the icon matches the style of other icons in Flow. 

If we should add an image to the error screen, I think yes. I like the general one with the magnifying "search" glass. What do you think?

**Comment by valllllll2000** [comment]
@janagombitova the search suggestion (the white list below the search) will work exactly the same way as now. Only if you actually press "search" will we get the filtered list (same content as in the white list) depending on what we put in the search text field. Once we press search the full list will be filtered out and only results that match the searched term will be displayed. If you press back then it will go back to the normal list.

**Comment by janagombitova** [comment]
@valllllll2000 ok. That sounds good. We can give it a try

**Comment by valllllll2000** [comment]
Latest screenshots (after discussing it with @janagombitova we have deviced to remove the white popup as it was a duplication)
![screenshot_20171017-154536](https://user-images.githubusercontent.com/923280/31670282-8981c5a4-b357-11e7-82f5-11971e37c276.png)

![screenshot_20171017-154526](https://user-images.githubusercontent.com/923280/31670274-8687167e-b357-11e7-899f-4c2c1515f496.png)

No results:
![screenshot_20171017-154503](https://user-images.githubusercontent.com/923280/31670269-82e07272-b357-11e7-879b-8c20bf4007a6.png)

**Comment by valllllll2000** [comment]
## Test plan:
Sync or create some datapoints
Try searching for an existing datapoint by name or id
Try searching for non existing datapoint, you should get error
After exiting search, make sure all datapoints are shown again
Make sure the map does not allow search

**Comment by janagombitova** [comment]
Hey. I have found one little issue with the No results found page. When I search for the first time and I type in a combination that does not match any data point (name or ID) I do not get the No results found page but the one below. After searching more I get the correct No results found page. 

This issue happens to me every time I search on a list for the 1st time. Then it goes ok. 

![screenshot_2017-10-23-12-30-57](https://user-images.githubusercontent.com/12456965/31884677-39d23fc0-b7ee-11e7-9191-ab40eb160ace.png)

Secondly. regarding the No results found page. I like the addition of a visual icon. Would the search icon not be a better representation? What do you think?  
![screenshot_2017-10-23-12-32-30](https://user-images.githubusercontent.com/12456965/31884749-72edee12-b7ee-11e7-9fcf-54e331f118a4.png)

All the other workflows work well - filtering the lists, selecting the chosen one, etc.

**Comment by janagombitova** [comment]
👍  works like a charm. Nicely done

**Comment by janagombitova** [comment]
Actually noticed this odd behaviour: When I search for a combination from the data point ID on my Samsung device the search works ok, but on the Samsung table it does not find anything matching and says no results found. Odd, right? But if I search for something the data point ID starts with then it finds the point. 

For example: Data point has the ID - tyh7-7pby-dr2m
- if I search for "ty" --> it finds the point 
- if I search for "7" --> it does not find the point 
- if I search for "7p" --> no find 

But if I search for something in the data point name (but the point name does not necessarily start with what I am searching for, then it works ok and finds the points

**Comment by janagombitova** [comment]
Perfect! all tested and works well. We are ready to go
