### ISSUE TITLE
Cookstoves and biogas app styling

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#759]
- [ ] Biogas and cookstoves used to have a blue toolbar but after the toolbar changes #668, their toolbar is now the same as for the rest of the flavours. 

- [ ] The background color and styling has to be checked to match the previous values

**Comment by valllllll2000** [comment]
This is how they are supposed to look:
![1497352095327](https://user-images.githubusercontent.com/923280/27082733-2ef6081c-5046-11e7-9397-71b8f0de9b9e.jpg)

**Comment by janagombitova** [comment]
@valllllll2000 do you need to deploy the apk separately? if so, then I am ready to test these now.

**Comment by valllllll2000** [comment]
@janagombitova I will bu this is not merged yet, I still need to fix one minor detail and will make the PR

**Comment by valllllll2000** [comment]
## Test plan
I need to deploy a special build for this one for both Biogas and Cookstoves
To test just make sure the app stayling matches the correct styling for SNV, especially the toolbar

**Comment by janagombitova** [comment]
Biogas app works and looks well 👍
