### ISSUE TITLE
Update translations 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#762]
The Flow app is available in: Bahasa Indonesia, English, Spanish, French, Hindi, Khmer, Portuguese, Vietnamese and Nepali

French, Spanish and Portuguese (thanks @valllllll2000) are not fully updated. Can you please make sure that they are updated in the app build as well? Thanks. 

The remaining languages are still a work in progress.

**Comment by valllllll2000** [comment]
## Test plan
Here strings have been updated mostly for Portuguese, Spanish and French so just play around with the app and see if everything works in these languages.

**Comment by janagombitova** [comment]
All good. If I spoke any of the three I could test more, but the app works as it should
