### ISSUE TITLE
SurveyedLocale name should be sent for monitoring forms

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow-mobile#766]
akvo/akvo-flow#1762
Partners have been having problems with names not showing up in the export files. They are also missing in the database; for SurveyInstance entites, the surveyedLocaleDisplayName field is null for those originating from a monitoring survey. This turns out to be because no META_NAME item is submitted for those surveys.

When a Survey/"form" is submitted for a previously registered SurveyedLocale/"data point", the META_NAME and META_GEO items from that SL should be included, not just the identifier.

**Comment by valllllll2000** [comment]
@stellanl, here is an example of json file for monitored survey, submitted from my device:
`{"dataPointId":"1p9r-4wat-7jn0","deviceId":"valeria_experia","uuid":"cc2879c0-635b-4100-8672-939440663b5e","email":null,"formId":"140119116","responses":[{"answerType":"META_NAME","iteration":0,"questionId":"-1","value":"test - 5"},{"answerType":"META_GEO","iteration":0,"questionId":"-2","value":"6|6|5|rkahilc"},{"answerType":"VALUE","iteration":0,"questionId":"138369117","value":"5"},{"answerType":"IMAGE","iteration":0,"questionId":"140289115","value":"{\"filename\":\"/mnt/sdcard/akvoflow/data/media/8338644d-d683-4b6b-8c73-6b5f471efb57.jpg\",\"location\":null}"},{"answerType":"VALUE","iteration":0,"questionId":"143149115","value":"ghh"},{"answerType":"OPTION","iteration":0,"questionId":"143999115","value":"[{\"text\":\"yes\"}]"},{"answerType":"VALUE","iteration":0,"questionId":"145559116","value":"test"},{"answerType":"GEO","iteration":0,"questionId":"145679117","value":"6|6|5|rkahilc"},{"answerType":"VALUE","iteration":0,"questionId":"146669116","value":"hhh"},{"answerType":"VALUE","iteration":0,"questionId":"146669117","value":"{\"features\":[],\"type\":\"FeatureCollection\"}"},{"answerType":"VALUE","iteration":0,"questionId":"147499115","value":"hhjj"}],"username":"valeria_experia","submissionDate":1497599648112,"duration":38}`
As you can see META_NAME and META_GEO are both present, could you please clarify where they are missing?

**Comment by valllllll2000** [comment]
It has been decided to hold off on this change for now.
