### ISSUE TITLE
Screen rotation by point lists shows wrong points

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#767]
@valllllll2000 I am copying here the description of the issue made by @guneetnarula 

**The problem**
When we are viewing the data points screen of a selected survey and the 
screen rotates, the list of data points is replaced by the list of data 
points of a different survey available in the application. I'll 
elaborate a bit more so you can try to recreate it:

- Say a device has to surveys: S1 and S2 
- Let's say we tap on S2 and there are two data points named: S2D1, S2D2 
- If we rotate the screen from portrait to landscape and back, 
everything looks fine. 
- Now we tap on S1 from the left-side menu and view the data point list, 
say: S1D1, S1D2, S1D3 
- If we rotate the screen now to landscape, the data point list is 
suddenly replaced with S2 data points, namely: S2D1 and S2D2. 
- Going back to portrait does not fix this. Therefore, in S1 we are now 
seeing data points from S2. 
- If I tap on an data point like S2D1 now, it will show a blank, but 
locked, form for S2. 
- To fix it, I have to switch to S2 and then come back to S1. 
- If we rotate again, the problem will happen again. 
- The choice of the first survey we opened does not affect this at all.

The app version we are using is 2.3.4. I tried to recreate this on a 
different device connected to a different dashboard, and I found the 
same problem. In fact it happened on version 2.3.3 as well. The android 
versions in all these devices is not at all consistent. Some are 
Lollipop, some Marsh-mellow.

**Comment by janagombitova** [comment]
Created via Reamaze:

Link: https://flowhelp.reamaze.com/admin/conversations/bug-found-in-app-screen-rotation

**Comment by janagombitova** [comment]
@valllllll2000 I confirm that we have troubles with the screen rotation in the data point list. What happened to me was that after rotating my points were gone fully from the screen.

**Comment by valllllll2000** [comment]
## Test plan
Create 2 surveys: survey 1 and survey 2 with one text question each and make them datapoint names so you can follow datapoints better.
Create one datapoint in each survey, for example datapoint survey 1 and datapoint survey 2.
select survey 1, make sure the correct datapoint is displayed
select survey 2, make sure correct datapoint is displayed
rotate device, make sure survey 2 is still selected and the correct datapoint for survey 2 is displayed. Make sure in the navigation drawer the survey 2 is highlighted. 
Press home and then reopen the app. Make sure the survey 2 is still displayed with its datapoint.

**Comment by janagombitova** [comment]
Works like a charm
