### ISSUE TITLE
Survey menu changes proposal

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#770]
As described in this issue, https://github.com/akvo/akvo-flow-mobile/issues/669 we will move the "+" menu item to using a FAB button. In that case, its previous "spot" will be left free and hence we could move another entry there so the candidates are:
- search
- sort
- stats
- sync -> that one is only there for monitored surveys
- nothing (we leave things as now)

I would say "search" is a good candidate or "sync".

As @janagombitova mentions in the comment we would in this case need to get an icon for that action.
@Kiarii or @loicsans your design opinion will be highly appreciated. In order to clarify the issue here is how we have it now:
![screenshot_2017-04-21-11-46-49](https://cloud.githubusercontent.com/assets/12456965/25272524/835bdf4a-2688-11e7-8a91-11ac794877d2.png)

in the issue #669, the look will become:
![screenshot_1497628159](https://user-images.githubusercontent.com/923280/27234098-273b460a-52bc-11e7-8be6-2f8943ecf384.png)

One alternative could be to have it like this, with the search icon:
![screenshot_1497628311](https://user-images.githubusercontent.com/923280/27234221-85b90244-52bc-11e7-9611-8b0e83f3a174.png)

**Comment by Kiarii** [comment]
I had a chat with @Loic on this one, we thought that the mostly used action should take the place of the [+]; and in so doing would somewhat simplify its workflow. Do we have some flow app usage stats or some user feedback on the frequency of use of those candidate actions?

**Comment by valllllll2000** [comment]
@Kiarii that is a good point, I do not have these statistics though, maybe @janagombitova has. If not we may first collect some statistics but we would need some development for that, which would take time and would require releasing the version with statistics first and then collect the info. It would also require some "backend" to collect the data or maybe use some kind of SDK.

**Comment by valllllll2000** [comment]
We have had to add "Search" as the visible option so this is no longer relevant
