### ISSUE TITLE
About page access

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#771]
The about page has been modified #595  but we also need to decide about the access to it and how to explain what it is.

- [x] Here is how it looks now (inside Settings):
![screenshot_1497858396](https://user-images.githubusercontent.com/923280/27274633-6b828570-54d4-11e7-8779-147a8efdebe4.png)

As @janagombitova commented on the other issue, this is not so clear. 

I do not know which would be the best naming for this entry, have nothing better that "about" or "about us".
This is what is contains:
- App name, version, copyright
- Possibility to update
- Release notes
- Legal info
- Terms of use

- [x] Also, I we agreed to move "About" out of settings to the hamburger menu see #501.

**Comment by janagombitova** [comment]
@valllllll2000 after looking at the Android material designs and some other apps out there I feel more confused than clear on what the best option is :) 

We both agree that the "About" should not be part of the Settings menu and this is also recommended in the material guidelines. Lets let's bring it to the hamburger menu under Settings. 

I would not change the label for now, as "About" is descriptive enough. 

The confusion I have is: we currently have a lot of items in the About page, following the Caddisfly app example. Some material design articles suggest to have a "Help" page that contains About page; Terms of service (currently in our About page); Privacy policy; Version info; link to Help page; Contact us as separate items under Help. Some have Help separately with links to the support page and to option how to contact us and About separately with the other items. 

So we could: 
1) Have the Settings and About in the hamburger menu and make no further changes 
2) Have Settings and About but break the About to more items: Version (would be the current page without the link mentioned next); Legal information; Terms of use
3) some other way

@valllllll2000 what do you think?

**Comment by valllllll2000** [comment]
@janagombitova I looked at other apps and maybe we could call About "app info", because about is not very precise. I agree to move about the the hamburger menu.
As for Legal info and Terms of use we could either leave them inside about screen as links now or maybe have them as menu items inside the about page. If we ever have a help screen, then we could add terms and legal to that screen as menu items.

**Comment by janagombitova** [comment]
@valllllll2000 I would leave it to "About" as it is a commonly used item across other Android apps and also the current name of the page, so we do not cause more confusion. Let's leave the legal info and Term of us in it for now.

**Comment by valllllll2000** [comment]
So to sum-up, this task is about:

- [ ] Move About entry out of settings
- [ ] Add About entry to Hamburger menu

**Comment by janagombitova** [comment]
About opens up nicely in the hamburger menu and works as expected 👍
