### ISSUE TITLE
Release information missing in sentry after moving to the new SDK

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#777]
https://sentry.io/akvo-foundation/flow-android/releases/

Since raven-java the release info seems to be mssing

**Comment by valllllll2000** [comment]
## Test plan
This does not really affect the way the app works, not the sending of the crashes, just an extra info which is nice to have in sentry.

**Comment by janagombitova** [comment]
If there is nothing I can test here, then we are ready to go 👍
