### ISSUE TITLE
New screen for when no survey is selected 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#783]
![screenshot_2017-06-26-13-47-13](https://user-images.githubusercontent.com/12456965/27543160-acbeb44a-5a89-11e7-8819-6c272704e3ad.png)

This is the screen that our users very seldom see, but can use some love and improvements. It is shown if the user installs the app (or deletes everything) and has not selected a survey yet to start collecting data. The goal of the screen is to bring the user to the menu navigation drawer on the left and select a survey. 

We should look at the improvements made on the empty data point screen to see if we can improve this one as well

**Comment by valllllll2000** [comment]
After the refactor work for the datapoints #583, this is how this screen will look like:
![screenshot_1499250095](https://user-images.githubusercontent.com/923280/27948210-3f673caa-62f9-11e7-88d8-7f84c537ce35.png)

**Comment by janagombitova** [comment]
@valllllll2000 could you make the text larger getting it centered and on two lines?

**Comment by janagombitova** [comment]
As mentioned in the comment above, the issue is resoled with the 2.4.0 refactor release. Closing the issue
