### ISSUE TITLE
Capturing multiple barcode scans 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#786]
![screenshot_2017-06-26-16-20-21](https://user-images.githubusercontent.com/12456965/27572727-dfd32224-5b0d-11e7-9635-620c1dcfd5ee.png)

Users can sometimes capture more than one barcode scan per question. They can do this manually or using an app. The little plus icon opens up a new line for the code. The trash can icon removes the captured barcode. 

Currently you: 
1. scan in the code 
1. hit plus (saves the last scan and opens a line for a new scan)
1. scan in the code
1. hit plus (saves the last scan and opens a line for a new scan)

The user has to hit plus in order for her last scan to be saved. Is she does not hit the plus icon, the typed in value is not saved. To me it is strange that I have to hit `plus` to save my last scan even though I am not going to add a following scan.

@Kiarii @valllllll2000 what do you both think?

**Comment by valllllll2000** [comment]
I agree, this is odd, maybe we can replace the + by a tick like save:
![ic_done_black_24dp](https://user-images.githubusercontent.com/923280/27575543-871cab0c-5b1a-11e7-917d-f0f3c597f1a0.png)

**Comment by janagombitova** [comment]
We have two cases: input of the code via a scanner app or manual entry. 

The **via app** option works well, because if the user can scan more than one code per question, she always clicks on the button. And once the app has done its scanning it automatically opens Flow app and the entry is there in a new line. 

![screenshot_2017-06-27-08-46-14](https://user-images.githubusercontent.com/12456965/27576784-859e2482-5b1e-11e7-8477-d2b2f423ac73.png)

The oddness is with **manual input** that is not so commonly used, but still we can make it better. Here the user can either type in the code (there is a line given) or hit the scanner button. When typing in the user types in her code and then has to hit the plus icon to confirm (and save) her code and also to create a new line to type in another code. 

Let's see if we can think of a better way for manual input of multiple barcode scans.

**Comment by Kiarii** [comment]
Are the multiple barcodes part of a repeat question group (by themselves)? it is hard to get the context in which multiple barcodes can be scanned as responses to a single question..

**Comment by valllllll2000** [comment]
@Kiarii this is not repeatable question groups. It is just a question where you can enter multiple barcode scans, I do not know how this can be useful or why would we not use 2 separate questions but they are allowed in the dashboard so I have to support them in the app.

**Comment by Kiarii** [comment]
@valllllll2000 thanks for the reply; do you have a concrete example from a survey, that might help..

**Comment by valllllll2000** [comment]
@Kiarii on uat1-> Surveys -> Valeria Test -> saved questions issues 

aved questions issues  is the name of the survey which has multiple barcode scanner questions with all the possible combinations: multiple, single, manual edit allowed/not allowed

**Comment by janagombitova** [comment]
@valllllll2000 have been thinking about this one the last two days and I think we can try out your suggestion with the tick image

![ic_done_black_24dp](https://user-images.githubusercontent.com/923280/27575543-871cab0c-5b1a-11e7-917d-f0f3c597f1a0.png)

it implies you want to save the barcode and Flow automatically gives you another new line to add another scan if you want so the "plus" (of adding another scan) is handled by Flow.
