### ISSUE TITLE
Simplify delete dialogues in geoshape editor 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#787]
There are two delete actions in the geoshape editor: 
- deleting a point 
- deleting the entire geoshape

## Deleting a point 

When creating a geoshape the user can add points that then form the shape. She can also delete a point if she is not happy with its location on the map. This is the dialogue we show when she selects a point to be deleted: 

![screenshot_2017-06-27-12-30-03](https://user-images.githubusercontent.com/12456965/27583749-b7f5cacc-5b35-11e7-9bcc-07c9a98c23e0.png)

This dialogue has an unneeded header and is unnecessarily too long. Let's go with the common and simplified:

Delete point?
Cancel
Delete

## Deleting the entire geoshape

The user can also fully delete the shape created. 

![screenshot_2017-06-27-08-27-55](https://user-images.githubusercontent.com/12456965/27583142-c01daa46-5b33-11e7-8566-feefa971ac49.png)

"Delete feature. Do you want to remove this feature? Cancel. OK" 

This current dialogue is confusing due to the word "feature". We do not use it in this context and should use the same vocabulary throughout. The button that opens the shape editor states "Capture shape". Perhaps we should use the word "shape" instead: 

Delete shape? 
Cancel 
Delete

**Comment by valllllll2000** [comment]
## Test plan
Try deleting a geoshape and a point and make sure the dialogs are displayed correctly as described above:
* Delete shape?
Cancel
Delete

*Delete point?
Cancel
Delete

**Comment by janagombitova** [comment]
Deletion dialogues are correct. All works as expected as well.
