### ISSUE TITLE
Update Sentry Android SDK

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#789]
The sentry for Android SDK has been updated and modified. We should update and make sure our code works with the newest version:
https://docs.sentry.io/clients/java/modules/android/

Also remove some of these exceptions:
* java.io.EOFException
* Remove the logging of IllegalArgumentException when surveys have been removed from assignment
* java.net.SocketException
* java.io.InterruptedIOException
* java.net.NoRouteToHostException
* okhttp3.internal.http2.StreamResetException

After the update, also review which tags are sent and in some cases add breadcrumbs if needed

**Comment by valllllll2000** [comment]
## Test plan
No manual testing required

**Comment by janagombitova** [comment]
ok 👍
