### ISSUE TITLE
Remove Power management from Settings

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#795]
From your comment here:  https://github.com/akvo/akvo-flow-mobile/issues/501

"Power Management
Location: Settings
Enables or disables wifi to save battery life, is that even useful, most devices (except some old android 2.3) have this at the top of the device screen (the dragable menu from the top of the screen). If we do decide to keep it, we should rename it to just either "enable wifi" or "disable wifi" depending if wifi is currently disabled or enabled, since "Power Management" is not clear at all."

and knowing that our users use the Android setting to enable or disable their wifi, I agree we can remove this feature from the app.

**Comment by valllllll2000** [comment]
## Test plan
Go to settings, make sure the Power management setting is no longer there.

**Comment by janagombitova** [comment]
👍 all ok
