### ISSUE TITLE
Add help section

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#798]
The help section will be accessible from the hamburger menu.
The help will display this page http://flowsupport.akvo.org/container/show/akvo-flow-app.
The help page will be a web view.
If the user is not online we need an error message to display.

**Comment by janagombitova** [comment]
I suggest we have the order of items: 
- Settings 
- About 
- Help 

Indeed we need tell the user he cannot access the Help center due to no network. Would you just go for a message to display after clicking on Help, or a page showing there is no connection after clicking on Help?

**Comment by valllllll2000** [comment]
@janagombitova For the error message I would say we attempt loading and if it fails, display error message on the help screen itself. 
There is on doubt though: what to do with people who disallow loading of data when using mobile networks, we cannot load the page in that case because it requires using data.

**Comment by janagombitova** [comment]
@valllllll2000 for those users we should not load in the page either. We can we use the same pattern as we have with notifications that we state that the failure to load is due to no connection because they have it disabled or we can just use the same error message

**Comment by valllllll2000** [comment]
Here is how it looks so far
* Navigation drawer
![screenshot_1499777938](https://user-images.githubusercontent.com/923280/28069568-3b623084-664a-11e7-9884-7ced2e6984e9.png)

* Normal load
![screenshot_1499778166](https://user-images.githubusercontent.com/923280/28069532-1a50916a-664a-11e7-91b3-5079f8dd2858.png)

* Error data disabled and no wifi
![screenshot_1499777942](https://user-images.githubusercontent.com/923280/28069632-6fa6343a-664a-11e7-99c7-6686e46a119d.png)

* Other error
![screenshot_1499777957](https://user-images.githubusercontent.com/923280/28069626-6808b69e-664a-11e7-8c7a-6d6b2222d054.png)

**Comment by janagombitova** [comment]
Works like a charm on the new devices. On my old dinosaur I however cannot see much on the screen, the behaviour when there is no network is ok though. So it is just how things are shown, see screen shot 

![img_4815](https://user-images.githubusercontent.com/12456965/28814764-363fdeac-769f-11e7-8a7a-dc38ed6fce7e.JPG)

**Comment by valllllll2000** [comment]
@janagombitova I have tried and it works on my old phone although it takes a long time to load. I have created a build with an attempt for a fix (blindly) maybe it will fix the issue. If could you please try to open this link on the browser of the device? http://flowsupport.akvo.org/container/show/akvo-flow-app. How about the links contained in about page, do they load correctly?

**Comment by janagombitova** [comment]
Hey @valllllll2000 

I think I know that the problem is on my old device: If I try the link you shared above using Opera then it loads fine, but if I use the Internet app (default on the phone) I see the same as in Flow's app. Can we conclude the issue it related to my specific device?  

Links in the About page work well if I select the Internet app or the Opera app to open them.

**Comment by valllllll2000** [comment]
@janagombitova Maybe an update to the browser would help but we could also ask whoever maintains the help section to check with http://www.supporthero.io/about/ (it is their tool) to see what is going on and if the had anyone else report this issue.

**Comment by janagombitova** [comment]
That sounds like a good plan. Thus this one is ready for release

**Comment by janagombitova** [comment]
(Y) works like a charm
