### ISSUE TITLE
Display user friendly dashboard url in Settings

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#804]
# Context 
Data server (only change if instructed) is an option in our current Settings -> Preferences on the Flow app. To the user it shows the url the app is linked to. it does not show the url the user is familiar with but the GAE url "akvoflow-xx.appspot.com" 

# Problem or Idea 

@valllllll2000 comment: Backend url, not sure if this is useful since the key still comes from the app so changing this would just break the app.

We refer to this feature when supporting app users who have issues with syncing data or forms. We ask them to tell us the url to cross check if their app is trying to communicate with the right instance. 

If you make any change in the url that causes the url does not point to the correct instance, the app will not work as expected. If you change the url to another instance and do not restart the app, nothing changes. If you change the url to an existing instance and reopen (fully) the app, then you app points to the new instance but I get an error that my Form is not found. 

I do not know if we have cases of one phone used for multiple instances, but I assume we say you need to uninstall and re-install the app to ensure the app will work properly. 

Can we take away this confusing and "dangerous" feature and change it to an info item? I can imagine that in the future an Alphonso can be hired to do data collection for more organisations, but I am not sure how what the current reality is.  

# Solution or next step 
Understand if we have cases of switching to a different instance (one phone being used for more instances):  
- Do you have users who use the Flow app for more than one instance? 
- If yes, how do you tell them to “switch the app”?

**Comment by janagombitova** [comment]
# Feedback (incomplete) 

- We tell users to *not* use this feature completely. We have never had the use case for it

**Do you have users who use the Flow app for more than one instance?** 
- I have not yet encountered this personally, but I had several partners ask me how to switch from one instance to the other if the app download is linked to only 1 specific instance.

**If yes, how do you tell them to “switch the app”?** 
- In my opinion this is an essential feature, it might not happen really often but some partners have 2 instances. It would complicate their work a lot if they have to de-install and re-install the app with another instance if the data collection happens for both instances at the same time.

**Comment by valllllll2000** [comment]
@janagombitova just to be clear: you can change the url but the app will not work because the other settings cannot be changed. So if we do allow changing it, we would have to allow changing all the settings: url, amazon keys and our api key. Allowing all these changes be made by the user is dangerous but would allow us to have just one single app for all instances.

**Comment by janagombitova** [comment]
@valllllll2000 I understand and I think this type of change is for later as from what I know we have minimum of such cases. So the safer option would be for now to remove the option to make a change and just show which instance you are linked to. Right?

**Comment by valllllll2000** [comment]
@janagombitova so in order to display the actual instance name, we do not have that information in the app, we would need to get it from the server config repo so this information should be added to the survey.properties file

**Comment by janagombitova** [comment]
@valllllll2000 would that be a risky change or a large effort? From the feedback we have received, we can conclude that eventually in the future we might need to consider how one user can switch between instance, but not for now. 

However, this information is important in supporting users and ensuring that all works well. To show this info while removing to option to switch instances, would be a good change

**Comment by janagombitova** [comment]
after talking to @valllllll2000 today we agreed we need to add here: https://github.com/akvo/akvo-flow-server-config/edit/master/akvoflow-1/survey.properties another item: `instanceUrl` with the user friendly url first to be able to display it in the app

Example: instanceUrl = https://uat1.akvoflow.org

**Comment by janagombitova** [comment]
I see the url as the users know it. This is great! 👍
