### ISSUE TITLE
Script app/sh/install.sh

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#811]
There is this script app/sh/install.sh, does it make sense to keep it? Investigate what it is used for and remove if no longer used.

https://github.com/akvo/akvo-flow-mobile/blob/develop/app/sh/install.sh

**Comment by valllllll2000** [comment]
## Test plan
Nothing to test here, does not affect code

**Comment by janagombitova** [comment]
👍  then it is ready to go
