### ISSUE TITLE
Add Dutch as a new language for the app

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#812]
Ground Truth is a programme in Belgium where Flow will be used by random citizens in the city of Mechelen to outsource data collection about noise and air pollution in the city. As the programme officers expect that not all people of Mechelen speak English, we have agreed to add Dutch the our language options. 

I will let you know once the translation is complete of Transifex. Akvo staff will maintain the language on long term

**Comment by janagombitova** [comment]
Translations are fully completed

**Comment by valllllll2000** [comment]
## Test plan
The idea would be to run regression tests using the mobile app in Dutch to test the whole app

**Comment by janagombitova** [comment]
@valllllll2000 I have just installed the 2.3.7 version from UAT1 and I do not see Dutch as a language to select in Settings > Preferences

**Comment by valllllll2000** [comment]
@janagombitova sorry, I forgot about that part, so for now if you put your phone in dutch, the app will be automatically in dutch (you have to install it after you set the phone in Dutch). Will make the change now to add the Dutch language in the Settings

**Comment by valllllll2000** [comment]
@janagombitova fixes done and app deployed for testing the fix

**Comment by janagombitova** [comment]
All works well now 👍
