### ISSUE TITLE
Improve UI for syncing in data points - progress spinner 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#822]
With the 2.4.0 version of the app (currently testable on uat1 - not released yet) we have made changes to how we inform users that things are happening in the app, in this case that after Alphonso requested data points submitted to his form to be synced into his device, he sees in his screen a progress spinner that the syncing is happening. Once the syncing is fully completed he gets a snack bar saying that the particular number of points was synced. 

The current indication of progress is a spinner. If Alphonso already has some points submitted to his form and want to sync in new points, the spinner is shown over the list of data points, what does not make it very visible and noticeable. 

The main goal is to let Aplhonso know something is happening. I think we can improve the visibility of the spinner or somehow else show him Flow is working on getting the points in. 

Here is how it looks currently on the 2.4.0 version of the app

<img width="1021" alt="screen shot 2017-08-02 at 13 33 07" src="https://user-images.githubusercontent.com/12456965/28871977-5165f020-7787-11e7-90dd-8f4e967cbd13.png">

@Kiarii @loicsans and @valllllll2000 What do you think?

**Comment by valllllll2000** [comment]
@janagombitova maybe I can change the color for the spinner? In the most recent android phones, it is blue so it is more visible:
![screenshot_20170802-150114](https://user-images.githubusercontent.com/923280/28874778-8fe22eca-7793-11e7-8110-1b9c5168f784.png)

**Comment by Kiarii** [comment]
https://material.io/guidelines/components/progress-activity.html#progress-activity-behavior: seems to suggest that 2 options may apply to the placement of the loading icon; a) Spinner with circular background on top of existing content, b colored spinner above the content 'panel': e.g.

![image](https://user-images.githubusercontent.com/12692444/28911941-dad99010-783a-11e7-96c0-e52bb01e492b.png)

**Comment by janagombitova** [comment]
From a chat with @Kiarii  and @loicsans the following options are: 
- spinner on a circular background overlapping the list
- coloured spinner without a background above the list 

Both options are good, so @valllllll2000 please choose what’s better for you to implement

**Comment by valllllll2000** [comment]
Here is how it looks
old devices:
![screenshot_2017-08-09_1318](https://user-images.githubusercontent.com/923280/29119160-527b9478-7d05-11e7-80a5-c43b492dbe14.png)
new devices:
![screenshot_20170809-131507](https://user-images.githubusercontent.com/923280/29119167-5c116030-7d05-11e7-991c-f7927d403506.png)

**Comment by valllllll2000** [comment]
## Test plan
Select a monitored survey and press sync in the menu. You should see a progress spinner similar to screenshots above.

**Comment by janagombitova** [comment]
All good 👍  ready to go
