### ISSUE TITLE
Portrait photo shown in app UI as landscape

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#832]
User can capture photos as part of their forms. Alphonso can either capture the image in landscape mode, holding the phone horizontally, or as a portrait, holding the phone vertically. The way the images are saved is correct, landscape or portrait but in the app in the phone all images are shown in landscape more, making the portrait images look odd. 

Can we save the portrait images as we do and also show them as portraits in the app? So images captured vertically are also shown vertically

<img width="807" alt="screen shot 2017-08-04 at 17 32 07" src="https://user-images.githubusercontent.com/12456965/28975595-de3305ba-793a-11e7-8464-af5c5bd2c4c8.png">

**Comment by valllllll2000** [comment]
## Test plan
Try viewing picture question view.
Try survey with multiple picture questions.
Important to test on older devices.

**Comment by janagombitova** [comment]
👍  works like a charm
