### ISSUE TITLE
Login screen ui improvements

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#838]
After looking at the login (initial screen), I would suggest these little improvements:
- Display "loading" once user presses "next" button until the screen is dismissed. This little timeout corresponds to the device saving all the data the user input. Most of the time it is very quick but it may be slower on old devices and the user may think nothing is happening
- Next button: maybe it should be "send" or "save". Next make you think there is something else you will have to enter but this is not the case.
- Suggestion: maybe display the dashboard name somewhere? 
- The keyboard covers the biggest part of the screen so on many devices we cannot see the "next" button nor even the second input field. Maybe we could raise the logo a bit towards the top of the screen?

**Comment by janagombitova** [comment]
Great initiative @valllllll2000. Here is my input: 
- loading after pressing "next" - yes 
- next button rename - good point, it does indeed suggest there is more to come. How about "Log in" or "Sign in"? 
- display instance name: I like that idea. We should bring in @loicsans and @Kiarii to hear their thoughts. The idea then is to display the Flow instance url they downloaded the app from and to which the app is linked to right? To make sure Alphonso knows he has the correct app on his phone. In Settings we show the instance info under the to be renamed Instance name
- Logo higher to fit the keyboard - yes, definitely. If you remember we partially solved this problem by allowing to hit next on the keyboard to move forward, but this is a more overarching solution.
