### ISSUE TITLE
Datapoints from wrong survey are sometimes displayed

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#841]
Steps to reproduce:
Sync all the forms with device
Select survey A
Sync datapoints
Select survey B
Sync datapoints
Sometimes at this point you will see datapoints from survey A displayed and not from survey B.
After opening the datapoint and going back, the correct datapoints are shown again.

Reproduce on Jana's Samsung device with Android 4.4.2

**Comment by janagombitova** [comment]
👍  Seems to work ok now
