### ISSUE TITLE
Endless syncing in data points for large survey forms

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#843]
#I have tested syncing in data for an existing survey form for the 2.4.0 version of the app. All worked well, but then I tried a form with 4124 data points. After I presses sync the data started coming in, and showing in the list and on the map, but once I reached 1197 data points (seeing the number on the map and in the Stats) it seems as if no more points are coming in, but the spinner keeps on spinning. 

I can submit new data and work with the app, but I have no way of "stopping" the syncing in or seeing if the data points are still coming in.

**Comment by valllllll2000** [comment]
I was not able to reproduce it.

**Comment by janagombitova** [comment]
Works fine now 👍
