### ISSUE TITLE
More than 1000 datapoints crashes with OOME

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#844]
This is due to using RxJava 1.0 https://github.com/ReactiveX/RxJava/wiki/What%27s-different-in-2.0#functional-interfaces

**Comment by janagombitova** [comment]
I assume testing the app with more than 1000 data points and ensuring all works ok is the key to this issue. Syncing in data points with over 2k points works ok and the rest I will check with the regression round
