### ISSUE TITLE
When deleting collected data selected survey still displays datapoints on map

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#846]
Tested with v2.4.0 of the app.
Steps to reproduce:
Select a survey with datapoints already synced in and shown on map correctly
Go to settings and delete collected data and images
Go back to main screen.
You will see that in the map tab the datapoints are still displayed 
Killing the app and restarting it fixes the issue.

Expected: after deleting collected data we should not see any datapoints

**Comment by valllllll2000** [comment]
This has been fixed while working on another issue
## Test plan
just follow the steps to reproduce

**Comment by janagombitova** [comment]
👍  works as expected. All points removed from list and map
