### ISSUE TITLE
App flickering on certain devices

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#847]
As you can see on the attached gif
![myimage](https://user-images.githubusercontent.com/923280/29553937-9fbc4846-871d-11e7-9bf5-f62abd42b7c7.gif)

This is reproduced on Samsung galaxy tab A, Android 5.1.1 seems to happen every time they open the app on the about us page. Still pending to confirm if it happens also on other screens.

**Comment by janagombitova** [comment]
Here is the feedback from the parter: 

"It happened on two tablets (same kind) when we opened the app. It went to the About Akvo screen on it’s own. We exited and re-entered the app several times and it didn’t stop until I forced stopped the app via the tablets' settings. This occurred only on the two tablets and almost at the same time (it occurred in one a couple minutes before the other). I was using a phone and had no trouble. 

However, on Tuesday (our second training day)  the app on the phone I was using crashed a few times (flickered and then closed by itself). After that I was able to open the app without problem every time."

**Comment by janagombitova** [comment]
@valllllll2000 this is the first time I could reproduce the same "flickering" state. I was collecting new data on the new device and on the tablet. After submitting a form I went to Settings with the idea to change the language when the screen started flickering and I could not press anything in the settings. Once I went back it stopped. Once I went back to settings it started again. I had to Force close the app to make it stop fully.

**Comment by janagombitova** [comment]
Managed to reproduce it consistently over the mobile phone and the tablet, both Samsung: 
1. Go to settings and select a new app language
2. Restart the app 
3. Go to settings again 
4. Rotate the screen 
5. The app should flicker now and you need to force close it to make it stop

**Comment by valllllll2000** [comment]
## Test plan

1. Go to settings and select a new app language
2. Restart the app
3. Go to settings again
4. Rotate the screen
5. The app should NOT flicker now

Repeat steps 3-5 with 
* Going to About screen and rotating
* Going to About -> Legal information and rotate
* Going to help and rotate
* Select a survey with images -> open image in full screen view and rotate

**Comment by janagombitova** [comment]
No more flickering! yay!
