### ISSUE TITLE
Improve the way dashboard configuration is stored/used

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#848]
For now, dashboard specific config has to read from a file constantly from raw folder, it would be better if it is processed in build.gradle and made available trough BuildConfig
https://developer.android.com/studio/build/gradle-tips.html#simplify-app-development

**Comment by valllllll2000** [comment]
## Test plan
Regression tests should detect any issues, nothing to test in particular

**Comment by janagombitova** [comment]
👍  looks good to me
