### ISSUE TITLE
Add leak canary library to debug builds

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#850]
Leak canary is a toll which helps to detect memory leaks
https://github.com/square/leakcanary

**Comment by valllllll2000** [comment]
Thanks to leak canary, I have found the 2 leaks both related to location manager:
`In org.akvo.flow:2.4.4:70.
* org.akvo.flow.activity.SurveyActivity has leaked:
* GC ROOT android.location.LocationManager$ListenerTransport.this$0
* references android.location.LocationManager.mContext
* references android.app.ContextImpl.mOuterContext
* leaks org.akvo.flow.activity.SurveyActivity instance

* Retaining: 2.2 KB.
* Reference Key: 64e12ad2-591c-4a87-bba1-edc93c0d8824
* Device: Sony Sony SGP611 SGP611
* Android Version: 6.0.1 API: 23 LeakCanary: 1.4 6b04880
* Durations: watch=5371ms, gc=150ms, heap dump=5578ms, analysis=44516ms

* Details:
* Instance of android.location.LocationManager$ListenerTransport
|   static TYPE_STATUS_CHANGED = 2
|   static TYPE_PROVIDER_DISABLED = 4
|   static TYPE_PROVIDER_ENABLED = 3
|   static TYPE_LOCATION_CHANGED = 1
|   static $staticOverhead = byte[32]@319379457 (0x13095801)
|   mListener = org.akvo.flow.util.WeakLocationListener@323127712 (0x134289a0)
|   mListenerHandler = android.location.LocationManager$ListenerTransport$1@322996640 (0x134089a0)
|   this$0 = android.location.LocationManager@321985360 (0x13311b50)
|   mDescriptor = java.lang.String@1882641680 (0x7036d510)
|   mObject = -1788632800
|   mOwner = android.location.LocationManager$ListenerTransport@322996544 (0x13408940)
|   shadow$_klass_ = android.location.LocationManager$ListenerTransport
|   shadow$_monitor_ = 0
* Instance of android.location.LocationManager`

**Comment by valllllll2000** [comment]
## Test plan
Create datapoints with location and an image question
Enable location on device
Go to datapoint list and select menu -> sort -> distance. 
Reply to an image and location question. Make sure location is acquired correctly
Bear in mind that in most devices GPS does not work indoors so if you are not outside you will not get a GPS reading.

**Comment by janagombitova** [comment]
Works like a charm 👍
