### ISSUE TITLE
For only monitoring assignments, cannot submit a form if no previous monitoring ones submitted

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#855]
# Context 

If you have a device, where you assign a monitoring survey to, but **not** the registration form these cases happen: 
* the user cannot submit a new data point - this is expected, as we assume you only want the enumerator to fill in monitoring forms 
* the enumerator can open up an existing data point and see the previously submitted monitoring forms (but only those that are assigned to him/her
* the enumerator can open up the data point, but he/she cannot see the previously submitted registration form, as that is not assigned to him/her
* the enumerator can fill in the monitoring forms, if there was at least one monitoring form already submitted to the data point
* if there was only the registration form submitted to the data point and no monitoring form, the user **cannot** submit any forms (no monitoring forms) as they are all greyed out

Sometimes a group of enumerators does the data registration and then a second group of data collectors step in over a course of time. No new data can be registered and only monitoring is to happen. 

**Example on UAT1**

https://uat1.akvoflow.org/admin/ > _1.9.22 and 2.4.0... > Moniotirng testing greyed forms 

I have captured data with different combinations of forms (check the data point name). Some points only have the registration form, some one monitoring form, some multiple monitoring forms. 
- Create an assignment where you do not assign to your device the registration form. 
- Sync in the data. 
- Open a data point called "MF...". You should be able to fill in all the assigned monitoring forms and see the submitted ones in the history tab. 
- Open a data point called "Only RF..." You should not be able to submit any form and the History is empty. 

# Problem

You should be able to submit a monitoring form (if assigned) even if only the registration form has been submitted to the data point.

**Comment by janagombitova** [comment]
Created via Reamaze:

Link: https://flowhelp.reamaze.com/admin/conversations/questionnaires-which-are-freezed-for-some-water-points-in-some-divices

**Comment by valllllll2000** [comment]
## Test plan
Try diferent combinations of registration form being assigned or not assigned to device

**Comment by janagombitova** [comment]
👍  works like a charm. Different combinations on different phones of the same survey, different combinations of different surveys on one device, monitoring and not monitored testes and all works great.

**Comment by janagombitova** [comment]
This does not work anymore in the 2.4.0.1 build

**Comment by valllllll2000** [comment]
I have merged the changes from master, with the next build this issue will be fixed

**Comment by janagombitova** [comment]
Works again as expected in the last build 👍
