### ISSUE TITLE
Travis builds broken after merge of test issue

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#858]
the error is
`The command "echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a -c 2048M" failed and exited with 1 during .`

**Comment by valllllll2000** [comment]
## Test plan
Nothing to test here, it only affects travis builds

**Comment by janagombitova** [comment]
Well if Travis works well then we can consider this one ready to go
