### ISSUE TITLE
Toolbar back navigation is slow to respond on some older devices

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#863]
apply this fix https://www.reddit.com/r/androiddev/comments/2ox3s6/appcompat_toolbar_back_button_functionality_on/

**Comment by janagombitova** [comment]
@valllllll2000 How would you like me to test this one?

**Comment by valllllll2000** [comment]
## Test plan
On an old phone with android 2.3.... test using the arrow in the toolbar to navigate back from another activity: for example from preference or about pages

**Comment by janagombitova** [comment]
My dinosaur phone is quite slow on its own but I did not experience any major issues with the tool bar, so we are ready to go with this fix as well 👍
