### ISSUE TITLE
Investigate the need to give users more info when syncing in many data points 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#872]
# Context 

Multiple users capture data for a form on multiple devices. This form can be part of a monitoring survey what means that besides the registration form other data will be collected to the data points. To share the data across different enumerators, the users sync in data points to their devices, check the already collected information and capture new data. 

With the 2.4.0.1 release we made a change to the UI and UX around syncing in data points. Before we used a notification to tell the user that the syncing is in progress and once it is done. However, this meant that the user had to go out of the app to check on the activity. Now we moved the info into the page in the app and show a spinner when the loading is in progress and a snackbar once syncing is completed with the number of forms synced this. 

<img width="1016" alt="screen shot 2017-09-18 at 10 26 16" src="https://user-images.githubusercontent.com/12456965/30533870-dbc23244-9c5b-11e7-9afe-06449897037f.png">

# Problem or opportunity

The improvement made with the last changes is already much better as it shows the user right away that syncing in data points is happening, you see points coming in and you know once it is done. 

However, we have cases where syncing in data points can take 10 minutes and more (measured around 23 minutes for large monitoring surveys). The question this issue would like to answer is: Is there more improvements we can make to the UX around syncing in data points? Is there more information we can give to the user in the UI, as point count (how many points are in and how many more need to come) in order to let the user know the syncing is in progress and this is what is coming your way?

# Next steps 
@Kiarii  and @loicsans can you take a look at this issue, try it out and share your thought? There is not urgency to this request.

**Comment by valllllll2000** [comment]
From the technical point of view we could inform the user how many datapoints have already come in (maybe add a number inside the spinning wheel) what is more complicated is to count the total number of datapoints as we may get back to the timeout issue we experienced with datapoint sync in the past.

**Comment by Kiarii** [comment]
In cases where we have such long loading times do we intend to keep the spinner on the screen? For long loading times, notifying the user when syncing starts, handling it in the background and notifying them when its done feels natural.. Am not sure android progress and activity controls (spinner, progress bar) when used within the content areas are meant for such long tasks.. A spinner / percentage indicator at the Toolbar could be considered..
