### ISSUE TITLE
Deleted form still shows after re-syncing in data 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#877]
# Context

I have a monitored survey on the device with the data points synced in. The Flow manager (Salim) realises that there was a monitoring form submitted wrongly and deletes it from the online workspace for the correct form to be submitted for the point. However after re-syncing in the points, the monitoring form still shows. 

Sometimes users submit a monitoring form to the wrong point and the data mangers to keep their data correct and clean, fully remove that submission and ask the enumerator to go back again to capture the correct data. 

# Problem
If a user has data points already on her device and only then a monitoring form is deleted, the change does not show after clicking on sync. Here are the steps I took 

1. In the Inspect data tab selected the monitoring form and deleted one submission 
2. Resynced in the data in the app, the submission still shows 
3. Deleted all data from the app using Delete collected data an images option 
4. Synced in the data for the survey again and then the monitoring form was gone

To conclude, to ensure I have the "updated" data set on my device I need to first remove what I had and then sync it all in again. 

The same steps apply for also deleting the registration form of a data point, that does not have any monitoring forms to it) 

# Next steps 

I would expect the changed form (deleted one) to magically disappear from my device, after I hit sync.

**Comment by valllllll2000** [comment]
@janagombitova when you say "sync" does it mean the data point sync?

**Comment by janagombitova** [comment]
By sync I mean syncing in data points. So users use the syncing in data points function not only to get the submitted data in, but also the "refresh" the data - if data cleaning took place or as in this case a form was fully removed. 

So what happens is, I already have data points on my device. Then you deleted a form submission which I mistakenly submitted. Then I hit the sync option to refresh what I have on my phone and I expect to not see the deleted form submission anymore.
