### ISSUE TITLE
Result images from Caddisfly show up in media browser apps

### ISSUE THREAD

**Issue by nhternup** [akvo/akvo-flow-mobile#878]
# Context
The akvoflow 'media' folder items show up in other apps that allow user to browse through media on the phone. (e.g. Gallery app)

# Problem 
The Caddisfly result images appearing in other apps, may be regarded as unnecessary clutter to the user especially since the images don't mean anything without the rest of the test details.

# Next steps 
Either the media folder can be hidden from other apps (using blank .nomedia file) or Caddisfly images could be placed in a separate hidden folder.

# Caveat
Some investigation may need to be done on how offline data collection is done and if hiding the folders would impact that process.

**Comment by valllllll2000** [comment]
The app akvoflow media file is now private and can no longer be viewed by other apps.
