### ISSUE TITLE
Unable to install app 2.4.0.1 on old devices

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#882]
Due to large amount of libraries the app can no longer be installed on old devices with dexopt failed error.

This is a recurring problem and for now will solve it by replacing glide image library (> 3000 methods) by picasso image library (>800 methods).

**Comment by valllllll2000** [comment]
## Test plan
**old devices with android 2.3...**
Try downloading the new version of the app either fresh download or using update

**any device**
Create a survey which has images and signature
Make sure the images and signature are displayed correctly for SYNCED datapoints
Make sure the images and signature are displayed correctly for SAVED datapoints
Make sure the images and signature are displayed correctly for datapoints created on a device

**Comment by janagombitova** [comment]
According to the test plan all works well 👍
