### ISSUE TITLE
Update French translations 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#885]
Hi @valllllll2000 I have contacted all our translators to update the languages the app is translated into, and Abdoulaye was super quick the get French ready. https://www.transifex.com/akvo-foundation/akvo-flow-mobile/dashboard/

Can you add the strings to the app build please? Thanks

**Comment by valllllll2000** [comment]
## Test plan
Regression testing should catch any issue
Test device in French (not all the translations will be available)

**Comment by janagombitova** [comment]
👍  works well on all devices (new ones - I will comment on the old one on this issue https://github.com/akvo/akvo-flow-mobile/issues/882)
