### ISSUE TITLE
Wrong exception throwing when assignment missing

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#895]
Steps to reproduce:
download a form from a monitoring survey which is not assigned to your device
try syncing device
you will see the default failure message "sync failed, please try again" 

expected
the error message should be "Sync failed. Assignment missing."

**Comment by valllllll2000** [comment]
## Test plan
download a form from a monitoring survey which is not assigned to your device
try syncing device
you should see the error message should be "Sync failed. Assignment missing."

**Comment by valllllll2000** [comment]
https://sentry.io/akvo-foundation/flow-android/issues/371199071/

**Comment by valllllll2000** [comment]
https://sentry.io/akvo-foundation/flow-android/issues/365786298/

**Comment by valllllll2000** [comment]
https://sentry.io/akvo-foundation/flow-android/issues/351710648/

**Comment by janagombitova** [comment]
👍  i am getting the correct snack bar for when syncing without an assignment and with an assignment syncing also works. Also when I have no network I get the expected correct message. Ready to go
