### ISSUE TITLE
Missing datapoint history

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#899]
As reported by a partner on reamaze, the responses history is missing in 2.4.0.1 and only answers to repeated question groups are shown.

**Comment by valllllll2000** [comment]
##Test plan
1) Install version 2.3.7.1 
2) Create some datapoints for a monitored survey
3) Make sure they are displayed correctly
4) Install version 2.4.0.1
5) You will see that datapoints history answers are missing
6) Using about us screen update to 2.4.0.2
7) Check that all answers are back
8) Test repeated question groups (multiple combinations: ej 1 repetition and more than one)

**Comment by janagombitova** [comment]
Tested and confirmed all is working well
