### ISSUE TITLE
Improve copy for new update message

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#903]
# Context 

Every time we release and deploy a new version of the Flow app we inform the user via the app directly in a message. The message contains this copy: 

**"A new version of the Flow app is available. Click 'Update' to download and install the new version."**

# Opportunity 
With this issue we want to get the help form the MarComms team to improve this copy. It should be engaging and clear. We might result in not making any changes, based on the input we get.

**Comment by valllllll2000** [comment]
Some suggestions:
* Shorter message: Update flow app to get the lastest features? Update/Cancel
* The dialog itself would benefit from redesign (material design vs currently old looking dialog).
* There are many steps to update: first select update, the app is being downloaded, then user has to confirm again to install and then the system will still ask them to confirm the install. Maybe reduce one step?

**Comment by janagombitova** [comment]
## On the shorter message
Reply from our comms team: 
Copy text: Click 'Update’ to install the new and improved version of the Flow app

What do you think? I am not so excited yet to be honest, but maybe we can think of something together

## Improved design
I agree on improving the design. Do you have anything specific in mind? 

## On showing another dialogue after the user hits Cancel 
I find that too intrusive for me. We should make sure the text is clear and then respect the user's decision, and bug her later of again.

**Comment by valllllll2000** [comment]
* Not sure about the text either as we have title and subtitle. Maybe
Title: New Flow version available
Subtitle: Click 'Update’ to install the latest version of the Flow app 
And maybe, next the subtitle we could add some "?" and if you click, then we till which version the user has and which one is available, eventually what has been fixed.... 

* Design improvements here is an idea:
Current design
![screenshot_20171120-173309](https://user-images.githubusercontent.com/923280/33031727-6239d76a-ce1f-11e7-9679-183bfdaf424c.png)

New design
![screenshot_20171120-181311](https://user-images.githubusercontent.com/923280/33031739-6be825c8-ce1f-11e7-95b6-d48fa64d8389.png)

**Comment by janagombitova** [comment]
- text - spoken with Comms once again, they agreed to your proposed title and here is their suggestion on the text: Update to get the most out of your Flow app
   - Title: New Flow version available
   - Subtitle: Update to get the most out of your Flow app
- design: Yes! Love it! 

I also thought we can do some validation if this brings us more updated app versions, so I thought to keep things simple to check 5 instances (active and of different sizes) how many devices connected last month were running an older version and then compare the numbers in two weeks from the release. Here are the numbers: 

**Devices connected from 1 Nov till 21 Nov 2017** 

instance | with new version | with older version | oldest version out there 
---- | ---- | ---- | ---- 
akvoflow-23 | 101 | 467 | 1.13.8 
wfp | 3 | 81 | 2.1.0 
akvoflow-89 | 77 | 138 | 2.2.10
akvoflow-137 | 6 | 41 | 2.2.10   
akvoflow-39 | 4  | 35 | 2.1.6

**Comment by valllllll2000** [comment]
@janagombitova Nice! Only detail: I would wait much longer to check for how many older devices there are, because only the users who have the latest version will see the dialog once there will be another release available, ie if the new dialog was added in v2.4.2, then users will only start seeing the new dialog when:
1) They already have at least 2.4.2 installed
2) A version > 2.4.2 is available

**Comment by janagombitova** [comment]
Ah good point @valllllll2000 Noted

**Comment by valllllll2000** [comment]
## Test plan
Go to about -> check for updates
The dialog displayed should look like the latest screenshot

**Comment by janagombitova** [comment]
could not actually test because the update message was the old one, but the update worked - so will cross check this next time, however we should be ready to roll 👍
