### ISSUE TITLE
Pre-fill not working 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#904]
# Context 

When monitoring sometime users need to fill in answers over and over again that do not change, due to how the form was set up. Some users use the Pre-fill responses feature in Flow app that takes the answers from a last submitted form and fills them in the newly opened monitoring form. 

# Issue 

Issue was reported via support that the Pre-fill responses does not work since. 2.4.0.1 (and 2.4.0.2). To be honest I have not tested out this feature for a while so I checked the older app build (2.3.7.1) you shared with me last week. It worked on the older build. 

Created via Reamaze:

Link: https://flowhelp.reamaze.com/admin/conversations/pre-fill-responses-function

**Comment by valllllll2000** [comment]
## Test plan
Inside a form use "prefill answers" menu entry. Make sure the answers are displayed correctly.

**Comment by janagombitova** [comment]
Works like a charm. Ready for the release
