### ISSUE TITLE
Inform user when there are no data points to sync in

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#922]
# Context

A few releases ago we changes how we show to users that they are syncing in data points for monitored surveys. Once they hit sync we show the spinning wheel and once all is synced in we say how many points are synced in. 

# Opportunity 

If there are no data points to the survey and the user hits sync, we show the spinning wheel for a second and then it disappears from the screen. We do not tell the user that there is actually nothing to sync in. So she ends up trying to sync, seeing that Flow tried too but nothing happened in the end. 

Shall we tell her that there are no data points for the survey to sync in?

**Comment by valllllll2000** [comment]
@janagombitova my suggestion: display Snackbar with the message: "No new datapoints found" or "No datapoints to sync"

**Comment by janagombitova** [comment]
I like your suggestion: "No datapoints to sync"

**Comment by valllllll2000** [comment]
## Test plan
Find a monitored survey which has no datapoints yet.
Try syncing, you should see "No datapoints to sync" in a snackbar.
This should work from both the datapoints and the map tabs.

**Comment by janagombitova** [comment]
👍  works like a charm, ready to go
