### ISSUE TITLE
Reload all forms (phase 1)

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#923]
For now in Settings we have the option to reload all forms. It behaves differently than when the forms are reloaded upon app restart. Also the dialogs displayed are too long and there are too many steps. In the issue #660 it has been decided that:
1) Reload all will behave the same way as when the app starts, ie we load all new surveys that have been assigned. We do not delete any surveys.
2) We no longer ask for admin passcode for this operation
3) The dialog:
No title only the question: Reload all forms?
Actions: Cancel, Reload
4) Setting title will be **Reload all forms**

**Comment by valllllll2000** [comment]
@janagombitova the subtitle of that entry is currently: "Deletes and re-downloads assigned surveys (only run if instructed)". Shall we just remove the subtitle as "Reload all forms" says it all.

**Comment by valllllll2000** [comment]
## Test plan
Try downloading 1 form using settings. Make sure form is correctly downloaded.
With the app running and connected to the internet, assign forms to device and use settings to Reload all forms. The behavior should be as described above. All forms should be displayed correctly. Include a cascade in one of the forms and make sure it is downloaded correctly.

**Comment by janagombitova** [comment]
👍  works like a charm
