### ISSUE TITLE
Device permissions android 6.0+

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#927]
Currently we have the following permissions on the app that the users can see through app info:
* Camera
* Location
* Phone
* Storage
Since our target api is 21, we do not have to request these permissions per usage as indicated here https://developer.android.com/training/permissions/requesting.html
The problem is even if we do not need to request these permissions and they are granted automatically, users on devices >=6.0 can go to their settings and disable them. 
What happens if the user does disable them:
* Storage: 
We check every time we open the app and if the storage is unavailable we just show this dialog and force close the app:
![screenshot_20171102-125721](https://user-images.githubusercontent.com/923280/32325009-8c08988e-bfcd-11e7-9cf0-046d26db90d9.png)
This is not correct and confusing for the user
* Location
When location is needed, nothing seems to happen but location updates just do not arrive
* Phone
Nothing seems to happen here as we only use this to retrieve the phone number. There are some permissions related errors on sentry though, not sure if related to this issue.
**Consider removing this one as it used to retrieve the phone number of the device**
* Camera
If we try to take a picture or video, nothing happens at all so it may be confusing or lead users to think the app does not work. 
We should:
1) Update target sdk
2) Consider requesting these permissions and inform the user why we need them or show errors on why the actions will not work if they do not allow these permissions.

**Comment by janagombitova** [comment]
closed by accident, sorry.

**Comment by valllllll2000** [comment]
more info about permissions https://developer.android.com/guide/topics/permissions/overview.html#normal-dangerous
and
https://developer.android.com/training/permissions/requesting.html

**Comment by valllllll2000** [comment]
closing as this has been separted into multiple issues
