### ISSUE TITLE
Flow app UI testing

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#930]
The main functionality of the app is the filling out of surveys which is complex and needs tests. The tests that exist are very simple. We need to consider the best approach to full survey ui tests to also to reduce the amount of manual testing needed.
Find a way to run regression tests for the app automatically.
Check https://www.browserstack.com/automate
Check screenshots recording https://github.com/Karumi/KataScreenshotAndroid

**Comment by valllllll2000** [comment]
Question types and constraints

1. Text
2. Option
3. Cascade
4. Number
5. Geolocation
6. Photo
7. Video
8. Date
9. Barcode
10. Geoshape
11. Signature
12. Caddisfly

**Comment by valllllll2000** [comment]
## Test plan
No manual tests required

**Comment by janagombitova** [comment]
👍  this is making me very happy. Ready for release, yay!
