### ISSUE TITLE
View filled survey responses improvements

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#949]
1) Text question or number question
The fields do not seem disabled although no answer can actually be entered.
Should it be disabled the same way as optional questions are.

2) Geo location
There is a greyed out button "check geo location" which should be removed.

3) Photo question or Video question
There is a greyed out button saying "take photo" or "take video" which should be removed

4) Date question
"Select  date" greyed out button should maybe removed.

5) Signature
Remove "edit signature" greyed out button

6) Caddisfly
Remove "go to test" greyed out button

**Comment by janagombitova** [comment]
All works well and this change made the screen much cleaner and more logical. Well done.
