### ISSUE TITLE
Revert reload all surveys setting

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#953]
There are multiple issues on sentry reporting missing survey files (File not found)
https://sentry.io/akvo-foundation/flow-android/issues/300021634/

**Possible reasons why this happens**
* File was deleted by user for some reason
* File was deleted by the system
* No space on device
* Delete all data is pressed (but this also deletes users, forms, images, data)
* Form download failed

The issue was reported on Remaze. Once the surveys files are missing there is no way to recover them as before. The previous option allowed to "force reload" all surveys so it corrected the error but the new setting only reloads the missing or outdated surveys, it does not check for missing/corrupted survey files. 
Currently there is no way to recover from this state a part from deleting everything option.

**Steps to reproduce** 
With an app that browses the device file system, go to:
Internal Storage/Android/data/org.akvo.flow/files and delete the forms folder
Then all the forms files will be missing

**Possible solutions**
- Revert this feature to work as before, ie the reload all forms should download all new forms and replace the old ones. This would fix the missing files issue as they would be re-downloaded. It would also fix the issue where we check the form version against the one existing on the device and if the form version did not change we do not update the survey BUT it often happens that in the dashboard we update the survey and the version does not get updated.
- Improve this feature with the following: 
-- When checking for outdated surveys also make sure we verify the survey files are actually there
-- Do not rely on version to know if to update an existing form, just always update it

**Comment by valllllll2000** [comment]
After discussing with @muloem we have decided the best way to solve it quickly for the partner is to revert the change https://github.com/akvo/akvo-flow-mobile/issues/923 in a hotfix. Discovering why the forms are deleted and further improvements will be dealt in future tasks.

**Comment by valllllll2000** [comment]
## Test plan
Assign at least one survey and try opening it on device
Make sure it can be opened correctly.
Break the survey: with an app that browses the device file system, go to: `Internal Storage/Android/data/org.akvo.flow/files` and delete the `forms` folder.
Try adding data point the form. You should see the toast saying the form is missing.
Go to "settings" and press "reload all forms". Once confirmed, you should see the notification that formas are downloaded. 
When done, try adding datapoint again: you should see that you are able to add the datapoint correctly and the missing form message is gone.

**Comment by janagombitova** [comment]
Hey, 

First of all my apologies if I type in something that is expected or unneeded - I am not as sharp as I normally am. 

I has 6 different surveys on my device, where three were no longer in an active assignment on my phone. I tried the one I still have an assignment for and followed your steps. After deleting the file I got the error message and went to reload the surveys. 

I reloaded all surveys (with the admin passcode and everything). They disappeared from my list. Nothing happened. After a minute I force closed the app and reopened it. The forms download to my app but only the three I had an assignment for. The rest did not download. I was able to submit a new form for the survey in mind. 

Is this expected?

**Comment by valllllll2000** [comment]
@janagombitova it is expected as the reload all forms deletes the forms and downloads only the ones that are assigned, hence the scary confirm message. This is how it worked before. What we could do is improve on that but  maybe after the hotfix?

**Comment by janagombitova** [comment]
That sounds good. What about the fact that I had to force close the app and then reopen it to get the forms in? 

Second time I tried without deleting the file, just deleting a survey from the list. Then I reloaded all and the survey appeared right away. 

Third time I redid the entire test plan again and the reload worked fine without the need to force close and open the app. Maybe an issue with my device at that point of time?

**Comment by valllllll2000** [comment]
@janagombitova that should not happen. On my device there is no need to force close the app as using the setting reloads all the forms but I have only tried with "correctly assigned" forms. Will try also adding forms downloaded by id.

**Comment by janagombitova** [comment]
Ok. tested once again. Let's hotfix release this 👍
