### ISSUE TITLE
Reload all forms feedback

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#954]
**Background**
Currently the reload all forms starts a service which attempts to find new or outdated forms on the server and if any downloads them. If there are forms to download, a notification is displayed although in the future the "updated" or "new" forms will be displayed in bold in the list. If the download fails we display a notification error but if there are 2 cases which are not covered and where we do not notify the user:
* User is not connected to wifi and he did not allow mobile data usage
* User is not connected to the internet
* There are no new forms to download
In all these cases, the user is not notified at all and may think the feature is broken. 

**Suggestion**
Display a Toast informing the user in these 3 cases

**Comment by janagombitova** [comment]
I like your suggestions 👍 

For the no internet case, we should "reuse" the other no internet toasts to have a consistent language across the app. What do you think of using the snack bar with the settings link to turn on mobile data? 

For the no new forms to download what text in the toast would you suggest?
