### ISSUE TITLE
Form files seem to have been deleted from the device

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#959]
This issue has been happening across multiple release versions to many devices and many dashboards and it has been reported by sentry https://sentry.io/akvo-foundation/flow-android/issues/300021634/.

A temporary fix is to reload all surveys using the settings -> reload all surveys (see #953 )

We need to find the reason why the files have been deleted. Possible reasons:
* File was deleted by user for some reason
* File was deleted by the system
* No space on device
* Delete all data is pressed (but this also deletes users, forms, images, data)
* Form download failed
* Forms can be deleted after sync if the form has been unassigned from a given device

We need to find out if we are deleting the forms by mistake in some cases

**Comment by valllllll2000** [comment]
https://sentry.io/akvo-foundation/flow-android/issues/300021634/

**Comment by valllllll2000** [comment]
https://sentry.io/akvo-foundation/flow-android/issues/304693248/

**Comment by valllllll2000** [comment]
https://sentry.io/akvo-foundation/flow-android/issues/292051062/

**Comment by valllllll2000** [comment]
## Ideas on how to reproduce the issue
Connect device to computer via usb.
On the device, if possible select something like "Mass Storage" in the usb options (not all devices allow to change.
Open the folder ....`/Android/data/org.akvo.flow/` with the computer.
The issue happens more often on samsung devices. It happens more often with android 6.0.1.
If the device has an external SD card slot, inserting and sd card may help.
Restarting the device may help.
Disconnecting the device without selecting "safely remove" may help.

The issue happens when the device file system is disrupted in some way. So the way to try is:
1) Try getting all the surveys with usb connected, try adding datapoint, it should work
2) Disconnect the usb cable, try adding datapoint again, this time it may fail
If the forms get "corrupted" do not try to recover, wait for the fix to make sure the fix fixes the issue.

**Comment by valllllll2000** [comment]
The fix has been to move the surveys to use app internal storage which should always be available whereas external may not in some cases. It will not fix an issue already existing on devices but will prevent future occurrences of it on newly installed surveys. The code also looks in multiple places for existing surveys.

## Test plan:
Create a survey with at least a mandatory cascade question. Please tests on new and old devices.
* Part 1
Download previous app version
Make sure your survey is downloaded correctly and you are able to create datapoints.
Update the app.
Make sure you can still create datapoints

* Part 2
Clean download of latest version.
Put phone in flight mode
Test bootstrap feature and make sure you can create datapoints correctly

* Part 3
Clean download of latest version.
Make sure surveys are downloaded and you can create datapoints correctly

**Comment by janagombitova** [comment]
tested the parts on a Samsung running Android 4.4.2 and all worked well. Tomorrow will check on the tablet and dinosaur.

**Comment by janagombitova** [comment]
@valllllll2000 tested the steps on my Samsung running Android 4. and I found one problem, not sure it belongs here. Steps I have taken: 
- on the new app version put the phone to flight mode
- captured two data points for this form: uat1.akvoflow.org > _1.9.27 and 2.4.4 > 1.9.27 non monitoring all questions with translations > 1.9.27 all questions form
- connected my device to my PC and copied over the Data folder and created a zip file (attached here - holding all mock data)
- used the Bulk upload feature in Flow 
- all seemed to work ok according to the messages tab 
- when inspecting the submissions in the Inspect data tab, I do not see my 2 submissions, only the 2 I synced in online 


Data file: https://drive.google.com/drive/u/1/folders/0B4BNcLtl6pHrb3RDa3FjampIbTQ

![screenshot_2018-01-22-17-21-22](https://user-images.githubusercontent.com/12456965/35231338-cbb5dcfc-ff98-11e7-802b-1f9a6b8970e9.png)

**Comment by janagombitova** [comment]
Hey @valllllll2000 thank you for checking out the bulk upload issue. It indeed seems to be not related to the app changes: https://github.com/akvo/akvo-flow/issues/2450 and all the above tests pass so this is good to go 👍
