### ISSUE TITLE
Media files synchonization

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#96]
## Problem
When survey data is collected, all the images are placed in the external storage, and appropriately uploaded when the corresponding Survey Instance gets synchronized. Later on, while reviewing a submitted Survey, all the images are still preserved in the storage, which is very handy when it comes to display them in the Survey review.

However, with the inclusion of monitoring features, previously collected surveys can be synchronized. These downloaded surveys might very well contain images, which at the moment are not synchronized at all (image URIs are, but the image file is not).

Users reviewing previously collected surveys should be able to view images.

## Proposed Solution
Downloading every single image when syncing the corresponding Survey Instances is far from being efficient, as the amount of files could rapidly grow to an unacceptable size. 

Also, images belonging to unsynced (locally collected, saved/exported) Survey Instances cannot be deleted.

These requirements clearly define the two types of images we can find throughout the app:
* Images yet to be synced.
* Images backed up in S3, whose local copy is only useful to review a particular survey.

My proposal is to treat these images in two different ways:

**Unsynced images:**
These images are part of locally collected, saved or exported (not synced) Survey Instances, thus should remain in the filesystem until they get synced. These images are treated the same way they were before. 

**Synced images:**
Synced images can belong to **a)** Locally collected, synced (uploaded) surveys or **b)** previously collected, synced (downloaded) surveys. Either way, the local copy of the image could safely be deleted if the circumstances require so (i.e. if the file storage is running out of space). As the total number of unsynced images is unlimited, downloading and caching these images should be done in a lazy way, depending on when the users need to review the corresponding survey instances.

There are two issues to consider: when to sync and cache approach.

The sync policies we could take for these images is still unclear, as a trivial "*load on demand, when the user reviews the survey*" will not suit some scenarios, since on-demand connectivity is a requirement for this approach. However, this could be a simple start. More complex solutions can involve user decisions on when to download each image.

Regarding the cache, I suggest to take a **Least Recently Used (LRU)** approach, automatically wiping out the least recently used images when the maximum size of the cache is reached. The cache size will be determined depending on each device's external storage, to allocate a proportional size for the cache. Furthermore, this new cache can now be placed in the application's specific directory (unlike the rest of the data, which is put in the root directory of the sdcard), and will automatically be deleted when the application is uninstalled.

## Conclusion
The above mentioned solution not only solves the synced surveys problem, but also makes a more efficient use of the file system, automatically making room for newly collected data in devices with little storage.

**Comment by ichinaski** [comment]
As discussed with @mtwestra, the first implementation will solve a simpler problem, namely downloading images on demand:
* By default, no image will be downloaded from synced datapoints (not locally responded)
* Once a user browses a submitted survey instance, an extra option will be shown for remote images. This will allow users to arbitrarily download a particular image, without the need of a complex cache system (this can be added later on, of course).

**Comment by ichinaski** [comment]
**Test plan** (iteration 1):
* Create (or reuse) a monitored survey, where the registration form contains a media question (or any other form, but it's simpler to use the registration one).
* Submit a bunch of datapoints, always responding the media question.
* Clean the app data (long-click the app > info > clean data) and remove the *akvoflow* directory in the sd card.
* Upon restarting the app, create the user and download the survey.
* Sync the datapoints
* Browse the synced datapoints' responses, and scroll down to the media questions, which should by default show a blurry image with a download icon.
* Click the icon under various conditions (WiFi enabled, data enabled, airplane mode), and ensure everything works as expected.

**Comment by rumca** [comment]
I'm not sure what the reason is, but when I try to complete the above test plan I can't sync the data points in step 5 - I get an authorisation error.

**Comment by rumca** [comment]
after the fix on #259 the above test plan works as described
