### ISSUE TITLE
Translate missing strings in app 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#967]
We have a few strings that are not translated. Translate missing language strings in Flow and update translations: 
* [x] French 
* [x] Spanish
* [x] Portuguese 
* [ ] Vietnamese 
* [ ] Indonesian 
* [x] Dutch 
* [ ] Nepali 
* [ ] Khmer
* [ ] Hindi

@valllllll2000 can you translate French, Spanish and Portuguese strings in Transifex and I will take care of the rest? Thanks

**Comment by janagombitova** [comment]
@valllllll2000 I have not received a reply from the translators for the other languages and we have a release next week, how about we update the strings that we have a leave the rest for next time?

**Comment by valllllll2000** [comment]
There is a new issue for the translations #1119 so closing this one
