### ISSUE TITLE
Use app dedicated public storage for apk files

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#968]
after moving forms and res to use internal storage in #959 we need to also move apk files to use app dedicated public storage. Internal storage cannot be used as we need another app to access this file (the system app that installs the update)

**Comment by valllllll2000** [comment]
## Test plan
In order to properly test this I need to provide an apk which can be updated (with a version older than the current one but which still has the latest code). Try updating apk manually, make sure the update worked.

**Comment by janagombitova** [comment]
@valllllll2000  the only thing I checked so far was installing an old apk 2.9.9, submitting some data and then updating the app and submitting more. All worked well. Is there a specific apk you would like me to test with?

**Comment by valllllll2000** [comment]
@janagombitova if it works, then everything fine, no need to check anything else
