### ISSUE TITLE
Move signature temp files to internal storage

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#970]
after moving forms, res and apk to use internal storage in #959 we #968  need to also move temporary signature files to use internal storage instead of external one which may sometimes be unavailable

**Comment by valllllll2000** [comment]
This might fix the issue https://github.com/akvo/akvo-flow-mobile/issues/940

**Comment by valllllll2000** [comment]
## Test plan
Create a monitored survey with images, videos and signature. Make sure all question types are correctly saved and synced. 
Delete everything and then sync the datapoints. Make sure all files are shown correctly. Also test on older devices

**Comment by janagombitova** [comment]
👍  looks good to me, well done.
