### ISSUE TITLE
Form viewing cascades

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#979]
When the form is in view only mode, if no cascade is filled (not mandatory question), we still see one spinner with the text "please select". This is a bit confusing, it should probably not be visible.

**Comment by valllllll2000** [comment]
## Test plan
Create a suvey with at text question mandatory and a non mandatory cascade
Fill the form answering only the text question and submit
Open datapoint and make sure the cascade is not displayed

**Comment by janagombitova** [comment]
works properly, ready to roll
