### ISSUE TITLE
Clicking cancel on "Other.." popup for option questions

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow-mobile#98]
This might not be an issue in the redesigned version of the application, however when an option question has the "Allow other" and "Allow multiple" properties enabled, and the following steps are performed:

* Select a few options 
* Select "Other..."
* Click cancel on the more detail popup which appears

The app is left as below:

![screenshot_2014-05-06-17-24-07](https://cloud.githubusercontent.com/assets/3003031/2893136/34b43960-d545-11e3-8d7d-3d9d46a0f953.png)

When the user then selects submit, no data for this option question is sent to the server.

**Comment by janagombitova** [comment]
We are investigating more in detail with users the way they use other and what type of information they want to gain out of using 'other' and an option. We see two cases right now, where other must be defined and where other does not have to be defined by the user. As these hypothesis still need to be validated, there is an issue in the product design repository where we will answer the larger questions first and then create specific issues here. For now closing the issue
