### ISSUE TITLE
Confirm overwriting geolocation data 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#981]
Created via Reamaze: https://flowhelp.reamaze.com/admin/conversations/enhancement-geolocation-question-in-the-app

# Context 
A common practice among data collectors is verification of data before submitting. This means that after the interaction with the respondent is complete, they go through the questionnaire once again to ensure every thing is ok before submitting , since the data is not editable post submitting.

Generally this task is done in bulk, say during the afternoon or end of day.

During this verification, a common mistake happens with the GPS questions. People inadvertently click the check geolocation button while scrolling, many times by accident. This leads to their current GPS location being recorded and not the respondents.

For all other types of questions mistakes because of inadvertent touches can always be undone, but not the geolocation question.

# Opportunity 
If there is already a location recorded for a geolocation question, then on subsequent clicks of the “Check Geolocation” button, show a warning dialog before overwriting.

**Comment by valllllll2000** [comment]
@janagombitova which text should we display? How about:
Title: Reset and update collected gps coordinates?
Buttons:
*Reset
*cancel

**Comment by janagombitova** [comment]
How about: 
Update GPS coordinates? 
Update
Cancel

or 

Change GPS coordinates? 
Change
Cancel

**Comment by valllllll2000** [comment]
Update sounds better to me:
Update GPS coordinates?
Update
Cancel

**Comment by valllllll2000** [comment]
## Test plan
Create a geolocation question preferably one you can edit manually. Fill in data or acquire location automatically. Once you have a latitude and lognitude press "check geolocation" again. You should see a dialog requesting confirmation.
![screenshot_1516127271](https://user-images.githubusercontent.com/923280/35005352-6723ad72-faf3-11e7-99d3-c8fc91cfe983.png)

**Comment by muloem** [comment]
Just as a comment for a longer term solution, perhaps we want to add the _Review_ state to a form? i.e. after collecting and saving, its viewable and only if we select edit, are the responses editable.  That way inadvertently clicking edit, not only for the GPS but for all other questions is avoided.

**Comment by valllllll2000** [comment]
@muloem I agree that it would be a better solution but it will take a significant amount of work to add a new state so how about we just add this change for now and I create an issue with your idea and we can think about it further? As you can see mentioned in the issue above mistakes for other question types can be easily undone. What do you both think @janagombitova @muloem?

**Comment by janagombitova** [comment]
I agree with @valllllll2000 that the longer term solution you mention @muloem is worth exploring in a separate issue. We need to understand better the review of a form, why it happens, is it something done often, by whom, what other reviews of forms happen, etc. 

For now, this fix solves the problem.

**Comment by janagombitova** [comment]
Works well 👍  Ready to go
