### ISSUE TITLE
Add walkthrough for data storage privacy changes 

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#984]
I got the idea after viewing this library 
https://github.com/Shashank02051997/FancyWalkthrough-Android

Idea:
The first time a user opens the app he gets a few slides presenting the app with 2 or 3 main features or some tips on how to use the app.

**Comment by janagombitova** [comment]
@valllllll2000 thank you for the explanation. In that case it might be indeed simpler just to go with the automatically detected device language and later in the future see what to do with the current change language option in the Setting. To be honest I am not sure if users who for example have requested Flow to be translated to Khmer have also their devices set to Khmer. But indeed worth the investigation. 

On this topic we could have: 
1. Welcome screen 
2. about creating an account
3. about selecting a survey 
4. about submitting data with a Get started button

**Comment by valllllll2000** [comment]
@janagombitova 
I agree about the languages and yes maybe khmer is the exception.
1, 3 and 4 are quite clear but how about 2? Do we explain how to login with the device id and username? What worries me is this part is about to change right?

**Comment by janagombitova** [comment]
@valllllll2000 that is a good point - on n2. We can think of another topic or just stick with three screens...

**Comment by janagombitova** [comment]
@valllllll2000 and @Kiarii today we agreed to consider using walkthrough to inform the users once they update their app to the new version holding the public/private folder change. Here we can add our ideas on what the pages should hold

**Comment by Kiarii** [comment]
for now, myself and Jana have settled for two screens for introducing the privacy change, to be shown once upon updating the app; talking to Loic on the graphics side of things..

![image](https://user-images.githubusercontent.com/12692444/35508028-83da9de6-04f7-11e8-8e78-9bf0b118f714.png)

**Comment by Kiarii** [comment]
we have also reconsidered the text in the second screen as "Use the *Pubish data* option under Settings to prepare data collected offline for bulk upload"

**Comment by janagombitova** [comment]
The latests mock ups can be found here:  https://projects.invisionapp.com/share/ABG2CT39MPC#/screens/281739054

Title on both pages: Data storage
1st page text: Data collected with Akvo Flow app is now stored privately in the device. 
2nd page text: Use the **Publish data** option in Settings to make data collected offline available for bulk upload.

**Comment by valllllll2000** [comment]
Here are the screenshots of how it looks
![screenshot_20180412-170905](https://user-images.githubusercontent.com/923280/38686323-5b02ff7e-3e74-11e8-8f46-18438fd15aed.png)
![screenshot_20180412-170909](https://user-images.githubusercontent.com/923280/38686325-5b23373a-3e74-11e8-93b4-e2e990a30581.png)

So as you can see, the buttons are at the top and the dots are at the bottom (unlike in the invision version). It seems to make more sense to me as the dots are "pages" and should be at the bottom whereas the buttons are part of each page. But if required I can make the change to make it look like in invision. 

Click on "next" button, moves to the next slide. Clicking OK dismisses the walkthrough and gets the user back to where he was in the beginning (either login screen or survey).
One more detail: I need to make the "Publish data" text in bold within the large text on the second slide (I will do it tomorrow).
The icons: I do not have access to the exact icons (the lock and the key) that are drawn in the invision. I found some similar icons but if you want me to use those exactly, I will need them sent to me.

@janagombitova @Kiarii what do you guys think?

**Comment by janagombitova** [comment]
@valllllll2000 I love it! it is perfect!

**Comment by Kiarii** [comment]
sorry for the belated comment: in my experience the dots are either placed above the actions (skip, next, ..) or are placed on the same line e.g. respectively:

<img width="802" alt="screen shot 2018-04-16 at 13 50 22" src="https://user-images.githubusercontent.com/12692444/38805072-399adbca-417d-11e8-8e59-65436d13ab3b.png">

![image](https://user-images.githubusercontent.com/12692444/38804998-fa51ecce-417c-11e8-9bce-8b86135c48bf.png)

**Comment by janagombitova** [comment]
Wonderful! 👍
