### ISSUE TITLE
Remove geocode

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow-mobile#990]
The app side of akvo/akvo-flow#2367 and akvo/akvo-flow#2451.
We should simply stop sending the geocode to the backend.

If we want to add accuracy instead, I recommend we wait a while and when geocodes are no longer submitted, we clean geocodes out of the db. (We then may consider taking the opportunity to switch GEO answers to a JSON format.)

**Comment by valllllll2000** [comment]
## Test plan
create a new datapoint with location question and submit. Using inspect data tab, make sure the geocode is gone
