### ISSUE TITLE
Create a service to make existing public data private (move data from public to private storage)

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#992]
-> service
run once, then we save to preferences that no need to run it again

list all files inside files/ folder -> delete them (data sync will recreate them)
list all files inside media/ folder 
	-> move them to private
	-> delete them if move sucessfull

1) add domain logic
2) add data logic
3) add presentation

**Comment by valllllll2000** [comment]
## Test plan
Create a survey with at least images and videos.
Use an old build.
Go offline
Create datapoints
Make sure they are in exported state
Update to latest build
Restart the app
Make sure the datapoints are still in exported state
Enable internet
Make sure syncing starts and check that all datapoint are synced
Check at data and images have been sent correctly

**Comment by janagombitova** [comment]
👍 works like a charm
